-- ===========================================================================
-- kalman_portfolio.10_screen_mc_summary_v2
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- DO NOT HAND-EDIT. It is rewritten
-- on every export, so an edit here is lost on the next run and, worse, is
-- invisible until then.
--
-- This line is also how the test suite FINDS these files. A reformatting pass
-- stripped it from all eleven in August 2026, and
-- `test_generated_analytics_ddls_carry_the_identity_block` went from checking
-- eleven schemas to checking zero -- passing the whole time, because it counts
-- what it found rather than what it expected to find. Reformat these files and
-- the committed schema stops being provably in sync with the code.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- WHO WRITES WHAT (2026-08-31). The fit `pymc_kalman_filter_pt_v2.py` writes
-- the panel, the diagnostics and the comparison; `kalman_portfolio.py` writes
-- the screen, the risk book and the canonical decision table the GEIB dashboard
-- reads. The replay's own frames live in the `kalman_portfolio` schema instead,
-- append-only.
-- ===========================================================================

DROP TABLE IF EXISTS kalman_portfolio."10_screen_mc_summary_v2";
CREATE TABLE kalman_portfolio."10_screen_mc_summary_v2"
(
    "isin" TEXT,
    "ticker" TEXT,
    "name" TEXT,
    "trading_region" TEXT,
    "region" TEXT,
    "country" TEXT,
    "country_name" TEXT,
    "trading_country" TEXT,
    "trading_country_name" TEXT,
    "exchange" TEXT,
    "exchange_name" TEXT,
    "unit" TEXT,
    "unit_name" TEXT,
    "style_class" TEXT,
    "size_class" TEXT,
    "sector" TEXT,
    "industry" TEXT,
    "last_updated" DATE,
    "income_statement_report_date" DATE,
    "next_earnings" DATE,
    "next_earnings_when" TEXT,
    "next_earnings_status" TEXT,
    "fy_end_date" DATE,
    "next_fiscal_quarter" DATE,
    "next_income_statement_report_date" DATE,
    "next_fy_end_date" DATE,
    "expected_report_date" DATE,
    "days_to_next_earnings" INTEGER,
    "days_since_last_report" INTEGER,
    "days_to_next_fy_end" INTEGER,
    "days_to_next_fiscal_quarter" INTEGER,
    "days_to_next_report" INTEGER,
    "days_to_expected_report" INTEGER,
    "days_since_fy_end" INTEGER,
    "market_cap" DOUBLE PRECISION,
    "enterprise_value" DOUBLE PRECISION,
    "market_cap_global_r" INTEGER,
    "market_cap_global_sec_r" INTEGER,
    "market_cap_region_r" INTEGER,
    "market_cap_region_sec_r" INTEGER,
    "market_cap_country_r" INTEGER,
    "market_cap_country_sec_r" INTEGER,
    "er_mean" DOUBLE PRECISION,
    "er_sd" DOUBLE PRECISION,
    "er_p05" DOUBLE PRECISION,
    "er_p50" DOUBLE PRECISION,
    "er_p95" DOUBLE PRECISION,
    "mc_prob_pos" DOUBLE PRECISION,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN kalman_portfolio."10_screen_mc_summary_v2"."er_mean" IS
    'Mean forward return over the Monte-Carlo horizon. Raw decimal.';
COMMENT ON COLUMN kalman_portfolio."10_screen_mc_summary_v2"."er_sd" IS
    'Pooled sd of the forward-return draws. Denominator of expected_sharpe_ratio.';
COMMENT ON COLUMN kalman_portfolio."10_screen_mc_summary_v2"."er_p05" IS
    '5th percentile forward return. Drives the upper out_of_support test.';
COMMENT ON COLUMN kalman_portfolio."10_screen_mc_summary_v2"."er_p95" IS
    '95th percentile forward return. Drives the lower out_of_support test.';
COMMENT ON COLUMN kalman_portfolio."10_screen_mc_summary_v2"."mc_prob_pos" IS
    'Share of Monte-Carlo forward-return draws above zero.';
COMMENT ON COLUMN kalman_portfolio."10_screen_mc_summary_v2"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN kalman_portfolio."10_screen_mc_summary_v2"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN kalman_portfolio."10_screen_mc_summary_v2"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN kalman_portfolio."10_screen_mc_summary_v2"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_10_screen_mc_summary_v2_isin
    ON kalman_portfolio."10_screen_mc_summary_v2" (isin);
