-- ===========================================================================
-- kalman_portfolio.10b_risk_analytics_v2
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- DO NOT HAND-EDIT. It is rewritten
-- on every export, so an edit here is lost on the next run and, worse, is
-- invisible until then.
--
-- This line is also how the test suite FINDS these files. A reformatting pass
-- stripped it from all eleven in August 2026, and
-- `test_generated_analytics_ddls_carry_the_identity_block` went from checking
-- eleven schemas to checking zero -- passing the whole time, because it counts
-- what it found rather than what it expected to find. Reformat these files and
-- the committed schema stops being provably in sync with the code.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- WHO WRITES WHAT (2026-08-31). The fit `pymc_kalman_filter_pt_v2.py` writes
-- the panel, the diagnostics and the comparison; `kalman_portfolio.py` writes
-- the screen, the risk book and the canonical decision table the GEIB dashboard
-- reads. The replay's own frames live in the `kalman_portfolio` schema instead,
-- append-only.
-- ===========================================================================

DROP TABLE IF EXISTS kalman_portfolio."10b_risk_analytics_v2";
CREATE TABLE kalman_portfolio."10b_risk_analytics_v2"
(
    "isin" TEXT,
    "ticker" TEXT,
    "name" TEXT,
    "trading_region" TEXT,
    "region" TEXT,
    "country" TEXT,
    "country_name" TEXT,
    "trading_country" TEXT,
    "trading_country_name" TEXT,
    "exchange" TEXT,
    "exchange_name" TEXT,
    "unit" TEXT,
    "unit_name" TEXT,
    "style_class" TEXT,
    "size_class" TEXT,
    "sector" TEXT,
    "industry" TEXT,
    "last_updated" DATE,
    "income_statement_report_date" DATE,
    "next_earnings" DATE,
    "next_earnings_when" TEXT,
    "next_earnings_status" TEXT,
    "fy_end_date" DATE,
    "next_fiscal_quarter" DATE,
    "next_income_statement_report_date" DATE,
    "next_fy_end_date" DATE,
    "expected_report_date" DATE,
    "days_to_next_earnings" INTEGER,
    "days_since_last_report" INTEGER,
    "days_to_next_fy_end" INTEGER,
    "days_to_next_fiscal_quarter" INTEGER,
    "days_to_next_report" INTEGER,
    "days_to_expected_report" INTEGER,
    "days_since_fy_end" INTEGER,
    "market_cap" DOUBLE PRECISION,
    "enterprise_value" DOUBLE PRECISION,
    "market_cap_global_r" INTEGER,
    "market_cap_global_sec_r" INTEGER,
    "market_cap_region_r" INTEGER,
    "market_cap_region_sec_r" INTEGER,
    "market_cap_country_r" INTEGER,
    "market_cap_country_sec_r" INTEGER,
    "n_analysts" DOUBLE PRECISION,
    "feat_analyst_rating" DOUBLE PRECISION,
    "mcap_global_r" DOUBLE PRECISION,
    "mcap_country_r" DOUBLE PRECISION,
    "last_price" DOUBLE PRECISION,
    "observed_pt" DOUBLE PRECISION,
    "expected_upside" DOUBLE PRECISION,
    "expected_upside_sd" DOUBLE PRECISION,
    "prob_pos" DOUBLE PRECISION,
    "implied_upside" DOUBLE PRECISION,
    "expected_pt" DOUBLE PRECISION,
    "expected_pt_hdi_lo" DOUBLE PRECISION,
    "expected_pt_hdi_hi" DOUBLE PRECISION,
    "shrink_gain" DOUBLE PRECISION,
    "risk_adj_return" DOUBLE PRECISION,
    "kalman_gain" DOUBLE PRECISION,
    "er_mean" DOUBLE PRECISION,
    "er_sd" DOUBLE PRECISION,
    "er_p05" DOUBLE PRECISION,
    "er_p50" DOUBLE PRECISION,
    "er_p95" DOUBLE PRECISION,
    "mc_prob_pos" DOUBLE PRECISION,
    "p_upside_pos_cond" DOUBLE PRECISION,
    "p_upside_pos" DOUBLE PRECISION,
    "band_width" DOUBLE PRECISION,
    "cvar05" DOUBLE PRECISION,
    "exp_vol" DOUBLE PRECISION,
    "ret_vol_ratio" DOUBLE PRECISION,
    "expected_sharpe_ratio" DOUBLE PRECISION,
    "tail_risk" DOUBLE PRECISION,
    "starr" DOUBLE PRECISION,
    "book_weight" DOUBLE PRECISION,
    "out_of_support" BOOLEAN,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."expected_upside_sd" IS
    'Posterior sd of the per-name expected upside -- ESTIMATION uncertainty, not return risk. This is what the retired expected_vol_kalman held before 2026-08-20. Since then it also carries the forecast-error term, so it is roughly an order of magnitude wider than the 0.47pp of run 49e84d7e9d59. Raw decimal. The column coverage_gradient is graded on.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."prob_pos" IS
    'NON-RANKING -- reported diagnostic. Share of the per-name posterior above zero. Do not rank, filter or size on it; rank on p_upside_pos_cond. It saturates: 59.4% of the universe sat at exactly 1.0 on run 0aa3397b1d01 and 87.4% on the pass-through 49e84d7e9d59, because the smoother is Rao-Blackwellised over the latent and the posterior sd collapsed to 0.47pp. The forecast-error term added 2026-08-20 widens it and the prob_pos_degenerate gate warns if it re-pins -- but that gate passes at 59.4% against a 60% ceiling, so it is reporting the threshold as much as the model. A column pinned for three names in five has almost no ordering to offer.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."implied_upside" IS
    'Analyst consensus upside, original_target/original_price - 1. Raw decimal.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."shrink_gain" IS
    'Weight on the name''s own smoothed observation in the forecast-error update; 1 - shrink_gain is the weight on the pooled drift + hierarchy prediction. Low for thinly covered or widely dispersed consensus. This is the column kalman_gain was mistakenly believed to be.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."kalman_gain" IS
    'NON-RANKING -- reported diagnostic, and a DEPRECATED NAME. Removed from the GEIB selectable-metric surface on 2026-08-24: 54.0% of the universe sat at exactly 0 or exactly 1 on run 0aa3397b1d01, up from 50.6%, so it orders barely half the names and is degenerate for the rest. Rank on p_upside_pos_cond instead. Definition, for the rows where it is not pinned: P(risk_adj_return > 0) over posterior draws -- a real tail probability since 2026-08-20. It was sigmoid(risk_adj_return), a sigmoid of a standardised log-uplift, which is not the probability of any event and correlated -0.004 with analyst count. It is NOT a Kalman gain and never was: for the shrinkage weight, which is the quantity this name has always suggested, see shrink_gain.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."er_mean" IS
    'Mean forward return over the Monte-Carlo horizon. Raw decimal.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."er_sd" IS
    'Pooled sd of the forward-return draws. Denominator of expected_sharpe_ratio.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."er_p05" IS
    '5th percentile forward return. Drives the upper out_of_support test.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."er_p95" IS
    '95th percentile forward return. Drives the lower out_of_support test.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."mc_prob_pos" IS
    'Share of Monte-Carlo forward-return draws above zero.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."p_upside_pos_cond" IS
    'THE PRIMARY PROBABILITY COLUMN -- rank on this one. P(risk-adjusted forward return > 0): the share of Monte-Carlo forward-return draws that are positive after the same risk / size / volume penalties the model applies to risk_adj_return. Changed 2026-08-20 from mc_prob_pos * kalman_gain, a probability times a sigmoid, whose ordering was usable but whose level was the probability of nothing. NULL when out_of_support.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."expected_sharpe_ratio" IS
    'er_mean / er_sd over Monte-Carlo draws of log price-target uplift. A t-statistic on the distance from price to the smoothed target, NOT an investment Sharpe ratio -- the numerator is an uplift, not a realised excess return. Median ~1.05, which is exactly the range a reader mistakes for a Sharpe. NULL when out_of_support.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."out_of_support" IS
    'TRUE when the forward-return distribution is pinned at a clip bound (er_p05 at the +500% cap or er_p95 at the -95% floor). Ranking metrics are NULL for these rows; identity and the raw er_* distribution are kept.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN kalman_portfolio."10b_risk_analytics_v2"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_10b_risk_analytics_v2_isin
    ON kalman_portfolio."10b_risk_analytics_v2" (isin);
