-- ===========================================================================
-- kalman_portfolio.15c_forecast_engines
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- DO NOT HAND-EDIT. It is rewritten
-- on every export, so an edit here is lost on the next run and, worse, is
-- invisible until then.
--
-- This line is also how the test suite FINDS these files. A reformatting pass
-- stripped it from all eleven in August 2026, and
-- `test_generated_analytics_ddls_carry_the_identity_block` went from checking
-- eleven schemas to checking zero -- passing the whole time, because it counts
-- what it found rather than what it expected to find. Reformat these files and
-- the committed schema stops being provably in sync with the code.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- WHO WRITES WHAT (2026-08-31). The fit `pymc_kalman_filter_pt_v2.py` writes
-- the panel, the diagnostics and the comparison; `kalman_portfolio.py` writes
-- the screen, the risk book and the canonical decision table the GEIB dashboard
-- reads. The replay's own frames live in the `kalman_portfolio` schema instead,
-- append-only.
-- ===========================================================================

DROP TABLE IF EXISTS kalman_portfolio."15c_forecast_engines";
CREATE TABLE kalman_portfolio."15c_forecast_engines"
(
    "isin" TEXT,
    "ticker" TEXT,
    "name" TEXT,
    "trading_region" TEXT,
    "region" TEXT,
    "country" TEXT,
    "country_name" TEXT,
    "trading_country" TEXT,
    "trading_country_name" TEXT,
    "exchange" TEXT,
    "exchange_name" TEXT,
    "unit" TEXT,
    "unit_name" TEXT,
    "style_class" TEXT,
    "size_class" TEXT,
    "sector" TEXT,
    "industry" TEXT,
    "last_updated" DATE,
    "income_statement_report_date" DATE,
    "next_earnings" DATE,
    "next_earnings_when" TEXT,
    "next_earnings_status" TEXT,
    "fy_end_date" DATE,
    "next_fiscal_quarter" DATE,
    "next_income_statement_report_date" DATE,
    "next_fy_end_date" DATE,
    "expected_report_date" DATE,
    "days_to_next_earnings" INTEGER,
    "days_since_last_report" INTEGER,
    "days_to_next_fy_end" INTEGER,
    "days_to_next_fiscal_quarter" INTEGER,
    "days_to_next_report" INTEGER,
    "days_to_expected_report" INTEGER,
    "days_since_fy_end" INTEGER,
    "market_cap" DOUBLE PRECISION,
    "enterprise_value" DOUBLE PRECISION,
    "market_cap_global_r" INTEGER,
    "market_cap_global_sec_r" INTEGER,
    "market_cap_region_r" INTEGER,
    "market_cap_region_sec_r" INTEGER,
    "market_cap_country_r" INTEGER,
    "market_cap_country_sec_r" INTEGER,
    "er_mean_fc" DOUBLE PRECISION,
    "er_sd_fc" DOUBLE PRECISION,
    "er_p05_fc" DOUBLE PRECISION,
    "er_p50_fc" DOUBLE PRECISION,
    "er_p95_fc" DOUBLE PRECISION,
    "prob_pos" DOUBLE PRECISION,
    "er_mean_ar" DOUBLE PRECISION,
    "er_sd_ar" DOUBLE PRECISION,
    "er_p05_ar" DOUBLE PRECISION,
    "er_p50_ar" DOUBLE PRECISION,
    "er_p95_ar" DOUBLE PRECISION,
    "sd_ratio" DOUBLE PRECISION,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN kalman_portfolio."15c_forecast_engines"."prob_pos" IS
    'NON-RANKING -- reported diagnostic. Share of the per-name posterior above zero. Do not rank, filter or size on it; rank on p_upside_pos_cond. It saturates: 59.4% of the universe sat at exactly 1.0 on run 0aa3397b1d01 and 87.4% on the pass-through 49e84d7e9d59, because the smoother is Rao-Blackwellised over the latent and the posterior sd collapsed to 0.47pp. The forecast-error term added 2026-08-20 widens it and the prob_pos_degenerate gate warns if it re-pins -- but that gate passes at 59.4% against a 60% ceiling, so it is reporting the threshold as much as the model. A column pinned for three names in five has almost no ordering to offer.';
COMMENT ON COLUMN kalman_portfolio."15c_forecast_engines"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN kalman_portfolio."15c_forecast_engines"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN kalman_portfolio."15c_forecast_engines"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN kalman_portfolio."15c_forecast_engines"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_15c_forecast_engines_isin
    ON kalman_portfolio."15c_forecast_engines" (isin);
