-- ===========================================================================
-- kalman_portfolio.15e_decision_books
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- DO NOT HAND-EDIT. It is rewritten
-- on every export, so an edit here is lost on the next run and, worse, is
-- invisible until then.
--
-- This line is also how the test suite FINDS these files. A reformatting pass
-- stripped it from all eleven in August 2026, and
-- `test_generated_analytics_ddls_carry_the_identity_block` went from checking
-- eleven schemas to checking zero -- passing the whole time, because it counts
-- what it found rather than what it expected to find. Reformat these files and
-- the committed schema stops being provably in sync with the code.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- WHO WRITES WHAT (2026-08-31). The fit `pymc_kalman_filter_pt_v2.py` writes
-- the panel, the diagnostics and the comparison; `kalman_portfolio.py` writes
-- the screen, the risk book and the canonical decision table the GEIB dashboard
-- reads. The replay's own frames live in the `kalman_portfolio` schema instead,
-- append-only.
-- ===========================================================================

DROP TABLE IF EXISTS kalman_portfolio."15e_decision_books";
CREATE TABLE kalman_portfolio."15e_decision_books"
(
    "isin" TEXT,
    "ticker" TEXT,
    "name" TEXT,
    "trading_region" TEXT,
    "region" TEXT,
    "country" TEXT,
    "country_name" TEXT,
    "trading_country" TEXT,
    "trading_country_name" TEXT,
    "exchange" TEXT,
    "exchange_name" TEXT,
    "unit" TEXT,
    "unit_name" TEXT,
    "style_class" TEXT,
    "size_class" TEXT,
    "sector" TEXT,
    "industry" TEXT,
    "last_updated" DATE,
    "income_statement_report_date" DATE,
    "next_earnings" DATE,
    "next_earnings_when" TEXT,
    "next_earnings_status" TEXT,
    "fy_end_date" DATE,
    "next_fiscal_quarter" DATE,
    "next_income_statement_report_date" DATE,
    "next_fy_end_date" DATE,
    "expected_report_date" DATE,
    "days_to_next_earnings" INTEGER,
    "days_since_last_report" INTEGER,
    "days_to_next_fy_end" INTEGER,
    "days_to_next_fiscal_quarter" INTEGER,
    "days_to_next_report" INTEGER,
    "days_to_expected_report" INTEGER,
    "days_since_fy_end" INTEGER,
    "market_cap" DOUBLE PRECISION,
    "enterprise_value" DOUBLE PRECISION,
    "market_cap_global_r" INTEGER,
    "market_cap_global_sec_r" INTEGER,
    "market_cap_region_r" INTEGER,
    "market_cap_region_sec_r" INTEGER,
    "market_cap_country_r" INTEGER,
    "market_cap_country_sec_r" INTEGER,
    "expected_return" DOUBLE PRECISION,
    "er_sd" DOUBLE PRECISION,
    "kelly_fraction" DOUBLE PRECISION,
    "kelly_interior" BOOLEAN,
    "kelly_endpoint_score" DOUBLE PRECISION,
    "kelly_max_feasible" DOUBLE PRECISION,
    "kelly_unbounded" BOOLEAN,
    "gvar" DOUBLE PRECISION,
    "ges" DOUBLE PRECISION,
    "gtr" DOUBLE PRECISION,
    "downside_dev" DOUBLE PRECISION,
    "er_p05" DOUBLE PRECISION,
    "er_p95" DOUBLE PRECISION,
    "tail_risk" DOUBLE PRECISION,
    "tail_risk_on_floor" BOOLEAN,
    "downside_dev_floored" BOOLEAN,
    "reward_to_downside" DOUBLE PRECISION,
    "tail_risk_floored" BOOLEAN,
    "reward_to_cvar" DOUBLE PRECISION,
    "rank_denominator_pctile" DOUBLE PRECISION,
    "weight" DOUBLE PRECISION,
    "rank_by" TEXT,
    "book_role" TEXT,
    "book_engine" TEXT,
    "book_universe" TEXT,
    "backend" TEXT,
    "factor_share" DOUBLE PRECISION,
    "sector_cap" DOUBLE PRECISION,
    "size_down_veto_applied" BOOLEAN,
    "p_upside_pos_cond" DOUBLE PRECISION,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."er_sd" IS
    'Pooled sd of the forward-return draws. Denominator of expected_sharpe_ratio.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."kelly_fraction" IS
    'Log-optimal position size solved on the forward-return draws by bisection on E[r / (1 + f*r)]. Read it WITH kelly_interior and kelly_unbounded: the bare column reads 1.000 both when the criterion chose the cap and when it had nothing to solve.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."kelly_interior" IS
    'TRUE when the Kelly solution lies strictly inside (0, max_fraction), i.e. the criterion actually chose it rather than being pinned at a bound. FALSE for 89.3% of the universe on run 448e7f055ef3.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."kelly_max_feasible" IS
    'Largest f with 1 + f*r > 0 on every draw. NULL where no finite bound exists -- see kelly_unbounded. Carried +inf until 2026-08-27, which is not exportable: it blocked export_finite and a float8 Infinity poisons every downstream aggregate.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."kelly_unbounded" IS
    'TRUE when the name''s draws contain no losing scenario, so no finite feasible fraction exists and kelly_max_feasible is NULL. That is a statement about the simulation, not about the opportunity. 626 of 6,513 names on run 6efb530d5881.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."er_p05" IS
    '5th percentile forward return. Drives the upper out_of_support test.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."er_p95" IS
    '95th percentile forward return. Drives the lower out_of_support test.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."downside_dev_floored" IS
    'TRUE when the ranking denominator floor excluded this name from the reward_to_downside arm -- its modelled downside sat below the floor, so the ratio would have ranked it on the ABSENCE of modelled risk.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."tail_risk_floored" IS
    'As downside_dev_floored, for the reward_to_cvar arm.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."reward_to_cvar" IS
    'expected_return_kalman / tail_risk (STARR). NULL when out_of_support.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."rank_denominator_pctile" IS
    'Where this name''s ranking denominator sits in the eligible universe''s distribution of the same. The column that makes ''selected on the absence of modelled downside'' a read rather than a diagnosis: every name of the run 448e7f055ef3 book sat in its bottom ~2%.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."p_upside_pos_cond" IS
    'THE PRIMARY PROBABILITY COLUMN -- rank on this one. P(risk-adjusted forward return > 0): the share of Monte-Carlo forward-return draws that are positive after the same risk / size / volume penalties the model applies to risk_adj_return. Changed 2026-08-20 from mc_prob_pos * kalman_gain, a probability times a sigmoid, whose ordering was usable but whose level was the probability of nothing. NULL when out_of_support.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN kalman_portfolio."15e_decision_books"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';

CREATE INDEX IF NOT EXISTS idx_15e_decision_books_isin
    ON kalman_portfolio."15e_decision_books" (isin);
