create table accounting_anomaly_analysis
(
    isin                                         text,
    ticker                                       text,
    name                                         text,
    description                                  text,
    region                                       text,
    country                                      text,
    trading_country                              text,
    exchange                                     text,
    sector                                       text,
    industry                                     text,
    dividend_record_frequency                    text,
    earnings_report_frequency                    text,
    fy_end                                       text,
    next_earnings_report                         text,
    next_earnings_status                         text,
    next_earnings_when                           text,
    next_fiscal_quarter                          text,
    reporting_interval                           double precision,
    size_class                                   text,
    style_class                                  text,
    unit                                         text,
    dividend_record_announce_date                date,
    dividend_record_ex_date                      date,
    dividend_record_payable_date                 date,
    dividend_record_record_date                  date,
    fy_end_date                                  date,
    income_statement_report_date                 date,
    last_updated                                 date,
    next_earnings                                date,
    next_fy_end_date                             date,
    next_income_statement_report_date            date,
    reference_date                               date,
    accounting_anomaly_score                     double precision,
    exceptional_items_frequency_z_robust         double precision,
    exceptional_items_frequency_anomaly_flag     boolean,
    exceptional_items_frequency_dist_name        text,
    exceptional_items_frequency_dist_pvalue      double precision,
    gaap_adj_eps_gap_pct_z_robust                double precision,
    gaap_adj_eps_gap_pct_anomaly_flag            boolean,
    gaap_adj_eps_gap_pct_dist_name               text,
    gaap_adj_eps_gap_pct_dist_pvalue             double precision,
    asset_sale_boost_z_robust                    double precision,
    asset_sale_boost_anomaly_flag                boolean,
    asset_sale_boost_dist_name                   text,
    asset_sale_boost_dist_pvalue                 double precision,
    ebitda_adjustment_ratio_z_robust             double precision,
    ebitda_adjustment_ratio_anomaly_flag         boolean,
    ebitda_adjustment_ratio_dist_name            text,
    ebitda_adjustment_ratio_dist_pvalue          double precision,
    eps_adjustment_ratio_z_robust                double precision,
    eps_adjustment_ratio_anomaly_flag            boolean,
    eps_adjustment_ratio_dist_name               text,
    eps_adjustment_ratio_dist_pvalue             double precision,
    exceptional_items_to_ebitda_z_robust         double precision,
    exceptional_items_to_ebitda_anomaly_flag     boolean,
    exceptional_items_to_ebitda_dist_name        text,
    exceptional_items_to_ebitda_dist_pvalue      double precision,
    restructuring_intensity_z_robust             double precision,
    restructuring_intensity_anomaly_flag         boolean,
    restructuring_intensity_dist_name            text,
    restructuring_intensity_dist_pvalue          double precision,
    goodwill_change_rate_z_robust                double precision,
    goodwill_change_rate_anomaly_flag            boolean,
    goodwill_change_rate_dist_name               text,
    goodwill_change_rate_dist_pvalue             double precision,
    eps_adjustment_ratio_comp_z_robust           double precision,
    eps_adjustment_ratio_comp_anomaly_flag       boolean,
    eps_adjustment_ratio_comp_dist_name          text,
    eps_adjustment_ratio_comp_dist_pvalue        double precision,
    eps_adjustment_spread_ltm_z_robust           double precision,
    eps_adjustment_spread_ltm_anomaly_flag       boolean,
    eps_adjustment_spread_ltm_dist_name          text,
    eps_adjustment_spread_ltm_dist_pvalue        double precision,
    eps_adjustment_spread_fy_z_robust            double precision,
    eps_adjustment_spread_fy_anomaly_flag        boolean,
    eps_adjustment_spread_fy_dist_name           text,
    eps_adjustment_spread_fy_dist_pvalue         double precision,
    eps_adjustment_pct_z_robust                  double precision,
    eps_adjustment_pct_anomaly_flag              boolean,
    eps_adjustment_pct_dist_name                 text,
    eps_adjustment_pct_dist_pvalue               double precision,
    net_income_adjustment_ratio_ltm_z_robust     double precision,
    net_income_adjustment_ratio_ltm_anomaly_flag boolean,
    net_income_adjustment_ratio_ltm_dist_name    text,
    net_income_adjustment_ratio_ltm_dist_pvalue  double precision,
    net_income_adjustment_ratio_fy_z_robust      double precision,
    net_income_adjustment_ratio_fy_anomaly_flag  boolean,
    net_income_adjustment_ratio_fy_dist_name     text,
    net_income_adjustment_ratio_fy_dist_pvalue   double precision,
    net_income_adjustment_pct_z_robust           double precision,
    net_income_adjustment_pct_anomaly_flag       boolean,
    net_income_adjustment_pct_dist_name          text,
    net_income_adjustment_pct_dist_pvalue        double precision,
    ebitda_adjustment_pct_ltm_z_robust           double precision,
    ebitda_adjustment_pct_ltm_anomaly_flag       boolean,
    ebitda_adjustment_pct_ltm_dist_name          text,
    ebitda_adjustment_pct_ltm_dist_pvalue        double precision,
    ebitda_adjustment_pct_fy_z_robust            double precision,
    ebitda_adjustment_pct_fy_anomaly_flag        boolean,
    ebitda_adjustment_pct_fy_dist_name           text,
    ebitda_adjustment_pct_fy_dist_pvalue         double precision,
    ebit_adjustment_pct_ltm_z_robust             double precision,
    ebit_adjustment_pct_ltm_anomaly_flag         boolean,
    ebit_adjustment_pct_ltm_dist_name            text,
    ebit_adjustment_pct_ltm_dist_pvalue          double precision,
    ebit_adjustment_pct_fy_z_robust              double precision,
    ebit_adjustment_pct_fy_anomaly_flag          boolean,
    ebit_adjustment_pct_fy_dist_name             text,
    ebit_adjustment_pct_fy_dist_pvalue           double precision,
    forward_eps_gaap_adj_spread_z_robust         double precision,
    forward_eps_gaap_adj_spread_anomaly_flag     boolean,
    forward_eps_gaap_adj_spread_dist_name        text,
    forward_eps_gaap_adj_spread_dist_pvalue      double precision,
    gaap_vs_norm_revision_spread_z_robust        double precision,
    gaap_vs_norm_revision_spread_anomaly_flag    boolean,
    gaap_vs_norm_revision_spread_dist_name       text,
    gaap_vs_norm_revision_spread_dist_pvalue     double precision,
    gaap_revision_momentum_z_robust              double precision,
    gaap_revision_momentum_anomaly_flag          boolean,
    gaap_revision_momentum_dist_name             text,
    gaap_revision_momentum_dist_pvalue           double precision,
    gaap_revision_1m_z_robust                    double precision,
    gaap_revision_1m_anomaly_flag                boolean,
    gaap_revision_1m_dist_name                   text,
    gaap_revision_1m_dist_pvalue                 double precision,
    gaap_revision_3m_z_robust                    double precision,
    gaap_revision_3m_anomaly_flag                boolean,
    gaap_revision_3m_dist_name                   text,
    gaap_revision_3m_dist_pvalue                 double precision,
    gaap_revision_6m_z_robust                    double precision,
    gaap_revision_6m_anomaly_flag                boolean,
    gaap_revision_6m_dist_name                   text,
    gaap_revision_6m_dist_pvalue                 double precision,
    gaap_revision_1y_z_robust                    double precision,
    gaap_revision_1y_anomaly_flag                boolean,
    gaap_revision_1y_dist_name                   text,
    gaap_revision_1y_dist_pvalue                 double precision,
    discontinued_ops_impact_z_robust             double precision,
    discontinued_ops_impact_anomaly_flag         boolean,
    discontinued_ops_impact_dist_name            text,
    discontinued_ops_impact_dist_pvalue          double precision,
    revision_quality_divergence_z_robust         double precision,
    revision_quality_divergence_anomaly_flag     boolean,
    revision_quality_divergence_dist_name        text,
    revision_quality_divergence_dist_pvalue      double precision,
    eps_growth_accel_z_robust                    double precision,
    eps_growth_accel_anomaly_flag                boolean,
    eps_growth_accel_dist_name                   text,
    eps_growth_accel_dist_pvalue                 double precision,
    eps_surprise_pct_z_robust                    double precision,
    eps_surprise_pct_anomaly_flag                boolean,
    eps_surprise_pct_dist_name                   text,
    eps_surprise_pct_dist_pvalue                 double precision,
    revenue_surprise_pct_z_robust                double precision,
    revenue_surprise_pct_anomaly_flag            boolean,
    revenue_surprise_pct_dist_name               text,
    revenue_surprise_pct_dist_pvalue             double precision,
    mahalanobis_distance                         double precision,
    sector_relative_anomaly                      double precision,
    benford_chi2_pvalue                          double precision,
    anomaly_feature_count                        bigint,
    accounting_anomaly_tier                      text,
    anomaly_severity_score                       double precision,
    anomaly_risk_rank                            double precision,
    sector_anomaly_percentile                    double precision,
    multi_flag_alert                             boolean,
    anomaly_conditional_probability              double precision
);

alter table accounting_anomaly_analysis
    owner to postgres;

