create table etf
(
    ticker                                 text,
    isin                                   text,
    issuer                                 text,
    name                                   text,
    "Fund Category"                        text,
    exchange                               text,
    region                                 text,
    "Fund Benchmark"                       text,
    administrator                          text,
    custodian                              text,
    "Fund Investment Strategy"             text,
    "Broad Benchmark"                      text,
    "Is Levered"                           text,
    "Inception Date"                       date,
    "Launch Date"                          date,
    "Notional Volume"                      double precision,
    distributor                            text,
    "Investment Advisor"                   text,
    classification                         text,
    "Peer Benchmark"                       text,
    class                                  text,
    "Last Updated"                         date,
    "ETF FY End"                           text,
    "Last Price"                           double precision,
    "1-Day Chg"                            double precision,
    "1-Day %"                              double precision,
    "Price Chg. % (1D)"                    double precision,
    "Price Chg. % (5D)"                    double precision,
    "Price Chg. % (1W)"                    double precision,
    "Price Chg. % (1M)"                    double precision,
    "Price Chg. % (3M)"                    double precision,
    "Price Chg. % (6M)"                    double precision,
    "Price Chg. % (1Y)"                    double precision,
    "Price Chg. % (3Y)"                    double precision,
    "Price Chg. % (5Y)"                    double precision,
    "Yield Month-End"                      double precision,
    "30-Day SEC Yield"                     double precision,
    "Beta 1Y Quarter End"                  double precision,
    "Beta 3Y Quarter End"                  double precision,
    "Beta 5Y Quarter End"                  double precision,
    "Net Expense Ratio Reported"           double precision,
    aum                                    double precision,
    "Put/Call Ratio"                       double precision,
    "52W High"                             double precision,
    "52W High/Adj"                         double precision,
    "52W Low"                              double precision,
    "52W Low/Adj"                          double precision,
    "EMA (5D)"                             double precision,
    "EMA (8D)"                             double precision,
    "EMA (10D)"                            double precision,
    "EMA (20D)"                            double precision,
    "EMA (21D)"                            double precision,
    "EMA (50D)"                            double precision,
    "EMA (100D)"                           double precision,
    "Active Return"                        double precision,
    "Alpha (1Y)"                           double precision,
    "Alpha (3Y)"                           double precision,
    "Alpha (5Y)"                           double precision,
    "Annualized excess returns"            double precision,
    "Annualized returns"                   double precision,
    "Asset Type"                           text,
    "Arithmetic Mean (1Y)"                 double precision,
    "Arithmetic Mean (3Y)"                 double precision,
    "Arithmetic Mean (5Y)"                 double precision,
    "Beta (1Y)"                            double precision,
    "Beta (3Y)"                            double precision,
    "Beta (5Y)"                            double precision,
    "Effective Duration (Yrs)"             double precision,
    "Downside Capture Ratio (1Y)"          double precision,
    "Downside Capture Ratio (3Y)"          double precision,
    "Downside Capture Ratio (5Y)"          text,
    "Information Ratio (1Y)"               text,
    "Information Ratio (3Y)"               text,
    "Information Ratio (5Y)"               text,
    domicile                               text,
    "Kurtosis (1Y)"                        text,
    "Kurtosis (3Y)"                        text,
    "Kurtosis (5Y)"                        text,
    "Sortino Ratio (1Y)"                   text,
    "Sortino Ratio (3Y)"                   text,
    "Sortino Ratio (5Y)"                   text,
    "Sharpe Ratio (1Y)"                    text,
    "Sharpe Ratio (3Y)"                    text,
    "Sharpe Ratio (5Y)"                    text,
    "Skewness (1Y)"                        text,
    "Skewness (3Y)"                        text,
    "Skewness (5Y)"                        text,
    "12B-1"                                text,
    "ETF Category"                         text,
    "Effective Maturity (Yrs)"             text,
    ytm                                    text,
    "Fund Total Assets (Day-End)"          text,
    "Mgmt Fees"                            text,
    "R-Squared (1Y)"                       text,
    "R-Squared (3Y)"                       text,
    "R-Squared (5Y)"                       text,
    "Months with Negative Performance YTD" text,
    "Months with Positive Performance YTD" text,
    "Batting Average (1Y)"                 text,
    "Batting Average (3Y)"                 text,
    "Batting Average (5Y)"                 text,
    "Volatility Score"                     text,
    "Upside Capture Ratio (1Y)"            text,
    "Upside Capture Ratio (3Y)"            text,
    "Upside Capture Ratio (5Y)"            text,
    "Risk Free Rate"                       text,
    "SEC Yield"                            text
);

alter table etf
    owner to postgres;

