create materialized view mv_dcf as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       e."Market Cap"             AS market_cap,
       e."Enterprise Value"       AS enterprise_value,
       e."Last Price"             AS last_price,
       e."Shrs Out"               AS shares_outstanding,
       gf.revenue_growth_yoy,
       gf.ebitda_growth_yoy,
       gf.operating_income_growth,
       gf.fcf_growth,
       gf.revenue_cagr_5y,
       gf.forward_revenue_growth,
       gf.revenue_vs_5y_avg,
       rff.revenue_est_spread,
       rff.revenue_beat_potential,
       rff.revenue_est_revision_trend,
       rff.ebitda_est_vs_actual,
       rff.forward_revenue_multiple,
       rff.revenue_estimate_count,
       rff.revenue_guidance_gap,
       rff.consensus_revenue_growth,
       rff.ebit_estimate_spread,
       rff.forward_ebitda_margin,
       rff.revenue_acceleration,
       rff.estimate_confidence_score,
       rec.revenue_est_avg_fy1e,
       rec.revenue_est_med_fy1e,
       rec.revenue_est_avg_ntm,
       rec.revenue_est_med_ntm,
       rec.revenue_avg_med_diff_pct,
       rec.revenue_consensus_strength,
       rec.revenue_revision_trend AS revenue_revision_trend_rec,
       rec.revenue_vs_current,
       rqf.revenue_fq,
       rqf.revenue_fy,
       rqf.revenue_ltm,
       rqf.revenue_5y_avg,
       rqf.revenue_1fqfq,
       rqf.revenue_2fqfq,
       rqf.revenue_3fqfq,
       rqf.revenue_4fqfq,
       rqf.revenue_1fy,
       rqf.revenue_2fy,
       rqf.revenue_3fy,
       rqf.revenue_4fy,
       rqf.revenue_qoq_growth,
       rqf.revenue_qoq_2q,
       rqf.revenue_qoq_3q,
       rqf.revenue_qoq_4q,
       rqf.revenue_yoy_quarterly,
       rqf.revenue_2y_growth,
       rqf.revenue_3y_growth,
       rqf.revenue_4y_growth,
       rqf.revenue_cagr_3y,
       rqf.revenue_cagr_4y,
       rqf.revenue_4q_trend,
       rqf.revenue_4q_avg,
       rqf.revenue_fq_vs_4q_avg,
       rqf.revenue_growth_flag,
       rqf.revenue_stability_score,
       rqf.revenue_accelerating_flag,
       rqf.revenue_positive_qoq_streak,
       trt.revenue_5yavgfq,
       trt.revenue_5yavgltm,
       trt.revenue_vs_5y_avg_fq,
       trt.revenue_vs_5y_avg_ltm,
       trt.revenue_fq_vs_avg,
       trt.revenue_momentum,
       cf.cfo_to_net_income,
       cf.fcf_to_net_income,
       cf.fcf_margin,
       cf.cfo_growth_yoy,
       cf.fcf_positive_ratio,
       cf.acquisition_intensity,
       cf.self_funding_ratio,
       ecff.fcf_positive_years,
       ecff.fcf_always_positive,
       ecff.capex_vs_5y_avg,
       ecff.underinvestment_flag,
       ecff.cfo_share_of_cf,
       ecff.cfi_share_of_cf,
       ecff.cff_share_of_cf,
       ecff.self_funding_flag,
       ecff.acquisition_to_fcf,
       ecff.sustainable_ma_flag,
       ecff.fcf_4q_improvement,
       ecff.cash_flow_quality_score,
       ecff.capex_yoy_growth,
       ecff.capex_qoq_growth,
       ecff.capex_3y_trend,
       ecff.capex_volatility,
       ecff.capex_acceleration,
       ecff.capex_cut_flag,
       ecff.overinvestment_flag,
       ecff.acquisitions_yoy_growth,
       ecff.acquisitions_vs_5y_avg,
       ecff.acquisitions_ltm_total,
       ecff.ma_intensity_score,
       ecff.serial_acquirer_flag,
       ecff.acquisition_pause_flag,
       ecff.total_investment_to_cfo,
       ecff.organic_vs_inorganic,
       ecff.investment_efficiency,
       ctf.cfo_quarterly_trend,
       ctf.cfo_yoy_quarterly,
       ctf.cfi_quarterly_trend,
       ctf.cff_quarterly_trend,
       ctf.fcf_quarterly_trend,
       ctf.cfo_positive_quarters,
       ctf.cfi_negative_quarters,
       ctf.cff_pattern_score,
       ctf.cash_burn_rate,
       ctf.cf_volatility_score,
       ctf.operating_cf_momentum,
       ctf.financing_dependency,
       cc.cfo_fq,
       cc.cfo_ltm,
       cc.cfo_fy,
       cc.fcf_fq,
       cc.fcf_ltm,
       cc.fcf_fy,
       cc.cfo_growth_yoy          AS cfo_growth_yoy_comp,
       cc.fcf_growth_yoy,
       cc.cfo_to_net_income       AS cfo_to_net_income_comp,
       cc.fcf_margin              AS fcf_margin_comp,
       cc.fcf_yield,
       cc.cfo_positive_years,
       cc.fcf_positive_years      AS fcf_positive_years_comp,
       cc.cash_flow_quality_score AS cash_flow_quality_score_comp,
       fge.fcf_est_fy1,
       fge.fcf_est_fy2,
       fge.fcf_est_fy3,
       fge.fcf_est_fy4,
       fge.fcf_est_fy5,
       fge.fcf_est_growth_fy1_vs_ltm,
       fge.fcf_est_growth_fy2_vs_fy1,
       fge.fcf_est_growth_fy3_vs_fy2,
       fge.fcf_est_growth_fy4_vs_fy3,
       fge.fcf_est_growth_fy5_vs_fy4,
       fge.fcf_est_cagr_3y,
       fge.fcf_est_cagr_5y,
       fge.fcf_est_margin_fy1,
       fge.fcf_est_yield_fy1,
       fge.fcf_est_growth_acceleration,
       fge.fcf_est_growth_deceleration,
       fge.fcf_est_trajectory_score,
       fge.fcf_est_always_positive,
       fge.fcf_est_vs_historical,
       fge.fcf_est_capex_implied_ratio,
       tat.assets_fq,
       tat.assets_fy,
       tat.assets_ltm,
       tat.assets_1fq,
       tat.assets_2fq,
       tat.assets_3fq,
       tat.assets_4fq,
       tat.assets_1fy,
       tat.assets_2fy,
       tat.assets_3fy,
       tat.assets_4fy,
       tat.assets_qoq_growth,
       tat.assets_yoy_growth,
       tat.assets_3y_cagr,
       tat.asset_growth_accel,
       tat.asset_base_stable,
       itf.inventory_ltm,
       itf.inventory_fq,
       itf.inventory_fy,
       itf.inventory_1fq,
       itf.inventory_2fq,
       itf.inventory_3fq,
       itf.inventory_4fq,
       itf.inventory_1fy,
       itf.inventory_2fy,
       itf.inventory_3fy,
       itf.inventory_4fy,
       itf.inventory_qoq_change,
       itf.inventory_yoy_change,
       itf.inventory_4q_trend,
       itf.inventory_vs_5y_avg,
       itf.inventory_days,
       itf.inventory_turnover,
       itf.inventory_to_revenue,
       itf.inventory_to_assets,
       itf.inventory_buildup_flag,
       itf.inventory_reduction_flag,
       itf.inventory_volatility,
       gtf.goodwill_fq,
       gtf.goodwill_ltm,
       gtf.goodwill_fy,
       gtf.goodwill_1fq,
       gtf.goodwill_2fq,
       gtf.goodwill_3fq,
       gtf.goodwill_4fq,
       gtf.goodwill_1fy,
       gtf.goodwill_2fy,
       gtf.goodwill_3fy,
       gtf.goodwill_4fy,
       gtf.goodwill_qoq_change,
       gtf.goodwill_yoy_change,
       gtf.goodwill_3y_growth,
       gtf.goodwill_vs_5y_avg,
       gtf.recent_acquisition_flag,
       gtf.goodwill_accumulation_rate,
       gtf.goodwill_to_assets_trend,
       gtf.impairment_risk_score,
       gtf.goodwill_concentration,
       ef.eps_surprise_pct,
       ef.revenue_surprise_pct,
       ef.eps_adjustment_ratio,
       ef.gaap_adj_eps_gap_pct,
       ef.ebitda_adjustment_ratio,
       ef.eps_quarterly_trend,
       ef.eps_yoy_growth,
       etf.eps_qoq_growth,
       etf.eps_yoy_quarterly,
       etf.eps_positive_streak,
       etf.eps_cagr_3y,
       etf.eps_cagr_5y,
       etf.eps_growth_accel,
       etf.eps_vs_5y_avg,
       etf.eps_improvement_count,
       etf.eps_trajectory_score,
       etf.eps_stability,
       ec.eps_basic_fq,
       ec.eps_basic_ltm,
       ec.eps_basic_fy,
       ec.eps_adj_ltm,
       ec.eps_norm_est_fy1e,
       ec.eps_growth_yoy          AS eps_growth_yoy_comp,
       ec.eps_cagr_3y             AS eps_cagr_3y_comp,
       ec.eps_adjustment_ratio    AS eps_adjustment_ratio_comp,
       ec.eps_positive_years,
       ec.eps_trajectory_score    AS eps_trajectory_score_comp,
       ecf.eps_cont_ltm,
       ecf.eps_cont_fq,
       ecf.eps_cont_fy,
       ecf.eps_cont_1fqfq,
       ecf.eps_cont_2fqfq,
       ecf.eps_cont_3fqfq,
       ecf.eps_cont_4fqfq,
       ecf.eps_cont_1fy,
       ecf.eps_cont_2fy,
       ecf.eps_cont_3fy,
       ecf.eps_cont_4fy,
       ecf.eps_cont_qoq_growth,
       ecf.eps_cont_yoy_growth,
       ecf.eps_cont_cagr_3y,
       ecf.eps_cont_vs_total_eps,
       ecf.eps_cont_positive_streak,
       ecf.eps_cont_trajectory_score,
       ecf.discontinued_ops_impact,
       ecf.core_earnings_stability,
       gaa.eps_adjustment_spread_ltm,
       gaa.eps_adjustment_spread_fy,
       gaa.eps_adjustment_pct,
       gaa.net_income_adjustment_ratio_ltm,
       gaa.net_income_adjustment_ratio_fy,
       gaa.net_income_adjustment_pct,
       gaa.ebitda_adjustment_pct_ltm,
       gaa.ebitda_adjustment_pct_fy,
       gaa.ebit_adjustment_pct_ltm,
       gaa.ebit_adjustment_pct_fy,
       gaa.earnings_quality_score,
       gaa.earnings_quality_warning,
       gaa.forward_eps_gaap_adj_spread,
       grf.gaap_revision_momentum,
       grf.gaap_revision_1m,
       grf.gaap_revision_3m,
       grf.gaap_revision_6m,
       grf.gaap_revision_1y,
       grf.gaap_vs_norm_revision_spread,
       grf.gaap_revision_acceleration,
       grf.gaap_positive_revision_flag,
       grf.revision_quality_divergence,
       csf.cogs_to_revenue,
       csf.opex_to_revenue,
       csf.sga_to_revenue,
       csf.rnd_to_revenue,
       csf.interest_to_revenue,
       csf.sga_trend_yoy,
       csf.operating_leverage_proxy,
       csf.cost_efficiency_score,
       csf.marketing_to_revenue,
       csf.marketing_trend_yoy,
       csf.marketing_vs_5y_avg,
       csf.sga_vs_5y_avg,
       csf.sga_efficiency_trend,
       rtf.rnd_ltm,
       rtf.rnd_fq,
       rtf.rnd_fy,
       rtf.rnd_1fqfq,
       rtf.rnd_2fqfq,
       rtf.rnd_3fqfq,
       rtf.rnd_4fqfq,
       rtf.rnd_1fy,
       rtf.rnd_2fy,
       rtf.rnd_3fy,
       rtf.rnd_4fy,
       rtf.rnd_intensity_ltm,
       rtf.rnd_intensity_fy,
       rtf.rnd_intensity_trend,
       rtf.rnd_qoq_growth,
       rtf.rnd_yoy_growth,
       rtf.rnd_cagr_3y,
       rtf.rnd_per_employee,
       rtf.rnd_to_gross_profit,
       rtf.rnd_roi_proxy,
       rtf.rnd_increasing_flag,
       rtf.rnd_cut_flag,
       rtf.high_rnd_intensity_flag,
       iif.interest_income_ltm,
       iif.interest_expense_ltm,
       iif.net_interest_income,
       iif.interest_coverage_ratio,
       iif.interest_income_to_revenue,
       iif.interest_expense_to_revenue,
       iif.net_interest_margin_proxy,
       pf.roe,
       pf.roa,
       pf.gross_margin_pct,
       pf.operating_margin_pct,
       pf.net_margin_pct,
       pf.ebitda_margin_pct,
       pf.roic,
       pf.rnd_intensity,
       pf.equity_multiplier,
       mt.gross_margin_trend_yoy,
       mt.operating_margin_trend,
       mt.net_margin_trend_yoy,
       mt.ebitda_margin_trend,
       mt.margin_expansion_flag,
       mt.margin_stability_score,
       eec.ebit_fq,
       eec.ebit_ltm,
       eec.ebit_fy,
       eec.ebit_1fy,
       eec.ebit_2fy,
       eec.ebit_3fy,
       eec.ebit_4fy,
       eec.ebitda_fq,
       eec.ebitda_ltm,
       eec.ebitda_fy,
       eec.ebitda_1fy,
       eec.ebitda_2fy,
       eec.ebitda_3fy,
       eec.ebitda_4fy,
       eec.ebit_5yavgfq,
       eec.ebit_5yavgltm,
       eec.ebitda_5yavgfq,
       eec.ebitda_5yavgltm,
       eec.ebit_adj_fq,
       eec.ebit_adj_ltm,
       eec.ebit_adj_fy,
       eec.ebitda_adj_fq,
       eec.ebitda_adj_ltm,
       eec.ebitda_adj_fy,
       eec.ebit_growth_yoy,
       eec.ebitda_growth_yoy      AS ebitda_growth_yoy_comp,
       eec.ebit_margin_ltm,
       eec.ebitda_margin_ltm,
       eec.ebit_positive_years,
       eec.ebitda_positive_years,
       eec.ebit_qoq_growth,
       eec.ebitda_qoq_growth,
       eec.ebit_cagr_3y,
       eec.ebitda_cagr_3y,
       eec.ebit_vs_5y_avg,
       eec.ebitda_vs_5y_avg,
       gpt.gp_fq,
       gpt.gp_fy,
       gpt.gp_ltm,
       gpt.gp_1fqfq,
       gpt.gp_2fqfq,
       gpt.gp_3fqfq,
       gpt.gp_4fqfq,
       gpt.gp_1fy,
       gpt.gp_2fy,
       gpt.gp_3fy,
       gpt.gp_4fy,
       gpt.gp_qoq_growth,
       gpt.gp_yoy_growth,
       gpt.gp_margin_fq,
       gpt.gp_margin_trend,
       gpt.gp_positive_quarters,
       gpt.gp_margin_expansion,
       uif.other_unusual_items_ltm,
       uif.impairment_goodwill_ltm,
       uif.asset_writedown_ltm,
       uif.restructuring_charges_ltm,
       uif.total_unusual_items,
       uif.unusual_items_to_revenue,
       uif.unusual_items_to_ebitda,
       uif.has_unusual_items_flag,
       uif.earnings_quality_impact,
       br.beta_1y,
       br.beta_5y,
       br.beta_spread,
       br.beta_trend,
       qf.altman_z_score,
       qf.altman_z_trend,
       fdf.distress_risk_score,
       fdf.combined_distress_score,
       lf.debt_to_equity,
       lf.debt_to_assets,
       lf.equity_ratio,
       lf.interest_coverage,
       tdt.debt_fq,
       tdt.debt_fy,
       tdt.debt_ltm,
       tdt.debt_1fq,
       tdt.debt_2fq,
       tdt.debt_3fq,
       tdt.debt_4fq,
       tdt.debt_1fy,
       tdt.debt_2fy,
       tdt.debt_3fy,
       tdt.debt_4fy,
       tdt.debt_qoq_change,
       tdt.debt_yoy_change,
       tdt.debt_4q_trend,
       tdt.debt_3y_cagr,
       tdt.debt_deleveraging,
       tdt.debt_to_equity_trend,
       emf.revenue_per_employee,
       emf.profit_per_employee,
       emf.ebitda_per_employee,
       CURRENT_TIMESTAMP          AS feature_calculated_at
FROM vw_identifier_columns id
         JOIN equities e ON id.isin = e."ISIN"
         LEFT JOIN calc_growth_features() gf(isin, revenue_growth_yoy, ebitda_growth_yoy, operating_income_growth,
                                             fcf_growth, revenue_cagr_5y, forward_revenue_growth, revenue_vs_5y_avg)
                   ON id.isin = gf.isin
         LEFT JOIN calc_revenue_forecast_features() rff(isin, revenue_est_spread, revenue_beat_potential,
                                                        revenue_est_revision_trend, ebitda_est_vs_actual,
                                                        forward_revenue_multiple, revenue_estimate_count,
                                                        revenue_guidance_gap, consensus_revenue_growth,
                                                        ebit_estimate_spread, forward_ebitda_margin,
                                                        revenue_acceleration, estimate_confidence_score)
                   ON id.isin = rff.isin
         LEFT JOIN calc_revenue_estimate_consensus() rec(isin, revenue_est_avg_fy1e, revenue_est_med_fy1e,
                                                         revenue_est_avg_ntm, revenue_est_med_ntm,
                                                         revenue_avg_med_diff_pct, revenue_consensus_strength,
                                                         revenue_revision_trend, revenue_vs_current)
                   ON id.isin = rec.isin
         LEFT JOIN calc_revenue_quarterly_features() rqf(isin, revenue_fq, revenue_fy, revenue_ltm, revenue_5y_avg,
                                                         revenue_1fqfq, revenue_2fqfq, revenue_3fqfq, revenue_4fqfq,
                                                         revenue_1fy, revenue_2fy, revenue_3fy, revenue_4fy,
                                                         revenue_yoy_growth, revenue_vs_5y_avg, revenue_ltm_vs_fy,
                                                         revenue_fq_vs_5y_avg_fq, revenue_qoq_growth, revenue_qoq_2q,
                                                         revenue_qoq_3q, revenue_qoq_4q, revenue_yoy_quarterly,
                                                         revenue_2y_growth, revenue_3y_growth, revenue_4y_growth,
                                                         revenue_cagr_3y, revenue_cagr_4y, revenue_4q_trend,
                                                         revenue_4q_avg, revenue_fq_vs_4q_avg, revenue_growth_flag,
                                                         revenue_stability_score, revenue_accelerating_flag,
                                                         revenue_positive_qoq_streak) ON id.isin = rqf.isin
         LEFT JOIN calc_total_revenues_temporal() trt(isin, revenue_fq, revenue_ltm, revenue_fy, revenue_1fy,
                                                      revenue_5yavgfq, revenue_5yavgltm, revenue_growth_yoy,
                                                      revenue_vs_5y_avg_fq, revenue_vs_5y_avg_ltm, revenue_fq_vs_avg,
                                                      revenue_momentum) ON id.isin = trt.isin
         LEFT JOIN calc_cashflow_features() cf(isin, cfo_to_net_income, fcf_to_net_income, fcf_margin, cfo_growth_yoy,
                                               fcf_positive_ratio, acquisition_intensity, self_funding_ratio)
                   ON id.isin = cf.isin
         LEFT JOIN calc_enhanced_cashflow_features() ecff(isin, fcf_positive_years, fcf_always_positive,
                                                          capex_vs_5y_avg, underinvestment_flag, cfo_share_of_cf,
                                                          cfi_share_of_cf, cff_share_of_cf, self_funding_flag,
                                                          acquisition_to_fcf, sustainable_ma_flag, fcf_4q_improvement,
                                                          cash_flow_quality_score, capex_yoy_growth, capex_qoq_growth,
                                                          capex_3y_trend, capex_volatility, capex_acceleration,
                                                          capex_cut_flag, overinvestment_flag, acquisitions_yoy_growth,
                                                          acquisitions_vs_5y_avg, acquisitions_ltm_total,
                                                          ma_intensity_score, serial_acquirer_flag,
                                                          acquisition_pause_flag, total_investment_to_cfo,
                                                          organic_vs_inorganic, investment_efficiency)
                   ON id.isin = ecff.isin
         LEFT JOIN calc_cashflow_temporal_features() ctf(isin, cfo_quarterly_trend, cfo_yoy_quarterly,
                                                         cfi_quarterly_trend, cff_quarterly_trend, fcf_quarterly_trend,
                                                         cfo_positive_quarters, cfi_negative_quarters,
                                                         cff_pattern_score, cash_burn_rate, cf_volatility_score,
                                                         operating_cf_momentum, financing_dependency)
                   ON id.isin = ctf.isin
         LEFT JOIN calc_cashflow_comprehensive() cc(isin, cfo_fq, cfo_ltm, cfo_fy, fcf_fq, fcf_ltm, fcf_fy,
                                                    cfo_growth_yoy, fcf_growth_yoy, cfo_to_net_income, fcf_margin,
                                                    fcf_yield, cfo_positive_years, fcf_positive_years,
                                                    cash_flow_quality_score) ON id.isin = cc.isin
         LEFT JOIN calc_fcf_growth_estimates() fge(isin, fcf_est_fy1, fcf_est_fy2, fcf_est_fy3, fcf_est_fy4,
                                                   fcf_est_fy5, fcf_est_growth_fy1_vs_ltm, fcf_est_growth_fy2_vs_fy1,
                                                   fcf_est_growth_fy3_vs_fy2, fcf_est_growth_fy4_vs_fy3,
                                                   fcf_est_growth_fy5_vs_fy4, fcf_est_cagr_3y, fcf_est_cagr_5y,
                                                   fcf_est_margin_fy1, fcf_est_yield_fy1, fcf_est_growth_acceleration,
                                                   fcf_est_growth_deceleration, fcf_est_trajectory_score,
                                                   fcf_est_always_positive, fcf_est_vs_historical,
                                                   fcf_est_capex_implied_ratio) ON id.isin = fge.isin
         LEFT JOIN calc_total_assets_temporal() tat(isin, assets_fq, assets_fy, assets_ltm, assets_1fq, assets_2fq,
                                                    assets_3fq, assets_4fq, assets_1fy, assets_2fy, assets_3fy,
                                                    assets_4fy, assets_qoq_growth, assets_yoy_growth, assets_3y_cagr,
                                                    asset_growth_accel, asset_base_stable) ON id.isin = tat.isin
         LEFT JOIN calc_inventory_temporal_features() itf(isin, inventory_ltm, inventory_fq, inventory_fy,
                                                          inventory_1fq, inventory_2fq, inventory_3fq, inventory_4fq,
                                                          inventory_1fy, inventory_2fy, inventory_3fy, inventory_4fy,
                                                          inventory_qoq_change, inventory_yoy_change,
                                                          inventory_4q_trend, inventory_vs_5y_avg, inventory_days,
                                                          inventory_turnover, inventory_to_revenue, inventory_to_assets,
                                                          inventory_buildup_flag, inventory_reduction_flag,
                                                          inventory_volatility) ON id.isin = itf.isin
         LEFT JOIN calc_goodwill_temporal_features() gtf(isin, goodwill_fq, goodwill_ltm, goodwill_fy, goodwill_1fq,
                                                         goodwill_2fq, goodwill_3fq, goodwill_4fq, goodwill_1fy,
                                                         goodwill_2fy, goodwill_3fy, goodwill_4fy, goodwill_qoq_change,
                                                         goodwill_yoy_change, goodwill_3y_growth, goodwill_vs_5y_avg,
                                                         recent_acquisition_flag, goodwill_accumulation_rate,
                                                         goodwill_to_assets_trend, impairment_risk_score,
                                                         goodwill_concentration) ON id.isin = gtf.isin
         LEFT JOIN calc_earnings_features() ef(isin, eps_surprise_pct, revenue_surprise_pct, eps_adjustment_ratio,
                                               gaap_adj_eps_gap_pct, ebitda_adjustment_ratio, eps_quarterly_trend,
                                               eps_yoy_growth) ON id.isin = ef.isin
         LEFT JOIN calc_eps_trajectory_features() etf(isin, eps_qoq_growth, eps_yoy_quarterly, eps_positive_streak,
                                                      eps_cagr_3y, eps_cagr_5y, eps_growth_accel, eps_vs_5y_avg,
                                                      eps_improvement_count, eps_trajectory_score, eps_stability)
                   ON id.isin = etf.isin
         LEFT JOIN calc_eps_comprehensive() ec(isin, eps_basic_fq, eps_basic_ltm, eps_basic_fy, eps_adj_ltm,
                                               eps_norm_est_fy1e, eps_growth_yoy, eps_cagr_3y, eps_adjustment_ratio,
                                               eps_positive_years, eps_trajectory_score) ON id.isin = ec.isin
         LEFT JOIN calc_eps_continuing_features() ecf(isin, eps_cont_ltm, eps_cont_fq, eps_cont_fy, eps_cont_1fqfq,
                                                      eps_cont_2fqfq, eps_cont_3fqfq, eps_cont_4fqfq, eps_cont_1fy,
                                                      eps_cont_2fy, eps_cont_3fy, eps_cont_4fy, eps_cont_qoq_growth,
                                                      eps_cont_yoy_growth, eps_cont_cagr_3y, eps_cont_vs_total_eps,
                                                      eps_cont_positive_streak, eps_cont_trajectory_score,
                                                      discontinued_ops_impact, core_earnings_stability)
                   ON id.isin = ecf.isin
         LEFT JOIN calc_gaap_adjusted_analytics() gaa(isin, eps_adjustment_spread_ltm, eps_adjustment_spread_fy,
                                                      eps_adjustment_spread_1fy, eps_adjustment_spread_fq,
                                                      eps_adjustment_spread_1fqfq, eps_adjustment_spread_2fqfq,
                                                      eps_adjustment_spread_3fqfq, eps_adjustment_spread_4fqfq,
                                                      eps_adjustment_spread_2fy, eps_adjustment_spread_3fy,
                                                      eps_adjustment_spread_4fy, eps_adjustment_pct,
                                                      net_income_adjustment_ratio_ltm, net_income_adjustment_ratio_fy,
                                                      net_income_adjustment_ratio_1fy, net_income_adjustment_ratio_fq,
                                                      net_income_adjustment_ratio_5yavgfq,
                                                      net_income_adjustment_ratio_1fqfq,
                                                      net_income_adjustment_ratio_2fqfq,
                                                      net_income_adjustment_ratio_3fqfq,
                                                      net_income_adjustment_ratio_4fqfq,
                                                      net_income_adjustment_ratio_2fy, net_income_adjustment_ratio_3fy,
                                                      net_income_adjustment_ratio_4fy, net_income_adjustment_pct,
                                                      ebitda_adjustment_pct_ltm, ebitda_adjustment_pct_fy,
                                                      ebitda_adjustment_pct_1fy, ebitda_adjustment_pct_fq,
                                                      ebitda_adjustment_pct_1fqfq, ebitda_adjustment_pct_2fqfq,
                                                      ebitda_adjustment_pct_3fqfq, ebitda_adjustment_pct_4fqfq,
                                                      ebitda_adjustment_pct_2fy, ebitda_adjustment_pct_3fy,
                                                      ebitda_adjustment_pct_4fy, ebit_adjustment_pct_ltm,
                                                      ebit_adjustment_pct_fy, ebit_adjustment_pct_1fy,
                                                      ebit_adjustment_pct_fq, ebit_adjustment_pct_1fqfq,
                                                      ebit_adjustment_pct_2fqfq, ebit_adjustment_pct_3fqfq,
                                                      ebit_adjustment_pct_4fqfq, ebit_adjustment_pct_2fy,
                                                      ebit_adjustment_pct_3fy, ebit_adjustment_pct_4fy,
                                                      earnings_quality_score, earnings_quality_warning,
                                                      forward_eps_gaap_adj_spread) ON id.isin = gaa.isin
         LEFT JOIN calc_gaap_revision_features() grf(isin, gaap_revision_momentum, gaap_revision_1m, gaap_revision_3m,
                                                     gaap_revision_6m, gaap_revision_1y, gaap_vs_norm_revision_spread,
                                                     gaap_revision_acceleration, gaap_positive_revision_flag,
                                                     revision_quality_divergence) ON id.isin = grf.isin
         LEFT JOIN calc_cost_structure_features() csf(isin, cogs_to_revenue, opex_to_revenue, sga_to_revenue,
                                                      rnd_to_revenue, interest_to_revenue, sga_trend_yoy,
                                                      operating_leverage_proxy, cost_efficiency_score,
                                                      marketing_to_revenue, marketing_trend_yoy, marketing_vs_5y_avg,
                                                      sga_vs_5y_avg, sga_efficiency_trend) ON id.isin = csf.isin
         LEFT JOIN calc_rnd_temporal_features() rtf(isin, rnd_ltm, rnd_fq, rnd_fy, rnd_1fqfq, rnd_2fqfq, rnd_3fqfq,
                                                    rnd_4fqfq, rnd_1fy, rnd_2fy, rnd_3fy, rnd_4fy, rnd_intensity_ltm,
                                                    rnd_intensity_fy, rnd_intensity_trend, rnd_qoq_growth,
                                                    rnd_yoy_growth, rnd_cagr_3y, rnd_per_employee, rnd_to_gross_profit,
                                                    rnd_roi_proxy, rnd_increasing_flag, rnd_cut_flag,
                                                    high_rnd_intensity_flag) ON id.isin = rtf.isin
         LEFT JOIN calc_interest_income_features() iif(isin, interest_income_ltm, interest_expense_ltm,
                                                       net_interest_income, interest_coverage_ratio,
                                                       interest_income_to_revenue, interest_expense_to_revenue,
                                                       net_interest_margin_proxy) ON id.isin = iif.isin
         LEFT JOIN calc_profitability_features() pf(isin, roe, roa, gross_margin_pct, operating_margin_pct,
                                                    net_margin_pct, ebitda_margin_pct, roic, rnd_intensity,
                                                    equity_multiplier) ON id.isin = pf.isin
         LEFT JOIN calc_margin_trends() mt(isin, gross_margin_trend_yoy, operating_margin_trend, net_margin_trend_yoy,
                                           ebitda_margin_trend, margin_expansion_flag, margin_stability_score)
                   ON id.isin = mt.isin
         LEFT JOIN calc_ebit_ebitda_comprehensive() eec(isin, ebit_fq, ebit_ltm, ebit_fy, ebit_1fy, ebitda_fq,
                                                        ebitda_ltm, ebitda_fy, ebitda_1fy, ebit_2fy, ebit_3fy, ebit_4fy,
                                                        ebitda_2fy, ebitda_3fy, ebitda_4fy, ebit_1fqfq, ebit_2fqfq,
                                                        ebit_3fqfq, ebit_4fqfq, ebitda_1fqfq, ebitda_2fqfq,
                                                        ebitda_3fqfq, ebitda_4fqfq, ebit_5yavgfq, ebit_5yavgltm,
                                                        ebitda_5yavgfq, ebitda_5yavgltm, ebit_adj_fq, ebit_adj_ltm,
                                                        ebit_adj_fy, ebitda_adj_fq, ebitda_adj_ltm, ebitda_adj_fy,
                                                        ebit_growth_yoy, ebitda_growth_yoy, ebit_margin_ltm,
                                                        ebitda_margin_ltm, ebit_positive_years, ebitda_positive_years,
                                                        ebit_qoq_growth, ebitda_qoq_growth, ebit_cagr_3y,
                                                        ebitda_cagr_3y, ebit_vs_5y_avg, ebitda_vs_5y_avg)
                   ON id.isin = eec.isin
         LEFT JOIN calc_gross_profit_temporal() gpt(isin, gp_fq, gp_fy, gp_ltm, gp_1fqfq, gp_2fqfq, gp_3fqfq, gp_4fqfq,
                                                    gp_1fy, gp_2fy, gp_3fy, gp_4fy, gp_qoq_growth, gp_yoy_growth,
                                                    gp_margin_fq, gp_margin_trend, gp_positive_quarters,
                                                    gp_margin_expansion) ON id.isin = gpt.isin
         LEFT JOIN calc_unusual_items_features() uif(isin, other_unusual_items_ltm, impairment_goodwill_ltm,
                                                     asset_writedown_ltm, restructuring_charges_ltm,
                                                     total_unusual_items, unusual_items_to_revenue,
                                                     unusual_items_to_ebitda, has_unusual_items_flag,
                                                     earnings_quality_impact) ON id.isin = uif.isin
         LEFT JOIN calc_quality_features() qf(isin, has_goodwill_impairment, has_asset_writedown, has_restructuring,
                                              goodwill_to_assets_pct, intangible_intensity, exceptional_items_to_ebitda,
                                              altman_z_score, altman_z_trend, current_ratio, quick_ratio)
                   ON id.isin = qf.isin
         LEFT JOIN calc_beta_risk_features() br(isin, beta_1y, beta_5y, beta_spread, beta_trend, high_beta_flag,
                                                low_beta_flag, beta_stability_score) ON id.isin = br.isin
         LEFT JOIN calc_financial_distress_features() fdf(isin, distress_risk_score, liquidity_stress_score,
                                                          working_capital_trend, cash_runway_months,
                                                          combined_distress_score, wc_deteriorating_flag,
                                                          retained_earnings_growth, accumulated_deficit_flag,
                                                          adequate_cash_buffer) ON id.isin = fdf.isin
         LEFT JOIN calc_leverage_features() lf(isin, debt_to_equity, debt_to_assets, equity_ratio, interest_coverage,
                                               current_ratio, cash_ratio, working_capital_ratio) ON id.isin = lf.isin
         LEFT JOIN calc_total_debt_temporal() tdt(isin, debt_fq, debt_fy, debt_ltm, debt_1fq, debt_2fq, debt_3fq,
                                                  debt_4fq, debt_1fy, debt_2fy, debt_3fy, debt_4fy, debt_qoq_change,
                                                  debt_yoy_change, debt_4q_trend, debt_3y_cagr, debt_deleveraging,
                                                  debt_to_equity_trend) ON id.isin = tdt.isin
         LEFT JOIN calc_employment_features() emf(isin, revenue_per_employee, profit_per_employee, ebitda_per_employee,
                                                  assets_per_employee, fte_growth_1y_pct, fte_growth_3y_pct,
                                                  workforce_stability) ON id.isin = emf.isin;

comment on materialized view mv_dcf is 'Materialized view for probabilistic Discounted Cash Flow (DCF) analysis.
    Combines features from 5 core views + supplementary inputs:

    Core Feature Views (per specification):
      1. Growth           (5 functions) - Revenue forecasts, growth rates, CAGR
      2. Cash Flow        (5 functions) - CFO, FCF, CapEx, FCF estimates
      3. Balance Sheet    (3 functions) - Assets, inventory, goodwill trends
      4. Earnings         (6 functions) - EPS, GAAP adjustments, revisions
      5. Cost Structure   (3 functions) - COGS, SG&A, R&D, interest analysis

    Supplementary Inputs:
      6. Profitability    (4 functions) - Margins for FCF margin forecasting
      7. Unusual Items    (1 function)  - Earnings quality normalization
      8. Quality & Risk   (2 functions) - Beta/distress for discount rate
      9. Leverage         (2 functions) - Debt structure for WACC
     10. Employment       (1 function)  - Productivity for revenue/employee

    Total: 32 calc_* functions joined via ISIN.
    Refresh with: REFRESH MATERIALIZED VIEW CONCURRENTLY mv_dcf;';

alter materialized view mv_dcf owner to postgres;

create unique index idx_mv_dcf_isin
    on mv_dcf (isin);

create index idx_mv_dcf_sector
    on mv_dcf (sector);

create index idx_mv_dcf_industry
    on mv_dcf (industry);

create index idx_mv_dcf_country
    on mv_dcf (country);

