create view vw_features_earnings
            (isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
             dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
             next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
             dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
             dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
             next_fy_end_date, next_income_statement_report_date, reference_date, eps_surprise_pct,
             revenue_surprise_pct, eps_adjustment_ratio, gaap_adj_eps_gap_pct, ebitda_adjustment_ratio,
             eps_quarterly_trend, eps_yoy_growth, eps_qoq_growth, eps_yoy_quarterly, eps_positive_streak, eps_cagr_3y,
             eps_cagr_5y, eps_growth_accel, eps_vs_5y_avg, eps_improvement_count, eps_trajectory_score, eps_stability,
             eps_basic_fq, eps_basic_ltm, eps_basic_fy, eps_adj_ltm, eps_norm_est_fy1e, eps_growth_yoy_comp,
             eps_cagr_3y_comp, eps_adjustment_ratio_comp, eps_positive_years, eps_trajectory_score_comp, eps_cont_ltm,
             eps_cont_fq, eps_cont_fy, eps_cont_1fqfq, eps_cont_2fqfq, eps_cont_3fqfq, eps_cont_4fqfq, eps_cont_1fy,
             eps_cont_2fy, eps_cont_3fy, eps_cont_4fy, eps_cont_qoq_growth, eps_cont_yoy_growth, eps_cont_cagr_3y,
             eps_cont_vs_total_eps, eps_cont_positive_streak, eps_cont_trajectory_score, discontinued_ops_impact,
             core_earnings_stability, eps_adjustment_spread_ltm, eps_adjustment_spread_fy, eps_adjustment_pct,
             net_income_adjustment_ratio_ltm, net_income_adjustment_ratio_fy, net_income_adjustment_pct,
             ebitda_adjustment_pct_ltm, ebitda_adjustment_pct_fy, ebit_adjustment_pct_ltm, ebit_adjustment_pct_fy,
             earnings_quality_score, earnings_quality_warning, forward_eps_gaap_adj_spread, gaap_revision_momentum,
             gaap_revision_1m, gaap_revision_3m, gaap_revision_6m, gaap_revision_1y, gaap_vs_norm_revision_spread,
             gaap_revision_acceleration, gaap_positive_revision_flag, revision_quality_divergence)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       ef.eps_surprise_pct,
       ef.revenue_surprise_pct,
       ef.eps_adjustment_ratio,
       ef.gaap_adj_eps_gap_pct,
       ef.ebitda_adjustment_ratio,
       ef.eps_quarterly_trend,
       ef.eps_yoy_growth,
       etf.eps_qoq_growth,
       etf.eps_yoy_quarterly,
       etf.eps_positive_streak,
       etf.eps_cagr_3y,
       etf.eps_cagr_5y,
       etf.eps_growth_accel,
       etf.eps_vs_5y_avg,
       etf.eps_improvement_count,
       etf.eps_trajectory_score,
       etf.eps_stability,
       ec.eps_basic_fq,
       ec.eps_basic_ltm,
       ec.eps_basic_fy,
       ec.eps_adj_ltm,
       ec.eps_norm_est_fy1e,
       ec.eps_growth_yoy       AS eps_growth_yoy_comp,
       ec.eps_cagr_3y          AS eps_cagr_3y_comp,
       ec.eps_adjustment_ratio AS eps_adjustment_ratio_comp,
       ec.eps_positive_years,
       ec.eps_trajectory_score AS eps_trajectory_score_comp,
       ecf.eps_cont_ltm,
       ecf.eps_cont_fq,
       ecf.eps_cont_fy,
       ecf.eps_cont_1fqfq,
       ecf.eps_cont_2fqfq,
       ecf.eps_cont_3fqfq,
       ecf.eps_cont_4fqfq,
       ecf.eps_cont_1fy,
       ecf.eps_cont_2fy,
       ecf.eps_cont_3fy,
       ecf.eps_cont_4fy,
       ecf.eps_cont_qoq_growth,
       ecf.eps_cont_yoy_growth,
       ecf.eps_cont_cagr_3y,
       ecf.eps_cont_vs_total_eps,
       ecf.eps_cont_positive_streak,
       ecf.eps_cont_trajectory_score,
       ecf.discontinued_ops_impact,
       ecf.core_earnings_stability,
       gaa.eps_adjustment_spread_ltm,
       gaa.eps_adjustment_spread_fy,
       gaa.eps_adjustment_pct,
       gaa.net_income_adjustment_ratio_ltm,
       gaa.net_income_adjustment_ratio_fy,
       gaa.net_income_adjustment_pct,
       gaa.ebitda_adjustment_pct_ltm,
       gaa.ebitda_adjustment_pct_fy,
       gaa.ebit_adjustment_pct_ltm,
       gaa.ebit_adjustment_pct_fy,
       gaa.earnings_quality_score,
       gaa.earnings_quality_warning,
       gaa.forward_eps_gaap_adj_spread,
       grf.gaap_revision_momentum,
       grf.gaap_revision_1m,
       grf.gaap_revision_3m,
       grf.gaap_revision_6m,
       grf.gaap_revision_1y,
       grf.gaap_vs_norm_revision_spread,
       grf.gaap_revision_acceleration,
       grf.gaap_positive_revision_flag,
       grf.revision_quality_divergence
FROM vw_identifier_columns id
         LEFT JOIN calc_earnings_features() ef(isin, eps_surprise_pct, revenue_surprise_pct, eps_adjustment_ratio,
                                               gaap_adj_eps_gap_pct, ebitda_adjustment_ratio, eps_quarterly_trend,
                                               eps_yoy_growth) USING (isin)
         LEFT JOIN calc_eps_trajectory_features() etf(isin, eps_qoq_growth, eps_yoy_quarterly, eps_positive_streak,
                                                      eps_cagr_3y, eps_cagr_5y, eps_growth_accel, eps_vs_5y_avg,
                                                      eps_improvement_count, eps_trajectory_score, eps_stability)
                   USING (isin)
         LEFT JOIN calc_eps_comprehensive() ec(isin, eps_basic_fq, eps_basic_ltm, eps_basic_fy, eps_adj_ltm,
                                               eps_norm_est_fy1e, eps_growth_yoy, eps_cagr_3y, eps_adjustment_ratio,
                                               eps_positive_years, eps_trajectory_score) USING (isin)
         LEFT JOIN calc_eps_continuing_features() ecf(isin, eps_cont_ltm, eps_cont_fq, eps_cont_fy, eps_cont_1fqfq,
                                                      eps_cont_2fqfq, eps_cont_3fqfq, eps_cont_4fqfq, eps_cont_1fy,
                                                      eps_cont_2fy, eps_cont_3fy, eps_cont_4fy, eps_cont_qoq_growth,
                                                      eps_cont_yoy_growth, eps_cont_cagr_3y, eps_cont_vs_total_eps,
                                                      eps_cont_positive_streak, eps_cont_trajectory_score,
                                                      discontinued_ops_impact, core_earnings_stability) USING (isin)
         LEFT JOIN calc_gaap_adjusted_analytics() gaa(isin, eps_adjustment_spread_ltm, eps_adjustment_spread_fy,
                                                      eps_adjustment_spread_1fy, eps_adjustment_spread_fq,
                                                      eps_adjustment_spread_1fqfq, eps_adjustment_spread_2fqfq,
                                                      eps_adjustment_spread_3fqfq, eps_adjustment_spread_4fqfq,
                                                      eps_adjustment_spread_2fy, eps_adjustment_spread_3fy,
                                                      eps_adjustment_spread_4fy, eps_adjustment_pct,
                                                      net_income_adjustment_ratio_ltm, net_income_adjustment_ratio_fy,
                                                      net_income_adjustment_ratio_1fy, net_income_adjustment_ratio_fq,
                                                      net_income_adjustment_ratio_5yavgfq,
                                                      net_income_adjustment_ratio_1fqfq,
                                                      net_income_adjustment_ratio_2fqfq,
                                                      net_income_adjustment_ratio_3fqfq,
                                                      net_income_adjustment_ratio_4fqfq,
                                                      net_income_adjustment_ratio_2fy, net_income_adjustment_ratio_3fy,
                                                      net_income_adjustment_ratio_4fy, net_income_adjustment_pct,
                                                      ebitda_adjustment_pct_ltm, ebitda_adjustment_pct_fy,
                                                      ebitda_adjustment_pct_1fy, ebitda_adjustment_pct_fq,
                                                      ebitda_adjustment_pct_1fqfq, ebitda_adjustment_pct_2fqfq,
                                                      ebitda_adjustment_pct_3fqfq, ebitda_adjustment_pct_4fqfq,
                                                      ebitda_adjustment_pct_2fy, ebitda_adjustment_pct_3fy,
                                                      ebitda_adjustment_pct_4fy, ebit_adjustment_pct_ltm,
                                                      ebit_adjustment_pct_fy, ebit_adjustment_pct_1fy,
                                                      ebit_adjustment_pct_fq, ebit_adjustment_pct_1fqfq,
                                                      ebit_adjustment_pct_2fqfq, ebit_adjustment_pct_3fqfq,
                                                      ebit_adjustment_pct_4fqfq, ebit_adjustment_pct_2fy,
                                                      ebit_adjustment_pct_3fy, ebit_adjustment_pct_4fy,
                                                      earnings_quality_score, earnings_quality_warning,
                                                      forward_eps_gaap_adj_spread) USING (isin)
         LEFT JOIN calc_gaap_revision_features() grf(isin, gaap_revision_momentum, gaap_revision_1m, gaap_revision_3m,
                                                     gaap_revision_6m, gaap_revision_1y, gaap_vs_norm_revision_spread,
                                                     gaap_revision_acceleration, gaap_positive_revision_flag,
                                                     revision_quality_divergence) USING (isin);

comment on view vw_features_earnings is 'Earnings metrics including EPS analysis, GAAP adjustments, and revision trends.
    Source functions: calc_earnings_features, calc_eps_trajectory_features, calc_eps_comprehensive,
    calc_eps_continuing_features, calc_gaap_adjusted_analytics, calc_gaap_revision_features';

alter table vw_features_earnings
    owner to postgres;

