create view vw_features_momentum
            (isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
             dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
             next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
             dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
             dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
             next_fy_end_date, next_income_statement_report_date, reference_date, price_momentum_1m, price_momentum_3m,
             price_momentum_6m, price_momentum_1y, price_momentum_5d, ema_crossover_20_50, ema_crossover_50_250,
             price_vs_ema_20d, price_vs_ema_250d, pct_off_52w_high, pct_above_52w_low, range_52w_position,
             beta_momentum, volatility_regime, price_momentum_1y_long, price_momentum_3y, price_momentum_5y,
             long_term_trend_score, price_vs_ema_250d_long, multi_year_high_flag, secular_trend_flag)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       mf.price_momentum_1m,
       mf.price_momentum_3m,
       mf.price_momentum_6m,
       mf.price_momentum_1y,
       mf.price_momentum_5d,
       mf.ema_crossover_20_50,
       mf.ema_crossover_50_250,
       mf.price_vs_ema_20d,
       mf.price_vs_ema_250d,
       mf.pct_off_52w_high,
       mf.pct_above_52w_low,
       mf.range_52w_position,
       mf.beta_momentum,
       mf.volatility_regime,
       ltm.price_momentum_1y AS price_momentum_1y_long,
       ltm.price_momentum_3y,
       ltm.price_momentum_5y,
       ltm.long_term_trend_score,
       ltm.price_vs_ema_250d AS price_vs_ema_250d_long,
       ltm.multi_year_high_flag,
       ltm.secular_trend_flag
FROM vw_identifier_columns id
         LEFT JOIN calc_momentum_features() mf(isin, price_momentum_1m, price_momentum_3m, price_momentum_6m,
                                               price_momentum_1y, price_momentum_5d, ema_crossover_20_50,
                                               ema_crossover_50_250, price_vs_ema_20d, price_vs_ema_250d,
                                               pct_off_52w_high, pct_above_52w_low, range_52w_position, beta_momentum,
                                               volatility_regime) USING (isin)
         LEFT JOIN calc_long_term_momentum_features() ltm(isin, price_momentum_1y, price_momentum_3y, price_momentum_5y,
                                                          long_term_trend_score, price_vs_ema_250d,
                                                          multi_year_high_flag, secular_trend_flag, total_return_ytd,
                                                          total_return_5y, total_return_10y, return_cagr_3y,
                                                          return_cagr_10y, return_vs_price_momentum,
                                                          return_consistency_score) USING (isin);

comment on view vw_features_momentum is 'Price momentum and trend indicators across multiple timeframes.
    Source functions: calc_momentum_features, calc_long_term_momentum_features';

alter table vw_features_momentum
    owner to postgres;

