create view vw_features_composite_scores
            (isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
             dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
             next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
             dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
             dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
             next_fy_end_date, next_income_statement_report_date, reference_date, piotroski_f_score,
             eps_trajectory_score, dilution_score, quality_momentum_score, net_income_is_fq, net_income_is_ltm,
             net_income_is_fy, net_income_adj_ltm, normalized_ni_ltm, net_income_is_1fqfq, net_income_is_2fqfq,
             net_income_is_3fqfq, net_income_is_4fqfq, net_income_is_1fy, net_income_is_2fy, net_income_is_3fy,
             net_income_is_4fy, net_income_is_5yavgfq, net_income_is_5yavgltm, normalized_ni_5yavgfq,
             normalized_ni_5yavgltm, net_income_growth_yoy, net_income_margin_ltm, ni_adjustment_ratio,
             net_income_positive_years, earnings_quality_composite, net_income_qoq_growth, net_income_yoy_quarterly,
             net_income_vs_5y_avg, normalized_ni_vs_5y_avg)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       cs.piotroski_f_score,
       etf.eps_trajectory_score,
       cs.dilution_score,
       cs.quality_momentum_score,
       nic.net_income_is_fq,
       nic.net_income_is_ltm,
       nic.net_income_is_fy,
       nic.net_income_adj_ltm,
       nic.normalized_ni_ltm,
       nic.net_income_is_1fqfq,
       nic.net_income_is_2fqfq,
       nic.net_income_is_3fqfq,
       nic.net_income_is_4fqfq,
       nic.net_income_is_1fy,
       nic.net_income_is_2fy,
       nic.net_income_is_3fy,
       nic.net_income_is_4fy,
       nic.net_income_is_5yavgfq,
       nic.net_income_is_5yavgltm,
       nic.normalized_ni_5yavgfq,
       nic.normalized_ni_5yavgltm,
       nic.net_income_growth_yoy,
       nic.net_income_margin_ltm,
       nic.ni_adjustment_ratio,
       nic.net_income_positive_years,
       nic.earnings_quality_composite,
       nic.net_income_qoq_growth,
       nic.net_income_yoy_quarterly,
       nic.net_income_vs_5y_avg,
       nic.normalized_ni_vs_5y_avg
FROM vw_identifier_columns id
         LEFT JOIN calc_composite_scores() cs(isin, piotroski_f_score, dilution_score, quality_momentum_score)
                   USING (isin)
         LEFT JOIN calc_eps_trajectory_features() etf(isin, eps_qoq_growth, eps_yoy_quarterly, eps_positive_streak,
                                                      eps_cagr_3y, eps_cagr_5y, eps_growth_accel, eps_vs_5y_avg,
                                                      eps_improvement_count, eps_trajectory_score, eps_stability)
                   USING (isin)
         LEFT JOIN calc_net_income_comprehensive() nic(isin, net_income_is_fq, net_income_is_ltm, net_income_is_fy,
                                                       net_income_adj_ltm, normalized_ni_ltm, net_income_is_1fqfq,
                                                       net_income_is_2fqfq, net_income_is_3fqfq, net_income_is_4fqfq,
                                                       net_income_is_1fy, net_income_is_2fy, net_income_is_3fy,
                                                       net_income_is_4fy, net_income_is_5yavgfq, net_income_is_5yavgltm,
                                                       normalized_ni_5yavgfq, normalized_ni_5yavgltm,
                                                       net_income_growth_yoy, net_income_margin_ltm,
                                                       ni_adjustment_ratio, net_income_positive_years,
                                                       earnings_quality_composite, net_income_qoq_growth,
                                                       net_income_yoy_quarterly, net_income_vs_5y_avg,
                                                       normalized_ni_vs_5y_avg) USING (isin);

comment on view vw_features_composite_scores is 'Composite scoring metrics including Piotroski F-Score and earnings quality.
    Source functions: calc_composite_scores, calc_net_income_comprehensive';

alter table vw_features_composite_scores
    owner to postgres;

