-- =============================================================================
-- UNIFIED MATERIALIZED VIEW - ALL STOCK FEATURES (RESTRUCTURED)
-- Aligns with 17 feature views covering all 54 calc_* functions
-- Standardized identifier column ordering per calculated_features_registry
-- =============================================================================

-- Pre-flight check: ensure prerequisite functions exist
DO
$$
    BEGIN
        -- Verify critical helper functions exist
        IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'safe_divide') THEN
            RAISE EXCEPTION 'Required function safe_divide() does not exist. Run feature_registry.sql first.';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'calc_piotroski_f_score') THEN
            RAISE EXCEPTION 'Required function calc_piotroski_f_score() does not exist. Run feature_registry.sql first.';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'pct_change') THEN
            RAISE EXCEPTION 'Required function pct_change() does not exist. Run feature_registry.sql first.';
        END IF;
    END
$$;

DROP MATERIALIZED VIEW IF EXISTS mv_exp_returns_df CASCADE;

-- =============================================================================
-- Registry-driven materialized view build.
--
-- The explicit column list / LEFT JOIN list previously hard-coded here produced
-- physical rows exceeding PostgreSQL's 8160-byte heap page limit
--   (ERROR: row is too big: size 8168, maximum size 8160).
--
-- The revised approach keeps only the identifier (id.*) and equities (e.*)
-- columns hardcoded and derives the remaining feature columns and LEFT JOINs
-- dynamically from calculated_features_registry using the clause:
--
--   select calculated_features_registry.category,
--          calculated_features_registry.feature_alias
--   from   calculated_features_registry
--   where  source_function notnull and calculation_type <> 'direct'
--   order  by category, source_function, feature_alias;
--
-- Only features whose `source_function` is registered and whose
-- `calculation_type` is not 'direct' are materialized here.  All id.* and e.*
-- columns (whose registry rows are `calculation_type = 'direct'`) are excluded
-- from the dynamic list and emitted as the static preamble below.
-- =============================================================================
DO
$build$
    DECLARE
        v_select_cols text;
        v_joins       text;
        v_sql         text;
    BEGIN
        -- Build one LEFT JOIN per distinct source_function, aliased as j_<fn>.
        -- Each calc_* set-returning function is wrapped in a subquery so the
        -- exact column signature does not need to be re-declared here.
        SELECT string_agg(
                       format('LEFT JOIN (SELECT * FROM %I()) j_%s ON id.isin = j_%s.isin',
                              source_function, source_function, source_function),
                       E'\n         '
                       ORDER BY source_function)
        INTO v_joins
        FROM (SELECT DISTINCT source_function
              FROM calculated_features_registry
              WHERE source_function IS NOT NULL
                AND calculation_type <> 'direct') sf;

        -- Build the dynamic SELECT column list.  Ordering matches the revised
        -- registry clause: category, source_function, feature_alias.
        SELECT string_agg(
                       format('j_%s.%I', source_function, feature_alias),
                       E',' || E'\n       '
                       ORDER BY category, source_function, feature_alias)
        INTO v_select_cols
        FROM calculated_features_registry
        WHERE source_function IS NOT NULL
          AND calculation_type <> 'direct';

        IF v_select_cols IS NULL OR v_joins IS NULL THEN
            RAISE EXCEPTION
                'calculated_features_registry returned no rows for source_function NOTNULL AND calculation_type <> ''direct''. '
                    'Populate the registry before creating mv_exp_returns_df.';
        END IF;

        v_sql := format($mv$
create materialized view mv_exp_returns_df as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       e."Market Cap"                      AS market_cap,
       e."Enterprise Value"                AS enterprise_value,
       e."Last Price"                      AS last_price,
       e."Price Target"                    AS price_target,
       e."Price Target - High"             AS price_target_high,
       e."Price Target - Low"              AS price_target_low,
       e."Price Target - Median"           AS price_target_median,
       %s,
       CURRENT_TIMESTAMP                   AS feature_calculated_at
FROM vw_identifier_columns id
         JOIN equities e ON id.isin = e."ISIN"
         %s
$mv$, v_select_cols, v_joins);

        EXECUTE v_sql;
    END
$build$;

-- The placeholder SELECT below is never executed; it exists only so that
-- downstream tooling which scans this file for the mv_exp_returns_df column
-- contract can still locate the hardcoded identifier/equities preamble.
-- The authoritative definition is produced by the DO block above.
--
-- BEGIN_STATIC_PREAMBLE_REFERENCE
/*
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       e."Market Cap"                      AS market_cap,
       e."Enterprise Value"                AS enterprise_value,
       e."Last Price"                      AS last_price,
       e."Price Target"                    AS price_target,
       e."Price Target - High"             AS price_target_high,
       e."Price Target - Low"              AS price_target_low,
       e."Price Target - Median"           AS price_target_median
FROM vw_identifier_columns id
         JOIN equities e ON id.isin = e."ISIN";
*/
-- END_STATIC_PREAMBLE_REFERENCE

-- Suppress the now-obsolete hard-coded feature SELECT/JOIN block below.
-- It is preserved inside a /* ... */ comment purely for historical reference
-- so reviewers can diff the materialized columns against the registry-driven
-- output if needed.  The actual view has already been created by the DO block.
/*
SELECT_LEGACY_FEATURE_COLUMNS_START
       vf.p_e_ratio,
       vf.p_b_ratio,
       vf.ev_ebitda_ratio,
       vf.ev_sales_ratio,
       vf.dividend_yield                   AS valuation_dividend_yield,
       vf.peg_ratio,
       vts.ev_sales_trend_1y,
       vts.ev_ebitda_momentum,
       vts.p_e_momentum_yoy,
       vts.p_e_momentum_qoq,
       vts.ev_sales_vs_3y_avg,
       vts.ev_ebitda_vs_3y_avg,
       vts.p_e_vs_3y_avg,
       vts.ev_sales_forward_discount,
       vts.ev_ebitda_forward_discount,
       vts.p_e_forward_discount,
       vts.p_b_vs_5y_avg,
       evt.ev_sales_qoq_1q,
       evt.ev_sales_qoq_2q,
       evt.ev_sales_qoq_3q,
       evt.ev_sales_qoq_4q,
       evt.p_e_vs_5y_avg,
       evt.p_e_percentile_proxy,
       evt.valuation_mean_reversion,
       evt.ev_ebitda_qoq_trend,
       evt.p_b_momentum_yoy,
       evt.valuation_compression,
       evt.forward_pe_premium,
       tb.tangible_book_value_fy,
       tb.tangible_book_value_ltm,
       tb.tangible_book_per_share,
       tb.price_to_tangible_book,
       tb.tangible_equity_ratio,
       tb.intangibles_to_equity,
       tb.goodwill_to_equity,
       tb.tangible_asset_quality,
       tb.tbv_yoy_growth,
       tb.tbv_vs_calculated,
       mf.price_momentum_1m,
       mf.price_momentum_3m,
       mf.price_momentum_6m,
       mf.price_momentum_1y,
       mf.price_momentum_5d,
       mf.ema_crossover_20_50,
       mf.ema_crossover_50_250,
       mf.price_vs_ema_20d,
       mf.price_vs_ema_250d,
       mf.pct_off_52w_high,
       mf.pct_above_52w_low,
       mf.range_52w_position,
       mf.beta_momentum,
       mf.volatility_regime,
       ltm.price_momentum_3y,
       ltm.price_momentum_5y,
       ltm.long_term_trend_score,
       ltm.multi_year_high_flag,
       ltm.secular_trend_flag,
       ta.ema_slope_20d,
       ta.ema_trend_consistency,
       ta.price_vs_ema_100d,
       ta.near_52w_high_flag,
       ta.near_52w_low_flag,
       ta.volume_momentum_score,
       ta.breakout_signal,
       ta.high_volume_flag,
       ta.low_volume_flag,
       ta.volatility_compression,
       ta.volatility_term_structure,
       pf.roe,
       pf.roa,
       pf.gross_margin_pct,
       pf.operating_margin_pct,
       pf.net_margin_pct,
       pf.ebitda_margin_pct,
       pf.roic,
       pf.rnd_intensity,
       pf.equity_multiplier,
       mt.gross_margin_trend_yoy,
       mt.operating_margin_trend,
       mt.net_margin_trend_yoy,
       mt.ebitda_margin_trend,
       mt.margin_expansion_flag,
       mt.margin_stability_score,
       eec.ebit_fq,
       eec.ebit_ltm,
       eec.ebit_fy,
       eec.ebit_1fy,
       eec.ebit_2fy,
       eec.ebit_3fy,
       eec.ebit_4fy,
       eec.ebit_1fqfq,
       eec.ebit_2fqfq,
       eec.ebit_3fqfq,
       eec.ebit_4fqfq,
       eec.ebit_5yavgfq,
       eec.ebit_5yavgltm,
       eec.ebit_adj_fq,
       eec.ebit_adj_ltm,
       eec.ebit_adj_fy,
       eec.ebitda_fq,
       eec.ebitda_ltm,
       eec.ebitda_fy,
       eec.ebitda_1fy,
       eec.ebitda_2fy,
       eec.ebitda_3fy,
       eec.ebitda_4fy,
       eec.ebitda_1fqfq,
       eec.ebitda_2fqfq,
       eec.ebitda_3fqfq,
       eec.ebitda_4fqfq,
       eec.ebitda_5yavgfq,
       eec.ebitda_5yavgltm,
       eec.ebitda_adj_fq,
       eec.ebitda_adj_ltm,
       eec.ebitda_adj_fy,
       eec.ebit_growth_yoy,
       eec.ebitda_growth_yoy,
       eec.ebit_margin_ltm,
       eec.ebitda_margin_ltm,
       eec.ebit_positive_years,
       eec.ebitda_positive_years,
       eec.ebit_qoq_growth,
       eec.ebitda_qoq_growth,
       eec.ebit_cagr_3y,
       eec.ebitda_cagr_3y,
       eec.ebit_vs_5y_avg,
       eec.ebitda_vs_5y_avg,
       gpt.gp_fq,
       gpt.gp_fy,
       gpt.gp_ltm,
       gpt.gp_1fqfq,
       gpt.gp_2fqfq,
       gpt.gp_3fqfq,
       gpt.gp_4fqfq,
       gpt.gp_1fy,
       gpt.gp_2fy,
       gpt.gp_3fy,
       gpt.gp_4fy,
       gpt.gp_qoq_growth,
       gpt.gp_yoy_growth,
       gpt.gp_margin_fq,
       gpt.gp_margin_trend,
       gpt.gp_positive_quarters,
       gpt.gp_margin_expansion,
       ef.eps_surprise_pct,
       ef.revenue_surprise_pct,
       ef.eps_adjustment_ratio,
       ef.gaap_adj_eps_gap_pct,
       ef.ebitda_adjustment_ratio,
       ef.eps_quarterly_trend,
       ef.eps_yoy_growth,
       etf.eps_qoq_growth,
       etf.eps_yoy_quarterly,
       etf.eps_positive_streak,
       etf.eps_cagr_3y,
       etf.eps_cagr_5y,
       etf.eps_growth_accel,
       etf.eps_vs_5y_avg,
       etf.eps_improvement_count,
       etf.eps_trajectory_score,
       etf.eps_stability,
       ec.eps_basic_fq,
       ec.eps_basic_ltm,
       ec.eps_basic_fy,
       ec.eps_adj_ltm,
       ec.eps_norm_est_fy1e,
       ec.eps_positive_years,
       ecf.eps_cont_ltm,
       ecf.eps_cont_fq,
       ecf.eps_cont_fy,
       ecf.eps_cont_1fqfq,
       ecf.eps_cont_2fqfq,
       ecf.eps_cont_3fqfq,
       ecf.eps_cont_4fqfq,
       ecf.eps_cont_1fy,
       ecf.eps_cont_2fy,
       ecf.eps_cont_3fy,
       ecf.eps_cont_4fy,
       ecf.eps_cont_qoq_growth,
       ecf.eps_cont_yoy_growth,
       ecf.eps_cont_cagr_3y,
       ecf.eps_cont_vs_total_eps,
       ecf.eps_cont_positive_streak,
       ecf.eps_cont_trajectory_score,
       ecf.discontinued_ops_impact,
       ecf.core_earnings_stability,
       gaa.eps_adjustment_spread_ltm,
       gaa.eps_adjustment_spread_fy,
       gaa.eps_adjustment_spread_1fy,
       gaa.eps_adjustment_spread_fq,
       gaa.eps_adjustment_spread_1fqfq,
       gaa.eps_adjustment_spread_2fqfq,
       gaa.eps_adjustment_spread_3fqfq,
       gaa.eps_adjustment_spread_4fqfq,
       gaa.eps_adjustment_spread_2fy,
       gaa.eps_adjustment_spread_3fy,
       gaa.eps_adjustment_spread_4fy,
       gaa.eps_adjustment_pct,
       gaa.net_income_adjustment_ratio_ltm,
       gaa.net_income_adjustment_ratio_fy,
       gaa.net_income_adjustment_ratio_1fy,
       gaa.net_income_adjustment_ratio_fq,
       gaa.net_income_adjustment_ratio_5yavgfq,
       gaa.net_income_adjustment_ratio_1fqfq,
       gaa.net_income_adjustment_ratio_2fqfq,
       gaa.net_income_adjustment_ratio_3fqfq,
       gaa.net_income_adjustment_ratio_4fqfq,
       gaa.net_income_adjustment_ratio_2fy,
       gaa.net_income_adjustment_ratio_3fy,
       gaa.net_income_adjustment_ratio_4fy,
       gaa.net_income_adjustment_pct,
       gaa.ebitda_adjustment_pct_ltm,
       gaa.ebitda_adjustment_pct_fy,
       gaa.ebitda_adjustment_pct_1fy,
       gaa.ebitda_adjustment_pct_fq,
       gaa.ebitda_adjustment_pct_1fqfq,
       gaa.ebitda_adjustment_pct_2fqfq,
       gaa.ebitda_adjustment_pct_3fqfq,
       gaa.ebitda_adjustment_pct_4fqfq,
       gaa.ebitda_adjustment_pct_2fy,
       gaa.ebitda_adjustment_pct_3fy,
       gaa.ebitda_adjustment_pct_4fy,
       gaa.ebit_adjustment_pct_ltm,
       gaa.ebit_adjustment_pct_fy,
       gaa.ebit_adjustment_pct_1fy,
       gaa.ebit_adjustment_pct_fq,
       gaa.ebit_adjustment_pct_1fqfq,
       gaa.ebit_adjustment_pct_2fqfq,
       gaa.ebit_adjustment_pct_3fqfq,
       gaa.ebit_adjustment_pct_4fqfq,
       gaa.ebit_adjustment_pct_2fy,
       gaa.ebit_adjustment_pct_3fy,
       gaa.ebit_adjustment_pct_4fy,
       gaa.earnings_quality_score,
       gaa.earnings_quality_warning,
       gaa.forward_eps_gaap_adj_spread,
       grf.gaap_revision_momentum,
       grf.gaap_revision_1m,
       grf.gaap_revision_3m,
       grf.gaap_revision_6m,
       grf.gaap_revision_1y,
       grf.gaap_vs_norm_revision_spread,
       grf.gaap_revision_acceleration,
       grf.gaap_positive_revision_flag,
       grf.revision_quality_divergence,
       gf.revenue_growth_yoy,
       gf.ebitda_growth_yoy                AS growth_ebitda_growth_yoy,
       gf.operating_income_growth,
       gf.fcf_growth,
       gf.revenue_cagr_5y,
       gf.forward_revenue_growth,
       gf.revenue_vs_5y_avg,
       rff.revenue_est_spread,
       rff.revenue_beat_potential,
       rff.revenue_est_revision_trend,
       rff.ebitda_est_vs_actual,
       rff.forward_revenue_multiple,
       rff.revenue_estimate_count,
       rff.revenue_guidance_gap,
       rff.consensus_revenue_growth,
       rff.ebit_estimate_spread,
       rff.forward_ebitda_margin,
       rff.revenue_acceleration,
       rff.estimate_confidence_score,
       rec.revenue_est_avg_fy1e,
       rec.revenue_est_med_fy1e,
       rec.revenue_est_avg_ntm,
       rec.revenue_est_med_ntm,
       rec.revenue_avg_med_diff_pct,
       rec.revenue_consensus_strength,
       rec.revenue_revision_trend,
       rec.revenue_vs_current,
       rqf.revenue_fq,
       rqf.revenue_fy,
       rqf.revenue_ltm,
       rqf.revenue_5y_avg,
       rqf.revenue_1fqfq,
       rqf.revenue_2fqfq,
       rqf.revenue_3fqfq,
       rqf.revenue_4fqfq,
       rqf.revenue_1fy,
       rqf.revenue_2fy,
       rqf.revenue_3fy,
       rqf.revenue_4fy,
       rqf.revenue_qoq_growth,
       rqf.revenue_qoq_2q,
       rqf.revenue_qoq_3q,
       rqf.revenue_qoq_4q,
       rqf.revenue_yoy_quarterly,
       rqf.revenue_2y_growth,
       rqf.revenue_3y_growth,
       rqf.revenue_4y_growth,
       rqf.revenue_cagr_3y,
       rqf.revenue_cagr_4y,
       rqf.revenue_4q_trend,
       rqf.revenue_4q_avg,
       rqf.revenue_fq_vs_4q_avg,
       rqf.revenue_growth_flag,
       rqf.revenue_stability_score,
       rqf.revenue_accelerating_flag,
       rqf.revenue_positive_qoq_streak,
       trt.revenue_5yavgfq,
       trt.revenue_5yavgltm,
       trt.revenue_vs_5y_avg_fq,
       trt.revenue_vs_5y_avg_ltm,
       trt.revenue_fq_vs_avg,
       trt.revenue_momentum,
       qf.has_goodwill_impairment,
       qf.has_asset_writedown,
       qf.has_restructuring,
       qf.goodwill_to_assets_pct,
       qf.intangible_intensity,
       qf.exceptional_items_to_ebitda,
       qf.altman_z_score,
       qf.altman_z_trend,
       qf.current_ratio,
       qf.quick_ratio,
       br.beta_1y,
       br.beta_5y,
       br.beta_spread,
       br.beta_trend,
       br.high_beta_flag,
       br.low_beta_flag,
       br.beta_stability_score,
       fdf.distress_risk_score,
       fdf.liquidity_stress_score,
       fdf.working_capital_trend,
       fdf.cash_runway_months,
       fdf.combined_distress_score,
       fdf.wc_deteriorating_flag,
       fdf.retained_earnings_growth,
       fdf.accumulated_deficit_flag,
       fdf.adequate_cash_buffer,
       aqf.goodwill_change_rate,
       aqf.restructuring_intensity,
       aqf.exceptional_items_frequency,
       aqf.merger_impact_ratio,
       aqf.non_operating_income_share,
       aqf.asset_sale_boost,
       aqf.accounting_quality_score,
       qfc.goodwill_impairment_ltm,
       qfc.asset_writedown_ltm,
       qfc.restructuring_ltm,
       qfc.has_goodwill_impairment_ltm,
       qfc.goodwill_impairment_frequency,
       qfc.asset_writedown_frequency,
       qfc.restructuring_frequency,
       qfc.exceptional_items_total_ltm,
       qfc.quality_issues_count_5y,
       lf.debt_to_equity,
       lf.debt_to_assets,
       lf.equity_ratio,
       lf.interest_coverage,
       lf.cash_ratio,
       lf.working_capital_ratio,
       er.asset_turnover,
       er.inventory_turnover,
       er.receivables_days,
       er.working_capital_turns,
       bsd.cash_to_assets_pct,
       bsd.cash_change_qoq,
       bsd.cash_vs_5y_avg,
       bsd.inventory_change_yoy,
       bsd.inventory_vs_5y_avg,
       bsd.receivables_change_yoy,
       bsd.receivables_vs_5y_avg,
       bsd.working_capital_vs_5y_avg,
       bsd.retained_earnings_vs_5y,
       bsd.intangibles_growth_flag,
       bsd.asset_quality_score,
       bsd.balance_sheet_strength,
       bsd.debt_maturity_risk,
       wct.wc_fq,
       wct.wc_fy,
       wct.wc_ltm,
       wct.wc_5yavgfy,
       wct.wc_1fq,
       wct.wc_2fq,
       wct.wc_3fq,
       wct.wc_4fq,
       wct.wc_1fy,
       wct.wc_2fy,
       wct.wc_3fy,
       wct.wc_4fy,
       wct.wc_qoq_change,
       wct.wc_yoy_change,
       wct.wc_4q_trend,
       wct.wc_vs_5y_avg,
       wct.wc_positive_quarters,
       wct.wc_improving_flag,
       wct.wc_volatility,
       tdt.debt_fq,
       tdt.debt_fy,
       tdt.debt_ltm,
       tdt.debt_1fq,
       tdt.debt_2fq,
       tdt.debt_3fq,
       tdt.debt_4fq,
       tdt.debt_1fy,
       tdt.debt_2fy,
       tdt.debt_3fy,
       tdt.debt_4fy,
       tdt.debt_qoq_change,
       tdt.debt_yoy_change,
       tdt.debt_4q_trend,
       tdt.debt_3y_cagr,
       tdt.debt_deleveraging,
       tdt.debt_to_equity_trend,
       wcd.wc_to_revenue,
       wcd.wc_to_assets,
       wcd.days_working_capital,
       wcd.wc_efficiency_score,
       wcd.negative_wc_flag,
       sf.analyst_bullish_pct,
       sf.analyst_bearish_pct,
       sf.analyst_neutral_pct,
       sf.analyst_conviction,
       sf.upside_potential,
       sf.price_target_spread_pct,
       sf.price_target_revision_1m,
       sf.price_target_revision_3m,
       sf.eps_revision_momentum,
       sf.analyst_rating_normalized,
       sf.analyst_coverage_quality,
       ptd.pt_momentum_1w,
       ptd.pt_momentum_1m,
       ptd.pt_momentum_3m,
       ptd.pt_momentum_6m,
       ptd.pt_momentum_1y,
       ptd.pt_median_momentum_1m,
       ptd.pt_median_momentum_3m,
       ptd.pt_acceleration_short,
       ptd.pt_acceleration_long,
       ptd.pt_consensus_convergence,
       ptd.analyst_coverage_change_1m,
       ptd.analyst_coverage_change_3m,
       ptd.analyst_coverage_change_1y,
       ptd.pt_vs_price_momentum,
       ptd.analyst_coverage_trend,
       df.dividend_streak,
       df.dividend_yield_ltm,
       df.dividend_yield_ntm,
       df.dividend_payout_ratio,
       df.fcf_dividend_coverage,
       df.buyback_yield,
       df.total_shareholder_yield,
       df.dividend_growth_expectation,
       dt.days_since_ex_date,
       dt.days_to_payment,
       dt.dividend_announced_flag,
       dt.ex_date_approaching_flag,
       dt.dividend_frequency_score,
       dt.dividend_consistency,
       dt.recent_dividend_change,
       dt.dividend_yield_vs_5y_avg,
       dyc.div_yield_ltm,
       dyc.div_yield_ntm,
       dyc.div_yield_ind,
       dyc.div_yield_1fy_ind,
       dyc.div_yield_5y_avg,
       dyc.div_yield_vs_5y_avg,
       dyc.div_yield_growth_expected,
       dyc.high_yield_flag,
       dyc.sustainable_dividend_flag,
       emf.revenue_per_employee,
       emf.profit_per_employee,
       emf.ebitda_per_employee,
       emf.assets_per_employee,
       emf.fte_growth_1y_pct,
       emf.fte_growth_3y_pct,
       emf.workforce_stability,
       ed.fte_growth_2y_pct,
       ed.fte_acceleration,
       ed.workforce_volatility,
       ed.hiring_intensity,
       ed.productivity_trend,
       ed.headcount_vs_revenue,
       ed.workforce_efficiency_gain,
       ed.layoff_risk_flag,
       ed.rapid_hiring_flag,
       ed.sustainable_growth_flag,
       cf.cfo_to_net_income,
       cf.fcf_to_net_income,
       cf.fcf_margin,
       cf.cfo_growth_yoy,
       cf.fcf_positive_ratio,
       cf.acquisition_intensity,
       cf.self_funding_ratio,
       ecff.fcf_positive_years,
       ecff.fcf_always_positive,
       ecff.capex_vs_5y_avg,
       ecff.underinvestment_flag,
       ecff.cfo_share_of_cf,
       ecff.cfi_share_of_cf,
       ecff.cff_share_of_cf,
       ecff.self_funding_flag,
       ecff.acquisition_to_fcf,
       ecff.sustainable_ma_flag,
       ecff.fcf_4q_improvement,
       ecff.cash_flow_quality_score,
       ecff.capex_yoy_growth,
       ecff.capex_qoq_growth,
       ecff.capex_3y_trend,
       ecff.capex_volatility,
       ecff.capex_acceleration,
       ecff.capex_cut_flag,
       ecff.overinvestment_flag,
       ecff.acquisitions_yoy_growth,
       ecff.acquisitions_vs_5y_avg,
       ecff.acquisitions_ltm_total,
       ecff.ma_intensity_score,
       ecff.serial_acquirer_flag,
       ecff.acquisition_pause_flag,
       ecff.total_investment_to_cfo,
       ecff.organic_vs_inorganic,
       ecff.investment_efficiency,
       ctf.cfo_quarterly_trend,
       ctf.cfo_yoy_quarterly,
       ctf.cfi_quarterly_trend,
       ctf.cff_quarterly_trend,
       ctf.fcf_quarterly_trend,
       ctf.cfo_positive_quarters,
       ctf.cfi_negative_quarters,
       ctf.cff_pattern_score,
       ctf.cash_burn_rate,
       ctf.cf_volatility_score,
       ctf.operating_cf_momentum,
       ctf.financing_dependency,
       cc.cfo_fq,
       cc.cfo_ltm,
       cc.cfo_fy,
       cc.fcf_fq,
       cc.fcf_ltm,
       cc.fcf_fy,
       cc.fcf_growth_yoy,
       cc.fcf_yield,
       cc.cfo_positive_years,
       cc.fcf_positive_years               AS fcf_positive_years_comp,
       tf.fiscal_quarter,
       tf.fiscal_month,
       tf.fiscal_year,
       tf.days_to_earnings,
       tf.earnings_report_recency,
       tf.reporting_lag,
       tf.fiscal_year_progress,
       fcf.days_since_last_report,
       fcf.days_to_fy_end,
       fcf.is_quarter_end_month,
       fcf.is_fy_end_month,
       fcf.earnings_season_flag,
       fcf.pre_earnings_window,
       fcf.post_earnings_window,
       fcf.reporting_freshness_score,
       fcf.fiscal_quarter_progress,
       tat.assets_fq,
       tat.assets_fy,
       tat.assets_ltm,
       tat.assets_1fq,
       tat.assets_2fq,
       tat.assets_3fq,
       tat.assets_4fq,
       tat.assets_1fy,
       tat.assets_2fy,
       tat.assets_3fy,
       tat.assets_4fy,
       tat.assets_qoq_growth,
       tat.assets_yoy_growth,
       tat.assets_3y_cagr,
       tat.asset_growth_accel,
       tat.asset_base_stable,
       itf.inventory_ltm,
       itf.inventory_fq,
       itf.inventory_fy,
       itf.inventory_1fq,
       itf.inventory_2fq,
       itf.inventory_3fq,
       itf.inventory_4fq,
       itf.inventory_1fy,
       itf.inventory_2fy,
       itf.inventory_3fy,
       itf.inventory_4fy,
       itf.inventory_qoq_change,
       itf.inventory_yoy_change,
       itf.inventory_4q_trend,
       itf.inventory_vs_5y_avg             AS inventory_vs_5y_avg_itf,
       itf.inventory_days,
       itf.inventory_turnover              AS inventory_turnover_itf,
       itf.inventory_to_revenue,
       itf.inventory_to_assets,
       itf.inventory_buildup_flag,
       itf.inventory_reduction_flag,
       itf.inventory_volatility,
       gtf.goodwill_fq,
       gtf.goodwill_ltm,
       gtf.goodwill_fy,
       gtf.goodwill_1fq,
       gtf.goodwill_2fq,
       gtf.goodwill_3fq,
       gtf.goodwill_4fq,
       gtf.goodwill_1fy,
       gtf.goodwill_2fy,
       gtf.goodwill_3fy,
       gtf.goodwill_4fy,
       gtf.goodwill_qoq_change,
       gtf.goodwill_yoy_change,
       gtf.goodwill_3y_growth,
       gtf.goodwill_vs_5y_avg,
       gtf.recent_acquisition_flag,
       gtf.goodwill_accumulation_rate,
       gtf.goodwill_to_assets_trend,
       gtf.impairment_risk_score,
       gtf.goodwill_concentration,
       csf.cogs_to_revenue,
       csf.opex_to_revenue,
       csf.sga_to_revenue,
       csf.rnd_to_revenue,
       csf.interest_to_revenue,
       csf.sga_trend_yoy,
       csf.operating_leverage_proxy,
       csf.cost_efficiency_score,
       csf.marketing_to_revenue,
       csf.marketing_trend_yoy,
       csf.marketing_vs_5y_avg,
       csf.sga_vs_5y_avg,
       csf.sga_efficiency_trend,
       rtf.rnd_ltm,
       rtf.rnd_fq,
       rtf.rnd_fy,
       rtf.rnd_1fqfq,
       rtf.rnd_2fqfq,
       rtf.rnd_3fqfq,
       rtf.rnd_4fqfq,
       rtf.rnd_1fy,
       rtf.rnd_2fy,
       rtf.rnd_3fy,
       rtf.rnd_4fy,
       rtf.rnd_intensity_ltm,
       rtf.rnd_intensity_fy,
       rtf.rnd_intensity_trend,
       rtf.rnd_qoq_growth,
       rtf.rnd_yoy_growth,
       rtf.rnd_cagr_3y,
       rtf.rnd_per_employee,
       rtf.rnd_to_gross_profit,
       rtf.rnd_roi_proxy,
       rtf.rnd_increasing_flag,
       rtf.rnd_cut_flag,
       rtf.high_rnd_intensity_flag,
       iif.interest_income_ltm,
       iif.interest_expense_ltm,
       iif.net_interest_income,
       iif.interest_coverage_ratio,
       iif.interest_income_to_revenue,
       iif.interest_expense_to_revenue,
       iif.net_interest_margin_proxy,
       cs.piotroski_f_score,
       etf.eps_trajectory_score            AS composite_eps_trajectory_score,
       cs.dilution_score,
       cs.quality_momentum_score,
       nic.net_income_is_fq,
       nic.net_income_is_ltm,
       nic.net_income_is_fy,
       nic.net_income_adj_ltm,
       nic.normalized_ni_ltm,
       nic.net_income_is_1fqfq,
       nic.net_income_is_2fqfq,
       nic.net_income_is_3fqfq,
       nic.net_income_is_4fqfq,
       nic.net_income_is_1fy,
       nic.net_income_is_2fy,
       nic.net_income_is_3fy,
       nic.net_income_is_4fy,
       nic.net_income_is_5yavgfq,
       nic.net_income_is_5yavgltm,
       nic.normalized_ni_5yavgfq,
       nic.normalized_ni_5yavgltm,
       nic.net_income_growth_yoy,
       nic.net_income_margin_ltm,
       nic.ni_adjustment_ratio,
       nic.net_income_positive_years,
       nic.earnings_quality_composite,
       nic.net_income_qoq_growth,
       nic.net_income_yoy_quarterly,
       nic.net_income_vs_5y_avg,
       nic.normalized_ni_vs_5y_avg,
       uif.other_unusual_items_ltm,
       uif.impairment_goodwill_ltm,
       uif.asset_writedown_ltm             AS unusual_asset_writedown_ltm,
       uif.restructuring_charges_ltm,
       uif.total_unusual_items,
       uif.unusual_items_to_revenue,
       uif.unusual_items_to_ebitda,
       uif.has_unusual_items_flag,
       uif.earnings_quality_impact,
       vsf.vol_1m                          AS volatility_1m,
       vsf.vol_3m                          AS volatility_3m,
       vsf.vol_6m                          AS volatility_6m,
       vsf.vol_1y                          AS volatility_1y,
       vsf.vol_term_spread_short           AS volatility_trend_short,
       vsf.vol_term_spread_long            AS volatility_trend_long,
       vsf.vol_ratio_3m_1y,
       vsf.vol_hump,
       vsf.beta_2y,
       vsf.beta_term_structure,
       vsf.beta_convexity,
       vsf.realized_vs_implied_proxy,
       vsf.beta_1y - vsf.beta_2y           AS beta_short_term_shift,
       txf.effective_tax_rate_ltm,
       txf.effective_tax_rate_fy,
       txf.tax_rate_yoy_change,
       txf.tax_rate_qoq_change,
       txf.tax_rate_stability,
       txf.low_tax_flag,
       txf.tax_rate_trend_4q,
       otf.opex_fq,
       otf.opex_ltm,
       otf.opex_fy,
       otf.opex_qoq_growth,
       otf.opex_yoy_growth,
       otf.opex_vs_revenue_trend,
       otf.sga_qoq_growth,
       otf.sga_yoy_growth,
       otf.operating_leverage_score,
       asf.gain_loss_on_sale_of_assets_ltm AS asset_sale_gain_loss_ltm,
       asf.asset_sale_frequency,
       asf.asset_sale_trend,
       fcfe.fcf_est_avg_fy1e,
       fcfe.fcf_est_avg_fy2e,
       fcfe.fcf_est_avg_fy3e,
       fcfe.fcf_est_avg_fy4e,
       fcfe.fcf_est_avg_fy5e,
       fcfe.fcf_est_cagr_5y,
       fcfe.fcf_est_trend,
       dhf.div_yield_2fy                   AS div_yield_2fyind,
       dhf.div_yield_3fy                   AS div_yield_3fyind,
       dhf.div_yield_4fy                   AS div_yield_4fyind,
       dhf.div_yield_5fy                   AS div_yield_5fyind,
       dhf.div_yield_trend_3y              AS div_yield_5y_trend,
       dhf.div_yield_volatility            AS div_yield_stability,
       dhf.div_yield_declining_flag,
       dhf.div_yield_mean_5y,
       dhf.div_yield_vs_5y_mean,
       iit.inv_income_fq                   AS interest_income_fq,
       iit.inv_income_fy                   AS interest_income_fy,
       iit.inv_income_qoq_growth           AS interest_income_qoq_growth,
       iit.inv_income_yoy_growth           AS interest_income_yoy_growth,
       iit.inv_income_to_revenue           AS interest_income_to_revenue_trend,
       sdt.shares_yoy_change_pct,
       sdt.net_buyback_flag,
       fcnf.pe_ntm,
       fcnf.pe_est_fy1,
       fcnf.pe_forward_discount,
       fcnf.eps_gaap_vs_norm_ntm,
       fcnf.eps_gaap_vs_norm_fy1e,
       fcnf.forward_adjustment_trend,
       fcnf.ebitda_est_ntm,
       fcnf.ebitda_est_fy1e,
       fcnf.ev_ebitda_est_fy1,
       fcnf.ebitda_forward_growth,
       fcnf.earnings_revision_divergence,
       fcnf.forward_pe_vs_sector_proxy,
       ptaf.pt_achievement_1y,
       ptaf.pt_accuracy_1y,
       ptaf.pt_optimism_bias,
       ptaf.pt_range_hit_rate,
       ptaf.pt_median_vs_mean_spread,
       ptaf.pt_high_low_convergence_1y,
       ptaf.analyst_count_stability,
       slf.log_market_cap,
       slf.daily_turnover_ratio,
       slf.liquidity_score,
       fge.fcf_est_fy1,
       fge.fcf_est_fy2,
       fge.fcf_est_fy3,
       fge.fcf_est_fy4,
       fge.fcf_est_fy5,
       fge.fcf_est_growth_fy1_vs_ltm,
       fge.fcf_est_growth_fy2_vs_fy1,
       fge.fcf_est_growth_fy3_vs_fy2,
       fge.fcf_est_growth_fy4_vs_fy3,
       fge.fcf_est_growth_fy5_vs_fy4,
       fge.fcf_est_cagr_3y,
       fge.fcf_est_cagr_5y
       fge.fcf_est_margin_fy1,
       fge.fcf_est_yield_fy1,
       fge.fcf_est_growth_acceleration,
       fge.fcf_est_growth_deceleration,
       fge.fcf_est_trajectory_score
       fge.fcf_est_always_positive
       fge.fcf_est_vs_historical,
       fge.fcf_est_capex_implied_ratio,
       CURRENT_TIMESTAMP                   AS feature_calculated_at
FROM vw_identifier_columns id
         JOIN equities e ON id.isin = e."ISIN"
         LEFT JOIN calc_valuation_features() vf(isin, p_e_ratio, p_b_ratio, ev_ebitda_ratio, ev_sales_ratio,
                                                dividend_yield, peg_ratio) ON id.isin = vf.isin
         LEFT JOIN calc_valuation_timeseries_features() vts(isin, ev_sales_trend_1y, ev_ebitda_momentum,
                                                            p_e_momentum_yoy, p_e_momentum_qoq, ev_sales_vs_3y_avg,
                                                            ev_ebitda_vs_3y_avg, p_e_vs_3y_avg,
                                                            ev_sales_forward_discount, ev_ebitda_forward_discount,
                                                            p_e_forward_discount, p_b_vs_5y_avg) ON id.isin = vts.isin
         LEFT JOIN calc_extended_valuation_timeseries() evt(isin, ev_sales_qoq_1q, ev_sales_qoq_2q, ev_sales_qoq_3q,
                                                            ev_sales_qoq_4q, p_e_vs_5y_avg, p_e_percentile_proxy,
                                                            valuation_mean_reversion, ev_ebitda_qoq_trend,
                                                            p_b_momentum_yoy, valuation_compression,
                                                            forward_pe_premium)
                   ON id.isin = evt.isin
         LEFT JOIN calc_tangible_book_features() tb(isin, tangible_book_value_fy, tangible_book_value_ltm,
                                                    tangible_book_per_share, price_to_tangible_book,
                                                    tangible_equity_ratio, intangibles_to_equity,
                                                    goodwill_to_equity,
                                                    tangible_asset_quality, tbv_yoy_growth, tbv_vs_calculated)
                   ON id.isin = tb.isin
         LEFT JOIN calc_momentum_features() mf(isin, price_momentum_1m, price_momentum_3m,
                                               price_momentum_6m,
                                               price_momentum_1y, price_momentum_5d, ema_crossover_20_50,
                                               ema_crossover_50_250, price_vs_ema_20d, price_vs_ema_250d,
                                               pct_off_52w_high, pct_above_52w_low, range_52w_position,
                                               beta_momentum,
                                               volatility_regime) ON id.isin = mf.isin
         LEFT JOIN calc_long_term_momentum_features() ltm(isin, price_momentum_1y, price_momentum_3y,
                                                          price_momentum_5y,
                                                          long_term_trend_score, price_vs_ema_250d,
                                                          multi_year_high_flag, secular_trend_flag, total_return_ytd,
                                                          total_return_5y, total_return_10y, return_cagr_3y,
                                                          return_cagr_10y, return_vs_price_momentum,
                                                          return_consistency_score) ON id.isin = ltm.isin
         LEFT JOIN calc_technical_analysis_features() ta(isin, ema_slope_20d, ema_trend_consistency,
                                                         price_vs_ema_100d,
                                                         near_52w_high_flag, near_52w_low_flag,
                                                         volume_momentum_score,
                                                         breakout_signal, high_volume_flag, low_volume_flag,
                                                         volatility_compression, volatility_term_structure)
                   ON id.isin = ta.isin
         LEFT JOIN calc_profitability_features() pf(isin, roe, roa, gross_margin_pct, operating_margin_pct,
                                                    net_margin_pct, ebitda_margin_pct, roic, rnd_intensity,
                                                    equity_multiplier) ON id.isin = pf.isin
         LEFT JOIN calc_margin_trends() mt(isin, gross_margin_trend_yoy, operating_margin_trend,
                                           net_margin_trend_yoy,
                                           ebitda_margin_trend, margin_expansion_flag,
                                           margin_stability_score)
                   ON id.isin = mt.isin
         LEFT JOIN calc_ebit_ebitda_comprehensive() eec(isin, ebit_fq, ebit_ltm, ebit_fy, ebit_1fy, ebitda_fq,
                                                        ebitda_ltm, ebitda_fy, ebitda_1fy, ebit_2fy, ebit_3fy,
                                                        ebit_4fy,
                                                        ebitda_2fy, ebitda_3fy, ebitda_4fy, ebit_1fqfq, ebit_2fqfq,
                                                        ebit_3fqfq, ebit_4fqfq, ebitda_1fqfq, ebitda_2fqfq,
                                                        ebitda_3fqfq, ebitda_4fqfq, ebit_5yavgfq, ebit_5yavgltm,
                                                        ebitda_5yavgfq, ebitda_5yavgltm, ebit_adj_fq, ebit_adj_ltm,
                                                        ebit_adj_fy, ebitda_adj_fq, ebitda_adj_ltm, ebitda_adj_fy,
                                                        ebit_growth_yoy, ebitda_growth_yoy, ebit_margin_ltm,
                                                        ebitda_margin_ltm, ebit_positive_years,
                                                        ebitda_positive_years,
                                                        ebit_qoq_growth, ebitda_qoq_growth, ebit_cagr_3y,
                                                        ebitda_cagr_3y, ebit_vs_5y_avg, ebitda_vs_5y_avg)
                   ON id.isin = eec.isin
         LEFT JOIN calc_gross_profit_temporal() gpt(isin, gp_fq, gp_fy, gp_ltm, gp_1fqfq, gp_2fqfq, gp_3fqfq,
                                                    gp_4fqfq,
                                                    gp_1fy, gp_2fy, gp_3fy, gp_4fy, gp_qoq_growth,
                                                    gp_yoy_growth,
                                                    gp_margin_fq, gp_margin_trend, gp_positive_quarters,
                                                    gp_margin_expansion) ON id.isin = gpt.isin
         LEFT JOIN calc_earnings_features() ef(isin, eps_surprise_pct, revenue_surprise_pct,
                                               eps_adjustment_ratio,
                                               gaap_adj_eps_gap_pct, ebitda_adjustment_ratio,
                                               eps_quarterly_trend,
                                               eps_yoy_growth) ON id.isin = ef.isin
         LEFT JOIN calc_eps_trajectory_features() etf(isin, eps_qoq_growth, eps_yoy_quarterly,
                                                      eps_positive_streak,
                                                      eps_cagr_3y, eps_cagr_5y, eps_growth_accel, eps_vs_5y_avg,
                                                      eps_improvement_count, eps_trajectory_score, eps_stability)
                   ON id.isin = etf.isin
         LEFT JOIN calc_eps_comprehensive() ec(isin, eps_basic_fq, eps_basic_ltm, eps_basic_fy,
                                               eps_adj_ltm,
                                               eps_norm_est_fy1e, eps_growth_yoy, eps_cagr_3y,
                                               eps_adjustment_ratio,
                                               eps_positive_years, eps_trajectory_score)
                   ON id.isin = ec.isin
         LEFT JOIN calc_eps_continuing_features() ecf(isin, eps_cont_ltm, eps_cont_fq, eps_cont_fy,
                                                      eps_cont_1fqfq,
                                                      eps_cont_2fqfq, eps_cont_3fqfq, eps_cont_4fqfq,
                                                      eps_cont_1fy,
                                                      eps_cont_2fy, eps_cont_3fy, eps_cont_4fy,
                                                      eps_cont_qoq_growth,
                                                      eps_cont_yoy_growth, eps_cont_cagr_3y,
                                                      eps_cont_vs_total_eps,
                                                      eps_cont_positive_streak, eps_cont_trajectory_score,
                                                      discontinued_ops_impact, core_earnings_stability)
                   ON id.isin = ecf.isin
         LEFT JOIN calc_gaap_adjusted_analytics() gaa(isin, eps_adjustment_spread_ltm, eps_adjustment_spread_fy,
                                                      eps_adjustment_spread_1fy, eps_adjustment_spread_fq,
                                                      eps_adjustment_spread_1fqfq, eps_adjustment_spread_2fqfq,
                                                      eps_adjustment_spread_3fqfq, eps_adjustment_spread_4fqfq,
                                                      eps_adjustment_spread_2fy, eps_adjustment_spread_3fy,
                                                      eps_adjustment_spread_4fy, eps_adjustment_pct,
                                                      net_income_adjustment_ratio_ltm,
                                                      net_income_adjustment_ratio_fy,
                                                      net_income_adjustment_ratio_1fy,
                                                      net_income_adjustment_ratio_fq,
                                                      net_income_adjustment_ratio_5yavgfq,
                                                      net_income_adjustment_ratio_1fqfq,
                                                      net_income_adjustment_ratio_2fqfq,
                                                      net_income_adjustment_ratio_3fqfq,
                                                      net_income_adjustment_ratio_4fqfq,
                                                      net_income_adjustment_ratio_2fy,
                                                      net_income_adjustment_ratio_3fy,
                                                      net_income_adjustment_ratio_4fy, net_income_adjustment_pct,
                                                      ebitda_adjustment_pct_ltm, ebitda_adjustment_pct_fy,
                                                      ebitda_adjustment_pct_1fy, ebitda_adjustment_pct_fq,
                                                      ebitda_adjustment_pct_1fqfq, ebitda_adjustment_pct_2fqfq,
                                                      ebitda_adjustment_pct_3fqfq, ebitda_adjustment_pct_4fqfq,
                                                      ebitda_adjustment_pct_2fy, ebitda_adjustment_pct_3fy,
                                                      ebitda_adjustment_pct_4fy, ebit_adjustment_pct_ltm,
                                                      ebit_adjustment_pct_fy, ebit_adjustment_pct_1fy,
                                                      ebit_adjustment_pct_fq, ebit_adjustment_pct_1fqfq,
                                                      ebit_adjustment_pct_2fqfq, ebit_adjustment_pct_3fqfq,
                                                      ebit_adjustment_pct_4fqfq, ebit_adjustment_pct_2fy,
                                                      ebit_adjustment_pct_3fy, ebit_adjustment_pct_4fy,
                                                      earnings_quality_score, earnings_quality_warning,
                                                      forward_eps_gaap_adj_spread) ON id.isin = gaa.isin
         LEFT JOIN calc_gaap_revision_features() grf(isin, gaap_revision_momentum, gaap_revision_1m,
                                                     gaap_revision_3m,
                                                     gaap_revision_6m, gaap_revision_1y,
                                                     gaap_vs_norm_revision_spread,
                                                     gaap_revision_acceleration, gaap_positive_revision_flag,
                                                     revision_quality_divergence) ON id.isin = grf.isin
         LEFT JOIN calc_growth_features() gf(isin, revenue_growth_yoy, ebitda_growth_yoy,
                                             operating_income_growth,
                                             fcf_growth, revenue_cagr_5y, forward_revenue_growth,
                                             revenue_vs_5y_avg)
                   ON id.isin = gf.isin
         LEFT JOIN calc_revenue_forecast_features() rff(isin, revenue_est_spread, revenue_beat_potential,
                                                        revenue_est_revision_trend, ebitda_est_vs_actual,
                                                        forward_revenue_multiple, revenue_estimate_count,
                                                        revenue_guidance_gap, consensus_revenue_growth,
                                                        ebit_estimate_spread, forward_ebitda_margin,
                                                        revenue_acceleration, estimate_confidence_score)
                   ON id.isin = rff.isin
         LEFT JOIN calc_revenue_estimate_consensus() rec(isin, revenue_est_avg_fy1e, revenue_est_med_fy1e,
                                                         revenue_est_avg_ntm, revenue_est_med_ntm,
                                                         revenue_avg_med_diff_pct, revenue_consensus_strength,
                                                         revenue_revision_trend, revenue_vs_current)
                   ON id.isin = rec.isin
         LEFT JOIN calc_revenue_quarterly_features() rqf(isin, revenue_fq, revenue_fy, revenue_ltm, revenue_5y_avg,
                                                         revenue_1fqfq, revenue_2fqfq, revenue_3fqfq, revenue_4fqfq,
                                                         revenue_1fy, revenue_2fy, revenue_3fy, revenue_4fy,
                                                         revenue_yoy_growth, revenue_vs_5y_avg, revenue_ltm_vs_fy,
                                                         revenue_fq_vs_5y_avg_fq, revenue_qoq_growth,
                                                         revenue_qoq_2q,
                                                         revenue_qoq_3q, revenue_qoq_4q, revenue_yoy_quarterly,
                                                         revenue_2y_growth, revenue_3y_growth, revenue_4y_growth,
                                                         revenue_cagr_3y, revenue_cagr_4y, revenue_4q_trend,
                                                         revenue_4q_avg, revenue_fq_vs_4q_avg, revenue_growth_flag,
                                                         revenue_stability_score, revenue_accelerating_flag,
                                                         revenue_positive_qoq_streak) ON id.isin = rqf.isin
         LEFT JOIN calc_total_revenues_temporal() trt(isin, revenue_fq, revenue_ltm, revenue_fy, revenue_1fy,
                                                      revenue_5yavgfq, revenue_5yavgltm, revenue_growth_yoy,
                                                      revenue_vs_5y_avg_fq, revenue_vs_5y_avg_ltm,
                                                      revenue_fq_vs_avg,
                                                      revenue_momentum) ON id.isin = trt.isin
         LEFT JOIN calc_quality_features() qf(isin, has_goodwill_impairment, has_asset_writedown,
                                              has_restructuring,
                                              goodwill_to_assets_pct, intangible_intensity,
                                              exceptional_items_to_ebitda,
                                              altman_z_score, altman_z_trend, current_ratio, quick_ratio)
                   ON id.isin = qf.isin
         LEFT JOIN calc_beta_risk_features() br(isin, beta_1y, beta_5y, beta_spread, beta_trend,
                                                high_beta_flag,
                                                low_beta_flag, beta_stability_score) ON id.isin = br.isin
         LEFT JOIN calc_financial_distress_features() fdf(isin, distress_risk_score, liquidity_stress_score,
                                                          working_capital_trend, cash_runway_months,
                                                          combined_distress_score, wc_deteriorating_flag,
                                                          retained_earnings_growth, accumulated_deficit_flag,
                                                          adequate_cash_buffer) ON id.isin = fdf.isin
         LEFT JOIN calc_accounting_quality_features() aqf(isin, goodwill_change_rate, restructuring_intensity,
                                                          exceptional_items_frequency, merger_impact_ratio,
                                                          non_operating_income_share, asset_sale_boost,
                                                          accounting_quality_score) ON id.isin = aqf.isin
         LEFT JOIN calc_quality_features_comprehensive() qfc(isin, goodwill_impairment_ltm, asset_writedown_ltm,
                                                             restructuring_ltm, has_goodwill_impairment_ltm,
                                                             goodwill_impairment_frequency, asset_writedown_frequency,
                                                             restructuring_frequency, exceptional_items_total_ltm,
                                                             exceptional_items_to_ebitda, quality_issues_count_5y,
                                                             accounting_quality_score) ON id.isin = qfc.isin
         LEFT JOIN calc_leverage_features() lf(isin, debt_to_equity, debt_to_assets, equity_ratio,
                                               interest_coverage,
                                               current_ratio, cash_ratio, working_capital_ratio)
                   ON id.isin = lf.isin
         LEFT JOIN calc_efficiency_ratios() er(isin, asset_turnover, inventory_turnover, receivables_days,
                                               working_capital_turns) ON id.isin = er.isin
         LEFT JOIN calc_balance_sheet_dynamics() bsd(isin, cash_to_assets_pct, cash_change_qoq, cash_vs_5y_avg,
                                                     inventory_change_yoy, inventory_vs_5y_avg,
                                                     receivables_change_yoy,
                                                     receivables_vs_5y_avg, working_capital_vs_5y_avg,
                                                     retained_earnings_vs_5y, intangibles_growth_flag,
                                                     asset_quality_score, balance_sheet_strength,
                                                     debt_maturity_risk)
                   ON id.isin = bsd.isin
         LEFT JOIN calc_working_capital_temporal() wct(isin, wc_fq, wc_fy, wc_ltm, wc_5yavgfy, wc_1fq, wc_2fq,
                                                       wc_3fq,
                                                       wc_4fq, wc_1fy, wc_2fy, wc_3fy, wc_4fy, wc_qoq_change,
                                                       wc_yoy_change, wc_4q_trend, wc_vs_5y_avg,
                                                       wc_positive_quarters,
                                                       wc_improving_flag, wc_volatility) ON id.isin = wct.isin
         LEFT JOIN calc_total_debt_temporal() tdt(isin, debt_fq, debt_fy, debt_ltm, debt_1fq, debt_2fq,
                                                  debt_3fq,
                                                  debt_4fq, debt_1fy, debt_2fy, debt_3fy, debt_4fy,
                                                  debt_qoq_change,
                                                  debt_yoy_change, debt_4q_trend, debt_3y_cagr,
                                                  debt_deleveraging,
                                                  debt_to_equity_trend) ON id.isin = tdt.isin
         LEFT JOIN calc_working_capital_deep_features() wcd(isin, working_capital_ltm, working_capital_fq,
                                                            working_capital_fy, wc_to_revenue, wc_to_assets,
                                                            wc_change_qoq, wc_change_yoy, days_working_capital,
                                                            wc_efficiency_score, negative_wc_flag, wc_improvement_flag)
                   ON id.isin = wcd.isin
         LEFT JOIN calc_sentiment_features() sf(isin, analyst_bullish_pct, analyst_bearish_pct,
                                                analyst_neutral_pct,
                                                analyst_conviction, upside_potential,
                                                price_target_spread_pct,
                                                price_target_revision_1m, price_target_revision_3m,
                                                eps_revision_momentum, analyst_rating_normalized,
                                                analyst_coverage_quality) ON id.isin = sf.isin
         LEFT JOIN calc_price_target_dynamics() ptd(isin, pt_momentum_1w, pt_momentum_1m, pt_momentum_3m,
                                                    pt_momentum_6m, pt_momentum_1y, pt_median_momentum_1m,
                                                    pt_median_momentum_3m, pt_acceleration_short,
                                                    pt_acceleration_long,
                                                    pt_consensus_convergence, analyst_coverage_change_1m,
                                                    analyst_coverage_change_3m, analyst_coverage_change_1y,
                                                    pt_vs_price_momentum, analyst_coverage_trend)
                   ON id.isin = ptd.isin
         LEFT JOIN calc_dividend_features() df(isin, dividend_streak, dividend_yield_ltm,
                                               dividend_yield_ntm,
                                               dividend_payout_ratio, fcf_dividend_coverage, buyback_yield,
                                               total_shareholder_yield, dividend_growth_expectation)
                   ON id.isin = df.isin
         LEFT JOIN calc_dividend_timing() dt(isin, days_since_ex_date, days_to_payment,
                                             dividend_announced_flag,
                                             ex_date_approaching_flag, dividend_frequency_score,
                                             dividend_consistency,
                                             recent_dividend_change, dividend_yield_vs_5y_avg)
                   ON id.isin = dt.isin
         LEFT JOIN calc_dividend_yield_comprehensive() dyc(isin, div_yield_ltm, div_yield_ntm, div_yield_ind,
                                                           div_yield_1fy_ind, div_yield_5y_avg, div_yield_vs_5y_avg,
                                                           div_yield_growth_expected, dividend_streak,
                                                           high_yield_flag,
                                                           sustainable_dividend_flag) ON id.isin = dyc.isin
         LEFT JOIN calc_employment_features() emf(isin, revenue_per_employee, profit_per_employee,
                                                  ebitda_per_employee,
                                                  assets_per_employee, fte_growth_1y_pct, fte_growth_3y_pct,
                                                  workforce_stability) ON id.isin = emf.isin
         LEFT JOIN calc_employment_dynamics() ed(isin, fte_growth_2y_pct, fte_acceleration,
                                                 workforce_volatility,
                                                 hiring_intensity, productivity_trend, headcount_vs_revenue,
                                                 workforce_efficiency_gain, layoff_risk_flag,
                                                 rapid_hiring_flag,
                                                 sustainable_growth_flag) ON id.isin = ed.isin
         LEFT JOIN calc_cashflow_features() cf(isin, cfo_to_net_income, fcf_to_net_income, fcf_margin,
                                               cfo_growth_yoy,
                                               fcf_positive_ratio, acquisition_intensity,
                                               self_funding_ratio)
                   ON id.isin = cf.isin
         LEFT JOIN calc_enhanced_cashflow_features() ecff(isin, fcf_positive_years, fcf_always_positive,
                                                          capex_vs_5y_avg, underinvestment_flag, cfo_share_of_cf,
                                                          cfi_share_of_cf, cff_share_of_cf, self_funding_flag,
                                                          acquisition_to_fcf, sustainable_ma_flag,
                                                          fcf_4q_improvement,
                                                          cash_flow_quality_score, capex_yoy_growth,
                                                          capex_qoq_growth,
                                                          capex_3y_trend, capex_volatility, capex_acceleration,
                                                          capex_cut_flag, overinvestment_flag,
                                                          acquisitions_yoy_growth,
                                                          acquisitions_vs_5y_avg, acquisitions_ltm_total,
                                                          ma_intensity_score, serial_acquirer_flag,
                                                          acquisition_pause_flag, total_investment_to_cfo,
                                                          organic_vs_inorganic, investment_efficiency)
                   ON id.isin = ecff.isin
         LEFT JOIN calc_cashflow_temporal_features() ctf(isin, cfo_quarterly_trend, cfo_yoy_quarterly,
                                                         cfi_quarterly_trend, cff_quarterly_trend,
                                                         fcf_quarterly_trend,
                                                         cfo_positive_quarters, cfi_negative_quarters,
                                                         cff_pattern_score, cash_burn_rate, cf_volatility_score,
                                                         operating_cf_momentum, financing_dependency)
                   ON id.isin = ctf.isin
         LEFT JOIN calc_cashflow_comprehensive() cc(isin, cfo_fq, cfo_ltm, cfo_fy, fcf_fq, fcf_ltm, fcf_fy,
                                                    cfo_growth_yoy, fcf_growth_yoy, cfo_to_net_income,
                                                    fcf_margin,
                                                    fcf_yield, cfo_positive_years, fcf_positive_years,
                                                    cash_flow_quality_score) ON id.isin = cc.isin
         LEFT JOIN calc_temporal_features() tf(isin, fiscal_quarter, fiscal_month, fiscal_year,
                                               days_to_earnings,
                                               earnings_report_recency, reporting_lag,
                                               fiscal_year_progress)
                   ON id.isin = tf.isin
         LEFT JOIN calc_fiscal_calendar_features() fcf(isin, days_since_last_report, days_to_fy_end,
                                                       is_quarter_end_month, is_fy_end_month,
                                                       earnings_season_flag,
                                                       pre_earnings_window, post_earnings_window,
                                                       reporting_freshness_score, fiscal_quarter_progress)
                   ON id.isin = fcf.isin
         LEFT JOIN calc_total_assets_temporal() tat(isin, assets_fq, assets_fy, assets_ltm, assets_1fq,
                                                    assets_2fq,
                                                    assets_3fq, assets_4fq, assets_1fy, assets_2fy, assets_3fy,
                                                    assets_4fy, assets_qoq_growth, assets_yoy_growth,
                                                    assets_3y_cagr,
                                                    asset_growth_accel, asset_base_stable)
                   ON id.isin = tat.isin
         LEFT JOIN calc_inventory_temporal_features() itf(isin, inventory_ltm, inventory_fq, inventory_fy,
                                                          inventory_1fq, inventory_2fq, inventory_3fq, inventory_4fq,
                                                          inventory_1fy, inventory_2fy, inventory_3fy, inventory_4fy,
                                                          inventory_qoq_change, inventory_yoy_change,
                                                          inventory_4q_trend, inventory_vs_5y_avg, inventory_days,
                                                          inventory_turnover, inventory_to_revenue,
                                                          inventory_to_assets,
                                                          inventory_buildup_flag, inventory_reduction_flag,
                                                          inventory_volatility) ON id.isin = itf.isin
         LEFT JOIN calc_goodwill_temporal_features() gtf(isin, goodwill_fq, goodwill_ltm, goodwill_fy, goodwill_1fq,
                                                         goodwill_2fq, goodwill_3fq, goodwill_4fq, goodwill_1fy,
                                                         goodwill_2fy, goodwill_3fy, goodwill_4fy,
                                                         goodwill_qoq_change,
                                                         goodwill_yoy_change, goodwill_3y_growth,
                                                         goodwill_vs_5y_avg,
                                                         recent_acquisition_flag, goodwill_accumulation_rate,
                                                         goodwill_to_assets_trend, impairment_risk_score,
                                                         goodwill_concentration) ON id.isin = gtf.isin
         LEFT JOIN calc_cost_structure_features() csf(isin, cogs_to_revenue, opex_to_revenue, sga_to_revenue,
                                                      rnd_to_revenue, interest_to_revenue, sga_trend_yoy,
                                                      operating_leverage_proxy, cost_efficiency_score,
                                                      marketing_to_revenue, marketing_trend_yoy,
                                                      marketing_vs_5y_avg,
                                                      sga_vs_5y_avg, sga_efficiency_trend) ON id.isin = csf.isin
         LEFT JOIN calc_rnd_temporal_features() rtf(isin, rnd_ltm, rnd_fq, rnd_fy, rnd_1fqfq, rnd_2fqfq,
                                                    rnd_3fqfq,
                                                    rnd_4fqfq, rnd_1fy, rnd_2fy, rnd_3fy, rnd_4fy,
                                                    rnd_intensity_ltm,
                                                    rnd_intensity_fy, rnd_intensity_trend, rnd_qoq_growth,
                                                    rnd_yoy_growth, rnd_cagr_3y, rnd_per_employee,
                                                    rnd_to_gross_profit,
                                                    rnd_roi_proxy, rnd_increasing_flag, rnd_cut_flag,
                                                    high_rnd_intensity_flag) ON id.isin = rtf.isin
         LEFT JOIN calc_interest_income_features() iif(isin, interest_income_ltm, interest_expense_ltm,
                                                       net_interest_income, interest_coverage_ratio,
                                                       interest_income_to_revenue, interest_expense_to_revenue,
                                                       net_interest_margin_proxy) ON id.isin = iif.isin
         LEFT JOIN calc_composite_scores() cs(isin, piotroski_f_score, dilution_score, quality_momentum_score)
                   ON id.isin = cs.isin
         LEFT JOIN calc_net_income_comprehensive() nic(isin, net_income_is_fq, net_income_is_ltm,
                                                       net_income_is_fy,
                                                       net_income_adj_ltm, normalized_ni_ltm, net_income_is_1fqfq,
                                                       net_income_is_2fqfq, net_income_is_3fqfq,
                                                       net_income_is_4fqfq,
                                                       net_income_is_1fy, net_income_is_2fy, net_income_is_3fy,
                                                       net_income_is_4fy, net_income_is_5yavgfq,
                                                       net_income_is_5yavgltm,
                                                       normalized_ni_5yavgfq, normalized_ni_5yavgltm,
                                                       net_income_growth_yoy, net_income_margin_ltm,
                                                       ni_adjustment_ratio, net_income_positive_years,
                                                       earnings_quality_composite, net_income_qoq_growth,
                                                       net_income_yoy_quarterly, net_income_vs_5y_avg,
                                                       normalized_ni_vs_5y_avg) ON id.isin = nic.isin
         LEFT JOIN calc_unusual_items_features() uif(isin, other_unusual_items_ltm, impairment_goodwill_ltm,
                                                     asset_writedown_ltm, restructuring_charges_ltm,
                                                     total_unusual_items, unusual_items_to_revenue,
                                                     unusual_items_to_ebitda, has_unusual_items_flag,
                                                     earnings_quality_impact) ON id.isin = uif.isin
         LEFT JOIN calc_volatility_surface_features() vsf(isin, vol_1m, vol_3m, vol_6m, vol_1y,
                                                          vol_term_spread_short,
                                                          vol_term_spread_long, vol_ratio_3m_1y, vol_hump, beta_1y,
                                                          beta_2y, beta_5y, beta_term_structure, beta_convexity,
                                                          realized_vs_implied_proxy) ON id.isin = vsf.isin
         LEFT JOIN calc_tax_rate_features() txf(isin, effective_tax_rate_ltm, effective_tax_rate_fy,
                                                tax_rate_yoy_change, tax_rate_qoq_change,
                                                tax_rate_stability,
                                                low_tax_flag, tax_rate_trend_4q) ON id.isin = txf.isin
         LEFT JOIN calc_opex_temporal_features() otf(isin, opex_fq, opex_ltm, opex_fy, opex_qoq_growth,
                                                     opex_yoy_growth,
                                                     opex_vs_revenue_trend, sga_qoq_growth, sga_yoy_growth,
                                                     operating_leverage_score) ON id.isin = otf.isin
         LEFT JOIN calc_asset_sale_features() asf(isin, gain_loss_on_sale_of_assets_ltm,
                                                  asset_sale_frequency,
                                                  asset_sale_trend) ON id.isin = asf.isin
         LEFT JOIN calc_fcf_estimate_features() fcfe(isin, fcf_est_avg_fy1e, fcf_est_avg_fy2e,
                                                     fcf_est_avg_fy3e,
                                                     fcf_est_avg_fy4e, fcf_est_avg_fy5e, fcf_est_cagr_5y,
                                                     fcf_est_trend)
                   ON id.isin = fcfe.isin
         LEFT JOIN calc_dividend_history_features() dhf(isin, div_yield_2fy, div_yield_3fy, div_yield_4fy,
                                                        div_yield_5fy, div_yield_trend_3y, div_yield_volatility,
                                                        div_yield_declining_flag, div_yield_mean_5y,
                                                        div_yield_vs_5y_mean) ON id.isin = dhf.isin
         LEFT JOIN calc_investment_income_temporal() iit(isin, inv_income_ltm, inv_income_fq, inv_income_fy,
                                                         inv_income_qoq_growth, inv_income_yoy_growth,
                                                         inv_income_to_revenue, inv_income_trend_3y,
                                                         inv_income_positive_quarters, financial_company_proxy)
                   ON id.isin = iit.isin
         LEFT JOIN calc_share_dilution_tracking() sdt(isin, shrs_out_1fy, shares_yoy_change_pct, net_buyback_flag)
                   ON id.isin = sdt.isin
         LEFT JOIN calc_forward_consensus_features() fcnf(isin, pe_ntm, pe_est_fy1, pe_forward_discount,
                                                          eps_gaap_vs_norm_ntm, eps_gaap_vs_norm_fy1e,
                                                          forward_adjustment_trend, ebitda_est_ntm, ebitda_est_fy1e,
                                                          ev_ebitda_est_fy1, ebitda_forward_growth,
                                                          earnings_revision_divergence, forward_pe_vs_sector_proxy)
                   ON id.isin = fcnf.isin
         LEFT JOIN calc_price_target_achievement_features() ptaf(isin, pt_achievement_1y, pt_accuracy_1y,
                                                                 pt_optimism_bias, pt_range_hit_rate,
                                                                 pt_median_vs_mean_spread,
                                                                 pt_high_low_convergence_1y,
                                                                 analyst_count_stability)
                   ON id.isin = ptaf.isin
         LEFT JOIN calc_size_liquidity_features() slf(isin, market_cap, market_cap_country_r, log_market_cap,
                                                      volume_shrs, relative_volume, shares_outstanding,
                                                      daily_turnover_ratio, size_class, style_class,
                                                      liquidity_score)
                   ON id.isin = slf.isin
         LEFT JOIN calc_fcf_growth_estimates() fge(isin, fcf_est_fy1, fcf_est_fy2, fcf_est_fy3,
                                                   fcf_est_fy4, fcf_est_fy5,
                                                   fcf_est_growth_fy1_vs_ltm,
                                                   fcf_est_growth_fy2_vs_fy1,
                                                   fcf_est_growth_fy3_vs_fy2,
                                                   fcf_est_growth_fy4_vs_fy3,
                                                   fcf_est_growth_fy5_vs_fy4,
                                                   fcf_est_cagr_3y, fcf_est_cagr_5y,
                                                   fcf_est_margin_fy1, fcf_est_yield_fy1,
                                                   fcf_est_growth_acceleration,
                                                   fcf_est_growth_deceleration,
                                                   fcf_est_trajectory_score,
                                                   fcf_est_always_positive,
                                                   fcf_est_vs_historical,
                                                   fcf_est_capex_implied_ratio)
                   ON id.isin = fge.isin
SELECT_LEGACY_FEATURE_COLUMNS_END
*/

comment on materialized view mv_exp_returns_df is 'Unified materialized view containing all calculated stock features.
    Covers 29 feature categories from 56 calc_* functions:
    1. Valuation Ratios (4 functions)
    2. Momentum (2 functions)
    3. Technical Analysis (1 function)
    4. Profitability (4 functions)
    5. Earnings (6 functions)
    6. Growth (5 functions) - includes Revenue Estimate Consensus
    7. Quality & Risk (5 functions)
    8. Leverage & Liquidity (6 functions)
    9. Analyst Sentiment (3 functions) - includes Price Target Achievement
    10. Dividends (3 functions)
    11. Employment (2 functions)
    12. Cash Flow (5 functions) - includes FCF Growth Estimates
    13. Temporal (2 functions)
    14. Balance Sheet (3 functions)
    15. Cost Structure (3 functions)
    16. Composite Scores (2 functions)
    17. Unusual Items (1 function)
    18. Volatility Surface (1 function)
    19. Tax Rate Features (1 function)
    20. OpEx Temporal (1 function)
    21. Asset Sale Features (1 function)
    22. FCF Estimate Curve (1 function)
    23. Dividend History (1 function)
    24. Investment Income Temporal (1 function)
    25. Share Dilution Tracking (1 function)
    26. Forward Consensus (1 function)
    27. Price Target Achievement (1 function) - NEW
    28. Size & Liquidity (1 function) - NEW
    29. FCF Growth Estimates (1 function) - NEW

    Direct reference columns include: identifiers (32 cols), equities (36 cols)

    Refresh with: REFRESH MATERIALIZED VIEW CONCURRENTLY mv_exp_returns_df;';


-- =============================================================================
-- REFRESH FUNCTION
-- =============================================================================
CREATE OR REPLACE FUNCTION refresh_all_stock_features()
    RETURNS void
    LANGUAGE plpgsql
AS
$$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_exp_returns_df;
    RAISE NOTICE 'mv_exp_returns_df refreshed at %', NOW();
END;
$$;

COMMENT ON FUNCTION refresh_all_stock_features() IS
    'Refreshes the mv_exp_returns_df materialized view concurrently (non-blocking).
    Call periodically after equities table updates.';
