-- ===================================================================
-- Equities Data Import Script (Revised)
-- ===================================================================
-- Documentation: See docs/column_mapping_reference.md for column aliases
-- Usage: psql -h localhost -p 5432 -U postgres -d postgres -f import_pml_data.sql
\echo 'Starting pml_df data import...'

-- ===================================================================
-- SESSION-LEVEL TUNING FOR BULK IMPORT
-- ===================================================================
SET search_path = pml, public;
SET work_mem = '256MB';
SET maintenance_work_mem = '512MB';
SET synchronous_commit = OFF;
SET checkpoint_completion_target = 0.9;
\echo 'Session tuning applied for bulk import optimization.'

DO $$ BEGIN RAISE NOTICE 'Import started at %', NOW(); END $$;

-- Show current target table status
SELECT 'Current pml_df table row count:' AS status, COUNT(*) AS row_count FROM pml_df;

-- ===================================================================
-- HELPER FUNCTIONS
-- ===================================================================
CREATE OR REPLACE FUNCTION text_to_numeric_safe(input_text TEXT)
    RETURNS NUMERIC AS
$$
SELECT CASE
           WHEN input_text IS NULL
               OR TRIM(input_text) IN ('', '-', '--', 'N/A', 'NA', 'NULL', 'NONE',
                                       'n/a', 'na', 'null', 'none')
               THEN NULL
           WHEN TRIM(input_text) ~ '^-?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$'
               THEN TRIM(input_text)::NUMERIC
           END
$$ LANGUAGE SQL IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION text_to_date_safe(input_text TEXT,
                                              date_format TEXT DEFAULT 'YYYY-MM-DD')
    RETURNS DATE AS
$$
BEGIN
    IF input_text IS NULL
       OR TRIM(input_text) IN ('', '-', '--', 'N/A', 'NA', 'NULL', 'NONE') THEN
        RETURN NULL;
    END IF;
    RETURN TO_DATE(TRIM(input_text), date_format);
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;

-- ===================================================================
-- STAGING TABLE
-- -------------------------------------------------------------------
-- This is a STABLE, persistent staging table whose column list and
-- ORDER match the regional CSV header exactly. \copy maps CSV fields
-- to columns positionally, so this ordering is the contract with the
-- data vendor. If the vendor adds/removes/renames a column, update
-- the DDL below ONCE and re-run.
--
-- All columns are TEXT so that:
--   * COPY never fails on numeric parsing,
--   * Empty strings, "n/a", "-", etc., are preserved as-is,
--   * The downstream INSERT casts each value with text_to_*_safe().
-- ===================================================================
DROP TABLE IF EXISTS pml.pml_staging;
CREATE TABLE pml.pml_staging
(
    "Ticker"                                           TEXT,
    "ISIN"                                             TEXT,
    "Name"                                             TEXT,
    "Description"                                      TEXT,
    "Region"                                           TEXT,
    "Country"                                          TEXT,
    "Trading Country"                                  TEXT,
    "Exchange"                                         TEXT,
    "Unit"                                             TEXT,
    "Sector"                                           TEXT,
    "Industry"                                         TEXT,
    "Style Class"                                      TEXT,
    "Size Class"                                       TEXT,
    "Last Updated"                                     TEXT,
    "Income Statement Report Date"                     TEXT,
    "FY End"                                           TEXT,
    "Next Earnings"                                    TEXT,
    "Next Earnings (When)"                             TEXT,
    "Next Earnings (Status)"                           TEXT,
    "Dividend Record (Currency)"                       TEXT,
    "Dividend Record (Amount)"                         TEXT,
    "Dividend Record (Frequency)"                      TEXT,
    "Dividend Streak"                                  TEXT,
    "Dividend Record (Announce Date)"                  TEXT,
    "Dividend Record (Payable Date)"                   TEXT,
    "Dividend Record (Record Date)"                    TEXT,
    "Dividend Record (Ex Date)"                        TEXT,
    "Market Cap"                                       TEXT,
    "Enterprise Value"                                 TEXT,
    "Last Price"                                       TEXT,
    "Price Target (YTD Ago)"                           TEXT,
    "Total Return (YTD)"                               TEXT,
    "Price Target"                                     TEXT,
    "Price Target - Low"                               TEXT,
    "Price Target - Median"                            TEXT,
    "Price Target - High"                              TEXT,
    "Price Target - #"                                 TEXT,
    "P/E (NTM)"                                        TEXT,
    "P/E (LTM)"                                        TEXT,
    "Altman Z-Score (FY)"                              TEXT,
    "Altman Z-Score (FQ)"                              TEXT,
    "Altman Z-Score (LTM)"                             TEXT,
    "Beta (1Y)"                                        TEXT,
    "Beta (2Y)"                                        TEXT,
    "Beta (5Y)"                                        TEXT,
    "Analyst Rating"                                   TEXT,
    "# Strong Sell Ratings"                            TEXT,
    "# Strong Buys Ratings"                            TEXT,
    "# Hold Ratings"                                   TEXT,
    "# Buys Ratings"                                   TEXT,
    "# Sell Ratings"                                   TEXT,
    "# No Opinion Ratings"                             TEXT,
    "Total Revenues/CAGR (5Y FY)"                      TEXT,
    "Total Revenues (FQ)"                              TEXT,
    "Total Revenues (-1FY)"                            TEXT,
    "Total Revenues (FY)"                              TEXT,
    "Total Revenues (LTM)"                             TEXT,
    "Total Operating Expenses (LTM)"                   TEXT,
    "P/TBV (LTM)"                                      TEXT,
    "TBV (FY)"                                         TEXT,
    "TBV (LTM)"                                        TEXT,
    "Market Cap (Country R)"                           TEXT,
    "Tot. Return %/CAGR (3Y)"                          TEXT,
    "Tot. Return %/CAGR (10Y)"                         TEXT,
    "Total Return (5Y)"                                TEXT,
    "Total Return (10Y)"                               TEXT,
    "Net Income/Adj. (-1FY)"                           TEXT,
    "CFF (LTM)"                                        TEXT,
    "CFI (LTM)"                                        TEXT,
    "FCF (LTM)"                                        TEXT,
    "CFO (LTM)"                                        TEXT,
    "EBITDA (FQ)"                                      TEXT,
    "EBITDA (LTM)"                                     TEXT,
    "EBITDA (FY)"                                      TEXT,
    "EBITDA (-1FY)"                                    TEXT,
    "EBITDA/Adj. (LTM)"                                TEXT,
    "EBITDA/Adj. (FY)"                                 TEXT,
    "EBITDA/Adj. (-1FY)"                               TEXT,
    "EBIT (FQ)"                                        TEXT,
    "EBIT (LTM)"                                       TEXT,
    "EBIT (FY)"                                        TEXT,
    "EBIT (-1FY)"                                      TEXT,
    "EBIT/Adj. (-1FY)"                                 TEXT,
    "EBIT/Adj. (FY)"                                   TEXT,
    "EBIT/Adj. (LTM)"                                  TEXT,
    "EBIT - Est Med (FY1E)"                            TEXT,
    "EBIT - Est Med (NTM)"                             TEXT,
    "Return On Equity % (LTM)"                         TEXT,
    "Return On Equity % (FY)"                          TEXT,
    "Net Income - (IS) (FY)"                           TEXT,
    "Net Income - (IS) (LTM)"                          TEXT,
    "Normalized Net Income (FY)"                       TEXT,
    "Normalized Net Income (LTM)"                      TEXT,
    "Net Income/Adj. (FY)"                             TEXT,
    "Net Income/Adj. (LTM)"                            TEXT,
    "Net Income Margin % (FY)"                         TEXT,
    "Net Income Margin % (LTM)"                        TEXT,
    "Volatility (1M)"                                  TEXT,
    "Volatility (3M)"                                  TEXT,
    "Volatility (6M)"                                  TEXT,
    "Volatility (1Y)"                                  TEXT,
    "Volume (Shrs)"                                    TEXT,
    "Dividend Per Share (LTM)"                         TEXT,
    "Div Yield (Ind)"                                  TEXT,
    "Div Yield (LTM)"                                  TEXT,
    "Total Debt (FY)"                                  TEXT,
    "Total Equity (FY)"                                TEXT,
    "Total Equity (LTM)"                               TEXT,
    "Total Debt (LTM)"                                 TEXT,
    "Total Assets (LTM)"                               TEXT,
    "Total Assets (FY)"                                TEXT,
    "Current Ratio (FY)"                               TEXT,
    "Current Ratio (LTM)"                              TEXT,
    "Gross Profit Margin % (FY)"                       TEXT,
    "Gross Profit Margin % (LTM)"                      TEXT,
    "Asset Turnover (FY)"                              TEXT,
    "Asset Turnover (LTM)"                             TEXT,
    "Gross Profit (LTM)"                               TEXT,
    "Gross Profit (FY)"                                TEXT,
    "EPS Norm - Est Avg (NTM)"                         TEXT,
    "EPS/Adj. (-1FY)"                                  TEXT,
    "EPS/Adj. (FY)"                                    TEXT,
    "EPS/Adj. (LTM)"                                   TEXT,
    "EPS Norm - Est Avg (FY1E)"                        TEXT,
    "Gain (Loss) On Sale Of Assets (LTM)"              TEXT,
    "Cost Of Revenues (LTM)"                           TEXT,
    "Cash Acquisitions (LTM)"                          TEXT,
    "Cash Acquisitions (FY)"                           TEXT,
    "Cash Acquisitions (-1FY)"                         TEXT,
    "Inventory (LTM)"                                  TEXT,
    "Goodwill (FQ)"                                    TEXT,
    "Goodwill (LTM)"                                   TEXT,
    "Goodwill (FY)"                                    TEXT,
    "Goodwill (-1FY)"                                  TEXT,
    "Impairment of Goodwill (FQ)"                      TEXT,
    "Impairment of Goodwill (LTM)"                     TEXT,
    "Impairment of Goodwill (-1FY)"                    TEXT,
    "Impairment of Goodwill (FY)"                      TEXT,
    "Operating Income (LTM)"                           TEXT,
    "Asset Writedown (LTM)"                            TEXT,
    "Asset Writedown (FY)"                             TEXT,
    "Asset Writedown (-1FY)"                           TEXT,
    "Operating Income (FY)"                            TEXT,
    "Capital Expenditure (LTM)"                        TEXT,
    "Capital Expenditure (-1FY)"                       TEXT,
    "Capital Expenditure (FY)"                         TEXT,
    "Retained Earnings (LTM)"                          TEXT,
    "Total Current Assets (LTM)"                       TEXT,
    "Total Current Liabilities (LTM)"                  TEXT,
    "R&D Expenses (LTM)"                               TEXT,
    "Restructuring Charges (LTM)"                      TEXT,
    "Restructuring Charges (FQ)"                       TEXT,
    "Restructuring Charges (-1FY)"                     TEXT,
    "Restructuring Charges (FY)"                       TEXT,
    "Interest Expense/Total (LTM)"                     TEXT,
    "Merger & Restructuring Charges (LTM)"             TEXT,
    "Working Capital (LTM)"                            TEXT,
    "Other Unusual Items/Total (LTM)"                  TEXT,
    "Interest Income On Investments (LTM)"             TEXT,
    "Buyback Yield (LTM)"                              TEXT,
    "Return on Assets (ROA) % (LTM)"                   TEXT,
    "Return on Assets (ROA) % (FY)"                    TEXT,
    "Net Income - (IS) (-1FY)"                         TEXT,
    "Normalized Net Income (-1FY)"                     TEXT,
    "CFF (FY)"                                         TEXT,
    "CFF (-1FY)"                                       TEXT,
    "CFI (FY)"                                         TEXT,
    "CFI (-1FY)"                                       TEXT,
    "CFO (FY)"                                         TEXT,
    "CFO (-1FY)"                                       TEXT,
    "Div Yield (-1FYInd)"                              TEXT,
    "FCF (FY)"                                         TEXT,
    "FCF (-1FY)"                                       TEXT,
    "Capital Expenditure (FQ)"                         TEXT,
    "Capital Expenditure (5YAVGFQ)"                    TEXT,
    "CFF (FQ)"                                         TEXT,
    "CFI (FQ)"                                         TEXT,
    "CFO (FQ)"                                         TEXT,
    "FCF (FQ)"                                         TEXT,
    "Total Revenues (5YAVGFQ)"                         TEXT,
    "EBITDA (5YAVGFQ)"                                 TEXT,
    "EBIT (5YAVGFQ)"                                   TEXT,
    "FCF (5YAVGFQ)"                                    TEXT,
    "Cash Acquisitions (FQ)"                           TEXT,
    "Cash Acquisitions (5YAVGFQ)"                      TEXT,
    "Asset Writedown (FQ)"                             TEXT,
    "Asset Writedown (5YAVGFQ)"                        TEXT,
    "Impairment of Goodwill (5YAVGFQ)"                 TEXT,
    "Operating Income (FQ)"                            TEXT,
    "Operating Income (5YAVGFQ)"                       TEXT,
    "P/B (LTM)"                                        TEXT,
    "P/B (-1FY)"                                       TEXT,
    "P/B (5YAVG)"                                      TEXT,
    "Cash And Equivalents (LTM)"                       TEXT,
    "Cash And Equivalents (FQ)"                        TEXT,
    "Cash And Equivalents (FY)"                        TEXT,
    "Cash And Equivalents (5YAVGFQ)"                   TEXT,
    "Inventory (FQ)"                                   TEXT,
    "Inventory (FY)"                                   TEXT,
    "Goodwill (5YAVGFQ)"                               TEXT,
    "Inventory (5YAVGFQ)"                              TEXT,
    "Retained Earnings (FQ)"                           TEXT,
    "Retained Earnings (FY)"                           TEXT,
    "Retained Earnings (5YAVGFQ)"                      TEXT,
    "Working Capital (FQ)"                             TEXT,
    "Working Capital (FY)"                             TEXT,
    "Working Capital (5YAVGFY)"                        TEXT,
    "Div Yield (TTM)"                                  TEXT,
    "Div Yield (NTM)"                                  TEXT,
    "Div Yield (5YAVGLTM)"                             TEXT,
    "Gross Intangible Assets (LTM)"                    TEXT,
    "Gross Intangible Assets (FY)"                     TEXT,
    "Gross Intangible Assets (5YAVGFQ)"                TEXT,
    "Restructuring Charges (5YAVGFQ)"                  TEXT,
    "Merger & Restructuring Charges (FQ)"              TEXT,
    "Merger & Restructuring Charges (FY)"              TEXT,
    "Merger & Restructuring Charges (5YAVGFQ)"         TEXT,
    "Normalized Net Income (FQ)"                       TEXT,
    "Normalized Net Income (5YAVGFQ)"                  TEXT,
    "Net Income/Adj. (FQ)"                             TEXT,
    "Net Income/Adj. (5YAVGFQ)"                        TEXT,
    "Net Income - (IS) (FQ)"                           TEXT,
    "Net Income - (IS) (5YAVGFQ)"                      TEXT,
    "Net Income - (IS) (5YAVGLTM)"                     TEXT,
    "Normalized Net Income (5YAVGLTM)"                 TEXT,
    "EBITDA (5YAVGLTM)"                                TEXT,
    "EBIT (5YAVGLTM)"                                  TEXT,
    "Total Revenues (5YAVGLTM)"                        TEXT,
    "Revenues - Est YoY % (FY1E)"                      TEXT,
    "Price Chg. % (1M)"                                TEXT,
    "Price Chg. % (3M)"                                TEXT,
    "1-Day %"                                          TEXT,
    "Price (5D Ago)"                                   TEXT,
    "Price (1W Ago)"                                   TEXT,
    "Price (1M Ago)"                                   TEXT,
    "Price (3M Ago)"                                   TEXT,
    "Price (6M Ago)"                                   TEXT,
    "Price (1Y Ago)"                                   TEXT,
    "Price (3Y Ago)"                                   TEXT,
    "Price (5Y Ago)"                                   TEXT,
    "Price (QTD Ago)"                                  TEXT,
    "Rel. Volume"                                      TEXT,
    "Shrs Out"                                         TEXT,
    "Shrs Out (-1FY)"                                  TEXT,
    "Common Dividends Paid (LTM)"                      TEXT,
    "Common Dividends Paid (FY)"                       TEXT,
    "Selling General & Admin Expenses/Total (FQ)"      TEXT,
    "Selling General & Admin Expenses/Total (FY)"      TEXT,
    "Selling General & Admin Expenses/Total (-1FY)"    TEXT,
    "Selling General & Admin Expenses/Total (5YAVGFQ)" TEXT,
    "Accounts Receivable/Total (FY)"                   TEXT,
    "Accounts Receivable/Total (-1FY)"                 TEXT,
    "Accounts Receivable/Total (5YAVGFQ)"              TEXT,
    "Marketing Expenses (FQ)"                          TEXT,
    "Marketing Expenses (FY)"                          TEXT,
    "Marketing Expenses (-1FY)"                        TEXT,
    "Marketing Expenses (5YAVGLTM)"                    TEXT,
    "Revenues - Est Avg (NTM)"                         TEXT,
    "Revenues - Est Avg (FY1E)"                        TEXT,
    "Revenues - Est Med (NTM)"                         TEXT,
    "Revenues - Est Med (FY1E)"                        TEXT,
    "EV/Sales (EST FY1)"                               TEXT,
    "EV/Sales (LTM)"                                   TEXT,
    "EV/Sales (NTM)"                                   TEXT,
    "EV/Sales (-1FYLTM)"                               TEXT,
    "EV/Sales (-2FYLTM)"                               TEXT,
    "EV/Sales (-3FYLTM)"                               TEXT,
    "EV/Sales (3YAVGLTM)"                              TEXT,
    "EV/Sales (-1FQLTM)"                               TEXT,
    "EV/Sales (-2FQLTM)"                               TEXT,
    "EV/Sales (-3FQLTM)"                               TEXT,
    "EV/Sales (-4FQLTM)"                               TEXT,
    "52W High/Adj"                                     TEXT,
    "52W Low/Adj"                                      TEXT,
    "EMA (20D)"                                        TEXT,
    "EMA (50D)"                                        TEXT,
    "EMA (100D)"                                       TEXT,
    "EMA (250D)"                                       TEXT,
    "EV/EBITDA (LTM)"                                  TEXT,
    "EV/EBITDA (NTM)"                                  TEXT,
    "EV/EBITDA (-1FYLTM)"                              TEXT,
    "EV/EBITDA (-1FQLTM)"                              TEXT,
    "EV/EBITDA (3YAVGLTM)"                             TEXT,
    "EV/EBITDA (EST FY1)"                              TEXT,
    "P/E (EST FY1)"                                    TEXT,
    "P/E (-1FYLTM)"                                    TEXT,
    "P/E (-2FYLTM)"                                    TEXT,
    "P/E (-3FYLTM)"                                    TEXT,
    "P/E (3YAVGLTM)"                                   TEXT,
    "P/E (-1FQLTM)"                                    TEXT,
    "P/E (-2FQLTM)"                                    TEXT,
    "P/E (-3FQLTM)"                                    TEXT,
    "P/E (5YAVGLTM)"                                   TEXT,
    "P/E (-0FQQoQLTM)"                                 TEXT,
    "P/E (-0FYYoYLTM)"                                 TEXT,
    "P/E (-1FYYoYLTM)"                                 TEXT,
    "P/E (-0FQYoYLTM)"                                 TEXT,
    "Full Time Employees (FQ)"                         TEXT,
    "Full Time Employees (FY)"                         TEXT,
    "Full Time Employees (-1FY)"                       TEXT,
    "Full Time Employees (-2FY)"                       TEXT,
    "Full Time Employees (-3FY)"                       TEXT,
    "Avg Employees (5YAVGFY)"                          TEXT,
    "Net EPS - Basic (LTM)"                            TEXT,
    "Net EPS - Basic (FQ)"                             TEXT,
    "Net EPS - Basic (FY)"                             TEXT,
    "Net EPS - Basic (-1FQFQ)"                         TEXT,
    "Net EPS - Basic (-2FQFQ)"                         TEXT,
    "Net EPS - Basic (-3FQFQ)"                         TEXT,
    "Net EPS - Basic (-4FQFQ)"                         TEXT,
    "Net EPS - Basic (-1FY)"                           TEXT,
    "Net EPS - Basic (-2FY)"                           TEXT,
    "Net EPS - Basic (-3FY)"                           TEXT,
    "Net EPS - Basic (-4FY)"                           TEXT,
    "Net EPS - Basic (-5FY)"                           TEXT,
    "EPS Est Avg Rev % (FY1E - 1W)"                    TEXT,
    "EPS Est Avg Rev % (FY1E - 1M)"                    TEXT,
    "EPS Est Avg Rev % (FY1E - 3M)"                    TEXT,
    "EPS Est Avg Rev % (FY1E - 6M)"                    TEXT,
    "EPS Est Avg Rev % (FY1E - 1Y)"                    TEXT,
    "Div Yield (-2FYInd)"                              TEXT,
    "Div Yield (-3FYInd)"                              TEXT,
    "Div Yield (-4FYInd)"                              TEXT,
    "Div Yield (-5FYInd)"                              TEXT,
    "EBITDA - Est Avg (NTM)"                           TEXT,
    "EBITDA - Est Avg (FY1E)"                          TEXT,
    "EPS GAAP - Est Avg (NTM)"                         TEXT,
    "EPS GAAP - Est Avg (FY1E)"                        TEXT,
    "EPS GAAP Est Avg Rev % (FY1E - 1M)"               TEXT,
    "EPS GAAP Est Avg Rev % (FY1E - 3M)"               TEXT,
    "EPS GAAP Est Avg Rev % (FY1E - 6M)"               TEXT,
    "EPS GAAP Est Avg Rev % (FY1E - 1Y)"               TEXT,
    "EPS Norm - Est # (FY1E)"                          TEXT,
    "CFO (-1FQFQ)"                                     TEXT,
    "CFO (-2FQFQ)"                                     TEXT,
    "CFO (-3FQFQ)"                                     TEXT,
    "CFO (-4FQFQ)"                                     TEXT,
    "CFI (-1FQFQ)"                                     TEXT,
    "CFI (-2FQFQ)"                                     TEXT,
    "CFI (-3FQFQ)"                                     TEXT,
    "CFI (-4FQFQ)"                                     TEXT,
    "CFI (-2FY)"                                       TEXT,
    "CFI (-3FY)"                                       TEXT,
    "CFI (-4FY)"                                       TEXT,
    "FCF (-1FQFQ)"                                     TEXT,
    "FCF (-2FQFQ)"                                     TEXT,
    "FCF (-3FQFQ)"                                     TEXT,
    "FCF (-4FQFQ)"                                     TEXT,
    "CFF (-2FY)"                                       TEXT,
    "CFF (-3FY)"                                       TEXT,
    "CFF (-4FY)"                                       TEXT,
    "CFF (-1FQFQ)"                                     TEXT,
    "CFF (-2FQFQ)"                                     TEXT,
    "CFF (-3FQFQ)"                                     TEXT,
    "CFF (-4FQFQ)"                                     TEXT,
    "CFO (-2FY)"                                       TEXT,
    "CFO (-3FY)"                                       TEXT,
    "CFO (-4FY)"                                       TEXT,
    "Cash Acquisitions (-1FQFQ)"                       TEXT,
    "Cash Acquisitions (-2FQFQ)"                       TEXT,
    "Cash Acquisitions (-3FQFQ)"                       TEXT,
    "Cash Acquisitions (-4FQFQ)"                       TEXT,
    "FCF (-2FY)"                                       TEXT,
    "FCF (-3FY)"                                       TEXT,
    "FCF (-4FY)"                                       TEXT,
    "Price Target (1W Ago)"                            TEXT,
    "Price Target (1M Ago)"                            TEXT,
    "Price Target (3M Ago)"                            TEXT,
    "Price Target (6M Ago)"                            TEXT,
    "Price Target (MTD Ago)"                           TEXT,
    "Price Target (QTD Ago)"                           TEXT,
    "Price Target (1Y Ago)"                            TEXT,
    "Price Target - # (3M Ago)"                        TEXT,
    "Price Target - # (6M Ago)"                        TEXT,
    "Price Target - # (YTD Ago)"                       TEXT,
    "Price Target - # (1Y Ago)"                        TEXT,
    "Price Target - # (1W Ago)"                        TEXT,
    "Price Target - # (1M Ago)"                        TEXT,
    "Price Target - # (MTD Ago)"                       TEXT,
    "Price Target - # (QTD Ago)"                       TEXT,
    "Price Target - High (1W Ago)"                     TEXT,
    "Price Target - High (1M Ago)"                     TEXT,
    "Price Target - High (6M Ago)"                     TEXT,
    "Price Target - High (MTD Ago)"                    TEXT,
    "Price Target - High (3M Ago)"                     TEXT,
    "Price Target - High (QTD Ago)"                    TEXT,
    "Price Target - High (1Y Ago)"                     TEXT,
    "Price Target - High (YTD Ago)"                    TEXT,
    "Price Target - Low (1W Ago)"                      TEXT,
    "Price Target - Low (1M Ago)"                      TEXT,
    "Price Target - Low (3M Ago)"                      TEXT,
    "Price Target - Low (6M Ago)"                      TEXT,
    "Price Target - Low (MTD Ago)"                     TEXT,
    "Price Target - Low (QTD Ago)"                     TEXT,
    "Price Target - Low (YTD Ago)"                     TEXT,
    "Price Target - Low (1Y Ago)"                      TEXT,
    "Price Target - Median (1W Ago)"                   TEXT,
    "Price Target - Median (1M Ago)"                   TEXT,
    "Price Target - Median (3M Ago)"                   TEXT,
    "Price Target - Median (6M Ago)"                   TEXT,
    "Price Target - Median (MTD Ago)"                  TEXT,
    "Price Target - Median (QTD Ago)"                  TEXT,
    "Price Target - Median (YTD Ago)"                  TEXT,
    "Price Target - Median (1Y Ago)"                   TEXT,
    "Impairment of Goodwill (-1FQFQ)"                  TEXT,
    "Impairment of Goodwill (-2FQFQ)"                  TEXT,
    "Impairment of Goodwill (-3FQFQ)"                  TEXT,
    "Impairment of Goodwill (-4FQFQ)"                  TEXT,
    "Impairment of Goodwill (-2FY)"                    TEXT,
    "Impairment of Goodwill (-3FY)"                    TEXT,
    "Impairment of Goodwill (-4FY)"                    TEXT,
    "Asset Writedown (-1FQFQ)"                         TEXT,
    "Asset Writedown (-2FQFQ)"                         TEXT,
    "Asset Writedown (-3FQFQ)"                         TEXT,
    "Asset Writedown (-4FQFQ)"                         TEXT,
    "Asset Writedown (-2FY)"                           TEXT,
    "Asset Writedown (-3FY)"                           TEXT,
    "Asset Writedown (-4FY)"                           TEXT,
    "Asset Writedown (-5FY)"                           TEXT,
    "Gain (Loss) On Sale Of Assets (FQ)"               TEXT,
    "Gain (Loss) On Sale Of Assets (FY)"               TEXT,
    "Gain (Loss) On Sale Of Assets (-1FQFQ)"           TEXT,
    "Gain (Loss) On Sale Of Assets (-2FQFQ)"           TEXT,
    "Gain (Loss) On Sale Of Assets (-3FQFQ)"           TEXT,
    "Gain (Loss) On Sale Of Assets (-4FQFQ)"           TEXT,
    "Gain (Loss) On Sale Of Assets (-1FY)"             TEXT,
    "Gain (Loss) On Sale Of Assets (-2FY)"             TEXT,
    "Gain (Loss) On Sale Of Assets (-3FY)"             TEXT,
    "Gain (Loss) On Sale Of Assets (-4FY)"             TEXT,
    "Restructuring Charges (-1FQFQ)"                   TEXT,
    "Restructuring Charges (-2FQFQ)"                   TEXT,
    "Restructuring Charges (-3FQFQ)"                   TEXT,
    "Restructuring Charges (-4FQFQ)"                   TEXT,
    "Restructuring Charges (-2FY)"                     TEXT,
    "Restructuring Charges (-3FY)"                     TEXT,
    "Restructuring Charges (-4FY)"                     TEXT,
    "Net Income - (IS) (-1FQFQ)"                       TEXT,
    "Net Income - (IS) (-2FQFQ)"                       TEXT,
    "Net Income - (IS) (-3FQFQ)"                       TEXT,
    "Net Income - (IS) (-4FQFQ)"                       TEXT,
    "Net Income - (IS) (-2FY)"                         TEXT,
    "Net Income - (IS) (-3FY)"                         TEXT,
    "Net Income - (IS) (-4FY)"                         TEXT,
    "Normalized Net Income (-1FQFQ)"                   TEXT,
    "Normalized Net Income (-2FQFQ)"                   TEXT,
    "Normalized Net Income (-3FQFQ)"                   TEXT,
    "Normalized Net Income (-4FQFQ)"                   TEXT,
    "Normalized Net Income (-2FY)"                     TEXT,
    "Normalized Net Income (-3FY)"                     TEXT,
    "Normalized Net Income (-4FY)"                     TEXT,
    "Net Income/Adj. (-1FQFQ)"                         TEXT,
    "Net Income/Adj. (-2FQFQ)"                         TEXT,
    "Net Income/Adj. (-3FQFQ)"                         TEXT,
    "Net Income/Adj. (-4FQFQ)"                         TEXT,
    "Net Income/Adj. (-2FY)"                           TEXT,
    "Net Income/Adj. (-3FY)"                           TEXT,
    "Net Income/Adj. (-4FY)"                           TEXT,
    "EBIT (-1FQFQ)"                                    TEXT,
    "EBIT (-2FQFQ)"                                    TEXT,
    "EBIT (-3FQFQ)"                                    TEXT,
    "EBIT (-4FQFQ)"                                    TEXT,
    "EBIT (-2FY)"                                      TEXT,
    "EBIT (-3FY)"                                      TEXT,
    "EBIT (-4FY)"                                      TEXT,
    "EBIT/Adj. (FQ)"                                   TEXT,
    "EBIT/Adj. (-1FQFQ)"                               TEXT,
    "EBIT/Adj. (-2FQFQ)"                               TEXT,
    "EBIT/Adj. (-3FQFQ)"                               TEXT,
    "EBIT/Adj. (-4FQFQ)"                               TEXT,
    "EBIT/Adj. (-2FY)"                                 TEXT,
    "EBIT/Adj. (-3FY)"                                 TEXT,
    "EBIT/Adj. (-4FY)"                                 TEXT
);

-- ===================================================================
-- DATA IMPORT EXECUTION
-- ===================================================================
-- All four regional CSVs MUST share the same header (column set & order)
-- as pml_staging. If they diverge, the COPY will fail loudly with
-- "extra data" or "missing data" - fix the staging DDL above.
-- ===================================================================
\echo 'Importing US data...'
\copy pml.pml_staging FROM 'data/pml/pml_us.csv'   WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8', QUOTE '"', ESCAPE '"', DELIMITER ',', FORCE_NULL("Description"))

\echo 'Importing EU data...'
\copy pml.pml_staging FROM 'data/pml/pml_eu.csv'   WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8', QUOTE '"', ESCAPE '"', DELIMITER ',', FORCE_NULL("Description"))

\echo 'Importing APAC data...'
\copy pml.pml_staging FROM 'data/pml/pml_apac.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8', QUOTE '"', ESCAPE '"', DELIMITER ',', FORCE_NULL("Description"))

\echo 'Importing ROTW data...'
\copy pml.pml_staging FROM 'data/pml/pml_rotw.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8', QUOTE '"', ESCAPE '"', DELIMITER ',', FORCE_NULL("Description"))

-- ===================================================================
-- DATA VALIDATION (PRE-INSERT)
-- ===================================================================
\echo 'Validating imported data...'
SELECT 'Total rows in staging:' AS info, COUNT(*) AS count FROM pml.pml_staging;

-- ===================================================================
-- TRANSFORM AND LOAD INTO pml_df
-- ===================================================================
TRUNCATE TABLE pml_df;

INSERT INTO pml_df ("Ticker", "ISIN", "Name", "Description", "Region",
                    "Country", "Trading Country", "Exchange", "Unit",
                    "Sector", "Industry", "Style Class", "Size Class",
                    "Last Updated", "Income Statement Report Date", "FY End",
                    "Next Earnings", "Next Earnings (When)", "Next Earnings (Status)",
                    "Dividend Record (Currency)", "Dividend Record (Amount)",
                    "Dividend Record (Frequency)", "Dividend Streak",
                    "Dividend Record (Announce Date)", "Dividend Record (Payable Date)",
                    "Dividend Record (Record Date)", "Dividend Record (Ex Date)",
                    "Market Cap", "Enterprise Value", "Last Price",
                    "Price Target (YTD Ago)", "Total Return (YTD)", "Price Target",
                    "Price Target - Low", "Price Target - Median", "Price Target - High",
                    "Price Target - #", "P/E (NTM)", "P/E (LTM)",
                    "Altman Z-Score (FY)", "Altman Z-Score (FQ)", "Altman Z-Score (LTM)",
                    "Beta (1Y)", "Beta (2Y)", "Beta (5Y)", "Analyst Rating",
                    "# Strong Sell Ratings", "# Strong Buys Ratings", "# Hold Ratings",
                    "# Buys Ratings", "# Sell Ratings", "# No Opinion Ratings",
                    "Market Cap (Country R)", "Tot. Return %/CAGR (3Y)",
                    "Tot. Return %/CAGR (10Y)", "Total Return (5Y)", "Total Return (10Y)",
                    "Volume (Shrs)", "Dividend Per Share (LTM)", "Div Yield (Ind)",
                    "Div Yield (LTM)", "Gross Profit Margin % (FY)",
                    "Gross Profit Margin % (LTM)", "EPS Norm - Est Avg (NTM)",
                    "EPS/Adj. (-1FY)", "EPS/Adj. (FY)", "EPS/Adj. (LTM)",
                    "EPS Norm - Est Avg (FY1E)", "Buyback Yield (LTM)",
                    "Return on Assets (ROA) % (LTM)", "Return on Assets (ROA) % (FY)",
                    "Div Yield (-1FYInd)", "P/B (LTM)", "P/B (-1FY)", "P/B (5YAVG)",
                    "Div Yield (TTM)", "Div Yield (NTM)", "Div Yield (5YAVGLTM)",
                    "Price Chg. % (3M)", "1-Day %", "Price (5D Ago)", "Price (1W Ago)",
                    "Price (1M Ago)", "Price (3M Ago)", "Price (6M Ago)",
                    "Price (1Y Ago)", "Price (3Y Ago)", "Price (5Y Ago)",
                    "Price (QTD Ago)", "Rel. Volume", "Shrs Out", "Shrs Out (-1FY)",
                    "Common Dividends Paid (LTM)", "Common Dividends Paid (FY)",
                    "EV/Sales (LTM)", "EV/Sales (NTM)", "EV/Sales (-1FYLTM)",
                    "EV/Sales (-2FYLTM)", "EV/Sales (-3FYLTM)", "EV/Sales (3YAVGLTM)",
                    "EV/Sales (-1FQLTM)", "EV/Sales (-2FQLTM)", "EV/Sales (-3FQLTM)",
                    "EV/Sales (-4FQLTM)", "52W High/Adj", "52W Low/Adj",
                    "EMA (20D)", "EMA (50D)", "EMA (100D)", "EMA (250D)",
                    "EV/EBITDA (LTM)", "EV/EBITDA (NTM)", "EV/EBITDA (-1FYLTM)",
                    "EV/EBITDA (-1FQLTM)", "EV/EBITDA (3YAVGLTM)", "EV/EBITDA (EST FY1)",
                    "P/E (EST FY1)", "P/E (-1FYLTM)", "P/E (-2FYLTM)", "P/E (-3FYLTM)",
                    "P/E (3YAVGLTM)", "P/E (-1FQLTM)", "P/E (-2FQLTM)", "P/E (-3FQLTM)",
                    "P/E (5YAVGLTM)", "P/E (-0FQQoQLTM)", "P/E (-0FYYoYLTM)",
                    "P/E (-1FYYoYLTM)", "P/E (-0FQYoYLTM)",
                    "Full Time Employees (FQ)", "Full Time Employees (FY)",
                    "Full Time Employees (-1FY)", "Full Time Employees (-2FY)",
                    "Full Time Employees (-3FY)", "Avg Employees (5YAVGFY)",
                    "Net EPS - Basic (LTM)", "Net EPS - Basic (FQ)", "Net EPS - Basic (FY)",
                    "Net EPS - Basic (-1FQFQ)", "Net EPS - Basic (-2FQFQ)",
                    "Net EPS - Basic (-3FQFQ)", "Net EPS - Basic (-4FQFQ)",
                    "Net EPS - Basic (-1FY)", "Net EPS - Basic (-2FY)",
                    "Net EPS - Basic (-3FY)", "Net EPS - Basic (-4FY)",
                    "Net EPS - Basic (-5FY)",
                    "EPS Est Avg Rev % (FY1E - 1W)", "EPS Est Avg Rev % (FY1E - 1M)",
                    "EPS Est Avg Rev % (FY1E - 3M)", "EPS Est Avg Rev % (FY1E - 6M)",
                    "EPS Est Avg Rev % (FY1E - 1Y)",
                    "Div Yield (-2FYInd)", "Div Yield (-3FYInd)", "Div Yield (-4FYInd)",
                    "Div Yield (-5FYInd)",
                    "EBITDA - Est Avg (NTM)", "EBITDA - Est Avg (FY1E)",
                    "EPS GAAP - Est Avg (NTM)", "EPS GAAP - Est Avg (FY1E)",
                    "EPS GAAP Est Avg Rev % (FY1E - 1M)", "EPS GAAP Est Avg Rev % (FY1E - 3M)",
                    "EPS GAAP Est Avg Rev % (FY1E - 6M)", "EPS GAAP Est Avg Rev % (FY1E - 1Y)",
                    "EPS Norm - Est # (FY1E)",
                    "Price Target (1W Ago)", "Price Target (1M Ago)",
                    "Price Target (3M Ago)", "Price Target (6M Ago)",
                    "Price Target (MTD Ago)", "Price Target (QTD Ago)",
                    "Price Target (1Y Ago)",
                    "Price Target - # (3M Ago)", "Price Target - # (6M Ago)",
                    "Price Target - # (YTD Ago)", "Price Target - # (1Y Ago)",
                    "Price Target - # (1W Ago)", "Price Target - # (1M Ago)",
                    "Price Target - # (MTD Ago)", "Price Target - # (QTD Ago)",
                    "Price Target - High (1W Ago)", "Price Target - High (1M Ago)",
                    "Price Target - High (6M Ago)", "Price Target - High (MTD Ago)",
                    "Price Target - High (3M Ago)", "Price Target - High (QTD Ago)",
                    "Price Target - High (1Y Ago)", "Price Target - High (YTD Ago)",
                    "Price Target - Low (1W Ago)", "Price Target - Low (1M Ago)",
                    "Price Target - Low (3M Ago)", "Price Target - Low (6M Ago)",
                    "Price Target - Low (MTD Ago)", "Price Target - Low (QTD Ago)",
                    "Price Target - Low (YTD Ago)", "Price Target - Low (1Y Ago)",
                    "Price Target - Median (1W Ago)", "Price Target - Median (1M Ago)",
                    "Price Target - Median (3M Ago)", "Price Target - Median (6M Ago)",
                    "Price Target - Median (MTD Ago)", "Price Target - Median (QTD Ago)",
                    "Price Target - Median (YTD Ago)", "Price Target - Median (1Y Ago)",
                    "Basic EPS - Cont (LTM)", "Basic EPS - Cont (FQ)", "Basic EPS - Cont (FY)",
                    "Basic EPS - Cont (-1FQFQ)", "Basic EPS - Cont (-2FQFQ)",
                    "Basic EPS - Cont (-4FQFQ)", "Basic EPS - Cont (-3FQFQ)",
                    "Basic EPS - Cont (-1FY)", "Basic EPS - Cont (-2FY)",
                    "Basic EPS - Cont (-3FY)", "Basic EPS - Cont (-4FY)",
                    "EPS/Adj. (FQ)", "EPS/Adj. (-1FQFQ)", "EPS/Adj. (-3FQFQ)",
                    "EPS/Adj. (-4FQFQ)", "EPS/Adj. (-2FQFQ)", "EPS/Adj. (-2FY)",
                    "EPS/Adj. (-3FY)", "EPS/Adj. (-4FY)",
                    "Gross Profit (-1FQFQ)", "Gross Profit (-3FQFQ)",
                    "Gross Profit (-4FQFQ)", "Gross Profit (-2FQFQ)",
                    "Gross Profit (-1FY)", "Gross Profit (-2FY)",
                    "Gross Profit (-3FY)", "Gross Profit (-4FY)",
                    "FCF (LTM)", "FCF (FQ)", "FCF (-1FQFQ)", "FCF (-3FQFQ)",
                    "FCF (-4FQFQ)", "FCF (-2FQFQ)", "FCF (FY)", "FCF (-1FY)",
                    "FCF (-3FY)", "FCF (-2FY)", "FCF (-4FY)",
                    "Capital Expenditure (LTM)", "Capital Expenditure (FQ)",
                    "Capital Expenditure (FY)",
                    "Capital Expenditure (-1FY)", "Capital Expenditure (-2FY)",
                    "Capital Expenditure (-4FY)", "Capital Expenditure (-3FY)",
                    "CFF (LTM)", "CFF (FQ)", "CFF (FY)", "CFF (-1FY)", "CFF (-2FY)",
                    "CFF (-3FY)", "CFF (-4FY)",
                    "CFI (LTM)", "CFI (FQ)", "CFI (FY)", "CFI (-1FQFQ)",
                    "CFI (-2FQFQ)", "CFI (-3FQFQ)", "CFI (-4FQFQ)",
                    "CFI (-1FY)", "CFI (-2FY)", "CFI (-3FY)", "CFI (-4FY)",
                    "CFO (LTM)", "CFO (FQ)", "CFO (FY)", "CFO (-1FQFQ)",
                    "CFO (-2FQFQ)", "CFO (-4FQFQ)", "CFO (-3FQFQ)",
                    "CFO (-1FY)", "CFO (-2FY)", "CFO (-3FY)", "CFO (-4FY)",
                    "Volatility (1M)", "Volatility (3M)", "Volatility (6M)", "Volatility (1Y)")
SELECT NULLIF(TRIM(s."Ticker"), '')                                       AS "Ticker",
       NULLIF(TRIM(s."ISIN"), '')                                         AS "ISIN",
       NULLIF(TRIM(s."Name"), '')                                         AS "Name",
       NULLIF(TRIM(s."Description"), '')                                  AS "Description",
       COALESCE(NULLIF(TRIM(s."Region"), ''), 'n/a')                      AS "Region",
       COALESCE(NULLIF(TRIM(s."Country"), ''), 'n/a')                     AS "Country",
       COALESCE(NULLIF(TRIM(s."Trading Country"), ''), 'n/a')             AS "Trading Country",
       COALESCE(NULLIF(TRIM(s."Exchange"), ''), 'n/a')                    AS "Exchange",
       COALESCE(NULLIF(TRIM(s."Unit"), ''), 'n/a')                        AS "Unit",
       COALESCE(NULLIF(TRIM(s."Sector"), ''), 'n/a')                      AS "Sector",
       COALESCE(NULLIF(TRIM(s."Industry"), ''), 'n/a')                    AS "Industry",
       COALESCE(NULLIF(TRIM(s."Style Class"), ''), 'n/a')                 AS "Style Class",
       COALESCE(NULLIF(TRIM(s."Size Class"), ''), 'n/a')                  AS "Size Class",
       text_to_date_safe(s."Last Updated")                                AS "Last Updated",
       text_to_date_safe(s."Income Statement Report Date")                AS "Income Statement Report Date",
       COALESCE(NULLIF(TRIM(s."FY End"), ''), 'n/a')                      AS "FY End",
       text_to_date_safe(s."Next Earnings")                               AS "Next Earnings",
       COALESCE(NULLIF(TRIM(s."Next Earnings (When)"), ''), 'n/a')        AS "Next Earnings (When)",
       COALESCE(NULLIF(TRIM(s."Next Earnings (Status)"), ''), 'n/a')      AS "Next Earnings (Status)",
       COALESCE(NULLIF(TRIM(s."Dividend Record (Currency)"), ''), 'n/a')  AS "Dividend Record (Currency)",
       text_to_numeric_safe(s."Dividend Record (Amount)")                 AS "Dividend Record (Amount)",
       COALESCE(NULLIF(TRIM(s."Dividend Record (Frequency)"), ''), 'n/a') AS "Dividend Record (Frequency)",
       text_to_numeric_safe(s."Dividend Streak")                          AS "Dividend Streak",
       text_to_date_safe(s."Dividend Record (Announce Date)")             AS "Dividend Record (Announce Date)",
       text_to_date_safe(s."Dividend Record (Payable Date)")              AS "Dividend Record (Payable Date)",
       text_to_date_safe(s."Dividend Record (Record Date)")               AS "Dividend Record (Record Date)",
       text_to_date_safe(s."Dividend Record (Ex Date)")                   AS "Dividend Record (Ex Date)",
       text_to_numeric_safe(s."Market Cap")                               AS "Market Cap",
       text_to_numeric_safe(s."Enterprise Value")                         AS "Enterprise Value",
       text_to_numeric_safe(s."Last Price")                               AS "Last Price",
       text_to_numeric_safe(s."Price Target (YTD Ago)")                   AS "Price Target (YTD Ago)",
       text_to_numeric_safe(s."Total Return (YTD)")                       AS "Total Return (YTD)",
       text_to_numeric_safe(s."Price Target")                             AS "Price Target",
       text_to_numeric_safe(s."Price Target - Low")                       AS "Price Target - Low",
       text_to_numeric_safe(s."Price Target - Median")                    AS "Price Target - Median",
       text_to_numeric_safe(s."Price Target - High")                      AS "Price Target - High",
       text_to_numeric_safe(s."Price Target - #")                         AS "Price Target - #",
       text_to_numeric_safe(s."P/E (NTM)")                                AS "P/E (NTM)",
       text_to_numeric_safe(s."P/E (LTM)")                                AS "P/E (LTM)",
       text_to_numeric_safe(s."Altman Z-Score (FY)")                      AS "Altman Z-Score (FY)",
       text_to_numeric_safe(s."Altman Z-Score (FQ)")                      AS "Altman Z-Score (FQ)",
       text_to_numeric_safe(s."Altman Z-Score (LTM)")                     AS "Altman Z-Score (LTM)",
       text_to_numeric_safe(s."Beta (1Y)")                                AS "Beta (1Y)",
       text_to_numeric_safe(s."Beta (2Y)")                                AS "Beta (2Y)",
       text_to_numeric_safe(s."Beta (5Y)")                                AS "Beta (5Y)",
       text_to_numeric_safe(s."Analyst Rating")                           AS "Analyst Rating",
       text_to_numeric_safe(s."# Strong Sell Ratings")::INT               AS "# Strong Sell Ratings",
       text_to_numeric_safe(s."# Strong Buys Ratings")::INT               AS "# Strong Buys Ratings",
       text_to_numeric_safe(s."# Hold Ratings")::INT                      AS "# Hold Ratings",
       text_to_numeric_safe(s."# Buys Ratings")::INT                      AS "# Buys Ratings",
       text_to_numeric_safe(s."# Sell Ratings")::INT                      AS "# Sell Ratings",
       text_to_numeric_safe(s."# No Opinion Ratings")::INT                AS "# No Opinion Ratings",
       text_to_numeric_safe(s."Market Cap (Country R)")::INT              AS "Market Cap (Country R)",
       text_to_numeric_safe(s."Tot. Return %/CAGR (3Y)")                  AS "Tot. Return %/CAGR (3Y)",
       text_to_numeric_safe(s."Tot. Return %/CAGR (10Y)")                 AS "Tot. Return %/CAGR (10Y)",
       text_to_numeric_safe(s."Total Return (5Y)")                        AS "Total Return (5Y)",
       text_to_numeric_safe(s."Total Return (10Y)")                       AS "Total Return (10Y)",
       text_to_numeric_safe(s."Volume (Shrs)")                            AS "Volume (Shrs)",
       text_to_numeric_safe(s."Dividend Per Share (LTM)")                 AS "Dividend Per Share (LTM)",
       text_to_numeric_safe(s."Div Yield (Ind)")                          AS "Div Yield (Ind)",
       text_to_numeric_safe(s."Div Yield (LTM)")                          AS "Div Yield (LTM)",
       text_to_numeric_safe(s."Gross Profit Margin % (FY)")               AS "Gross Profit Margin % (FY)",
       text_to_numeric_safe(s."Gross Profit Margin % (LTM)")              AS "Gross Profit Margin % (LTM)",
       text_to_numeric_safe(s."EPS Norm - Est Avg (NTM)")                 AS "EPS Norm - Est Avg (NTM)",
       text_to_numeric_safe(s."EPS/Adj. (-1FY)")                          AS "EPS/Adj. (-1FY)",
       text_to_numeric_safe(s."EPS/Adj. (FY)")                            AS "EPS/Adj. (FY)",
       text_to_numeric_safe(s."EPS/Adj. (LTM)")                           AS "EPS/Adj. (LTM)",
       text_to_numeric_safe(s."EPS Norm - Est Avg (FY1E)")                AS "EPS Norm - Est Avg (FY1E)",
       text_to_numeric_safe(s."Buyback Yield (LTM)")                      AS "Buyback Yield (LTM)",
       text_to_numeric_safe(s."Return on Assets (ROA) % (LTM)")           AS "Return on Assets (ROA) % (LTM)",
       text_to_numeric_safe(s."Return on Assets (ROA) % (FY)")            AS "Return on Assets (ROA) % (FY)",
       text_to_numeric_safe(s."Div Yield (-1FYInd)")                      AS "Div Yield (-1FYInd)",
       text_to_numeric_safe(s."P/B (LTM)")                                AS "P/B (LTM)",
       text_to_numeric_safe(s."P/B (-1FY)")                               AS "P/B (-1FY)",
       text_to_numeric_safe(s."P/B (5YAVG)")                              AS "P/B (5YAVG)",
       text_to_numeric_safe(s."Div Yield (TTM)")                          AS "Div Yield (TTM)",
       text_to_numeric_safe(s."Div Yield (NTM)")                          AS "Div Yield (NTM)",
       text_to_numeric_safe(s."Div Yield (5YAVGLTM)")                     AS "Div Yield (5YAVGLTM)",
       text_to_numeric_safe(s."Price Chg. % (3M)")                        AS "Price Chg. % (3M)",
       text_to_numeric_safe(s."1-Day %")                                  AS "1-Day %",
       text_to_numeric_safe(s."Price (5D Ago)")                           AS "Price (5D Ago)",
       text_to_numeric_safe(s."Price (1W Ago)")                           AS "Price (1W Ago)",
       text_to_numeric_safe(s."Price (1M Ago)")                           AS "Price (1M Ago)",
       text_to_numeric_safe(s."Price (3M Ago)")                           AS "Price (3M Ago)",
       text_to_numeric_safe(s."Price (6M Ago)")                           AS "Price (6M Ago)",
       text_to_numeric_safe(s."Price (1Y Ago)")                           AS "Price (1Y Ago)",
       text_to_numeric_safe(s."Price (3Y Ago)")                           AS "Price (3Y Ago)",
       text_to_numeric_safe(s."Price (5Y Ago)")                           AS "Price (5Y Ago)",
       text_to_numeric_safe(s."Price (QTD Ago)")                          AS "Price (QTD Ago)",
       text_to_numeric_safe(s."Rel. Volume")                              AS "Rel. Volume",
       text_to_numeric_safe(s."Shrs Out")                                 AS "Shrs Out",
       text_to_numeric_safe(s."Shrs Out (-1FY)")                          AS "Shrs Out (-1FY)",
       text_to_numeric_safe(s."Common Dividends Paid (LTM)")              AS "Common Dividends Paid (LTM)",
       text_to_numeric_safe(s."Common Dividends Paid (FY)")               AS "Common Dividends Paid (FY)",
       text_to_numeric_safe(s."EV/Sales (LTM)")                           AS "EV/Sales (LTM)",
       text_to_numeric_safe(s."EV/Sales (NTM)")                           AS "EV/Sales (NTM)",
       text_to_numeric_safe(s."EV/Sales (-1FYLTM)")                       AS "EV/Sales (-1FYLTM)",
       text_to_numeric_safe(s."EV/Sales (-2FYLTM)")                       AS "EV/Sales (-2FYLTM)",
       text_to_numeric_safe(s."EV/Sales (-3FYLTM)")                       AS "EV/Sales (-3FYLTM)",
       text_to_numeric_safe(s."EV/Sales (3YAVGLTM)")                      AS "EV/Sales (3YAVGLTM)",
       text_to_numeric_safe(s."EV/Sales (-1FQLTM)")                       AS "EV/Sales (-1FQLTM)",
       text_to_numeric_safe(s."EV/Sales (-2FQLTM)")                       AS "EV/Sales (-2FQLTM)",
       text_to_numeric_safe(s."EV/Sales (-3FQLTM)")                       AS "EV/Sales (-3FQLTM)",
       text_to_numeric_safe(s."EV/Sales (-4FQLTM)")                       AS "EV/Sales (-4FQLTM)",
       text_to_numeric_safe(s."52W High/Adj")                             AS "52W High/Adj",
       text_to_numeric_safe(s."52W Low/Adj")                              AS "52W Low/Adj",
       text_to_numeric_safe(s."EMA (20D)")                                AS "EMA (20D)",
       text_to_numeric_safe(s."EMA (50D)")                                AS "EMA (50D)",
       text_to_numeric_safe(s."EMA (100D)")                               AS "EMA (100D)",
       text_to_numeric_safe(s."EMA (250D)")                               AS "EMA (250D)",
       text_to_numeric_safe(s."EV/EBITDA (LTM)")                          AS "EV/EBITDA (LTM)",
       text_to_numeric_safe(s."EV/EBITDA (NTM)")                          AS "EV/EBITDA (NTM)",
       text_to_numeric_safe(s."EV/EBITDA (-1FYLTM)")                      AS "EV/EBITDA (-1FYLTM)",
       text_to_numeric_safe(s."EV/EBITDA (-1FQLTM)")                      AS "EV/EBITDA (-1FQLTM)",
       text_to_numeric_safe(s."EV/EBITDA (3YAVGLTM)")                     AS "EV/EBITDA (3YAVGLTM)",
       text_to_numeric_safe(s."EV/EBITDA (EST FY1)")                      AS "EV/EBITDA (EST FY1)",
       text_to_numeric_safe(s."P/E (EST FY1)")                            AS "P/E (EST FY1)",
       text_to_numeric_safe(s."P/E (-1FYLTM)")                            AS "P/E (-1FYLTM)",
       text_to_numeric_safe(s."P/E (-2FYLTM)")                            AS "P/E (-2FYLTM)",
       text_to_numeric_safe(s."P/E (-3FYLTM)")                            AS "P/E (-3FYLTM)",
       text_to_numeric_safe(s."P/E (3YAVGLTM)")                           AS "P/E (3YAVGLTM)",
       text_to_numeric_safe(s."P/E (-1FQLTM)")                            AS "P/E (-1FQLTM)",
       text_to_numeric_safe(s."P/E (-2FQLTM)")                            AS "P/E (-2FQLTM)",
       text_to_numeric_safe(s."P/E (-3FQLTM)")                            AS "P/E (-3FQLTM)",
       text_to_numeric_safe(s."P/E (5YAVGLTM)")                           AS "P/E (5YAVGLTM)",
       text_to_numeric_safe(s."P/E (-0FQQoQLTM)")                         AS "P/E (-0FQQoQLTM)",
       text_to_numeric_safe(s."P/E (-0FYYoYLTM)")                         AS "P/E (-0FYYoYLTM)",
       text_to_numeric_safe(s."P/E (-1FYYoYLTM)")                         AS "P/E (-1FYYoYLTM)",
       text_to_numeric_safe(s."P/E (-0FQYoYLTM)")                         AS "P/E (-0FQYoYLTM)",
       text_to_numeric_safe(s."Full Time Employees (FQ)")                 AS "Full Time Employees (FQ)",
       text_to_numeric_safe(s."Full Time Employees (FY)")                 AS "Full Time Employees (FY)",
       text_to_numeric_safe(s."Full Time Employees (-1FY)")               AS "Full Time Employees (-1FY)",
       text_to_numeric_safe(s."Full Time Employees (-2FY)")               AS "Full Time Employees (-2FY)",
       text_to_numeric_safe(s."Full Time Employees (-3FY)")               AS "Full Time Employees (-3FY)",
       text_to_numeric_safe(s."Avg Employees (5YAVGFY)")                  AS "Avg Employees (5YAVGFY)",
       text_to_numeric_safe(s."Net EPS - Basic (LTM)")                    AS "Net EPS - Basic (LTM)",
       text_to_numeric_safe(s."Net EPS - Basic (FQ)")                     AS "Net EPS - Basic (FQ)",
       text_to_numeric_safe(s."Net EPS - Basic (FY)")                     AS "Net EPS - Basic (FY)",
       text_to_numeric_safe(s."Net EPS - Basic (-1FQFQ)")                 AS "Net EPS - Basic (-1FQFQ)",
       text_to_numeric_safe(s."Net EPS - Basic (-2FQFQ)")                 AS "Net EPS - Basic (-2FQFQ)",
       text_to_numeric_safe(s."Net EPS - Basic (-3FQFQ)")                 AS "Net EPS - Basic (-3FQFQ)",
       text_to_numeric_safe(s."Net EPS - Basic (-4FQFQ)")                 AS "Net EPS - Basic (-4FQFQ)",
       text_to_numeric_safe(s."Net EPS - Basic (-1FY)")                   AS "Net EPS - Basic (-1FY)",
       text_to_numeric_safe(s."Net EPS - Basic (-2FY)")                   AS "Net EPS - Basic (-2FY)",
       text_to_numeric_safe(s."Net EPS - Basic (-3FY)")                   AS "Net EPS - Basic (-3FY)",
       text_to_numeric_safe(s."Net EPS - Basic (-4FY)")                   AS "Net EPS - Basic (-4FY)",
       text_to_numeric_safe(s."Net EPS - Basic (-5FY)")                   AS "Net EPS - Basic (-5FY)",
       text_to_numeric_safe(s."EPS Est Avg Rev % (FY1E - 1W)")            AS "EPS Est Avg Rev % (FY1E - 1W)",
       text_to_numeric_safe(s."EPS Est Avg Rev % (FY1E - 1M)")            AS "EPS Est Avg Rev % (FY1E - 1M)",
       text_to_numeric_safe(s."EPS Est Avg Rev % (FY1E - 3M)")            AS "EPS Est Avg Rev % (FY1E - 3M)",
       text_to_numeric_safe(s."EPS Est Avg Rev % (FY1E - 6M)")            AS "EPS Est Avg Rev % (FY1E - 6M)",
       text_to_numeric_safe(s."EPS Est Avg Rev % (FY1E - 1Y)")            AS "EPS Est Avg Rev % (FY1E - 1Y)",
       text_to_numeric_safe(s."Div Yield (-2FYInd)")                      AS "Div Yield (-2FYInd)",
       text_to_numeric_safe(s."Div Yield (-3FYInd)")                      AS "Div Yield (-3FYInd)",
       text_to_numeric_safe(s."Div Yield (-4FYInd)")                      AS "Div Yield (-4FYInd)",
       text_to_numeric_safe(s."Div Yield (-5FYInd)")                      AS "Div Yield (-5FYInd)",
       text_to_numeric_safe(s."EBITDA - Est Avg (NTM)")                   AS "EBITDA - Est Avg (NTM)",
       text_to_numeric_safe(s."EBITDA - Est Avg (FY1E)")                  AS "EBITDA - Est Avg (FY1E)",
       text_to_numeric_safe(s."EPS GAAP - Est Avg (NTM)")                 AS "EPS GAAP - Est Avg (NTM)",
       text_to_numeric_safe(s."EPS GAAP - Est Avg (FY1E)")                AS "EPS GAAP - Est Avg (FY1E)",
       text_to_numeric_safe(s."EPS GAAP Est Avg Rev % (FY1E - 1M)")       AS "EPS GAAP Est Avg Rev % (FY1E - 1M)",
       text_to_numeric_safe(s."EPS GAAP Est Avg Rev % (FY1E - 3M)")       AS "EPS GAAP Est Avg Rev % (FY1E - 3M)",
       text_to_numeric_safe(s."EPS GAAP Est Avg Rev % (FY1E - 6M)")       AS "EPS GAAP Est Avg Rev % (FY1E - 6M)",
       text_to_numeric_safe(s."EPS GAAP Est Avg Rev % (FY1E - 1Y)")       AS "EPS GAAP Est Avg Rev % (FY1E - 1Y)",
       text_to_numeric_safe(s."EPS Norm - Est # (FY1E)")                  AS "EPS Norm - Est # (FY1E)",
       text_to_numeric_safe(s."Price Target (1W Ago)")                    AS "Price Target (1W Ago)",
       text_to_numeric_safe(s."Price Target (1M Ago)")                    AS "Price Target (1M Ago)",
       text_to_numeric_safe(s."Price Target (3M Ago)")                    AS "Price Target (3M Ago)",
       text_to_numeric_safe(s."Price Target (6M Ago)")                    AS "Price Target (6M Ago)",
       text_to_numeric_safe(s."Price Target (MTD Ago)")                   AS "Price Target (MTD Ago)",
       text_to_numeric_safe(s."Price Target (QTD Ago)")                   AS "Price Target (QTD Ago)",
       text_to_numeric_safe(s."Price Target (1Y Ago)")                    AS "Price Target (1Y Ago)",
       text_to_numeric_safe(s."Price Target - # (3M Ago)")                AS "Price Target - # (3M Ago)",
       text_to_numeric_safe(s."Price Target - # (6M Ago)")                AS "Price Target - # (6M Ago)",
       text_to_numeric_safe(s."Price Target - # (YTD Ago)")               AS "Price Target - # (YTD Ago)",
       text_to_numeric_safe(s."Price Target - # (1Y Ago)")                AS "Price Target - # (1Y Ago)",
       text_to_numeric_safe(s."Price Target - # (1W Ago)")                AS "Price Target - # (1W Ago)",
       text_to_numeric_safe(s."Price Target - # (1M Ago)")                AS "Price Target - # (1M Ago)",
       text_to_numeric_safe(s."Price Target - # (MTD Ago)")               AS "Price Target - # (MTD Ago)",
       text_to_numeric_safe(s."Price Target - # (QTD Ago)")               AS "Price Target - # (QTD Ago)",
       text_to_numeric_safe(s."Price Target - High (1W Ago)")             AS "Price Target - High (1W Ago)",
       text_to_numeric_safe(s."Price Target - High (1M Ago)")             AS "Price Target - High (1M Ago)",
       text_to_numeric_safe(s."Price Target - High (6M Ago)")             AS "Price Target - High (6M Ago)",
       text_to_numeric_safe(s."Price Target - High (MTD Ago)")            AS "Price Target - High (MTD Ago)",
       text_to_numeric_safe(s."Price Target - High (3M Ago)")             AS "Price Target - High (3M Ago)",
       text_to_numeric_safe(s."Price Target - High (QTD Ago)")            AS "Price Target - High (QTD Ago)",
       text_to_numeric_safe(s."Price Target - High (1Y Ago)")             AS "Price Target - High (1Y Ago)",
       text_to_numeric_safe(s."Price Target - High (YTD Ago)")            AS "Price Target - High (YTD Ago)",
       text_to_numeric_safe(s."Price Target - Low (1W Ago)")              AS "Price Target - Low (1W Ago)",
       text_to_numeric_safe(s."Price Target - Low (1M Ago)")              AS "Price Target - Low (1M Ago)",
       text_to_numeric_safe(s."Price Target - Low (3M Ago)")              AS "Price Target - Low (3M Ago)",
       text_to_numeric_safe(s."Price Target - Low (6M Ago)")              AS "Price Target - Low (6M Ago)",
       text_to_numeric_safe(s."Price Target - Low (MTD Ago)")             AS "Price Target - Low (MTD Ago)",
       text_to_numeric_safe(s."Price Target - Low (QTD Ago)")             AS "Price Target - Low (QTD Ago)",
       text_to_numeric_safe(s."Price Target - Low (YTD Ago)")             AS "Price Target - Low (YTD Ago)",
       text_to_numeric_safe(s."Price Target - Low (1Y Ago)")              AS "Price Target - Low (1Y Ago)",
       text_to_numeric_safe(s."Price Target - Median (1W Ago)")           AS "Price Target - Median (1W Ago)",
       text_to_numeric_safe(s."Price Target - Median (1M Ago)")           AS "Price Target - Median (1M Ago)",
       text_to_numeric_safe(s."Price Target - Median (3M Ago)")           AS "Price Target - Median (3M Ago)",
       text_to_numeric_safe(s."Price Target - Median (6M Ago)")           AS "Price Target - Median (6M Ago)",
       text_to_numeric_safe(s."Price Target - Median (MTD Ago)")          AS "Price Target - Median (MTD Ago)",
       text_to_numeric_safe(s."Price Target - Median (QTD Ago)")          AS "Price Target - Median (QTD Ago)",
       text_to_numeric_safe(s."Price Target - Median (YTD Ago)")          AS "Price Target - Median (YTD Ago)",
       text_to_numeric_safe(s."Price Target - Median (1Y Ago)")           AS "Price Target - Median (1Y Ago)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (LTM)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (FQ)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (FY)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (-1FQFQ)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (-2FQFQ)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (-4FQFQ)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (-3FQFQ)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (-1FY)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (-2FY)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (-3FY)",
       NULL::NUMERIC                                                      AS "Basic EPS - Cont (-4FY)",
       text_to_numeric_safe(s."EBIT/Adj. (FQ)")                           AS "EPS/Adj. (FQ)",
       NULL::NUMERIC                                                      AS "EPS/Adj. (-1FQFQ)",
       NULL::NUMERIC                                                      AS "EPS/Adj. (-3FQFQ)",
       NULL::NUMERIC                                                      AS "EPS/Adj. (-4FQFQ)",
       NULL::NUMERIC                                                      AS "EPS/Adj. (-2FQFQ)",
       NULL::NUMERIC                                                      AS "EPS/Adj. (-2FY)",
       NULL::NUMERIC                                                      AS "EPS/Adj. (-3FY)",
       NULL::NUMERIC                                                      AS "EPS/Adj. (-4FY)",
       NULL::NUMERIC                                                      AS "Gross Profit (-1FQFQ)",
       NULL::NUMERIC                                                      AS "Gross Profit (-3FQFQ)",
       NULL::NUMERIC                                                      AS "Gross Profit (-4FQFQ)",
       NULL::NUMERIC                                                      AS "Gross Profit (-2FQFQ)",
       NULL::NUMERIC                                                      AS "Gross Profit (-1FY)",
       NULL::NUMERIC                                                      AS "Gross Profit (-2FY)",
       NULL::NUMERIC                                                      AS "Gross Profit (-3FY)",
       NULL::NUMERIC                                                      AS "Gross Profit (-4FY)",
       text_to_numeric_safe(s."FCF (LTM)")                                AS "FCF (LTM)",
       text_to_numeric_safe(s."FCF (FQ)")                                 AS "FCF (FQ)",
       NULL::NUMERIC                                                      AS "FCF (-1FQFQ)",
       NULL::NUMERIC                                                      AS "FCF (-3FQFQ)",
       NULL::NUMERIC                                                      AS "FCF (-4FQFQ)",
       NULL::NUMERIC                                                      AS "FCF (-2FQFQ)",
       text_to_numeric_safe(s."FCF (FY)")                                 AS "FCF (FY)",
       text_to_numeric_safe(s."FCF (-1FY)")                               AS "FCF (-1FY)",
       NULL::NUMERIC                                                      AS "FCF (-3FY)",
       NULL::NUMERIC                                                      AS "FCF (-2FY)",
       NULL::NUMERIC                                                      AS "FCF (-4FY)",
       text_to_numeric_safe(s."Capital Expenditure (LTM)")                AS "Capital Expenditure (LTM)",
       text_to_numeric_safe(s."Capital Expenditure (FQ)")                 AS "Capital Expenditure (FQ)",
       text_to_numeric_safe(s."Capital Expenditure (FY)")                 AS "Capital Expenditure (FY)",
       text_to_numeric_safe(s."Capital Expenditure (-1FY)")               AS "Capital Expenditure (-1FY)",
       NULL::NUMERIC                                                      AS "Capital Expenditure (-2FY)",
       NULL::NUMERIC                                                      AS "Capital Expenditure (-4FY)",
       NULL::NUMERIC                                                      AS "Capital Expenditure (-3FY)",
       text_to_numeric_safe(s."CFF (LTM)")                                AS "CFF (LTM)",
       text_to_numeric_safe(s."CFF (FQ)")                                 AS "CFF (FQ)",
       text_to_numeric_safe(s."CFF (FY)")                                 AS "CFF (FY)",
       text_to_numeric_safe(s."CFF (-1FY)")                               AS "CFF (-1FY)",
       NULL::NUMERIC                                                      AS "CFF (-2FY)",
       NULL::NUMERIC                                                      AS "CFF (-3FY)",
       NULL::NUMERIC                                                      AS "CFF (-4FY)",
       text_to_numeric_safe(s."CFI (LTM)")                                AS "CFI (LTM)",
       text_to_numeric_safe(s."CFI (FQ)")                                 AS "CFI (FQ)",
       text_to_numeric_safe(s."CFI (FY)")                                 AS "CFI (FY)",
       NULL::NUMERIC                                                      AS "CFI (-1FQFQ)",
       NULL::NUMERIC                                                      AS "CFI (-2FQFQ)",
       NULL::NUMERIC                                                      AS "CFI (-3FQFQ)",
       NULL::NUMERIC                                                      AS "CFI (-4FQFQ)",
       text_to_numeric_safe(s."CFI (-1FY)")                               AS "CFI (-1FY)",
       NULL::NUMERIC                                                      AS "CFI (-2FY)",
       NULL::NUMERIC                                                      AS "CFI (-3FY)",
       NULL::NUMERIC                                                      AS "CFI (-4FY)",
       text_to_numeric_safe(s."CFO (LTM)")                                AS "CFO (LTM)",
       text_to_numeric_safe(s."CFO (FQ)")                                 AS "CFO (FQ)",
       text_to_numeric_safe(s."CFO (FY)")                                 AS "CFO (FY)",
       text_to_numeric_safe(s."CFO (-1FQFQ)")                             AS "CFO (-1FQFQ)",
       text_to_numeric_safe(s."CFO (-2FQFQ)")                             AS "CFO (-2FQFQ)",
       text_to_numeric_safe(s."CFO (-4FQFQ)")                             AS "CFO (-4FQFQ)",
       text_to_numeric_safe(s."CFO (-3FQFQ)")                             AS "CFO (-3FQFQ)",
       text_to_numeric_safe(s."CFO (-1FY)")                               AS "CFO (-1FY)",
       NULL::NUMERIC                                                      AS "CFO (-2FY)",
       NULL::NUMERIC                                                      AS "CFO (-3FY)",
       NULL::NUMERIC                                                      AS "CFO (-4FY)",
       text_to_numeric_safe(s."Volatility (1M)")                          AS "Volatility (1M)",
       text_to_numeric_safe(s."Volatility (3M)")                          AS "Volatility (3M)",
       text_to_numeric_safe(s."Volatility (6M)")                          AS "Volatility (6M)",
       text_to_numeric_safe(s."Volatility (1Y)")                          AS "Volatility (1Y)"
FROM pml.pml_staging s;

-- ===================================================================
-- FINAL VALIDATION
-- ===================================================================
\echo 'Final validation...'
SELECT 'Total rows in pml_df:' AS info, COUNT(*) AS count FROM pml_df;

SELECT 'Rows by Region:' AS info, "Region", COUNT(*) AS count
FROM pml_df GROUP BY "Region" ORDER BY "Region";

SELECT 'Rows by Sector (top 10):' AS info, "Sector", COUNT(*) AS count
FROM pml_df GROUP BY "Sector" ORDER BY COUNT(*) DESC LIMIT 10;

-- ===================================================================
-- CLEANUP
-- ===================================================================
DROP TABLE IF EXISTS pml.pml_staging;
DROP FUNCTION IF EXISTS text_to_numeric_safe(TEXT);
DROP FUNCTION IF EXISTS text_to_date_safe(TEXT, TEXT);

\echo 'Import complete!'
