-- =============================================================================
-- MATERIALIZED VIEW: mv_equities
-- Uses column_alias from equities_schema_metadata to rename all equities columns
-- Falls back to the original column_name where alias is 'n/a' or missing
-- =============================================================================

CREATE MATERIALIZED VIEW mv_equities AS
SELECT
    -- ID
    e."Ticker"                                           AS ticker,
    e."ISIN"                                             AS isin,
    e."Name"                                             AS name,
    e."Description"                                      AS description,

    -- CATEGORICAL
    e."Region"                                           AS region,
    e."Country"                                          AS country,
    e."Trading Country"                                  AS trading_country,
    e."Exchange"                                         AS exchange,
    e."Unit"                                             AS unit,
    e."Sector"                                           AS sector,
    e."Industry"                                         AS industry,
    e."Style Class"                                      AS style_class,
    e."Size Class"                                       AS size_class,
    e."FY End"                                           AS fy_end,
    e."Next Earnings (When)"                             AS next_earnings_when,
    e."Next Earnings (Status)"                           AS next_earnings_status,
    e."Dividend Record (Currency)"                       AS dividend_record_currency,
    e."Dividend Record (Frequency)"                      AS dividend_record_frequency,
    e."Current Fiscal Quarter"                           AS current_fiscal_quarter,
    e."Next Fiscal Quarter"                              AS next_fiscal_quarter,
    e."Next Earnings (Report)"                           AS next_earnings_report,
    e."Reporting Interval"                               AS reporting_interval,
    e."Earnings Report (Frequency)"                      AS earnings_report_frequency,

    -- DATE
    e."Last Updated"                                     AS last_updated,
    e."Income Statement Report Date"                     AS income_statement_report_date,
    e."Next Earnings"                                    AS next_earnings,
    e."Dividend Record (Announce Date)"                  AS dividend_record_announce_date,
    e."Dividend Record (Payable Date)"                   AS dividend_record_payable_date,
    e."Dividend Record (Record Date)"                    AS dividend_record_record_date,
    e."Dividend Record (Ex Date)"                        AS dividend_record_ex_date,
    e."Reference Date"                                   AS reference_date,
    e."FY End Date"                                      AS fy_end_date,
    e."Next FY End Date"                                 AS next_fy_end_date,
    e."Next Income Statement Report Date"                AS next_income_statement_report_date,

    -- MARKET DATA
    e."Price Target"                                     AS price_target,
    e."Price Target - Median"                            AS price_target_median,
    e."Dividend Record (Amount)"                         AS dividend_record_amount,
    e."Market Cap"                                       AS market_cap,
    e."Enterprise Value"                                 AS enterprise_value,
    e."Last Price"                                       AS last_price,
    e."Price Target (YTD Ago)"                           AS price_target_ytd_ago,
    e."Price Target - Low"                               AS price_target_low,
    e."Price Target - High"                              AS price_target_high,
    e."Market Cap (Country R)"                           AS market_cap_country_r,
    e."Volume (Shrs)"                                    AS volume_shrs,
    e."Dividend Per Share (LTM)"                         AS dividend_per_share_ltm,
    e."Price (5D Ago)"                                   AS price_5d_ago,
    e."Price (1W Ago)"                                   AS price_1w_ago,
    e."Price (1M Ago)"                                   AS price_1m_ago,
    e."Price (3M Ago)"                                   AS price_3m_ago,
    e."Price (6M Ago)"                                   AS price_6m_ago,
    e."Price (1Y Ago)"                                   AS price_1y_ago,
    e."Price (3Y Ago)"                                   AS price_3y_ago,
    e."Price (5Y Ago)"                                   AS price_5y_ago,
    e."Price (QTD Ago)"                                  AS price_qtd_ago,
    e."Rel. Volume"                                      AS rel_volume,
    e."52W High/Adj"                                     AS "52w_high_adj",
    e."52W Low/Adj"                                      AS "52w_low_adj",
    e."EMA (20D)"                                        AS ema_20d,
    e."EMA (50D)"                                        AS ema_50d,
    e."EMA (100D)"                                       AS ema_100d,
    e."EMA (250D)"                                       AS ema_250d,
    e."Price Target (1W Ago)"                            AS price_target_1w_ago,
    e."Price Target (1M Ago)"                            AS price_target_1m_ago,
    e."Price Target (3M Ago)"                            AS price_target_3m_ago,
    e."Price Target (6M Ago)"                            AS price_target_6m_ago,
    e."Price Target (MTD Ago)"                           AS price_target_mtd_ago,
    e."Price Target (QTD Ago)"                           AS price_target_qtd_ago,
    e."Price Target (1Y Ago)"                            AS price_target_1y_ago,
    e."Price Target - High (1W Ago)"                     AS price_target_high_1w_ago,
    e."Price Target - High (1M Ago)"                     AS price_target_high_1m_ago,
    e."Price Target - High (6M Ago)"                     AS price_target_high_6m_ago,
    e."Price Target - High (MTD Ago)"                    AS price_target_high_mtd_ago,
    e."Price Target - High (3M Ago)"                     AS price_target_high_3m_ago,
    e."Price Target - High (QTD Ago)"                    AS price_target_high_qtd_ago,
    e."Price Target - High (1Y Ago)"                     AS price_target_high_1y_ago,
    e."Price Target - High (YTD Ago)"                    AS price_target_high_ytd_ago,
    e."Price Target - Low (1W Ago)"                      AS price_target_low_1w_ago,
    e."Price Target - Low (1M Ago)"                      AS price_target_low_1m_ago,
    e."Price Target - Low (3M Ago)"                      AS price_target_low_3m_ago,
    e."Price Target - Low (6M Ago)"                      AS price_target_low_6m_ago,
    e."Price Target - Low (MTD Ago)"                     AS price_target_low_mtd_ago,
    e."Price Target - Low (QTD Ago)"                     AS price_target_low_qtd_ago,
    e."Price Target - Low (YTD Ago)"                     AS price_target_low_ytd_ago,
    e."Price Target - Low (1Y Ago)"                      AS price_target_low_1y_ago,
    e."Price Target - Median (1W Ago)"                   AS price_target_median_1w_ago,
    e."Price Target - Median (1M Ago)"                   AS price_target_median_1m_ago,
    e."Price Target - Median (3M Ago)"                   AS price_target_median_3m_ago,
    e."Price Target - Median (6M Ago)"                   AS price_target_median_6m_ago,
    e."Price Target - Median (MTD Ago)"                  AS price_target_median_mtd_ago,
    e."Price Target - Median (QTD Ago)"                  AS price_target_median_qtd_ago,
    e."Price Target - Median (YTD Ago)"                  AS price_target_median_ytd_ago,
    e."Price Target - Median (1Y Ago)"                   AS price_target_median_1y_ago,

    -- INCOME STATEMENT
    e."Total Revenues (FQ)"                              AS total_revenues_fq,
    e."Total Revenues (-1FY)"                            AS total_revenues_1fy,
    e."Total Revenues (FY)"                              AS total_revenues_fy,
    e."Total Revenues (LTM)"                             AS total_revenues_ltm,
    e."Total Operating Expenses (LTM)"                   AS total_operating_expenses_ltm,
    e."Total Operating Expenses (FQ)"                    AS total_operating_expenses_fq,
    e."Total Operating Expenses (FY)"                    AS total_operating_expenses_fy,
    e."Total Operating Expenses (-1FQFQ)"                AS total_operating_expenses_1fqfq,
    e."Total Operating Expenses (-2FQFQ)"                AS total_operating_expenses_2fqfq,
    e."Total Operating Expenses (-3FQFQ)"                AS total_operating_expenses_3fqfq,
    e."Total Operating Expenses (-4FQFQ)"                AS total_operating_expenses_4fqfq,
    e."Total Operating Expenses (-1FY)"                  AS total_operating_expenses_1fy,
    e."Total Operating Expenses (-2FY)"                  AS total_operating_expenses_2fy,
    e."Total Operating Expenses (-3FY)"                  AS total_operating_expenses_3fy,
    e."Total Operating Expenses (-4FY)"                  AS total_operating_expenses_4fy,
    e."Net Income/Adj. (-1FY)"                           AS net_income_adj_1fy,
    e."EBITDA (FQ)"                                      AS ebitda_fq,
    e."EBITDA (LTM)"                                     AS ebitda_ltm,
    e."EBITDA (FY)"                                      AS ebitda_fy,
    e."EBITDA (-1FY)"                                    AS ebitda_1fy,
    e."EBITDA/Adj. (LTM)"                                AS ebitda_adj_ltm,
    e."EBITDA/Adj. (FY)"                                 AS ebitda_adj_fy,
    e."EBITDA/Adj. (-1FY)"                               AS ebitda_adj_1fy,
    e."EBIT (FQ)"                                        AS ebit_fq,
    e."EBIT (LTM)"                                       AS ebit_ltm,
    e."EBIT (FY)"                                        AS ebit_fy,
    e."EBIT (-1FY)"                                      AS ebit_1fy,
    e."EBIT/Adj. (-1FY)"                                 AS ebit_adj_1fy,
    e."EBIT/Adj. (FY)"                                   AS ebit_adj_fy,
    e."EBIT/Adj. (LTM)"                                  AS ebit_adj_ltm,
    e."EBIT - Est Med (FY1E)"                            AS ebit_est_med_fy1e,
    e."EBIT - Est Med (NTM)"                             AS ebit_est_med_ntm,
    e."Net Income - (IS) (FY)"                           AS net_income_is_fy,
    e."Net Income - (IS) (LTM)"                          AS net_income_is_ltm,
    e."Normalized Net Income (FY)"                       AS normalized_net_income_fy,
    e."Normalized Net Income (LTM)"                      AS normalized_net_income_ltm,
    e."Net Income/Adj. (FY)"                             AS net_income_adj_fy,
    e."Net Income/Adj. (LTM)"                            AS net_income_adj_ltm,
    e."Gross Profit (LTM)"                               AS gross_profit_ltm,
    e."Gross Profit (FY)"                                AS gross_profit_fy,
    e."Cost Of Revenues (LTM)"                           AS cost_of_revenues_ltm,
    e."Operating Income (LTM)"                           AS operating_income_ltm,
    e."Operating Income (FY)"                            AS operating_income_fy,
    e."R&D Expenses (LTM)"                               AS randd_expenses_ltm,
    e."Interest Expense/Total (LTM)"                     AS interest_expense_total_ltm,
    e."Interest Income On Investments (LTM)"             AS interest_income_on_investments_ltm,
    e."Net Income - (IS) (-1FY)"                         AS net_income_is_1fy,
    e."Normalized Net Income (-1FY)"                     AS normalized_net_income_1fy,
    e."Total Revenues (5YAVGFQ)"                         AS total_revenues_5yavgfq,
    e."EBITDA (5YAVGFQ)"                                 AS ebitda_5yavgfq,
    e."EBIT (5YAVGFQ)"                                   AS ebit_5yavgfq,
    e."Operating Income (FQ)"                            AS operating_income_fq,
    e."Operating Income (5YAVGFQ)"                       AS operating_income_5yavgfq,
    e."Normalized Net Income (FQ)"                       AS normalized_net_income_fq,
    e."Normalized Net Income (5YAVGFQ)"                  AS normalized_net_income_5yavgfq,
    e."Net Income/Adj. (FQ)"                             AS net_income_adj_fq,
    e."Net Income/Adj. (5YAVGFQ)"                        AS net_income_adj_5yavgfq,
    e."Net Income - (IS) (FQ)"                           AS net_income_is_fq,
    e."Net Income - (IS) (5YAVGFQ)"                      AS net_income_is_5yavgfq,
    e."Net Income - (IS) (5YAVGLTM)"                     AS net_income_is_5yavgltm,
    e."Normalized Net Income (5YAVGLTM)"                 AS normalized_net_income_5yavgltm,
    e."EBITDA (5YAVGLTM)"                                AS ebitda_5yavgltm,
    e."EBIT (5YAVGLTM)"                                  AS ebit_5yavgltm,
    e."Total Revenues (5YAVGLTM)"                        AS total_revenues_5yavgltm,
    e."Selling General & Admin Expenses/Total (FQ)"      AS selling_general_and_admin_expenses_total_fq,
    e."Selling General & Admin Expenses/Total (FY)"      AS selling_general_and_admin_expenses_total_fy,
    e."Selling General & Admin Expenses/Total (-1FY)"    AS selling_general_and_admin_expenses_total_1fy,
    e."Selling General & Admin Expenses/Total (5YAVGFQ)" AS selling_general_and_admin_expenses_total_5yavgfq,
    e."Marketing Expenses (FQ)"                          AS marketing_expenses_fq,
    e."Marketing Expenses (FY)"                          AS marketing_expenses_fy,
    e."Marketing Expenses (-1FY)"                        AS marketing_expenses_1fy,
    e."Marketing Expenses (5YAVGLTM)"                    AS marketing_expenses_5yavgltm,
    e."Revenues - Est Avg (NTM)"                         AS revenues_est_avg_ntm,
    e."Revenues - Est Avg (FY1E)"                        AS revenues_est_avg_fy1e,
    e."Revenues - Est Med (NTM)"                         AS revenues_est_med_ntm,
    e."Revenues - Est Med (FY1E)"                        AS revenues_est_med_fy1e,
    e."EBITDA - Est Avg (NTM)"                           AS ebitda_est_avg_ntm,
    e."EBITDA - Est Avg (FY1E)"                          AS ebitda_est_avg_fy1e,
    e."Total Revenues (-1FQFQ)"                          AS total_revenues_1fqfq,
    e."Total Revenues (-2FQFQ)"                          AS total_revenues_2fqfq,
    e."Total Revenues (-3FQFQ)"                          AS total_revenues_3fqfq,
    e."Total Revenues (-4FQFQ)"                          AS total_revenues_4fqfq,
    e."Total Revenues (-2FY)"                            AS total_revenues_2fy,
    e."Total Revenues (-3FY)"                            AS total_revenues_3fy,
    e."Total Revenues (-4FY)"                            AS total_revenues_4fy,
    e."Gross Profit (FQ)"                                AS gross_profit_fq,
    e."Gross Profit (-1FQFQ)"                            AS gross_profit_1fqfq,
    e."Gross Profit (-2FQFQ)"                            AS gross_profit_2fqfq,
    e."Gross Profit (-3FQFQ)"                            AS gross_profit_3fqfq,
    e."Gross Profit (-4FQFQ)"                            AS gross_profit_4fqfq,
    e."Gross Profit (-1FY)"                              AS gross_profit_1fy,
    e."Gross Profit (-2FY)"                              AS gross_profit_2fy,
    e."Gross Profit (-3FY)"                              AS gross_profit_3fy,
    e."Gross Profit (-4FY)"                              AS gross_profit_4fy,
    e."Operating Income (-1FQFQ)"                        AS operating_income_1fqfq,
    e."Operating Income (-2FQFQ)"                        AS operating_income_2fqfq,
    e."Operating Income (-3FQFQ)"                        AS operating_income_3fqfq,
    e."Operating Income (-4FQFQ)"                        AS operating_income_4fqfq,
    e."Operating Income (-1FY)"                          AS operating_income_1fy,
    e."Operating Income (-2FY)"                          AS operating_income_2fy,
    e."Operating Income (-3FY)"                          AS operating_income_3fy,
    e."Operating Income (-4FY)"                          AS operating_income_4fy,
    e."R&D Expenses (FQ)"                                AS randd_expenses_fq,
    e."R&D Expenses (FY)"                                AS randd_expenses_fy,
    e."R&D Expenses (-1FQFQ)"                            AS randd_expenses_1fqfq,
    e."R&D Expenses (-2FQFQ)"                            AS randd_expenses_2fqfq,
    e."R&D Expenses (-3FQFQ)"                            AS randd_expenses_3fqfq,
    e."R&D Expenses (-4FQFQ)"                            AS randd_expenses_4fqfq,
    e."R&D Expenses (-1FY)"                              AS randd_expenses_1fy,
    e."R&D Expenses (-2FY)"                              AS randd_expenses_2fy,
    e."R&D Expenses (-3FY)"                              AS randd_expenses_3fy,
    e."R&D Expenses (-4FY)"                              AS randd_expenses_4fy,
    e."Net Income - (IS) (-1FQFQ)"                       AS net_income_is_1fqfq,
    e."Net Income - (IS) (-2FQFQ)"                       AS net_income_is_2fqfq,
    e."Net Income - (IS) (-3FQFQ)"                       AS net_income_is_3fqfq,
    e."Net Income - (IS) (-4FQFQ)"                       AS net_income_is_4fqfq,
    e."Net Income - (IS) (-2FY)"                         AS net_income_is_2fy,
    e."Net Income - (IS) (-3FY)"                         AS net_income_is_3fy,
    e."Net Income - (IS) (-4FY)"                         AS net_income_is_4fy,
    e."Normalized Net Income (-1FQFQ)"                   AS normalized_net_income_1fqfq,
    e."Normalized Net Income (-2FQFQ)"                   AS normalized_net_income_2fqfq,
    e."Normalized Net Income (-3FQFQ)"                   AS normalized_net_income_3fqfq,
    e."Normalized Net Income (-4FQFQ)"                   AS normalized_net_income_4fqfq,
    e."Normalized Net Income (-2FY)"                     AS normalized_net_income_2fy,
    e."Normalized Net Income (-3FY)"                     AS normalized_net_income_3fy,
    e."Normalized Net Income (-4FY)"                     AS normalized_net_income_4fy,
    e."Net Income/Adj. (-1FQFQ)"                         AS net_income_adj_1fqfq,
    e."Net Income/Adj. (-2FQFQ)"                         AS net_income_adj_2fqfq,
    e."Net Income/Adj. (-3FQFQ)"                         AS net_income_adj_3fqfq,
    e."Net Income/Adj. (-4FQFQ)"                         AS net_income_adj_4fqfq,
    e."Net Income/Adj. (-2FY)"                           AS net_income_adj_2fy,
    e."Net Income/Adj. (-3FY)"                           AS net_income_adj_3fy,
    e."Net Income/Adj. (-4FY)"                           AS net_income_adj_4fy,
    e."EBIT (-1FQFQ)"                                    AS ebit_1fqfq,
    e."EBIT (-2FQFQ)"                                    AS ebit_2fqfq,
    e."EBIT (-3FQFQ)"                                    AS ebit_3fqfq,
    e."EBIT (-4FQFQ)"                                    AS ebit_4fqfq,
    e."EBIT (-2FY)"                                      AS ebit_2fy,
    e."EBIT (-3FY)"                                      AS ebit_3fy,
    e."EBIT (-4FY)"                                      AS ebit_4fy,
    e."EBIT/Adj. (FQ)"                                   AS ebit_adj_fq,
    e."EBIT/Adj. (-1FQFQ)"                               AS ebit_adj_1fqfq,
    e."EBIT/Adj. (-2FQFQ)"                               AS ebit_adj_2fqfq,
    e."EBIT/Adj. (-3FQFQ)"                               AS ebit_adj_3fqfq,
    e."EBIT/Adj. (-4FQFQ)"                               AS ebit_adj_4fqfq,
    e."EBIT/Adj. (-2FY)"                                 AS ebit_adj_2fy,
    e."EBIT/Adj. (-3FY)"                                 AS ebit_adj_3fy,
    e."EBIT/Adj. (-4FY)"                                 AS ebit_adj_4fy,
    e."EBITDA (-1FQFQ)"                                  AS ebitda_1fqfq,
    e."EBITDA (-2FQFQ)"                                  AS ebitda_2fqfq,
    e."EBITDA (-3FQFQ)"                                  AS ebitda_3fqfq,
    e."EBITDA (-4FQFQ)"                                  AS ebitda_4fqfq,
    e."EBITDA (-2FY)"                                    AS ebitda_2fy,
    e."EBITDA (-3FY)"                                    AS ebitda_3fy,
    e."EBITDA (-4FY)"                                    AS ebitda_4fy,
    e."EBITDA/Adj. (FQ)"                                 AS ebitda_adj_fq,
    e."EBITDA/Adj. (-1FQFQ)"                             AS ebitda_adj_1fqfq,
    e."EBITDA/Adj. (-2FQFQ)"                             AS ebitda_adj_2fqfq,
    e."EBITDA/Adj. (-3FQFQ)"                             AS ebitda_adj_3fqfq,
    e."EBITDA/Adj. (-4FQFQ)"                             AS ebitda_adj_4fqfq,
    e."EBITDA/Adj. (-2FY)"                               AS ebitda_adj_2fy,
    e."EBITDA/Adj. (-3FY)"                               AS ebitda_adj_3fy,
    e."EBITDA/Adj. (-4FY)"                               AS ebitda_adj_4fy,
    e."Gain (Loss) On Sale Of Assets (LTM)"              AS gain_loss_on_sale_of_assets_ltm,
    e."Impairment of Goodwill (FQ)"                      AS impairment_of_goodwill_fq,
    e."Impairment of Goodwill (LTM)"                     AS impairment_of_goodwill_ltm,
    e."Impairment of Goodwill (-1FY)"                    AS impairment_of_goodwill_1fy,
    e."Impairment of Goodwill (FY)"                      AS impairment_of_goodwill_fy,
    e."Asset Writedown (LTM)"                            AS asset_writedown_ltm,
    e."Asset Writedown (FY)"                             AS asset_writedown_fy,
    e."Asset Writedown (-1FY)"                           AS asset_writedown_1fy,
    e."Restructuring Charges (LTM)"                      AS restructuring_charges_ltm,
    e."Restructuring Charges (FQ)"                       AS restructuring_charges_fq,
    e."Restructuring Charges (-1FY)"                     AS restructuring_charges_1fy,
    e."Restructuring Charges (FY)"                       AS restructuring_charges_fy,
    e."Merger & Restructuring Charges (LTM)"             AS merger_and_restructuring_charges_ltm,
    e."Other Unusual Items/Total (LTM)"                  AS other_unusual_items_total_ltm,
    e."Asset Writedown (FQ)"                             AS asset_writedown_fq,
    e."Asset Writedown (5YAVGFQ)"                        AS asset_writedown_5yavgfq,
    e."Impairment of Goodwill (5YAVGFQ)"                 AS impairment_of_goodwill_5yavgfq,
    e."Restructuring Charges (5YAVGFQ)"                  AS restructuring_charges_5yavgfq,
    e."Merger & Restructuring Charges (FQ)"              AS merger_and_restructuring_charges_fq,
    e."Merger & Restructuring Charges (FY)"              AS merger_and_restructuring_charges_fy,
    e."Merger & Restructuring Charges (5YAVGFQ)"         AS merger_and_restructuring_charges_5yavgfq,
    e."Merger & Restructuring Charges (-1FQFQ)"          AS merger_and_restructuring_charges_1fqfq,
    e."Merger & Restructuring Charges (-2FQFQ)"          AS merger_and_restructuring_charges_2fqfq,
    e."Merger & Restructuring Charges (-3FQFQ)"          AS merger_and_restructuring_charges_3fqfq,
    e."Merger & Restructuring Charges (-4FQFQ)"          AS merger_and_restructuring_charges_4fqfq,
    e."Merger & Restructuring Charges (-1FY)"            AS merger_and_restructuring_charges_1fy,
    e."Merger & Restructuring Charges (-2FY)"            AS merger_and_restructuring_charges_2fy,
    e."Merger & Restructuring Charges (-3FY)"            AS merger_and_restructuring_charges_3fy,
    e."Merger & Restructuring Charges (-4FY)"            AS merger_and_restructuring_charges_4fy,
    e."Impairment of Goodwill (-1FQFQ)"                  AS impairment_of_goodwill_1fqfq,
    e."Impairment of Goodwill (-2FQFQ)"                  AS impairment_of_goodwill_2fqfq,
    e."Impairment of Goodwill (-3FQFQ)"                  AS impairment_of_goodwill_3fqfq,
    e."Impairment of Goodwill (-4FQFQ)"                  AS impairment_of_goodwill_4fqfq,
    e."Impairment of Goodwill (-2FY)"                    AS impairment_of_goodwill_2fy,
    e."Impairment of Goodwill (-3FY)"                    AS impairment_of_goodwill_3fy,
    e."Impairment of Goodwill (-4FY)"                    AS impairment_of_goodwill_4fy,
    e."Asset Writedown (-1FQFQ)"                         AS asset_writedown_1fqfq,
    e."Asset Writedown (-2FQFQ)"                         AS asset_writedown_2fqfq,
    e."Asset Writedown (-3FQFQ)"                         AS asset_writedown_3fqfq,
    e."Asset Writedown (-4FQFQ)"                         AS asset_writedown_4fqfq,
    e."Asset Writedown (-2FY)"                           AS asset_writedown_2fy,
    e."Asset Writedown (-3FY)"                           AS asset_writedown_3fy,
    e."Asset Writedown (-4FY)"                           AS asset_writedown_4fy,
    e."Asset Writedown (-5FY)"                           AS asset_writedown_5fy,
    e."Gain (Loss) On Sale Of Assets (FQ)"               AS gain_loss_on_sale_of_assets_fq,
    e."Gain (Loss) On Sale Of Assets (FY)"               AS gain_loss_on_sale_of_assets_fy,
    e."Gain (Loss) On Sale Of Assets (-1FQFQ)"           AS gain_loss_on_sale_of_assets_1fqfq,
    e."Gain (Loss) On Sale Of Assets (-2FQFQ)"           AS gain_loss_on_sale_of_assets_2fqfq,
    e."Gain (Loss) On Sale Of Assets (-3FQFQ)"           AS gain_loss_on_sale_of_assets_3fqfq,
    e."Gain (Loss) On Sale Of Assets (-4FQFQ)"           AS gain_loss_on_sale_of_assets_4fqfq,
    e."Gain (Loss) On Sale Of Assets (-1FY)"             AS gain_loss_on_sale_of_assets_1fy,
    e."Gain (Loss) On Sale Of Assets (-2FY)"             AS gain_loss_on_sale_of_assets_2fy,
    e."Gain (Loss) On Sale Of Assets (-3FY)"             AS gain_loss_on_sale_of_assets_3fy,
    e."Gain (Loss) On Sale Of Assets (-4FY)"             AS gain_loss_on_sale_of_assets_4fy,
    e."Restructuring Charges (-1FQFQ)"                   AS restructuring_charges_1fqfq,
    e."Restructuring Charges (-2FQFQ)"                   AS restructuring_charges_2fqfq,
    e."Restructuring Charges (-3FQFQ)"                   AS restructuring_charges_3fqfq,
    e."Restructuring Charges (-4FQFQ)"                   AS restructuring_charges_4fqfq,
    e."Restructuring Charges (-2FY)"                     AS restructuring_charges_2fy,
    e."Restructuring Charges (-3FY)"                     AS restructuring_charges_3fy,
    e."Restructuring Charges (-4FY)"                     AS restructuring_charges_4fy,
    e."Interest And Investment Income (LTM)"             AS interest_and_investment_income_ltm,
    e."Interest And Investment Income (FQ)"              AS interest_and_investment_income_fq,
    e."Interest And Investment Income (FY)"              AS interest_and_investment_income_fy,
    e."Interest And Investment Income (-1FQFQ)"          AS interest_and_investment_income_1fqfq,
    e."Interest And Investment Income (-2FQFQ)"          AS interest_and_investment_income_2fqfq,
    e."Interest And Investment Income (-3FQFQ)"          AS interest_and_investment_income_3fqfq,
    e."Interest And Investment Income (-4FQFQ)"          AS interest_and_investment_income_4fqfq,
    e."Interest And Investment Income (-1FY)"            AS interest_and_investment_income_1fy,
    e."Interest And Investment Income (-2FY)"            AS interest_and_investment_income_2fy,
    e."Interest And Investment Income (-3FY)"            AS interest_and_investment_income_3fy,
    e."Interest And Investment Income (-4FY)"            AS interest_and_investment_income_4fy,
    e."Effective Tax Rate - (Ratio) (LTM)"               AS effective_tax_rate_ltm,
    e."Effective Tax Rate - (Ratio) (FQ)"                AS effective_tax_rate_fq,
    e."Effective Tax Rate - (Ratio) (-1FQFQ)"            AS effective_tax_rate_1fqfq,
    e."Effective Tax Rate - (Ratio) (-2FQFQ)"            AS effective_tax_rate_2fqfq,
    e."Effective Tax Rate - (Ratio) (-4FQFQ)"            AS effective_tax_rate_4fqfq,
    e."Effective Tax Rate - (Ratio) (-3FQFQ)"            AS effective_tax_rate_3fqfq,
    e."Effective Tax Rate - (Ratio) (FY)"                AS effective_tax_rate_fy,
    e."Effective Tax Rate - (Ratio) (-1FY)"              AS effective_tax_rate_1fy,
    e."Effective Tax Rate - (Ratio) (-2FY)"              AS effective_tax_rate_2fy,
    e."Effective Tax Rate - (Ratio) (-3FY)"              AS effective_tax_rate_3fy,
    e."Effective Tax Rate - (Ratio) (-4FY)"              AS effective_tax_rate_4fy,

    -- BALANCE SHEET
    e."TBV (FY)"                                         AS tbv_fy,
    e."TBV (LTM)"                                        AS tbv_ltm,
    e."Total Debt (FY)"                                  AS total_debt_fy,
    e."Total Equity (FY)"                                AS total_equity_fy,
    e."Total Equity (LTM)"                               AS total_equity_ltm,
    e."Total Debt (LTM)"                                 AS total_debt_ltm,
    e."Total Assets (LTM)"                               AS total_assets_ltm,
    e."Total Assets (FY)"                                AS total_assets_fy,
    e."Inventory (LTM)"                                  AS inventory_ltm,
    e."Goodwill (FQ)"                                    AS goodwill_fq,
    e."Goodwill (LTM)"                                   AS goodwill_ltm,
    e."Goodwill (FY)"                                    AS goodwill_fy,
    e."Goodwill (-1FY)"                                  AS goodwill_1fy,
    e."Retained Earnings (LTM)"                          AS retained_earnings_ltm,
    e."Total Current Assets (LTM)"                       AS total_current_assets_ltm,
    e."Total Current Liabilities (LTM)"                  AS total_current_liabilities_ltm,
    e."Working Capital (LTM)"                            AS working_capital_ltm,
    e."Cash And Equivalents (LTM)"                       AS cash_and_equivalents_ltm,
    e."Cash And Equivalents (FQ)"                        AS cash_and_equivalents_fq,
    e."Cash And Equivalents (FY)"                        AS cash_and_equivalents_fy,
    e."Cash And Equivalents (5YAVGFQ)"                   AS cash_and_equivalents_5yavgfq,
    e."Inventory (FQ)"                                   AS inventory_fq,
    e."Inventory (FY)"                                   AS inventory_fy,
    e."Goodwill (5YAVGFQ)"                               AS goodwill_5yavgfq,
    e."Inventory (5YAVGFQ)"                              AS inventory_5yavgfq,
    e."Retained Earnings (FQ)"                           AS retained_earnings_fq,
    e."Retained Earnings (FY)"                           AS retained_earnings_fy,
    e."Retained Earnings (5YAVGFQ)"                      AS retained_earnings_5yavgfq,
    e."Working Capital (FQ)"                             AS working_capital_fq,
    e."Working Capital (FY)"                             AS working_capital_fy,
    e."Working Capital (5YAVGFY)"                        AS working_capital_5yavgfy,
    e."Gross Intangible Assets (LTM)"                    AS gross_intangible_assets_ltm,
    e."Gross Intangible Assets (FY)"                     AS gross_intangible_assets_fy,
    e."Gross Intangible Assets (5YAVGFQ)"                AS gross_intangible_assets_5yavgfq,
    e."Accounts Receivable/Total (FY)"                   AS accounts_receivable_total_fy,
    e."Accounts Receivable/Total (-1FY)"                 AS accounts_receivable_total_1fy,
    e."Accounts Receivable/Total (5YAVGFQ)"              AS accounts_receivable_total_5yavgfq,
    e."Working Capital (-1FQ)"                           AS working_capital_1fq,
    e."Working Capital (-2FQ)"                           AS working_capital_2fq,
    e."Working Capital (-3FQ)"                           AS working_capital_3fq,
    e."Working Capital (-4FQ)"                           AS working_capital_4fq,
    e."Working Capital (-1FY)"                           AS working_capital_1fy,
    e."Working Capital (-2FY)"                           AS working_capital_2fy,
    e."Working Capital (-3FY)"                           AS working_capital_3fy,
    e."Working Capital (-4FY)"                           AS working_capital_4fy,
    e."Total Debt (FQ)"                                  AS total_debt_fq,
    e."Total Debt (-1FQ)"                                AS total_debt_1fq,
    e."Total Debt (-2FQ)"                                AS total_debt_2fq,
    e."Total Debt (-3FQ)"                                AS total_debt_3fq,
    e."Total Debt (-4FQ)"                                AS total_debt_4fq,
    e."Total Debt (-1FY)"                                AS total_debt_1fy,
    e."Total Debt (-2FY)"                                AS total_debt_2fy,
    e."Total Debt (-3FY)"                                AS total_debt_3fy,
    e."Total Debt (-4FY)"                                AS total_debt_4fy,
    e."Total Assets (FQ)"                                AS total_assets_fq,
    e."Total Assets (-1FQ)"                              AS total_assets_1fq,
    e."Total Assets (-2FQ)"                              AS total_assets_2fq,
    e."Total Assets (-3FQ)"                              AS total_assets_3fq,
    e."Total Assets (-4FQ)"                              AS total_assets_4fq,
    e."Total Assets (-1FY)"                              AS total_assets_1fy,
    e."Total Assets (-2FY)"                              AS total_assets_2fy,
    e."Total Assets (-3FY)"                              AS total_assets_3fy,
    e."Total Assets (-4FY)"                              AS total_assets_4fy,
    e."Inventory (-1FQ)"                                 AS inventory_1fq,
    e."Inventory (-2FQ)"                                 AS inventory_2fq,
    e."Inventory (-3FQ)"                                 AS inventory_3fq,
    e."Inventory (-4FQ)"                                 AS inventory_4fq,
    e."Inventory (-1FY)"                                 AS inventory_1fy,
    e."Inventory (-2FY)"                                 AS inventory_2fy,
    e."Inventory (-3FY)"                                 AS inventory_3fy,
    e."Inventory (-4FY)"                                 AS inventory_4fy,
    e."Goodwill (-1FQ)"                                  AS goodwill_1fq,
    e."Goodwill (-2FQ)"                                  AS goodwill_2fq,
    e."Goodwill (-3FQ)"                                  AS goodwill_3fq,
    e."Goodwill (-4FQ)"                                  AS goodwill_4fq,
    e."Goodwill (-2FY)"                                  AS goodwill_2fy,
    e."Goodwill (-3FY)"                                  AS goodwill_3fy,
    e."Goodwill (-4FY)"                                  AS goodwill_4fy,
    e."Retained Earnings (-1FQ)"                         AS retained_earnings_1fq,
    e."Retained Earnings (-2FQ)"                         AS retained_earnings_2fq,
    e."Retained Earnings (-3FQ)"                         AS retained_earnings_3fq,
    e."Retained Earnings (-4FQ)"                         AS retained_earnings_4fq,
    e."Retained Earnings (-1FY)"                         AS retained_earnings_1fy,
    e."Retained Earnings (-2FY)"                         AS retained_earnings_2fy,
    e."Retained Earnings (-3FY)"                         AS retained_earnings_3fy,
    e."Retained Earnings (-4FY)"                         AS retained_earnings_4fy,
    e."Cash And Equivalents (-1FQ)"                      AS cash_and_equivalents_1fq,
    e."Cash And Equivalents (-2FQ)"                      AS cash_and_equivalents_2fq,
    e."Cash And Equivalents (-3FQ)"                      AS cash_and_equivalents_3fq,
    e."Cash And Equivalents (-4FQ)"                      AS cash_and_equivalents_4fq,
    e."Cash And Equivalents (-1FY)"                      AS cash_and_equivalents_1fy,
    e."Cash And Equivalents (-2FY)"                      AS cash_and_equivalents_2fy,
    e."Cash And Equivalents (-3FY)"                      AS cash_and_equivalents_3fy,
    e."Cash And Equivalents (-4FY)"                      AS cash_and_equivalents_4fy,
    e."Gross Intangible Assets (FQ)"                     AS gross_intangible_assets_fq,
    e."Gross Intangible Assets (-1FQ)"                   AS gross_intangible_assets_1fq,
    e."Gross Intangible Assets (-2FQ)"                   AS gross_intangible_assets_2fq,
    e."Gross Intangible Assets (-3FQ)"                   AS gross_intangible_assets_3fq,
    e."Gross Intangible Assets (-4FQ)"                   AS gross_intangible_assets_4fq,
    e."Gross Intangible Assets (-1FY)"                   AS gross_intangible_assets_1fy,
    e."Gross Intangible Assets (-2FY)"                   AS gross_intangible_assets_2fy,
    e."Gross Intangible Assets (-3FY)"                   AS gross_intangible_assets_3fy,
    e."Gross Intangible Assets (-4FY)"                   AS gross_intangible_assets_4fy,

    -- CASH FLOW
    e."CFF (LTM)"                                        AS cff_ltm,
    e."CFI (LTM)"                                        AS cfi_ltm,
    e."FCF (LTM)"                                        AS fcf_ltm,
    e."CFO (LTM)"                                        AS cfo_ltm,
    e."Cash Acquisitions (LTM)"                          AS cash_acquisitions_ltm,
    e."Cash Acquisitions (FY)"                           AS cash_acquisitions_fy,
    e."Cash Acquisitions (-1FY)"                         AS cash_acquisitions_1fy,
    e."Capital Expenditure (LTM)"                        AS capital_expenditure_ltm,
    e."Capital Expenditure (-1FY)"                       AS capital_expenditure_1fy,
    e."Capital Expenditure (FY)"                         AS capital_expenditure_fy,
    e."CFF (FY)"                                         AS cff_fy,
    e."CFF (-1FY)"                                       AS cff_1fy,
    e."CFI (FY)"                                         AS cfi_fy,
    e."CFI (-1FY)"                                       AS cfi_1fy,
    e."CFO (FY)"                                         AS cfo_fy,
    e."CFO (-1FY)"                                       AS cfo_1fy,
    e."FCF (FY)"                                         AS fcf_fy,
    e."FCF (-1FY)"                                       AS fcf_1fy,
    e."Capital Expenditure (FQ)"                         AS capital_expenditure_fq,
    e."Capital Expenditure (5YAVGFQ)"                    AS capital_expenditure_5yavgfq,
    e."CFF (FQ)"                                         AS cff_fq,
    e."CFI (FQ)"                                         AS cfi_fq,
    e."CFO (FQ)"                                         AS cfo_fq,
    e."FCF (FQ)"                                         AS fcf_fq,
    e."FCF (5YAVGFQ)"                                    AS fcf_5yavgfq,
    e."Cash Acquisitions (FQ)"                           AS cash_acquisitions_fq,
    e."Cash Acquisitions (5YAVGFQ)"                      AS cash_acquisitions_5yavgfq,
    e."Common Dividends Paid (LTM)"                      AS common_dividends_paid_ltm,
    e."Common Dividends Paid (FY)"                       AS common_dividends_paid_fy,
    e."CFO (-1FQFQ)"                                     AS cfo_1fqfq,
    e."CFO (-2FQFQ)"                                     AS cfo_2fqfq,
    e."CFO (-3FQFQ)"                                     AS cfo_3fqfq,
    e."CFO (-4FQFQ)"                                     AS cfo_4fqfq,
    e."CFI (-1FQFQ)"                                     AS cfi_1fqfq,
    e."CFI (-2FQFQ)"                                     AS cfi_2fqfq,
    e."CFI (-3FQFQ)"                                     AS cfi_3fqfq,
    e."CFI (-4FQFQ)"                                     AS cfi_4fqfq,
    e."CFI (-2FY)"                                       AS cfi_2fy,
    e."CFI (-3FY)"                                       AS cfi_3fy,
    e."CFI (-4FY)"                                       AS cfi_4fy,
    e."FCF (-1FQFQ)"                                     AS fcf_1fqfq,
    e."FCF (-2FQFQ)"                                     AS fcf_2fqfq,
    e."FCF (-3FQFQ)"                                     AS fcf_3fqfq,
    e."FCF (-4FQFQ)"                                     AS fcf_4fqfq,
    e."CFF (-2FY)"                                       AS cff_2fy,
    e."CFF (-3FY)"                                       AS cff_3fy,
    e."CFF (-4FY)"                                       AS cff_4fy,
    e."CFF (-1FQFQ)"                                     AS cff_1fqfq,
    e."CFF (-2FQFQ)"                                     AS cff_2fqfq,
    e."CFF (-3FQFQ)"                                     AS cff_3fqfq,
    e."CFF (-4FQFQ)"                                     AS cff_4fqfq,
    e."CFO (-2FY)"                                       AS cfo_2fy,
    e."CFO (-3FY)"                                       AS cfo_3fy,
    e."CFO (-4FY)"                                       AS cfo_4fy,
    e."Cash Acquisitions (-1FQFQ)"                       AS cash_acquisitions_1fqfq,
    e."Cash Acquisitions (-2FQFQ)"                       AS cash_acquisitions_2fqfq,
    e."Cash Acquisitions (-3FQFQ)"                       AS cash_acquisitions_3fqfq,
    e."Cash Acquisitions (-4FQFQ)"                       AS cash_acquisitions_4fqfq,
    e."FCF (-2FY)"                                       AS fcf_2fy,
    e."FCF (-3FY)"                                       AS fcf_3fy,
    e."FCF (-4FY)"                                       AS fcf_4fy,
    e."Cash Acquisitions (-2FY)"                         AS cash_acquisitions_2fy,
    e."Cash Acquisitions (-3FY)"                         AS cash_acquisitions_3fy,
    e."Cash Acquisitions (-4FY)"                         AS cash_acquisitions_4fy,
    e."Capital Expenditure (-1FQFQ)"                     AS capital_expenditure_1fqfq,
    e."Capital Expenditure (-2FQFQ)"                     AS capital_expenditure_2fqfq,
    e."Capital Expenditure (-3FQFQ)"                     AS capital_expenditure_3fqfq,
    e."Capital Expenditure (-4FQFQ)"                     AS capital_expenditure_4fqfq,
    e."Capital Expenditure (-2FY)"                       AS capital_expenditure_2fy,
    e."Capital Expenditure (-3FY)"                       AS capital_expenditure_3fy,
    e."Capital Expenditure (-4FY)"                       AS capital_expenditure_4fy,
    e."FCF - Est Avg (FY1E)"                             AS fcf_est_avg_fy1e,
    e."FCF - Est Avg (FY2E)"                             AS fcf_est_avg_fy2e,
    e."FCF - Est Avg (FY3E)"                             AS fcf_est_avg_fy3e,
    e."FCF - Est Avg (FY4E)"                             AS fcf_est_avg_fy4e,
    e."FCF - Est Avg (FY5E)"                             AS fcf_est_avg_fy5e,

    -- RATIOS
    e."P/E (NTM)"                                        AS p_e_ntm,
    e."P/E (LTM)"                                        AS p_e_ltm,
    e."Altman Z-Score (FY)"                              AS altman_z_score_fy,
    e."Altman Z-Score (FQ)"                              AS altman_z_score_fq,
    e."Altman Z-Score (LTM)"                             AS altman_z_score_ltm,
    e."P/TBV (LTM)"                                      AS p_tbv_ltm,
    e."Return On Equity % (LTM)"                         AS return_on_equity_pct_ltm,
    e."Return On Equity % (FY)"                          AS return_on_equity_pct_fy,
    e."Current Ratio (FY)"                               AS current_ratio_fy,
    e."Current Ratio (LTM)"                              AS current_ratio_ltm,
    e."Asset Turnover (FY)"                              AS asset_turnover_fy,
    e."Asset Turnover (LTM)"                             AS asset_turnover_ltm,
    e."EPS Norm - Est Avg (NTM)"                         AS eps_norm_est_avg_ntm,
    e."EPS/Adj. (-1FY)"                                  AS eps_adj_1fy,
    e."EPS/Adj. (FY)"                                    AS eps_adj_fy,
    e."EPS/Adj. (LTM)"                                   AS eps_adj_ltm,
    e."EPS Norm - Est Avg (FY1E)"                        AS eps_norm_est_avg_fy1e,
    e."Return on Assets (ROA) % (LTM)"                   AS return_on_assets_roa_pct_ltm,
    e."Return on Assets (ROA) % (FY)"                    AS return_on_assets_roa_pct_fy,
    e."P/B (LTM)"                                        AS p_b_ltm,
    e."P/B (-1FY)"                                       AS p_b_1fy,
    e."P/B (5YAVG)"                                      AS p_b_5yavg,
    e."EV/Sales (EST FY1)"                               AS ev_sales_est_fy1,
    e."EV/Sales (LTM)"                                   AS ev_sales_ltm,
    e."EV/Sales (NTM)"                                   AS ev_sales_ntm,
    e."EV/Sales (-1FYLTM)"                               AS ev_sales_1fyltm,
    e."EV/Sales (-2FYLTM)"                               AS ev_sales_2fyltm,
    e."EV/Sales (-3FYLTM)"                               AS ev_sales_3fyltm,
    e."EV/Sales (3YAVGLTM)"                              AS ev_sales_3yavgltm,
    e."EV/Sales (-1FQLTM)"                               AS ev_sales_1fqltm,
    e."EV/Sales (-2FQLTM)"                               AS ev_sales_2fqltm,
    e."EV/Sales (-3FQLTM)"                               AS ev_sales_3fqltm,
    e."EV/Sales (-4FQLTM)"                               AS ev_sales_4fqltm,
    e."EV/EBITDA (LTM)"                                  AS ev_ebitda_ltm,
    e."EV/EBITDA (NTM)"                                  AS ev_ebitda_ntm,
    e."EV/EBITDA (-1FYLTM)"                              AS ev_ebitda_1fyltm,
    e."EV/EBITDA (-1FQLTM)"                              AS ev_ebitda_1fqltm,
    e."EV/EBITDA (3YAVGLTM)"                             AS ev_ebitda_3yavgltm,
    e."EV/EBITDA (EST FY1)"                              AS ev_ebitda_est_fy1,
    e."P/E (EST FY1)"                                    AS p_e_est_fy1,
    e."P/E (-1FYLTM)"                                    AS p_e_1fyltm,
    e."P/E (-2FYLTM)"                                    AS p_e_2fyltm,
    e."P/E (-3FYLTM)"                                    AS p_e_3fyltm,
    e."P/E (3YAVGLTM)"                                   AS p_e_3yavgltm,
    e."P/E (-1FQLTM)"                                    AS p_e_1fqltm,
    e."P/E (-2FQLTM)"                                    AS p_e_2fqltm,
    e."P/E (-3FQLTM)"                                    AS p_e_3fqltm,
    e."P/E (5YAVGLTM)"                                   AS p_e_5yavgltm,
    e."P/E (-0FQQoQLTM)"                                 AS p_e_0fqqoqltm,
    e."P/E (-0FYYoYLTM)"                                 AS p_e_0fyyoyltm,
    e."P/E (-1FYYoYLTM)"                                 AS p_e_1fyyoyltm,
    e."P/E (-0FQYoYLTM)"                                 AS p_e_0fqyoyltm,
    e."Net EPS - Basic (LTM)"                            AS net_eps_basic_ltm,
    e."Net EPS - Basic (FQ)"                             AS net_eps_basic_fq,
    e."Net EPS - Basic (FY)"                             AS net_eps_basic_fy,
    e."Net EPS - Basic (-1FQFQ)"                         AS net_eps_basic_1fqfq,
    e."Net EPS - Basic (-2FQFQ)"                         AS net_eps_basic_2fqfq,
    e."Net EPS - Basic (-3FQFQ)"                         AS net_eps_basic_3fqfq,
    e."Net EPS - Basic (-4FQFQ)"                         AS net_eps_basic_4fqfq,
    e."Net EPS - Basic (-1FY)"                           AS net_eps_basic_1fy,
    e."Net EPS - Basic (-2FY)"                           AS net_eps_basic_2fy,
    e."Net EPS - Basic (-3FY)"                           AS net_eps_basic_3fy,
    e."Net EPS - Basic (-4FY)"                           AS net_eps_basic_4fy,
    e."Net EPS - Basic (-5FY)"                           AS net_eps_basic_5fy,
    e."EPS GAAP - Est Avg (NTM)"                         AS eps_gaap_est_avg_ntm,
    e."EPS GAAP - Est Avg (FY1E)"                        AS eps_gaap_est_avg_fy1e,
    e."Basic EPS - Cont (LTM)"                           AS basic_eps_cont_ltm,
    e."Basic EPS - Cont (FQ)"                            AS basic_eps_cont_fq,
    e."Basic EPS - Cont (FY)"                            AS basic_eps_cont_fy,
    e."Basic EPS - Cont (-1FQFQ)"                        AS basic_eps_cont_1fqfq,
    e."Basic EPS - Cont (-2FQFQ)"                        AS basic_eps_cont_2fqfq,
    e."Basic EPS - Cont (-3FQFQ)"                        AS basic_eps_cont_3fqfq,
    e."Basic EPS - Cont (-4FQFQ)"                        AS basic_eps_cont_4fqfq,
    e."Basic EPS - Cont (-1FY)"                          AS basic_eps_cont_1fy,
    e."Basic EPS - Cont (-2FY)"                          AS basic_eps_cont_2fy,
    e."Basic EPS - Cont (-3FY)"                          AS basic_eps_cont_3fy,
    e."Basic EPS - Cont (-4FY)"                          AS basic_eps_cont_4fy,
    e."EPS/Adj. (FQ)"                                    AS eps_adj_fq,
    e."EPS/Adj. (-1FQFQ)"                                AS eps_adj_1fqfq,
    e."EPS/Adj. (-2FQFQ)"                                AS eps_adj_2fqfq,
    e."EPS/Adj. (-3FQFQ)"                                AS eps_adj_3fqfq,
    e."EPS/Adj. (-4FQFQ)"                                AS eps_adj_4fqfq,
    e."EPS/Adj. (-2FY)"                                  AS eps_adj_2fy,
    e."EPS/Adj. (-3FY)"                                  AS eps_adj_3fy,
    e."EPS/Adj. (-4FY)"                                  AS eps_adj_4fy,

    -- PERCENTAGES
    e."Total Return (YTD)"                               AS total_return_ytd,
    e."Beta (1Y)"                                        AS beta_1y,
    e."Beta (2Y)"                                        AS beta_2y,
    e."Beta (5Y)"                                        AS beta_5y,
    e."Total Revenues/CAGR (5Y FY)"                      AS total_revenues_cagr_5y_fy,
    e."Tot. Return %/CAGR (3Y)"                          AS tot_return_pct_cagr_3y,
    e."Tot. Return %/CAGR (10Y)"                         AS tot_return_pct_cagr_10y,
    e."Total Return (5Y)"                                AS total_return_5y,
    e."Total Return (10Y)"                               AS total_return_10y,
    e."Net Income Margin % (FY)"                         AS net_income_margin_pct_fy,
    e."Net Income Margin % (LTM)"                        AS net_income_margin_pct_ltm,
    e."Volatility (1M)"                                  AS volatility_1m,
    e."Volatility (3M)"                                  AS volatility_3m,
    e."Volatility (6M)"                                  AS volatility_6m,
    e."Volatility (1Y)"                                  AS volatility_1y,
    e."Div Yield (Ind)"                                  AS div_yield_ind,
    e."Div Yield (LTM)"                                  AS div_yield_ltm,
    e."Gross Profit Margin % (FY)"                       AS gross_profit_margin_pct_fy,
    e."Gross Profit Margin % (LTM)"                      AS gross_profit_margin_pct_ltm,
    e."Buyback Yield (LTM)"                              AS buyback_yield_ltm,
    e."Div Yield (-1FYInd)"                              AS div_yield_1fyind,
    e."Div Yield (TTM)"                                  AS div_yield_ttm,
    e."Div Yield (NTM)"                                  AS div_yield_ntm,
    e."Div Yield (5YAVGLTM)"                             AS div_yield_5yavgltm,
    e."Revenues - Est YoY % (FY1E)"                      AS revenues_est_yoy_pct_fy1e,
    e."Price Chg. % (1M)"                                AS price_chg_pct_1m,
    e."Price Chg. % (3M)"                                AS price_chg_pct_3m,
    e."1-Day %"                                          AS one_day_pct,
    e."EPS Est Avg Rev % (FY1E - 1W)"                    AS eps_est_avg_rev_pct_fy1e_1w,
    e."EPS Est Avg Rev % (FY1E - 1M)"                    AS eps_est_avg_rev_pct_fy1e_1m,
    e."EPS Est Avg Rev % (FY1E - 3M)"                    AS eps_est_avg_rev_pct_fy1e_3m,
    e."EPS Est Avg Rev % (FY1E - 6M)"                    AS eps_est_avg_rev_pct_fy1e_6m,
    e."EPS Est Avg Rev % (FY1E - 1Y)"                    AS eps_est_avg_rev_pct_fy1e_1y,
    e."Div Yield (-2FYInd)"                              AS div_yield_2fyind,
    e."Div Yield (-3FYInd)"                              AS div_yield_3fyind,
    e."Div Yield (-4FYInd)"                              AS div_yield_4fyind,
    e."Div Yield (-5FYInd)"                              AS div_yield_5fyind,
    e."EPS GAAP Est Avg Rev % (FY1E - 1M)"               AS eps_gaap_est_avg_rev_pct_fy1e_1m,
    e."EPS GAAP Est Avg Rev % (FY1E - 3M)"               AS eps_gaap_est_avg_rev_pct_fy1e_3m,
    e."EPS GAAP Est Avg Rev % (FY1E - 6M)"               AS eps_gaap_est_avg_rev_pct_fy1e_6m,
    e."EPS GAAP Est Avg Rev % (FY1E - 1Y)"               AS eps_gaap_est_avg_rev_pct_fy1e_1y,

    -- COUNTS
    e."Dividend Streak"                                  AS dividend_streak,
    e."Price Target - #"                                 AS price_target_count,
    e."Analyst Rating"                                   AS analyst_rating,
    e."# Strong Sell Ratings"                            AS num_strong_sell_ratings,
    e."# Strong Buys Ratings"                            AS num_strong_buys_ratings,
    e."# Hold Ratings"                                   AS num_hold_ratings,
    e."# Buys Ratings"                                   AS num_buys_ratings,
    e."# Sell Ratings"                                   AS num_sell_ratings,
    e."# No Opinion Ratings"                             AS num_no_opinion_ratings,
    e."Shrs Out"                                         AS shares_outstanding,
    e."Shrs Out (-1FY)"                                  AS shrs_out_1fy,
    e."Full Time Employees (FQ)"                         AS full_time_employees_fq,
    e."Full Time Employees (FY)"                         AS full_time_employees_fy,
    e."Full Time Employees (-1FY)"                       AS full_time_employees_1fy,
    e."Full Time Employees (-2FY)"                       AS full_time_employees_2fy,
    e."Full Time Employees (-3FY)"                       AS full_time_employees_3fy,
    e."Avg Employees (5YAVGFY)"                          AS avg_employees_5yavgfy,
    e."EPS Norm - Est # (FY1E)"                          AS eps_norm_est_num_fy1e,
    e."Price Target - # (3M Ago)"                        AS price_target_num_3m_ago,
    e."Price Target - # (6M Ago)"                        AS price_target_num_6m_ago,
    e."Price Target - # (YTD Ago)"                       AS price_target_num_ytd_ago,
    e."Price Target - # (1Y Ago)"                        AS price_target_num_1y_ago,
    e."Price Target - # (1W Ago)"                        AS price_target_num_1w_ago,
    e."Price Target - # (1M Ago)"                        AS price_target_num_1m_ago,
    e."Price Target - # (MTD Ago)"                       AS price_target_num_mtd_ago,
    e."Price Target - # (QTD Ago)"                       AS price_target_num_qtd_ago,

    -- FEATURES
    e."Fiscal Month"                                     AS fiscal_month,
    e."Fiscal Quarter"                                   AS fiscal_quarter,
    e."Fiscal Year"                                      AS fiscal_year,
    e."Reporting Lag"                                    AS reporting_lag

FROM equities e;

-- Unique index on ISIN to support REFRESH MATERIALIZED VIEW CONCURRENTLY
CREATE UNIQUE INDEX idx_mv_equities_isin ON mv_equities (isin);

-- Additional indexes mirroring the base table for query performance
CREATE INDEX idx_mv_equities_ticker ON mv_equities (ticker);
CREATE INDEX idx_mv_equities_geography ON mv_equities (region, country, exchange);
CREATE INDEX idx_mv_equities_class ON mv_equities (sector, industry, size_class, style_class);
CREATE INDEX idx_mv_equities_market_cap ON mv_equities (market_cap DESC);
CREATE INDEX idx_mv_equities_fiscal ON mv_equities (fiscal_year, fiscal_quarter, income_statement_report_date);

COMMENT ON MATERIALIZED VIEW mv_equities IS
    'Aliased snapshot of the equities table. Column names sourced from equities_schema_metadata.column_alias. '
        'Refresh with: REFRESH MATERIALIZED VIEW CONCURRENTLY mv_equities;';
