CREATE MATERIALIZED VIEW pml.mv_pymc_price_target AS
SELECT isin,
       ticker,
       region,
       country,
       trading_country,
       exchange,
       unit,
       style_class,
       size_class,
       sector,
       industry,
       income_statement_report_date,
       next_earnings,
       fy_end_date,
       next_income_statement_report_date,
       next_fy_end_date,
       expected_report_date,
       next_earnings - CURRENT_DATE                     AS days_to_next_earnings,
       CURRENT_DATE - income_statement_report_date      AS days_since_last_report,
       next_fy_end_date - CURRENT_DATE                  AS days_to_next_fy_end,
       next_income_statement_report_date - CURRENT_DATE AS days_to_next_report,
       expected_report_date - CURRENT_DATE              AS days_to_expected_report,
       fy_end_date - CURRENT_DATE                       AS days_to_fy_end,
       target_pct_avg                                                                                 AS observed_target_pct,
       target_pct_med                                                                                 AS observed_target_pct_med,
       last_price,
       price_target_num                                                                               AS n_analysts,
       num_strong_buys_ratings + num_buys_ratings - num_sell_ratings -
       num_strong_sell_ratings                                                                        AS feat_net_buy_sentiment,
       safe_divide((num_strong_buys_ratings + num_strong_sell_ratings)::numeric, NULLIF(
		       num_strong_buys_ratings + num_buys_ratings + num_hold_ratings + num_sell_ratings +
		       num_strong_sell_ratings,
		       0)::numeric)                                                                           AS feat_conviction_ratio,
       num_hold_ratings                                                                               AS feat_holds,
       num_no_opinion_ratings                                                                         AS feat_no_opinion,
       calc_change_ratio(price_target::numeric, last_price::numeric)                                  AS feat_implied_upside,
       calc_change_ratio(target_pct_high::numeric, target_pct_low::numeric)                           AS feat_target_range_width,
       calc_change_ratio(price_target::numeric,
                         price_target_3m_ago::numeric)                                                AS feat_pt_momentum_3m,
       calc_change_ratio(price_target_num::numeric,
                         price_target_num_3m_ago::numeric)                                            AS feat_coverage_change_3m,
       coef_var(price_target::numeric, price_target_stddev::numeric)                                  AS feat_target_dispersion_cv,
       safe_divide(last_price - w_52low_adj,
                   NULLIF(w_52high_adj - w_52low_adj, 0::double precision))                           AS feat_52w_range_position,
       p_e_ntm                                                                                        AS feat_pe_ntm,
       ev_ebitda_ntm                                                                                  AS feat_ev_ebitda_ntm,
       volatility_3m                                                                                  AS feat_vol_3m,
       analyst_rating                                   AS feat_analyst_rating,
       price_target,
       price_target_high,
       price_target_low,
       price_target_median,
       price_target_stddev,
       target_pct_high,
       target_pct_low,
       num_strong_buys_ratings,
       num_buys_ratings,
       num_sell_ratings,
       num_strong_sell_ratings,
       w_52high_adj,
       w_52low_adj,
       p_e_ltm,
       p_e_3yavgltm,
       p_e_3yavgntm,
       p_e_5yavgltm,
       p_e_5yavgntm,
       p_e_est_fy1,
       p_e_est_fy2,
       p_e_est_fy3,
       p_e_est_fy4,
       p_e_est_fy5,
       ev_ebitda_ltm,
       ev_ebitda_3yavgltm,
       ev_ebitda_est_fy1,
       ev_sales_ltm,
       ev_sales_ntm,
       ev_sales_3yavgltm,
       p_b_ltm,
       p_b_5yavg,
       peg_ntm,
       peg_3yavg,
       peg_5yavg,
       p_e_neg1fqltm,
       p_e_neg2fqltm,
       p_e_neg3fqltm,
       p_e_neg4fqltm,
       p_e_neg1fyltm,
       p_e_neg2fyltm,
       p_e_neg3fyltm,
       p_e_neg4fyltm,
       p_e_neg0fqqoqltm,
       p_e_neg0fqyoyltm,
       p_e_neg0fyyoyltm,
       p_e_neg1fyyoyltm,
       ev_ebitda_neg1fqltm,
       ev_ebitda_neg1fyltm,
       ev_sales_neg1fqltm,
       ev_sales_neg2fqltm,
       ev_sales_neg3fqltm,
       ev_sales_neg4fqltm,
       ev_sales_neg1fyltm,
       ev_sales_neg2fyltm,
       ev_sales_neg3fyltm,
       p_b_neg1fy,
       peg_neg1fy,
       peg_neg2fy,
       peg_neg3fy,
       peg_neg4fy,
       peg_neg5fy,
       price_target_1w_ago,
       price_target_1m_ago,
       price_target_6m_ago,
       price_target_1y_ago,
       price_target_mtd_ago,
       price_target_qtd_ago,
       price_target_ytd_ago,
       price_target_high_1w_ago,
       price_target_high_1m_ago,
       price_target_high_3m_ago,
       price_target_high_6m_ago,
       price_target_high_1y_ago,
       price_target_high_mtd_ago,
       price_target_high_qtd_ago,
       price_target_high_ytd_ago,
       price_target_low_1w_ago,
       price_target_low_1m_ago,
       price_target_low_3m_ago,
       price_target_low_6m_ago,
       price_target_low_1y_ago,
       price_target_low_mtd_ago,
       price_target_low_qtd_ago,
       price_target_low_ytd_ago,
       price_target_median_1w_ago,
       price_target_median_1m_ago,
       price_target_median_3m_ago,
       price_target_median_6m_ago,
       price_target_median_1y_ago,
       price_target_median_mtd_ago,
       price_target_median_qtd_ago,
       price_target_median_ytd_ago,
       price_target_num_1w_ago,
       price_target_num_1m_ago,
       price_target_num_6m_ago,
       price_target_num_1y_ago,
       price_target_num_mtd_ago,
       price_target_num_qtd_ago,
       price_target_num_ytd_ago,
       price_target_stddev_1w_ago,
       price_target_stddev_1m_ago,
       price_target_stddev_3m_ago,
       price_target_stddev_6m_ago,
       price_target_stddev_1y_ago,
       price_target_stddev_mtd_ago,
       price_target_stddev_qtd_ago,
       price_target_stddev_ytd_ago
FROM pml_df;

ALTER MATERIALIZED VIEW pml.mv_pymc_price_target OWNER TO postgres;

CREATE UNIQUE INDEX idx_mv_pymc_price_target_isin ON pml.mv_pymc_price_target (isin);