CREATE MATERIALIZED VIEW pml.mv_pymc_kalman_pt AS
SELECT pml_df.isin,
       pml_df.ticker,
       pml_df.name,
       pml_df.trading_region,
       pml_df.region,
       pml_df.country,
       pml_df.country_name,
       pml_df.trading_country,
       pml_df.trading_country_name,
       pml_df.exchange,
       pml_df.exchange_name,
       pml_df.unit,
       pml_df.unit_name,
       pml_df.style_class,
       pml_df.size_class,
       pml_df.sector,
       pml_df.industry,
       pml_df.last_updated,
       pml_df.income_statement_report_date,
       pml_df.next_earnings,
       pml_df.next_earnings_when,
       pml_df.next_earnings_status,
       pml_df.fy_end_date,
       pml_df.next_fiscal_quarter,
       pml_df.next_income_statement_report_date,
       pml_df.next_fy_end_date,
       pml_df.expected_report_date,
       pml_df.next_earnings - CURRENT_DATE                                                                                                                                                                                                           AS days_to_next_earnings,
       CURRENT_DATE - pml_df.income_statement_report_date                                                                                                                                                                                            AS days_since_last_report,
       pml_df.next_fy_end_date - CURRENT_DATE                                                                                                                                                                                                        AS days_to_next_fy_end,
       pml_df.next_fiscal_quarter - CURRENT_DATE                                                                                                                                                                                                     AS days_to_next_fiscal_quarter,
       pml_df.next_income_statement_report_date - CURRENT_DATE                                                                                                                                                                                       AS days_to_next_report,
       pml_df.expected_report_date - CURRENT_DATE                                                                                                                                                                                                    AS days_to_expected_report,
       pml_df.fy_end_date - CURRENT_DATE                                                                                                                                                                                                             AS days_since_fy_end,
       pml_df.market_cap,
       pml_df.enterprise_value,
       pml_df.market_cap_country_r,
       pml_df.rel_volume                                                                                                                                                                                                                              AS feat_rel_volume,
       pml_df.price_target                                                                                                                                                                                                                           AS observed_pt,
       pml_df.last_price,
       pml_df.price_target_median,
       pml_df.price_target_high,
       pml_df.price_target_low,
       pml_df.price_target_num                                                                                                                                                                                                                       AS n_analysts,
       pml_df.price_target_1w_ago,
       pml_df.price_target_mtd_ago,
       pml_df.price_target_1m_ago,
       pml_df.price_target_qtd_ago,
       pml_df.price_target_3m_ago,
       pml_df.price_target_6m_ago,
       pml_df.price_target_ytd_ago,
       pml_df.price_target_1y_ago,
       pml_df.price_target_low_1w_ago,
       pml_df.price_target_low_mtd_ago,
       pml_df.price_target_low_1m_ago,
       pml_df.price_target_low_qtd_ago,
       pml_df.price_target_low_3m_ago,
       pml_df.price_target_low_6m_ago,
       pml_df.price_target_low_ytd_ago,
       pml_df.price_target_low_1y_ago,
       pml_df.price_target_high_1w_ago,
       pml_df.price_target_high_mtd_ago,
       pml_df.price_target_high_1m_ago,
       pml_df.price_target_high_qtd_ago,
       pml_df.price_target_high_3m_ago,
       pml_df.price_target_high_6m_ago,
       pml_df.price_target_high_ytd_ago,
       pml_df.price_target_high_1y_ago,
       pml_df.price_target_median_1w_ago,
       pml_df.price_target_median_mtd_ago,
       pml_df.price_target_median_1m_ago,
       pml_df.price_target_median_qtd_ago,
       pml_df.price_target_median_3m_ago,
       pml_df.price_target_median_6m_ago,
       pml_df.price_target_median_ytd_ago,
       pml_df.price_target_median_1y_ago,
       pml_df.price_target_num_1w_ago,
       pml_df.price_target_num_mtd_ago,
       pml_df.price_target_num_1m_ago,
       pml_df.price_target_num_qtd_ago,
       pml_df.price_target_num_3m_ago,
       pml_df.price_target_num_6m_ago,
       pml_df.price_target_num_ytd_ago,
       pml_df.price_target_num_1y_ago,
       pml_df.price_1d_ago,
       pml_df.price_5d_ago,
       pml_df.price_1w_ago,
       pml_df.price_mtd_ago,
       pml_df.price_1m_ago,
       pml_df.price_3m_ago,
       pml_df.price_6m_ago,
       pml_df.price_ytd_ago,
       pml_df.price_1y_ago,
       pml_df.price_3y_ago,
       pml_df.price_5y_ago,
       pml_df.price_qtd_ago,
       public.calc_change_ratio(pml_df.price_target::numeric,
                                pml_df.last_price::numeric)                                                                                                                                                                                          AS feat_implied_upside,
       pml_df.num_hold_ratings                                                                                                                                                                                                                       AS feat_holds,
       pml_df.num_strong_buys_ratings + pml_df.num_buys_ratings                                                                                                                                                                                      AS feat_buys,
       pml_df.num_strong_sell_ratings + pml_df.num_sell_ratings                                                                                                                                                                                      AS feat_sells,
       pml_df.num_no_opinion_ratings                                                                                                                                                                                                                 AS feat_no_opinion,
       safe_divide((pml_df.num_strong_buys_ratings + pml_df.num_buys_ratings)::numeric,
                   (pml_df.num_strong_buys_ratings + pml_df.num_buys_ratings + pml_df.num_hold_ratings +
                    pml_df.num_no_opinion_ratings + pml_df.num_sell_ratings +
                    pml_df.num_strong_sell_ratings)::numeric)                                                                                                                                                                                        AS feat_analyst_bullish_pct,
       safe_divide((pml_df.num_sell_ratings + pml_df.num_strong_sell_ratings)::numeric,
                   (pml_df.num_strong_buys_ratings + pml_df.num_buys_ratings + pml_df.num_hold_ratings +
                    pml_df.num_no_opinion_ratings + pml_df.num_sell_ratings +
                    pml_df.num_strong_sell_ratings)::numeric)                                                                                                                                                                                        AS feat_analyst_bearish_pct,
       safe_divide(pml_df.num_hold_ratings::numeric,
                   (pml_df.num_strong_buys_ratings + pml_df.num_buys_ratings + pml_df.num_hold_ratings +
                    pml_df.num_no_opinion_ratings + pml_df.num_sell_ratings +
                    pml_df.num_strong_sell_ratings)::numeric)                                                                                                                                                                                        AS feat_analyst_neutral_pct,
       abs(safe_divide((pml_df.num_strong_buys_ratings + pml_df.num_buys_ratings -
                        (pml_df.num_sell_ratings + pml_df.num_strong_sell_ratings))::numeric,
                       (pml_df.num_strong_buys_ratings + pml_df.num_buys_ratings + pml_df.num_hold_ratings +
                        pml_df.num_no_opinion_ratings + pml_df.num_sell_ratings +
                        pml_df.num_strong_sell_ratings)::numeric))                                                                                                                                                                                   AS feat_analyst_conviction,
       pml_df.analyst_rating                                                                                                                                                                                                                         AS feat_analyst_rating,
       CASE
	       WHEN pml_df.price_target_1y_ago > 0::double precision AND pml_df.last_price >= pml_df.price_target_1y_ago
		       THEN 1.0::double precision
	       WHEN pml_df.price_target_1y_ago > 0::double precision
		       THEN safe_divide(pml_df.last_price, pml_df.price_target_1y_ago)
	       ELSE NULL::double precision END                                                                                                                                                                                                           AS feat_pt_achievement_1y,
       safe_divide(abs(pml_df.last_price - pml_df.price_target_1y_ago),
                   abs(pml_df.price_target_1y_ago))                                                                                                                                                                                                  AS feat_pt_accuracy_1y,
       CASE
	       WHEN pml_df.last_price >= pml_df.price_target_low_1y_ago AND
	            pml_df.last_price <= pml_df.price_target_high_1y_ago THEN 1.0
	       ELSE 0.0 END                                                                                                                                                                                                                              AS feat_pt_range_hit_rate,
       winsorise(target_drift(
		                 ARRAY [pml_df.price_target::numeric, pml_df.price_target_1w_ago::numeric, pml_df.price_target_1m_ago::numeric, pml_df.price_target_3m_ago::numeric, pml_df.price_target_6m_ago::numeric, pml_df.price_target_1y_ago::numeric],
		                 2), '-1'::integer::numeric,
                 1::numeric)                                                                                                                                                                                                                         AS feat_pt_drift,
       target_drift_n(ARRAY [pml_df.price_target::numeric, pml_df.price_target_1w_ago::numeric, pml_df.price_target_1m_ago::numeric, pml_df.price_target_3m_ago::numeric, pml_df.price_target_6m_ago::numeric, pml_df.price_target_1y_ago::numeric]) AS feat_pt_drift_n,
       winsorise(target_drift(
		                 ARRAY [pml_df.last_price::numeric, pml_df.price_1w_ago::numeric, pml_df.price_1m_ago::numeric, pml_df.price_3m_ago::numeric, pml_df.price_6m_ago::numeric, pml_df.price_1y_ago::numeric],
		                 2), '-1'::integer::numeric,
                 1::numeric)                                                                                                                                                                                                                         AS feat_price_drift,
       target_drift_n(ARRAY [pml_df.last_price::numeric, pml_df.price_1w_ago::numeric, pml_df.price_1m_ago::numeric, pml_df.price_3m_ago::numeric, pml_df.price_6m_ago::numeric, pml_df.price_1y_ago::numeric])                                      AS feat_price_drift_n,
       winsorise(target_drift(
		                 ARRAY [pml_df.price_target_high::numeric, pml_df.price_target_high_1w_ago::numeric, pml_df.price_target_high_1m_ago::numeric, pml_df.price_target_high_3m_ago::numeric, pml_df.price_target_high_6m_ago::numeric, pml_df.price_target_high_1y_ago::numeric],
		                 2), '-1'::integer::numeric,
                 1::numeric)                                                                                                                                                                                                                         AS feat_pt_high_drift,
       winsorise(target_drift(
		                 ARRAY [pml_df.price_target_low::numeric, pml_df.price_target_low_1w_ago::numeric, pml_df.price_target_low_1m_ago::numeric, pml_df.price_target_low_3m_ago::numeric, pml_df.price_target_low_6m_ago::numeric, pml_df.price_target_low_1y_ago::numeric],
		                 2), '-1'::integer::numeric,
                 1::numeric)                                                                                                                                                                                                                         AS feat_pt_low_drift,
       winsorise(target_drift(
		                 ARRAY [pml_df.price_target_median::numeric, pml_df.price_target_median_1w_ago::numeric, pml_df.price_target_median_1m_ago::numeric, pml_df.price_target_median_3m_ago::numeric, pml_df.price_target_median_6m_ago::numeric, pml_df.price_target_median_1y_ago::numeric],
		                 2), '-1'::integer::numeric,
                 1::numeric)                                                                                                                                                                                                                         AS feat_pt_median_drift,
       winsorise(target_drift(
		                 ARRAY [pml_df.price_target_num::numeric, pml_df.price_target_num_1w_ago::numeric, pml_df.price_target_num_1m_ago::numeric, pml_df.price_target_num_3m_ago::numeric, pml_df.price_target_num_6m_ago::numeric, pml_df.price_target_num_1y_ago::numeric],
		                 2), '-1'::integer::numeric,
                 1::numeric)                                                                                                                                                                                                                         AS feat_coverage_drift,
       winsorise(target_drift(
		                 ARRAY [pml_df.price_target_stddev::numeric, pml_df.price_target_stddev_1w_ago::numeric, pml_df.price_target_stddev_1m_ago::numeric, pml_df.price_target_stddev_3m_ago::numeric, pml_df.price_target_stddev_6m_ago::numeric, pml_df.price_target_stddev_1y_ago::numeric],
		                 2), '-1'::integer::numeric,
                 1::numeric)                                                                                                                                                                                                                         AS feat_pt_noise_drift,
       pml_df.price_target_stddev                                                                                                                                                                                                                    AS feat_pt_noise_sigma,
       pml_df.price_target_stddev_1w_ago,
       pml_df.price_target_stddev_mtd_ago,
       pml_df.price_target_stddev_1m_ago,
       pml_df.price_target_stddev_qtd_ago,
       pml_df.price_target_stddev_3m_ago,
       pml_df.price_target_stddev_6m_ago,
       pml_df.price_target_stddev_ytd_ago,
       pml_df.price_target_stddev_1y_ago,
       safe_divide(pml_df.price_target_high - pml_df.price_target_low,
                   NULLIF(pml_df.price_target, 0::double precision))                                                                                                                                                                                 AS feat_pt_range_norm,
       pml_df.one_day_pct                                                                                                                                                                                                                            AS feat_one_day_return,
       pml_df.price_chg_pct_3m                                                                                                                                                                                                                       AS feat_price_chg_pct_3m,
       winsorise(target_drift(
		                 ARRAY [pml_df.volatility_1m::numeric, pml_df.volatility_3m::numeric, pml_df.volatility_6m::numeric, pml_df.volatility_1y::numeric],
		                 2), '-1'::integer::numeric,
                 1::numeric)                                                                                                                                                                                                                         AS feat_vol_drift,
       target_drift_n(ARRAY [pml_df.volatility_1m::numeric, pml_df.volatility_3m::numeric, pml_df.volatility_6m::numeric, pml_df.volatility_1y::numeric])                                                                                            AS feat_vol_drift_n,
       pml_df.beta_1y,
       pml_df.beta_2y,
       pml_df.beta_5y,
       (COALESCE(pml_df.beta_1y, 0::double precision) + COALESCE(pml_df.beta_2y, 0::double precision) +
        COALESCE(pml_df.beta_5y, 0::double precision)) / NULLIF(
		       (pml_df.beta_1y IS NOT NULL)::integer + (pml_df.beta_2y IS NOT NULL)::integer +
		       (pml_df.beta_5y IS NOT NULL)::integer,
		       0)::double precision                                                                                                                                                                                                                  AS feat_avg_beta,
       pml_df.total_return_ytd                                                                                                                                                                                                                       AS feat_total_return_ytd,
       pml_df.total_return_5y                                                                                                                                                                                                                        AS feat_total_return_5y,
       pml_df.total_return_10y                                                                                                                                                                                                                       AS feat_total_return_10y,
       pml_df.tot_return_pct_cagr_3y                                                                                                                                                                                                                 AS feat_tr_cagr_3y,
       pml_df.tot_return_pct_cagr_10y                                                                                                                                                                                                                AS feat_tr_cagr_10y,
       pml_df.tot_return_pct_cagr_5y                                                                                                                                                                                                                 AS feat_tr_cagr_5y,
       pml_df.tot_return_pct_cagr_1y                                                                                                                                                                                                                 AS feat_tr_cagr_1y,
       pml_df.total_return_1d                                                                                                                                                                                                                        AS feat_total_return_1d,
       pml_df.total_return_5d                                                                                                                                                                                                                        AS feat_total_return_5d,
       pml_df.total_return_1w                                                                                                                                                                                                                        AS feat_total_return_1w,
       pml_df.total_return_1m                                                                                                                                                                                                                        AS feat_total_return_1m,
       pml_df.total_return_3m                                                                                                                                                                                                                        AS feat_total_return_3m,
       pml_df.total_return_6m                                                                                                                                                                                                                        AS feat_total_return_6m,
       pml_df.total_return_1y                                                                                                                                                                                                                        AS feat_total_return_1y,
       pml_df.total_return_3y                                                                                                                                                                                                                        AS feat_total_return_3y,
       pml_df.total_return_mtd                                                                                                                                                                                                                       AS feat_total_return_mtd,
       pml_df.total_return_qtd                                                                                                                                                                                                                       AS feat_total_return_qtd,
       pml_df.total_return_2025                                                                                                                                                                                                                      AS feat_total_return_2025,
       pml_df.total_return_2024                                                                                                                                                                                                                      AS feat_total_return_2024,
       pml_df.total_return_2023                                                                                                                                                                                                                      AS feat_total_return_2023,
       pml_df.total_return_2022                                                                                                                                                                                                                      AS feat_total_return_2022,
       pml_df.total_return_2021                                                                                                                                                                                                                      AS feat_total_return_2021,
       calc_change_ratio(pml_df.market_cap, pml_df.market_cap_neg1fy)                                                                                                                                                                                AS feat_mcap_trend_1y,
       safe_divide(pml_df.market_cap, pml_df.market_cap_3yavg)                                                                                                                                                                                       AS feat_mcap_vs_3yavg,
       safe_divide((100 - pml_df.market_cap_country_r)::double precision,
                   100::double precision)                                                                                                                                                                                                            AS feat_mcap_country_r,
       safe_divide(pml_df.enterprise_value, pml_df.enterprise_value_3yavg)                                                                                                                                                                           AS feat_ev_vs_3yavg,
       safe_divide(pml_df.market_cap, pml_df.enterprise_value)                                                                                                                                                                                       AS market_cap_ev,
       safe_divide(pml_df.market_cap_neg1fq,
                   pml_df.enterprise_value_neg1fq)                                                                                                                                                                                                   AS market_cap_ev_neg1fq,
       safe_divide(pml_df.market_cap_neg2fq,
                   pml_df.enterprise_value_neg2fq)                                                                                                                                                                                                   AS market_cap_ev_neg2fq,
       safe_divide(pml_df.market_cap_neg3fq,
                   pml_df.enterprise_value_neg3fq)                                                                                                                                                                                                   AS market_cap_ev_neg3fq,
       safe_divide(pml_df.market_cap_neg4fq,
                   pml_df.enterprise_value_neg4fq)                                                                                                                                                                                                   AS market_cap_ev_neg4fq,
       safe_divide(pml_df.market_cap_neg1fy,
                   pml_df.enterprise_value_neg1fy)                                                                                                                                                                                                   AS market_cap_ev_neg1fy,
       safe_divide(pml_df.market_cap_neg2fy,
                   pml_df.enterprise_value_neg2fy)                                                                                                                                                                                                   AS market_cap_ev_neg2fy,
       safe_divide(pml_df.market_cap_neg3fy,
                   pml_df.enterprise_value_neg3fy)                                                                                                                                                                                                   AS market_cap_ev_neg3fy,
       safe_divide(pml_df.market_cap_neg4fy,
                   pml_df.enterprise_value_neg4fy)                                                                                                                                                                                                   AS market_cap_ev_neg4fy,
       safe_divide(pml_df.market_cap_3yavg, pml_df.enterprise_value_3yavg)                                                                                                                                                                           AS market_cap_ev_3yavg,
       safe_divide(pml_df.market_cap_5yavg, pml_df.enterprise_value_5yavg)                                                                                                                                                                           AS market_cap_ev_5yavg,
       winsorise(target_drift(ARRAY [safe_divide(pml_df.market_cap, pml_df.enterprise_value), safe_divide(
		       pml_df.market_cap_neg1fy, pml_df.enterprise_value_neg1fy), safe_divide(pml_df.market_cap_neg2fy,
                                                                                      pml_df.enterprise_value_neg2fy), safe_divide(
		       pml_df.market_cap_neg3fy, pml_df.enterprise_value_neg3fy), safe_divide(pml_df.market_cap_neg4fy,
                                                                                      pml_df.enterprise_value_neg4fy)],
                              2), '-1'::integer::double precision,
                 1::double precision)                                                                                                                                                                                                                AS feat_mv_ev_drift,
       pio.feat_piotroski_f_score_fy,
       pio.feat_piotroski_f_score_neg1fy,
       pio.feat_piotroski_f_score_neg2fy,
       pio.feat_piotroski_f_score_neg3fy,
       ((pio.feat_piotroski_f_score_fy + pio.feat_piotroski_f_score_neg1fy + pio.feat_piotroski_f_score_neg2fy +
         pio.feat_piotroski_f_score_neg3fy -
         GREATEST(pio.feat_piotroski_f_score_fy, pio.feat_piotroski_f_score_neg1fy, pio.feat_piotroski_f_score_neg2fy,
                  pio.feat_piotroski_f_score_neg3fy) -
         LEAST(pio.feat_piotroski_f_score_fy, pio.feat_piotroski_f_score_neg1fy, pio.feat_piotroski_f_score_neg2fy,
               pio.feat_piotroski_f_score_neg3fy))::numeric /
        2.0)::double precision                                                                                                                                                                                                                       AS feat_median_piotroski_f_score
FROM pml_df
	     CROSS JOIN LATERAL ( SELECT piotroski_f_score(pml_df.return_on_assets_roa_pct_fy,
	                                                   pml_df.return_on_assets_roa_pct_neg1fy, pml_df.cfo_fy,
	                                                   pml_df.net_income_fy, pml_df.long_term_debt_equity_fy,
	                                                   pml_df.long_term_debt_equity_neg1fy, pml_df.current_ratio_fy,
	                                                   pml_df.current_ratio_neg1fy, pml_df.shrs_out,
	                                                   pml_df.shrs_out_neg1fy, pml_df.gross_profit_margin_pct_fy,
	                                                   pml_df.gross_profit_margin_pct_neg1fy, pml_df.asset_turnover_fy,
	                                                   pml_df.asset_turnover_neg1fy)                               AS feat_piotroski_f_score_fy,
	                                 piotroski_f_score(pml_df.return_on_assets_roa_pct_neg1fy,
	                                                   pml_df.return_on_assets_roa_pct_neg2fy, pml_df.cfo_neg1fy,
	                                                   pml_df.net_income_neg1fy, pml_df.long_term_debt_equity_neg1fy,
	                                                   pml_df.long_term_debt_equity_neg2fy, pml_df.current_ratio_neg1fy,
	                                                   pml_df.current_ratio_neg2fy, pml_df.shrs_out_neg1fy,
	                                                   pml_df.shrs_out_neg2fy, pml_df.gross_profit_margin_pct_neg1fy,
	                                                   pml_df.gross_profit_margin_pct_neg2fy,
	                                                   pml_df.asset_turnover_neg1fy,
	                                                   pml_df.asset_turnover_neg2fy)                               AS feat_piotroski_f_score_neg1fy,
	                                 piotroski_f_score(pml_df.return_on_assets_roa_pct_neg2fy,
	                                                   pml_df.return_on_assets_roa_pct_neg3fy, pml_df.cfo_neg2fy,
	                                                   pml_df.net_income_neg2fy, pml_df.long_term_debt_equity_neg2fy,
	                                                   pml_df.long_term_debt_equity_neg3fy, pml_df.current_ratio_neg2fy,
	                                                   pml_df.current_ratio_neg3fy, pml_df.shrs_out_neg2fy,
	                                                   pml_df.shrs_out_neg3fy, pml_df.gross_profit_margin_pct_neg2fy,
	                                                   pml_df.gross_profit_margin_pct_neg3fy,
	                                                   pml_df.asset_turnover_neg2fy,
	                                                   pml_df.asset_turnover_neg3fy)                               AS feat_piotroski_f_score_neg2fy,
	                                 piotroski_f_score(pml_df.return_on_assets_roa_pct_neg3fy,
	                                                   pml_df.return_on_assets_roa_pct_neg4fy, pml_df.cfo_neg3fy,
	                                                   pml_df.net_income_neg3fy, pml_df.long_term_debt_equity_neg3fy,
	                                                   pml_df.long_term_debt_equity_neg4fy, pml_df.current_ratio_neg3fy,
	                                                   pml_df.current_ratio_neg4fy, pml_df.shrs_out_neg3fy,
	                                                   pml_df.shrs_out_neg4fy, pml_df.gross_profit_margin_pct_neg3fy,
	                                                   pml_df.gross_profit_margin_pct_neg4fy,
	                                                   pml_df.asset_turnover_neg3fy,
	                                                   pml_df.asset_turnover_neg4fy)                               AS feat_piotroski_f_score_neg3fy) pio;

ALTER MATERIALIZED VIEW pml.mv_pymc_kalman_pt OWNER TO postgres;

CREATE UNIQUE INDEX idx_mv_pymc_kalman_pt_isin ON pml.mv_pymc_kalman_pt (isin);