create materialized view mv_pymc_earnings_beat as
WITH beats AS (SELECT pml_df.isin,
                      pml_df.ticker,
                      pml_df.trading_region,
                      pml_df.region,
                      pml_df.country,
                      pml_df.trading_country,
                      pml_df.exchange,
                      pml_df.unit,
                      pml_df.style_class,
                      pml_df.size_class,
                      pml_df.sector,
                      pml_df.industry,
                      ARRAY [pml_df.eps_neg0fqsurprise_pct, pml_df.eps_neg1fqsurprise_pct, pml_df.eps_neg2fqsurprise_pct, pml_df.eps_neg3fqsurprise_pct, pml_df.eps_neg4fqsurprise_pct]                                                  AS eps_surprises_q,
                      ARRAY [pml_df.eps_neg0fysurprise_pct, pml_df.eps_neg1fysurprise_pct, pml_df.eps_neg2fysurprise_pct, pml_df.eps_neg3fysurprise_pct, pml_df.eps_neg4fysurprise_pct]                                                  AS eps_surprises_y,
                      ARRAY [pml_df.ebit_neg0fqsurprise_pct, pml_df.ebit_neg1fqsurprise_pct, pml_df.ebit_neg2fqsurprise_pct, pml_df.ebit_neg3fqsurprise_pct, pml_df.ebit_neg4fqsurprise_pct]                                             AS ebit_surprises_q,
                      ARRAY [pml_df.ebit_neg0fysurprise_pct, pml_df.ebit_neg1fysurprise_pct, pml_df.ebit_neg2fysurprise_pct, pml_df.ebit_neg3fysurprise_pct, pml_df.ebit_neg4fysurprise_pct, pml_df.ebit_neg5fysurprise_pct]             AS ebit_surprises_y,
                      ARRAY [pml_df.ebitda_neg0fqsurprise_pct, pml_df.ebitda_neg1fqsurprise_pct, pml_df.ebitda_neg2fqsurprise_pct, pml_df.ebitda_neg3fqsurprise_pct, pml_df.ebitda_neg4fqsurprise_pct]                                   AS ebitda_surprises_q,
                      ARRAY [pml_df.ebitda_neg0fysurprise_pct, pml_df.ebitda_neg1fysurprise_pct, pml_df.ebitda_neg2fysurprise_pct, pml_df.ebitda_neg3fysurprise_pct, pml_df.ebitda_neg4fysurprise_pct, pml_df.ebitda_neg5fysurprise_pct] AS ebitda_surprises_y,
                      ARRAY [pml_df.sales_neg0fqsurprise_pct, pml_df.sales_neg1fqsurprise_pct, pml_df.sales_neg2fqsurprise_pct, pml_df.sales_neg3fqsurprise_pct, pml_df.sales_neg4fqsurprise_pct]                                        AS sales_surprises_q,
                      ARRAY [pml_df.sales_neg0fysurprise_pct, pml_df.sales_neg1fysurprise_pct, pml_df.sales_neg2fysurprise_pct, pml_df.sales_neg3fysurprise_pct, pml_df.sales_neg4fysurprise_pct, pml_df.sales_neg5fysurprise_pct]       AS sales_surprises_y,
                      pml_df.eps_norm_est_avg_fy1e,
                      pml_df.eps_norm_est_avg_fq1e,
                      pml_df.eps_norm_est_num_fy1e,
                      pml_df.eps_est_avg_rev_pct_fy1e_1w,
                      pml_df.eps_est_avg_rev_pct_fy1e_1m,
                      pml_df.eps_est_avg_rev_pct_fy1e_3m,
                      pml_df.eps_est_avg_rev_pct_fy1e_6m,
                      pml_df.eps_est_avg_rev_pct_fy1e_1y,
                      pml_df.eps_gaap_est_avg_rev_pct_fy1e_1m,
                      pml_df.eps_gaap_est_avg_rev_pct_fy1e_3m,
                      pml_df.eps_gaap_est_avg_rev_pct_fy1e_6m,
                      pml_df.eps_neg0fqsurprise_pct,
                      pml_df.eps_neg0fysurprise_pct,
                      pml_df.ebit_neg0fqsurprise_pct,
                      pml_df.ebit_neg0fysurprise_pct,
                      pml_df.ebitda_neg0fqsurprise_pct,
                      pml_df.ebitda_neg0fysurprise_pct,
                      pml_df.sales_neg0fqsurprise_pct,
                      pml_df.sales_neg0fysurprise_pct,
                      pml_df.days_to_earnings,
                      pml_df.earnings_report_recency,
                      pml_df.next_earnings_status,
                      pml_df.market_cap,
                      pml_df.market_cap_neg1fy,
                      pml_df.market_cap_3yavg,
                      pml_df.enterprise_value,
                      pml_df.enterprise_value_3yavg
               FROM pml_df)
SELECT b.isin,
       b.ticker,
       b.trading_region,
       b.region,
       b.country,
       b.trading_country,
       b.exchange,
       b.unit,
       b.style_class,
       b.size_class,
       b.sector,
       b.industry,
       bc_q.n_total,
       bc_q.n_beats,
       bc_y.n_total                                                                        AS n_total_annual,
       bc_y.n_beats                                                                        AS n_beats_annual,
       safe_logit(safe_divide(bc_q.n_beats::numeric, bc_q.n_total::numeric))               AS feat_logit_beat_rate,
       safe_logit(safe_divide(bc_y.n_beats::numeric, bc_y.n_total::numeric))               AS feat_logit_beat_rate_annual,
       bc_ebit_q.n_total                                                                   AS n_ebit_total,
       bc_ebit_q.n_beats                                                                   AS n_ebit_beats,
       bc_ebit_y.n_total                                                                   AS n_ebit_total_annual,
       bc_ebit_y.n_beats                                                                   AS n_ebit_beats_annual,
       safe_logit(safe_divide(bc_ebit_q.n_beats::numeric, bc_ebit_q.n_total::numeric))     AS feat_ebit_logit_beat_rate,
       safe_logit(safe_divide(bc_ebit_y.n_beats::numeric,
                              bc_ebit_y.n_total::numeric))                                 AS feat_ebit_logit_beat_rate_annual,
       bc_ebitda_q.n_total                                                                 AS n_ebitda_total,
       bc_ebitda_q.n_beats                                                                 AS n_ebitda_beats,
       bc_ebitda_y.n_total                                                                 AS n_ebitda_total_annual,
       bc_ebitda_y.n_beats                                                                 AS n_ebitda_beats_annual,
       safe_logit(safe_divide(bc_ebitda_q.n_beats::numeric,
                              bc_ebitda_q.n_total::numeric))                               AS feat_ebitda_logit_beat_rate,
       safe_logit(safe_divide(bc_ebitda_y.n_beats::numeric,
                              bc_ebitda_y.n_total::numeric))                               AS feat_ebitda_logit_beat_rate_annual,
       bc_sales_q.n_total                                                                  AS n_sales_total,
       bc_sales_q.n_beats                                                                  AS n_sales_beats,
       bc_sales_y.n_total                                                                  AS n_sales_total_annual,
       bc_sales_y.n_beats                                                                  AS n_sales_beats_annual,
       safe_logit(safe_divide(bc_sales_q.n_beats::numeric,
                              bc_sales_q.n_total::numeric))                                AS feat_sales_logit_beat_rate,
       safe_logit(safe_divide(bc_sales_y.n_beats::numeric,
                              bc_sales_y.n_total::numeric))                                AS feat_sales_logit_beat_rate_annual,
       b.eps_norm_est_avg_fy1e                                                             AS feat_eps_fy1e,
       b.eps_norm_est_avg_fq1e                                                             AS feat_eps_fq1e,
       b.eps_norm_est_num_fy1e                                                             AS n_eps_estimates,
       b.eps_est_avg_rev_pct_fy1e_1w                                                       AS feat_rev_1w,
       b.eps_est_avg_rev_pct_fy1e_1m                                                       AS feat_rev_1m,
       b.eps_est_avg_rev_pct_fy1e_3m                                                       AS feat_rev_3m,
       b.eps_est_avg_rev_pct_fy1e_6m                                                       AS feat_rev_6m,
       b.eps_est_avg_rev_pct_fy1e_1y                                                       AS feat_rev_1y,
       b.eps_est_avg_rev_pct_fy1e_1m - b.eps_est_avg_rev_pct_fy1e_6m                       AS feat_rev_accel_1m_6m,
       b.eps_est_avg_rev_pct_fy1e_3m - b.eps_gaap_est_avg_rev_pct_fy1e_3m                  AS feat_rev_gaap_gap_3m,
       b.eps_neg0fqsurprise_pct                                                            AS feat_last_q_surprise,
       b.eps_neg0fysurprise_pct                                                            AS feat_last_y_surprise,
       b.ebit_neg0fqsurprise_pct                                                           AS feat_ebit_last_q_surprise,
       b.ebit_neg0fysurprise_pct                                                           AS feat_ebit_last_y_surprise,
       b.ebitda_neg0fqsurprise_pct                                                         AS feat_ebitda_last_q_surprise,
       b.ebitda_neg0fysurprise_pct                                                         AS feat_ebitda_last_y_surprise,
       b.sales_neg0fqsurprise_pct                                                          AS feat_sales_last_q_surprise,
       b.sales_neg0fysurprise_pct                                                          AS feat_sales_last_y_surprise,
       b.days_to_earnings                                                                  AS feat_days_to_earnings,
       b.earnings_report_recency                                                           AS feat_report_recency,
       b.next_earnings_status                                                              AS feat_next_earnings_status,
       calc_change_ratio(b.market_cap, b.market_cap_neg1fy)                                AS feat_mcap_trend_1y,
       safe_divide(b.market_cap, b.market_cap_3yavg)                                       AS feat_mcap_vs_3yavg,
       safe_divide(b.enterprise_value, b.enterprise_value_3yavg)                           AS feat_ev_vs_3yavg
FROM beats                                                b,
     LATERAL beat_counts(b.eps_surprises_q::numeric[])    bc_q(n_total, n_beats),
     LATERAL beat_counts(b.eps_surprises_y::numeric[])    bc_y(n_total, n_beats),
     LATERAL beat_counts(b.ebit_surprises_q::numeric[])   bc_ebit_q(n_total, n_beats),
     LATERAL beat_counts(b.ebit_surprises_y::numeric[])   bc_ebit_y(n_total, n_beats),
     LATERAL beat_counts(b.ebitda_surprises_q::numeric[]) bc_ebitda_q(n_total, n_beats),
     LATERAL beat_counts(b.ebitda_surprises_y::numeric[]) bc_ebitda_y(n_total, n_beats),
     LATERAL beat_counts(b.sales_surprises_q::numeric[])  bc_sales_q(n_total, n_beats),
     LATERAL beat_counts(b.sales_surprises_y::numeric[])  bc_sales_y(n_total, n_beats)
;

alter materialized view mv_pymc_earnings_beat owner to postgres
;

create unique index idx_mv_pymc_earnings_beat_isin
	on mv_pymc_earnings_beat (isin)
;