CREATE MATERIALIZED VIEW mv_pymc_kalman_pt AS
SELECT isin,
       ticker,
       name,
       region,
       country,
       trading_country,
       exchange,
       unit,
       style_class,
       size_class,
       sector,
       industry,
       income_statement_report_date,
       next_earnings,
       fy_end_date,
       next_income_statement_report_date,
       next_fy_end_date,
       expected_report_date,
       next_earnings - CURRENT_DATE                                                                                                                                                                                                                AS days_to_next_earnings,
       CURRENT_DATE - income_statement_report_date                                                                                                                                                                                                 AS days_since_last_report,
       next_fy_end_date - CURRENT_DATE                                                                                                                                                                                                             AS days_to_next_fy_end,
       next_income_statement_report_date - CURRENT_DATE                                                                                                                                                                                            AS days_to_next_report,
       expected_report_date - CURRENT_DATE                                                                                                                                                                                                         AS days_to_expected_report,
       fy_end_date - CURRENT_DATE                                                                                                                                                                                                                  AS days_to_fy_end,
       price_target                                                                                                                                                                                                                                AS observed_pt,
       last_price,
       price_target_median,
       price_target_high,
       price_target_low,
       price_target_num                                                                                                                                                                                                                            AS n_analysts,
       price_target_1w_ago,
       price_target_mtd_ago,
       price_target_1m_ago,
       price_target_qtd_ago,
       price_target_3m_ago,
       price_target_6m_ago,
       price_target_ytd_ago,
       price_target_1y_ago,
       price_target_low_1w_ago,
       price_target_low_mtd_ago,
       price_target_low_1m_ago,
       price_target_low_qtd_ago,
       price_target_low_3m_ago,
       price_target_low_6m_ago,
       price_target_low_ytd_ago,
       price_target_low_1y_ago,
       price_target_high_1w_ago,
       price_target_high_mtd_ago,
       price_target_high_1m_ago,
       price_target_high_qtd_ago,
       price_target_high_3m_ago,
       price_target_high_6m_ago,
       price_target_high_ytd_ago,
       price_target_high_1y_ago,
       price_target_median_1w_ago,
       price_target_median_mtd_ago,
       price_target_median_1m_ago,
       price_target_median_qtd_ago,
       price_target_median_3m_ago,
       price_target_median_6m_ago,
       price_target_median_ytd_ago,
       price_target_median_1y_ago,
       price_target_num_1w_ago,
       price_target_num_mtd_ago,
       price_target_num_1m_ago,
       price_target_num_qtd_ago,
       price_target_num_3m_ago,
       price_target_num_ytd_ago,
       price_target_num_1y_ago,
       calc_change_ratio(price_target::numeric, last_price::numeric)                                                                                                                                                                               AS feat_implied_upside,
       target_drift(ARRAY [price_target::numeric, price_target_1w_ago::numeric, price_target_1m_ago::numeric, price_target_3m_ago::numeric, price_target_6m_ago::numeric, price_target_1y_ago::numeric])                                           AS feat_pt_drift,
       target_drift(ARRAY [last_price::numeric, price_1w_ago::numeric, price_1m_ago::numeric, price_3m_ago::numeric, price_6m_ago::numeric, price_1y_ago::numeric])                                                                                AS feat_price_drift,
       target_drift(ARRAY [price_target_high::numeric, price_target_high_1w_ago::numeric, price_target_high_1m_ago::numeric, price_target_high_3m_ago::numeric, price_target_high_6m_ago::numeric, price_target_high_1y_ago::numeric])             AS feat_pt_high_drift,
       target_drift(ARRAY [price_target_low::numeric, price_target_low_1w_ago::numeric, price_target_low_1m_ago::numeric, price_target_low_3m_ago::numeric, price_target_low_6m_ago::numeric, price_target_low_1y_ago::numeric])                   AS feat_pt_low_drift,
       target_drift(ARRAY [price_target_median::numeric, price_target_median_1w_ago::numeric, price_target_median_1m_ago::numeric, price_target_median_3m_ago::numeric, price_target_median_6m_ago::numeric, price_target_median_1y_ago::numeric]) AS feat_pt_median_drift,
       target_drift(ARRAY [price_target_num::numeric, price_target_num_1w_ago::numeric, price_target_num_1m_ago::numeric, price_target_num_3m_ago::numeric, price_target_num_6m_ago::numeric, price_target_num_1y_ago::numeric])                   AS feat_coverage_drift,
       target_drift(ARRAY [price_target_stddev::numeric, price_target_stddev_1w_ago::numeric, price_target_stddev_1m_ago::numeric, price_target_stddev_3m_ago::numeric, price_target_stddev_6m_ago::numeric, price_target_stddev_1y_ago::numeric]) AS feat_pt_noise_drift,
       price_target_stddev                                                                                                                                                                                                                         AS feat_pt_noise_sigma,
       safe_divide(price_target_high - price_target_low,
                   NULLIF(price_target, 0::double precision))                                                                                                                                                                                      AS feat_pt_range_norm,
       volatility_1m                                                                                                                                                                                                                               AS feat_vol_1m,
       volatility_3m                                                                                                                                                                                                                               AS feat_vol_3m,
       volatility_6m                                                                                                                                                                                                                               AS feat_vol_6m,
       volatility_1y                                                                                                                                                                                                                               AS feat_vol_1y,
       total_return_ytd                                                                                                                                                                                                                            AS feat_total_return_ytd
FROM pml_df;

ALTER MATERIALIZED VIEW mv_pymc_kalman_pt OWNER TO postgres;

CREATE UNIQUE INDEX idx_mv_pymc_kalman_pt_isin ON mv_pymc_kalman_pt (isin);