CREATE MATERIALIZED VIEW mv_pymc_earnings_beat AS
WITH beats AS (SELECT pml_df.isin,
                      pml_df.ticker,
                      pml_df.region,
                      pml_df.country,
                      pml_df.trading_country,
                      pml_df.exchange,
                      pml_df.unit,
                      pml_df.style_class,
                      pml_df.size_class,
                      pml_df.sector,
                      pml_df.industry,
                      ARRAY [pml_df.eps_neg0fqsurprise_pct, pml_df.eps_neg1fqsurprise_pct, pml_df.eps_neg2fqsurprise_pct, pml_df.eps_neg3fqsurprise_pct, pml_df.eps_neg4fqsurprise_pct] AS eps_surprises_q,
                      ARRAY [pml_df.eps_neg0fysurprise_pct, pml_df.eps_neg1fysurprise_pct, pml_df.eps_neg2fysurprise_pct, pml_df.eps_neg3fysurprise_pct, pml_df.eps_neg4fysurprise_pct] AS eps_surprises_y,
                      pml_df.eps_norm_est_avg_fy1e,
                      pml_df.eps_norm_est_avg_fq1e,
                      pml_df.eps_norm_est_num_fy1e,
                      pml_df.eps_est_avg_rev_pct_fy1e_1w,
                      pml_df.eps_est_avg_rev_pct_fy1e_1m,
                      pml_df.eps_est_avg_rev_pct_fy1e_3m,
                      pml_df.eps_est_avg_rev_pct_fy1e_6m,
                      pml_df.eps_est_avg_rev_pct_fy1e_1y,
                      pml_df.eps_gaap_est_avg_rev_pct_fy1e_1m,
                      pml_df.eps_gaap_est_avg_rev_pct_fy1e_3m,
                      pml_df.eps_gaap_est_avg_rev_pct_fy1e_6m,
                      pml_df.eps_neg0fqsurprise_pct,
                      pml_df.eps_neg0fysurprise_pct,
                      pml_df.days_to_earnings,
                      pml_df.earnings_report_recency,
                      pml_df.next_earnings_status
               FROM pml_df
              )
SELECT b.isin,
       b.ticker,
       b.region,
       b.country,
       b.trading_country,
       b.exchange,
       b.unit,
       b.style_class,
       b.size_class,
       b.sector,
       b.industry,
       bc_q.n_total,
       bc_q.n_beats,
       bc_y.n_total                                                          AS n_total_annual,
       bc_y.n_beats                                                          AS n_beats_annual,
       safe_logit(safe_divide(bc_q.n_beats::numeric, bc_q.n_total::numeric)) AS feat_logit_beat_rate,
       safe_logit(safe_divide(bc_y.n_beats::numeric, bc_y.n_total::numeric)) AS feat_logit_beat_rate_annual,
       b.eps_norm_est_avg_fy1e                                               AS feat_eps_fy1e,
       b.eps_norm_est_avg_fq1e                                               AS feat_eps_fq1e,
       b.eps_norm_est_num_fy1e                                               AS n_eps_estimates,
       b.eps_est_avg_rev_pct_fy1e_1w                                         AS feat_rev_1w,
       b.eps_est_avg_rev_pct_fy1e_1m                                         AS feat_rev_1m,
       b.eps_est_avg_rev_pct_fy1e_3m                                         AS feat_rev_3m,
       b.eps_est_avg_rev_pct_fy1e_6m                                         AS feat_rev_6m,
       b.eps_est_avg_rev_pct_fy1e_1y                                         AS feat_rev_1y,
       b.eps_est_avg_rev_pct_fy1e_1m - b.eps_est_avg_rev_pct_fy1e_6m         AS feat_rev_accel_1m_6m,
       b.eps_est_avg_rev_pct_fy1e_3m - b.eps_gaap_est_avg_rev_pct_fy1e_3m    AS feat_rev_gaap_gap_3m,
       b.eps_neg0fqsurprise_pct                                              AS feat_last_q_surprise,
       b.eps_neg0fysurprise_pct                                              AS feat_last_y_surprise,
       b.days_to_earnings                                                    AS feat_days_to_earnings,
       b.earnings_report_recency                                             AS feat_report_recency,
       b.next_earnings_status                                                AS feat_next_earnings_status
FROM beats                                             b,
     LATERAL beat_counts(b.eps_surprises_q::numeric[]) bc_q(n_total, n_beats),
     LATERAL beat_counts(b.eps_surprises_y::numeric[]) bc_y(n_total, n_beats);

ALTER MATERIALIZED VIEW mv_pymc_earnings_beat OWNER TO postgres;

CREATE UNIQUE INDEX idx_mv_pymc_earnings_beat_isin ON mv_pymc_earnings_beat (isin);