create table pml_df
(
    "Ticker"                              text,
    "ISIN"                                text,
    "Name"                                text,
    "Description"                         text,
    "Region"                              text,
    "Country"                             text,
    "Trading Country"                     text,
    "Exchange"                            text,
    "Unit"                                text,
    "Sector"                              text,
    "Industry"                            text,
    "Style Class"                         text,
    "Size Class"                          text,
    "Last Updated"                        date,
    "Income Statement Report Date"        date,
    "FY End"                              text,
    "Next Earnings"                       date,
    "Next Earnings (When)"                text,
    "Next Earnings (Status)"              text,
    "Dividend Record (Currency)"          text,
    "Dividend Record (Amount)"            double precision,
    "Dividend Record (Frequency)"         text,
    "Dividend Streak"                     double precision,
    "Dividend Record (Announce Date)"     date,
    "Dividend Record (Payable Date)"      date,
    "Dividend Record (Record Date)"       date,
    "Dividend Record (Ex Date)"           date,
    "Market Cap"                          double precision,
    "Enterprise Value"                    double precision,
    "Last Price"                          double precision,
    "Price Target (YTD Ago)"              double precision,
    "Total Return (YTD)"                  double precision,
    "Price Target"                        double precision,
    "Price Target - Low"                  double precision,
    "Price Target - Median"               double precision,
    "Price Target - High"                 double precision,
    "Price Target - #"                    double precision,
    "P/E (NTM)"                           double precision,
    "P/E (LTM)"                           double precision,
    "Altman Z-Score (FY)"                 double precision,
    "Altman Z-Score (FQ)"                 double precision,
    "Altman Z-Score (LTM)"                double precision,
    "Beta (1Y)"                           double precision,
    "Beta (2Y)"                           double precision,
    "Beta (5Y)"                           double precision,
    "Analyst Rating"                      double precision,
    "# Strong Sell Ratings"               integer,
    "# Strong Buys Ratings"               integer,
    "# Hold Ratings"                      integer,
    "# Buys Ratings"                      integer,
    "# Sell Ratings"                      integer,
    "# No Opinion Ratings"                integer,
    "Market Cap (Country R)"              integer,
    "Tot. Return %/CAGR (3Y)"             double precision,
    "Tot. Return %/CAGR (10Y)"            double precision,
    "Total Return (5Y)"                   double precision,
    "Total Return (10Y)"                  double precision,
    "Volume (Shrs)"                       double precision,
    "Dividend Per Share (LTM)"            double precision,
    "Div Yield (Ind)"                     double precision,
    "Div Yield (LTM)"                     double precision,
    "Gross Profit Margin % (FY)"          double precision,
    "Gross Profit Margin % (LTM)"         double precision,
    "EPS Norm - Est Avg (NTM)"            double precision,
    "EPS/Adj. (-1FY)"                     double precision,
    "EPS/Adj. (FY)"                       double precision,
    "EPS/Adj. (LTM)"                      double precision,
    "EPS Norm - Est Avg (FY1E)"           double precision,
    "Buyback Yield (LTM)"                 double precision,
    "Return on Assets (ROA) % (LTM)"      double precision,
    "Return on Assets (ROA) % (FY)"       double precision,
    "Div Yield (-1FYInd)"                 double precision,
    "P/B (LTM)"                           double precision,
    "P/B (-1FY)"                          double precision,
    "P/B (5YAVG)"                         double precision,
    "Div Yield (TTM)"                     double precision,
    "Div Yield (NTM)"                     double precision,
    "Div Yield (5YAVGLTM)"                double precision,
    "Price Chg. % (3M)"                   double precision,
    "1-Day %"                             double precision,
    "Price (5D Ago)"                      double precision,
    "Price (1W Ago)"                      double precision,
    "Price (1M Ago)"                      double precision,
    "Price (3M Ago)"                      double precision,
    "Price (6M Ago)"                      double precision,
    "Price (1Y Ago)"                      double precision,
    "Price (3Y Ago)"                      double precision,
    "Price (5Y Ago)"                      double precision,
    "Price (QTD Ago)"                     double precision,
    "Rel. Volume"                         double precision,
    "Shrs Out"                            double precision,
    "Shrs Out (-1FY)"                     double precision,
    "Common Dividends Paid (LTM)"         double precision,
    "Common Dividends Paid (FY)"          double precision,
    "EV/Sales (LTM)"                      double precision,
    "EV/Sales (NTM)"                      double precision,
    "EV/Sales (-1FYLTM)"                  double precision,
    "EV/Sales (-2FYLTM)"                  double precision,
    "EV/Sales (-3FYLTM)"                  double precision,
    "EV/Sales (3YAVGLTM)"                 double precision,
    "EV/Sales (-1FQLTM)"                  double precision,
    "EV/Sales (-2FQLTM)"                  double precision,
    "EV/Sales (-3FQLTM)"                  double precision,
    "EV/Sales (-4FQLTM)"                  double precision,
    "52W High/Adj"                        double precision,
    "52W Low/Adj"                         double precision,
    "EMA (20D)"                           double precision,
    "EMA (50D)"                           double precision,
    "EMA (100D)"                          double precision,
    "EMA (250D)"                          double precision,
    "EV/EBITDA (LTM)"                     double precision,
    "EV/EBITDA (NTM)"                     double precision,
    "EV/EBITDA (-1FYLTM)"                 double precision,
    "EV/EBITDA (-1FQLTM)"                 double precision,
    "EV/EBITDA (3YAVGLTM)"                double precision,
    "EV/EBITDA (EST FY1)"                 double precision,
    "P/E (EST FY1)"                       double precision,
    "P/E (-1FYLTM)"                       double precision,
    "P/E (-2FYLTM)"                       double precision,
    "P/E (-3FYLTM)"                       double precision,
    "P/E (3YAVGLTM)"                      double precision,
    "P/E (-1FQLTM)"                       double precision,
    "P/E (-2FQLTM)"                       double precision,
    "P/E (-3FQLTM)"                       double precision,
    "P/E (5YAVGLTM)"                      double precision,
    "P/E (-0FQQoQLTM)"                    double precision,
    "P/E (-0FYYoYLTM)"                    double precision,
    "P/E (-1FYYoYLTM)"                    double precision,
    "P/E (-0FQYoYLTM)"                    double precision,
    "Full Time Employees (FQ)"            double precision,
    "Full Time Employees (FY)"            double precision,
    "Full Time Employees (-1FY)"          double precision,
    "Full Time Employees (-2FY)"          double precision,
    "Full Time Employees (-3FY)"          double precision,
    "Avg Employees (5YAVGFY)"             double precision,
    "Net EPS - Basic (LTM)"               double precision,
    "Net EPS - Basic (FQ)"                double precision,
    "Net EPS - Basic (FY)"                double precision,
    "Net EPS - Basic (-1FQFQ)"            double precision,
    "Net EPS - Basic (-2FQFQ)"            double precision,
    "Net EPS - Basic (-3FQFQ)"            double precision,
    "Net EPS - Basic (-4FQFQ)"            double precision,
    "Net EPS - Basic (-1FY)"              double precision,
    "Net EPS - Basic (-2FY)"              double precision,
    "Net EPS - Basic (-3FY)"              double precision,
    "Net EPS - Basic (-4FY)"              double precision,
    "Net EPS - Basic (-5FY)"              double precision,
    "EPS Est Avg Rev % (FY1E - 1W)"       double precision,
    "EPS Est Avg Rev % (FY1E - 1M)"       double precision,
    "EPS Est Avg Rev % (FY1E - 3M)"       double precision,
    "EPS Est Avg Rev % (FY1E - 6M)"       double precision,
    "EPS Est Avg Rev % (FY1E - 1Y)"       double precision,
    "Div Yield (-2FYInd)"                 double precision,
    "Div Yield (-3FYInd)"                 double precision,
    "Div Yield (-4FYInd)"                 double precision,
    "Div Yield (-5FYInd)"                 double precision,
    "EBITDA - Est Avg (NTM)"              double precision,
    "EBITDA - Est Avg (FY1E)"             double precision,
    "EPS GAAP - Est Avg (NTM)"            double precision,
    "EPS GAAP - Est Avg (FY1E)"           double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 1M)"  double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 3M)"  double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 6M)"  double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 1Y)"  double precision,
    "EPS Norm - Est # (FY1E)"             double precision,
    "Price Target (1W Ago)"               double precision,
    "Price Target (1M Ago)"               double precision,
    "Price Target (3M Ago)"               double precision,
    "Price Target (6M Ago)"               double precision,
    "Price Target (MTD Ago)"              double precision,
    "Price Target (QTD Ago)"              double precision,
    "Price Target (1Y Ago)"               double precision,
    "Price Target - # (3M Ago)"           double precision,
    "Price Target - # (6M Ago)"           double precision,
    "Price Target - # (YTD Ago)"          double precision,
    "Price Target - # (1Y Ago)"           double precision,
    "Price Target - # (1W Ago)"           double precision,
    "Price Target - # (1M Ago)"           double precision,
    "Price Target - # (MTD Ago)"          double precision,
    "Price Target - # (QTD Ago)"          double precision,
    "Price Target - High (1W Ago)"        double precision,
    "Price Target - High (1M Ago)"        double precision,
    "Price Target - High (6M Ago)"        double precision,
    "Price Target - High (MTD Ago)"       double precision,
    "Price Target - High (3M Ago)"        double precision,
    "Price Target - High (QTD Ago)"       double precision,
    "Price Target - High (1Y Ago)"        double precision,
    "Price Target - High (YTD Ago)"       double precision,
    "Price Target - Low (1W Ago)"         double precision,
    "Price Target - Low (1M Ago)"         double precision,
    "Price Target - Low (3M Ago)"         double precision,
    "Price Target - Low (6M Ago)"         double precision,
    "Price Target - Low (MTD Ago)"        double precision,
    "Price Target - Low (QTD Ago)"        double precision,
    "Price Target - Low (YTD Ago)"        double precision,
    "Price Target - Low (1Y Ago)"         double precision,
    "Price Target - Median (1W Ago)"      double precision,
    "Price Target - Median (1M Ago)"      double precision,
    "Price Target - Median (3M Ago)"      double precision,
    "Price Target - Median (6M Ago)"      double precision,
    "Price Target - Median (MTD Ago)"     double precision,
    "Price Target - Median (QTD Ago)"     double precision,
    "Price Target - Median (YTD Ago)"     double precision,
    "Price Target - Median (1Y Ago)"      double precision,
    "Basic EPS - Cont (LTM)"              double precision,
    "Basic EPS - Cont (FQ)"               double precision,
    "Basic EPS - Cont (FY)"               double precision,
    "Basic EPS - Cont (-1FQFQ)"           double precision,
    "Basic EPS - Cont (-2FQFQ)"           double precision,
    "Basic EPS - Cont (-4FQFQ)"           double precision,
    "Basic EPS - Cont (-3FQFQ)"           double precision,
    "Basic EPS - Cont (-1FY)"             double precision,
    "Basic EPS - Cont (-2FY)"             double precision,
    "Basic EPS - Cont (-3FY)"             double precision,
    "Basic EPS - Cont (-4FY)"             double precision,
    "EPS/Adj. (FQ)"                       double precision,
    "EPS/Adj. (-1FQFQ)"                   double precision,
    "EPS/Adj. (-3FQFQ)"                   double precision,
    "EPS/Adj. (-4FQFQ)"                   double precision,
    "EPS/Adj. (-2FQFQ)"                   double precision,
    "EPS/Adj. (-2FY)"                     double precision,
    "EPS/Adj. (-3FY)"                     double precision,
    "EPS/Adj. (-4FY)"                     double precision,
    "Gross Profit (-1FQFQ)"               double precision,
    "Gross Profit (-3FQFQ)"               double precision,
    "Gross Profit (-4FQFQ)"               double precision,
    "Gross Profit (-2FQFQ)"               double precision,
    "Gross Profit (-1FY)"                 double precision,
    "Gross Profit (-2FY)"                 double precision,
    "Gross Profit (-3FY)"                 double precision,
    "Gross Profit (-4FY)"                 double precision,
    "FCF - Est Avg (FY1E)"                double precision,
    "FCF - Est Avg (FY2E)"                double precision,
    "FCF - Est Avg (FY3E)"                double precision,
    "FCF - Est Avg (FY4E)"                double precision,
    "FCF - Est Avg (FY5E)"                double precision,
    "EPS (-0FYEstimate)"                  double precision,
    "EPS (-0FYActual)"                    double precision,
    "EPS (-0FYSurprise %)"                double precision,
    "EPS (-1FYEstimate)"                  double precision,
    "EPS (-1FYActual)"                    double precision,
    "EPS (-1FYSurprise %)"                double precision,
    "EPS (-2FYEstimate)"                  double precision,
    "EPS (-2FYActual)"                    double precision,
    "EPS (-2FYSurprise %)"                double precision,
    "EPS (-3FYEstimate)"                  double precision,
    "EPS (-3FYActual)"                    double precision,
    "EPS (-3FYSurprise %)"                double precision,
    "EPS (-4FYActual)"                    double precision,
    "EPS (-4FYEstimate)"                  double precision,
    "EPS (-4FYSurprise %)"                double precision,
    "EPS (-5FYEstimate)"                  double precision,
    "EPS (-5FYActual)"                    double precision,
    "EPS (-5FYSurprise %)"                double precision,
    "EPS (-0FQEstimate)"                  double precision,
    "EPS (-0FQActual)"                    double precision,
    "EPS (-0FQSurprise %)"                double precision,
    "EPS (-1FQEstimate)"                  double precision,
    "EPS (-1FQActual)"                    double precision,
    "EPS (-1FQSurprise %)"                double precision,
    "EPS (-2FQEstimate)"                  double precision,
    "EPS (-2FQActual)"                    double precision,
    "EPS (-2FQSurprise %)"                double precision,
    "EPS (-3FQEstimate)"                  double precision,
    "EPS (-3FQActual)"                    double precision,
    "EPS (-3FQSurprise %)"                double precision,
    "EPS (-4FQEstimate)"                  double precision,
    "EPS (-4FQActual)"                    double precision,
    "EPS (-4FQSurprise %)"                double precision,
    "FCF (LTM)"                           double precision,
    "FCF (FQ)"                            double precision,
    "FCF (-1FQFQ)"                        double precision,
    "FCF (-3FQFQ)"                        double precision,
    "FCF (-4FQFQ)"                        double precision,
    "FCF (-2FQFQ)"                        double precision,
    "FCF (FY)"                            double precision,
    "FCF (-1FY)"                          double precision,
    "FCF (-3FY)"                          double precision,
    "FCF (-2FY)"                          double precision,
    "FCF (-4FY)"                          double precision,
    "FCF (-5FY)"                          double precision,
    "Target % (Avg)"                      double precision,
    "Target % (Med)"                      double precision,
    "Target % (Low)"                      double precision,
    "Target % (High)"                     double precision,
    "Price Target - StdDev"               double precision,
    "Price Target - StdDev (1W Ago)"      double precision,
    "Price Target - StdDev (1M Ago)"      double precision,
    "Price Target - StdDev (3M Ago)"      double precision,
    "Price Target - StdDev (6M Ago)"      double precision,
    "Price Target - StdDev (1Y Ago)"      double precision,
    "Altman Z-Score (-1FY)"               double precision,
    "Altman Z-Score (-2FY)"               double precision,
    "Altman Z-Score (-3FY)"               double precision,
    "Altman Z-Score (-4FY)"               double precision,
    "Altman Z-Score (-5FY)"               double precision,
    "Altman Z-Score (-1FQFQ)"             double precision,
    "Altman Z-Score (-2FQFQ)"             double precision,
    "Altman Z-Score (-3FQFQ)"             double precision,
    "Altman Z-Score (-4FQFQ)"             double precision,
    "Altman Z-Score (-0FYYoYLTM)"         double precision,
    "Altman Z-Score (-1FYYoYLTM)"         double precision,
    "Altman Z-Score (-3FYYoYLTM)"         double precision,
    "Altman Z-Score (-4FYYoYLTM)"         double precision,
    "Altman Z-Score (-5FYYoYLTM)"         double precision,
    "Altman Z-Score (-2FYYoYLTM)"         double precision,
    "P/E (EST FY2)"                       double precision,
    "P/E (EST FY3)"                       double precision,
    "P/E (EST FY4)"                       double precision,
    "P/E (EST FY5)"                       double precision,
    "P/E (-4FYLTM)"                       double precision,
    "P/E (-4FQLTM)"                       double precision,
    "P/E (3YAVGNTM)"                      double precision,
    "P/E (5YAVGNTM)"                      double precision,
    "EPS Norm - Est Avg (FQ1E)"           double precision,
    "EPS Norm - Est Avg (FQ2E)"           double precision,
    "EPS Norm - Est Avg (FQ3E)"           double precision,
    "EPS Norm - Est Avg (FQ4E)"           double precision,
    "EPS Norm - Est Avg (FY2E)"           double precision,
    "EPS Norm - Est Avg (FY3E)"           double precision,
    "EPS Norm - Est Avg (FY4E)"           double precision,
    "EPS Norm - Est Avg (FY5E)"           double precision,
    "Capital Expenditure (LTM)"           double precision,
    "Capital Expenditure (FQ)"            double precision,
    "Capital Expenditure (FY)"            double precision,
    "Capital Expenditure (-1FQFQ)"        double precision,
    "Capital Expenditure (-2FQFQ)"        double precision,
    "Capital Expenditure (-3FQFQ)"        double precision,
    "Capital Expenditure (-4FQFQ)"        double precision,
    "Capital Expenditure (-1FY)"          double precision,
    "Capital Expenditure (-2FY)"          double precision,
    "Capital Expenditure (-4FY)"          double precision,
    "Capital Expenditure (-3FY)"          double precision,
    "Capital Expenditure (-5FY)"          double precision,
    "CFF (LTM)"                           double precision,
    "CFF (FQ)"                            double precision,
    "CFF (FY)"                            double precision,
    "CFF (-1FQFQ)"                        double precision,
    "CFF (-2FQFQ)"                        double precision,
    "CFF (-3FQFQ)"                        double precision,
    "CFF (-4FQFQ)"                        double precision,
    "CFF (-1FY)"                          double precision,
    "CFF (-2FY)"                          double precision,
    "CFF (-3FY)"                          double precision,
    "CFF (-4FY)"                          double precision,
    "CFI (LTM)"                           double precision,
    "CFI (FQ)"                            double precision,
    "CFI (FY)"                            double precision,
    "CFI (-1FQFQ)"                        double precision,
    "CFI (-2FQFQ)"                        double precision,
    "CFI (-3FQFQ)"                        double precision,
    "CFI (-4FQFQ)"                        double precision,
    "CFI (-1FY)"                          double precision,
    "CFI (-2FY)"                          double precision,
    "CFI (-3FY)"                          double precision,
    "CFI (-5FY)"                          double precision,
    "CFI (-4FY)"                          double precision,
    "CFO (LTM)"                           double precision,
    "CFO (FQ)"                            double precision,
    "CFO (FY)"                            double precision,
    "CFO (-1FQFQ)"                        double precision,
    "CFO (-2FQFQ)"                        double precision,
    "CFO (-4FQFQ)"                        double precision,
    "CFO (-3FQFQ)"                        double precision,
    "CFO (-1FY)"                          double precision,
    "CFO (-2FY)"                          double precision,
    "CFO (-3FY)"                          double precision,
    "CFO (-4FY)"                          double precision,
    "CFO (-5FY)"                          double precision,
    "Dividend Per Share (FQ)"             double precision,
    "Dividend Per Share (FY)"             double precision,
    "Dividend Per Share (-1FQFQ)"         double precision,
    "Dividend Per Share (-2FQFQ)"         double precision,
    "Dividend Per Share (-3FQFQ)"         double precision,
    "Dividend Per Share (-4FQFQ)"         double precision,
    "Dividend Per Share (-1FY)"           double precision,
    "Dividend Per Share (-2FY)"           double precision,
    "Dividend Per Share (-3FY)"           double precision,
    "Dividend Per Share (-4FY)"           double precision,
    "Dividend Per Share (-5FY)"           double precision,
    "Enterprise Value (-1FQ)"             double precision,
    "Enterprise Value (-2FQ)"             double precision,
    "Enterprise Value (-3FQ)"             double precision,
    "Enterprise Value (-4FQ)"             double precision,
    "Enterprise Value (-1FY)"             double precision,
    "Enterprise Value (-2FY)"             double precision,
    "Enterprise Value (-3FY)"             double precision,
    "Enterprise Value (-4FY)"             double precision,
    "Enterprise Value (-5FY)"             double precision,
    "Volatility (1M)"                     double precision,
    "Volatility (3M)"                     double precision,
    "Volatility (6M)"                     double precision,
    "Volatility (1Y)"                     double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 1W)"  double precision,
    "EPS GAAP Est Avg Rev % (FY1E - MTD)" double precision,
    "EPS GAAP Est Avg Rev % (FY1E - QTD)" double precision,
    "EPS GAAP Est Avg Rev % (FY1E - YTD)" double precision,
    "Price Target - StdDev (MTD Ago)"     double precision,
    "Price Target - StdDev (QTD Ago)"     double precision,
    "Price Target - StdDev (YTD Ago)"     double precision
);

alter table pml_df
    owner to postgres;

