CREATE TABLE pml.staging
(
	ticker                                 text,
	isin                                   text,
	name                                   text,
	description                            text,
	region                                 text,
	country                                text,
	"Trading Country"                      text,
	exchange                               text,
	unit                                   text,
	sector                                 text,
	industry                               text,
	"Style Class"                          text,
	"Size Class"                           text,
	"Last Updated"                         text,
	"Income Statement Report Date"         text,
	"FY End"                               text,
	"Next Earnings"                        text,
	"Next Earnings (When)"                 text,
	"Next Earnings (Status)"               text,
	"Dividend Record (Currency)"           text,
	"Dividend Record (Amount)"             double precision,
	"Dividend Record (Frequency)"          text,
	"Dividend Streak"                      integer,
	"Dividend Record (Announce Date)"      text,
	"Dividend Record (Payable Date)"       text,
	"Dividend Record (Record Date)"        text,
	"Dividend Record (Ex Date)"            text,
	"Market Cap"                           double precision,
	"Enterprise Value"                     double precision,
	"Last Price"                           double precision,
	"Price Target (YTD Ago)"               double precision,
	"Total Return (YTD)"                   double precision,
	"Price Target"                         double precision,
	"Price Target - Low"                   double precision,
	"Price Target - Median"                double precision,
	"Price Target - High"                  double precision,
	"Price Target - #"                     double precision,
	"P/E (NTM)"                            double precision,
	"P/E (LTM)"                            double precision,
	"Altman Z-Score (FY)"                  double precision,
	"Altman Z-Score (FQ)"                  double precision,
	"Altman Z-Score (LTM)"                 double precision,
	"Beta (1Y)"                            double precision,
	"Beta (2Y)"                            double precision,
	"Beta (5Y)"                            double precision,
	"Analyst Rating"                       double precision,
	"# Strong Sell Ratings"                integer,
	"# Strong Buys Ratings"                integer,
	"# Hold Ratings"                       integer,
	"# Buys Ratings"                       integer,
	"# Sell Ratings"                       integer,
	"# No Opinion Ratings"                 integer,
	"Market Cap (Country R)"               integer,
	"Tot. Return %/CAGR (3Y)"              double precision,
	"Tot. Return %/CAGR (10Y)"             double precision,
	"Total Return (5Y)"                    double precision,
	"Total Return (10Y)"                   double precision,
	"Volume (Shrs)"                        integer,
	"Dividend Per Share (LTM)"             double precision,
	"Div Yield (Ind)"                      double precision,
	"Div Yield (LTM)"                      double precision,
	"Gross Profit Margin % (FY)"           double precision,
	"Gross Profit Margin % (LTM)"          text,
	"EPS Norm - Est Avg (NTM)"             text,
	"EPS/Adj. (-1FY)"                      text,
	"EPS/Adj. (FY)"                        text,
	"EPS/Adj. (LTM)"                       text,
	"EPS Norm - Est Avg (FY1E)"            text,
	"Buyback Yield (LTM)"                  text,
	"Return on Assets (ROA) % (LTM)"       text,
	"Return on Assets (ROA) % (FY)"        text,
	"Div Yield (-1FYInd)"                  text,
	"P/B (LTM)"                            text,
	"P/B (-1FY)"                           text,
	"P/B (5YAVG)"                          text,
	"Div Yield (TTM)"                      text,
	"Div Yield (NTM)"                      text,
	"Div Yield (5YAVGLTM)"                 text,
	"Price Chg. % (3M)"                    text,
	"1-Day %"                              text,
	"Price (5D Ago)"                       text,
	"Price (1W Ago)"                       text,
	"Price (1M Ago)"                       text,
	"Price (3M Ago)"                       text,
	"Price (6M Ago)"                       text,
	"Price (1Y Ago)"                       text,
	"Price (3Y Ago)"                       text,
	"Price (5Y Ago)"                       text,
	"Price (QTD Ago)"                      text,
	"Rel. Volume"                          text,
	"Shrs Out"                             text,
	"Shrs Out (-1FY)"                      text,
	"Common Dividends Paid (LTM)"          text,
	"Common Dividends Paid (FY)"           text,
	"EV/Sales (LTM)"                       text,
	"EV/Sales (NTM)"                       text,
	"EV/Sales (-1FYLTM)"                   text,
	"EV/Sales (-2FYLTM)"                   text,
	"EV/Sales (-3FYLTM)"                   text,
	"EV/Sales (3YAVGLTM)"                  text,
	"EV/Sales (-1FQLTM)"                   text,
	"EV/Sales (-2FQLTM)"                   text,
	"EV/Sales (-3FQLTM)"                   text,
	"EV/Sales (-4FQLTM)"                   text,
	"52W High/Adj"                         text,
	"52W Low/Adj"                          text,
	"EMA (20D)"                            text,
	"EMA (50D)"                            text,
	"EMA (100D)"                           text,
	"EMA (250D)"                           text,
	"EV/EBITDA (LTM)"                      text,
	"EV/EBITDA (NTM)"                      text,
	"EV/EBITDA (-1FYLTM)"                  text,
	"EV/EBITDA (-1FQLTM)"                  text,
	"EV/EBITDA (3YAVGLTM)"                 text,
	"EV/EBITDA (EST FY1)"                  text,
	"P/E (EST FY1)"                        text,
	"P/E (-1FYLTM)"                        text,
	"P/E (-2FYLTM)"                        text,
	"P/E (-3FYLTM)"                        text,
	"P/E (3YAVGLTM)"                       text,
	"P/E (-1FQLTM)"                        text,
	"P/E (-2FQLTM)"                        text,
	"P/E (-3FQLTM)"                        text,
	"P/E (5YAVGLTM)"                       text,
	"P/E (-0FQQoQLTM)"                     text,
	"P/E (-0FYYoYLTM)"                     text,
	"P/E (-1FYYoYLTM)"                     text,
	"P/E (-0FQYoYLTM)"                     text,
	"Full Time Employees (FQ)"             text,
	"Full Time Employees (FY)"             text,
	"Full Time Employees (-1FY)"           text,
	"Full Time Employees (-2FY)"           text,
	"Full Time Employees (-3FY)"           text,
	"Avg Employees (5YAVGFY)"              text,
	"Net EPS - Basic (LTM)"                text,
	"Net EPS - Basic (FQ)"                 text,
	"Net EPS - Basic (FY)"                 text,
	"Net EPS - Basic (-1FQFQ)"             text,
	"Net EPS - Basic (-2FQFQ)"             text,
	"Net EPS - Basic (-3FQFQ)"             text,
	"Net EPS - Basic (-4FQFQ)"             text,
	"Net EPS - Basic (-1FY)"               text,
	"Net EPS - Basic (-2FY)"               text,
	"Net EPS - Basic (-3FY)"               text,
	"Net EPS - Basic (-4FY)"               text,
	"Net EPS - Basic (-5FY)"               text,
	"EPS Est Avg Rev % (FY1E - 1W)"        text,
	"EPS Est Avg Rev % (FY1E - 1M)"        text,
	"EPS Est Avg Rev % (FY1E - 3M)"        text,
	"EPS Est Avg Rev % (FY1E - 6M)"        text,
	"EPS Est Avg Rev % (FY1E - 1Y)"        text,
	"Div Yield (-2FYInd)"                  text,
	"Div Yield (-3FYInd)"                  text,
	"Div Yield (-4FYInd)"                  text,
	"Div Yield (-5FYInd)"                  text,
	"EBITDA - Est Avg (NTM)"               text,
	"EBITDA - Est Avg (FY1E)"              text,
	"EPS GAAP - Est Avg (NTM)"             text,
	"EPS GAAP - Est Avg (FY1E)"            text,
	"EPS GAAP Est Avg Rev % (FY1E - 1M)"   text,
	"EPS GAAP Est Avg Rev % (FY1E - 3M)"   text,
	"EPS GAAP Est Avg Rev % (FY1E - 6M)"   text,
	"EPS GAAP Est Avg Rev % (FY1E - 1Y)"   text,
	"EPS Norm - Est # (FY1E)"              text,
	"Price Target (1W Ago)"                text,
	"Price Target (1M Ago)"                text,
	"Price Target (3M Ago)"                text,
	"Price Target (6M Ago)"                text,
	"Price Target (MTD Ago)"               text,
	"Price Target (QTD Ago)"               text,
	"Price Target (1Y Ago)"                text,
	"Price Target - # (3M Ago)"            text,
	"Price Target - # (6M Ago)"            text,
	"Price Target - # (YTD Ago)"           text,
	"Price Target - # (1Y Ago)"            text,
	"Price Target - # (1W Ago)"            text,
	"Price Target - # (1M Ago)"            text,
	"Price Target - # (MTD Ago)"           text,
	"Price Target - # (QTD Ago)"           text,
	"Price Target - High (1W Ago)"         text,
	"Price Target - High (1M Ago)"         text,
	"Price Target - High (6M Ago)"         text,
	"Price Target - High (MTD Ago)"        text,
	"Price Target - High (3M Ago)"         text,
	"Price Target - High (QTD Ago)"        text,
	"Price Target - High (1Y Ago)"         text,
	"Price Target - High (YTD Ago)"        text,
	"Price Target - Low (1W Ago)"          text,
	"Price Target - Low (1M Ago)"          text,
	"Price Target - Low (3M Ago)"          text,
	"Price Target - Low (6M Ago)"          text,
	"Price Target - Low (MTD Ago)"         text,
	"Price Target - Low (QTD Ago)"         text,
	"Price Target - Low (YTD Ago)"         text,
	"Price Target - Low (1Y Ago)"          text,
	"Price Target - Median (1W Ago)"       text,
	"Price Target - Median (1M Ago)"       text,
	"Price Target - Median (3M Ago)"       text,
	"Price Target - Median (6M Ago)"       text,
	"Price Target - Median (MTD Ago)"      text,
	"Price Target - Median (QTD Ago)"      text,
	"Price Target - Median (YTD Ago)"      text,
	"Price Target - Median (1Y Ago)"       text,
	"Basic EPS - Cont (LTM)"               text,
	"Basic EPS - Cont (FQ)"                text,
	"Basic EPS - Cont (FY)"                text,
	"Basic EPS - Cont (-1FQFQ)"            text,
	"Basic EPS - Cont (-2FQFQ)"            text,
	"Basic EPS - Cont (-4FQFQ)"            text,
	"Basic EPS - Cont (-3FQFQ)"            text,
	"Basic EPS - Cont (-1FY)"              text,
	"Basic EPS - Cont (-2FY)"              text,
	"Basic EPS - Cont (-3FY)"              text,
	"Basic EPS - Cont (-4FY)"              text,
	"EPS/Adj. (FQ)"                        text,
	"EPS/Adj. (-1FQFQ)"                    text,
	"EPS/Adj. (-3FQFQ)"                    text,
	"EPS/Adj. (-4FQFQ)"                    text,
	"EPS/Adj. (-2FQFQ)"                    text,
	"EPS/Adj. (-2FY)"                      text,
	"EPS/Adj. (-3FY)"                      text,
	"EPS/Adj. (-4FY)"                      text,
	"Gross Profit (-1FQFQ)"                text,
	"Gross Profit (-3FQFQ)"                text,
	"Gross Profit (-4FQFQ)"                text,
	"Gross Profit (-2FQFQ)"                text,
	"Gross Profit (-1FY)"                  text,
	"Gross Profit (-2FY)"                  text,
	"Gross Profit (-3FY)"                  text,
	"Gross Profit (-4FY)"                  text,
	"FCF - Est Avg (FY1E)"                 text,
	"FCF - Est Avg (FY2E)"                 text,
	"FCF - Est Avg (FY3E)"                 text,
	"FCF - Est Avg (FY4E)"                 text,
	"FCF - Est Avg (FY5E)"                 text,
	"EPS (-0FYEstimate)"                   text,
	"EPS (-0FYActual)"                     text,
	"EPS (-0FYSurprise %)"                 text,
	"EPS (-1FYEstimate)"                   text,
	"EPS (-1FYActual)"                     text,
	"EPS (-1FYSurprise %)"                 text,
	"EPS (-2FYEstimate)"                   text,
	"EPS (-2FYActual)"                     text,
	"EPS (-2FYSurprise %)"                 text,
	"EPS (-3FYEstimate)"                   text,
	"EPS (-3FYActual)"                     text,
	"EPS (-3FYSurprise %)"                 text,
	"EPS (-4FYActual)"                     text,
	"EPS (-4FYEstimate)"                   text,
	"EPS (-4FYSurprise %)"                 text,
	"EPS (-5FYEstimate)"                   text,
	"EPS (-5FYActual)"                     text,
	"EPS (-5FYSurprise %)"                 text,
	"EPS (-0FQEstimate)"                   text,
	"EPS (-0FQActual)"                     text,
	"EPS (-0FQSurprise %)"                 text,
	"EPS (-1FQEstimate)"                   text,
	"EPS (-1FQActual)"                     text,
	"EPS (-1FQSurprise %)"                 text,
	"EPS (-2FQEstimate)"                   text,
	"EPS (-2FQActual)"                     text,
	"EPS (-2FQSurprise %)"                 text,
	"EPS (-3FQEstimate)"                   text,
	"EPS (-3FQActual)"                     text,
	"EPS (-3FQSurprise %)"                 text,
	"EPS (-4FQEstimate)"                   text,
	"EPS (-4FQActual)"                     text,
	"EPS (-4FQSurprise %)"                 text,
	"FCF (LTM)"                            text,
	"FCF (FQ)"                             text,
	"FCF (-1FQFQ)"                         text,
	"FCF (-3FQFQ)"                         text,
	"FCF (-4FQFQ)"                         text,
	"FCF (-2FQFQ)"                         text,
	"FCF (FY)"                             text,
	"FCF (-1FY)"                           text,
	"FCF (-3FY)"                           text,
	"FCF (-2FY)"                           text,
	"FCF (-4FY)"                           text,
	"FCF (-5FY)"                           text,
	"Target % (Avg)"                       text,
	"Target % (Med)"                       text,
	"Target % (Low)"                       text,
	"Target % (High)"                      text,
	"Price Target - StdDev"                text,
	"Price Target - StdDev (1W Ago)"       text,
	"Price Target - StdDev (1M Ago)"       text,
	"Price Target - StdDev (3M Ago)"       text,
	"Price Target - StdDev (6M Ago)"       text,
	"Price Target - StdDev (1Y Ago)"       text,
	"Altman Z-Score (-1FY)"                text,
	"Altman Z-Score (-2FY)"                text,
	"Altman Z-Score (-3FY)"                text,
	"Altman Z-Score (-4FY)"                text,
	"Altman Z-Score (-5FY)"                text,
	"Altman Z-Score (-1FQFQ)"              text,
	"Altman Z-Score (-2FQFQ)"              text,
	"Altman Z-Score (-3FQFQ)"              text,
	"Altman Z-Score (-4FQFQ)"              text,
	"Altman Z-Score (-0FYYoYLTM)"          text,
	"Altman Z-Score (-1FYYoYLTM)"          text,
	"Altman Z-Score (-3FYYoYLTM)"          text,
	"Altman Z-Score (-4FYYoYLTM)"          text,
	"Altman Z-Score (-5FYYoYLTM)"          text,
	"Altman Z-Score (-2FYYoYLTM)"          text,
	"P/E (EST FY2)"                        text,
	"P/E (EST FY3)"                        text,
	"P/E (EST FY4)"                        text,
	"P/E (EST FY5)"                        text,
	"P/E (-4FYLTM)"                        text,
	"P/E (-4FQLTM)"                        text,
	"P/E (3YAVGNTM)"                       text,
	"P/E (5YAVGNTM)"                       text,
	"EPS Norm - Est Avg (FQ1E)"            text,
	"EPS Norm - Est Avg (FQ2E)"            text,
	"EPS Norm - Est Avg (FQ3E)"            text,
	"EPS Norm - Est Avg (FQ4E)"            text,
	"EPS Norm - Est Avg (FY2E)"            text,
	"EPS Norm - Est Avg (FY3E)"            text,
	"EPS Norm - Est Avg (FY4E)"            text,
	"EPS Norm - Est Avg (FY5E)"            text,
	"Capital Expenditure (LTM)"            text,
	"Capital Expenditure (FQ)"             text,
	"Capital Expenditure (FY)"             text,
	"Capital Expenditure (-1FQFQ)"         text,
	"Capital Expenditure (-2FQFQ)"         text,
	"Capital Expenditure (-3FQFQ)"         text,
	"Capital Expenditure (-4FQFQ)"         text,
	"Capital Expenditure (-1FY)"           text,
	"Capital Expenditure (-2FY)"           text,
	"Capital Expenditure (-4FY)"           text,
	"Capital Expenditure (-3FY)"           text,
	"Capital Expenditure (-5FY)"           text,
	"CFF (LTM)"                            text,
	"CFF (FQ)"                             text,
	"CFF (FY)"                             text,
	"CFF (-1FQFQ)"                         text,
	"CFF (-2FQFQ)"                         text,
	"CFF (-3FQFQ)"                         text,
	"CFF (-4FQFQ)"                         text,
	"CFF (-1FY)"                           text,
	"CFF (-2FY)"                           text,
	"CFF (-3FY)"                           text,
	"CFF (-4FY)"                           text,
	"CFI (LTM)"                            text,
	"CFI (FQ)"                             text,
	"CFI (FY)"                             text,
	"CFI (-1FQFQ)"                         text,
	"CFI (-2FQFQ)"                         text,
	"CFI (-3FQFQ)"                         text,
	"CFI (-4FQFQ)"                         text,
	"CFI (-1FY)"                           text,
	"CFI (-2FY)"                           text,
	"CFI (-3FY)"                           text,
	"CFI (-5FY)"                           text,
	"CFI (-4FY)"                           text,
	"CFO (LTM)"                            text,
	"CFO (FQ)"                             text,
	"CFO (FY)"                             text,
	"CFO (-1FQFQ)"                         text,
	"CFO (-2FQFQ)"                         text,
	"CFO (-4FQFQ)"                         text,
	"CFO (-3FQFQ)"                         text,
	"CFO (-1FY)"                           text,
	"CFO (-2FY)"                           text,
	"CFO (-3FY)"                           text,
	"CFO (-4FY)"                           text,
	"CFO (-5FY)"                           text,
	"Dividend Per Share (FQ)"              text,
	"Dividend Per Share (FY)"              text,
	"Dividend Per Share (-1FQFQ)"          text,
	"Dividend Per Share (-2FQFQ)"          text,
	"Dividend Per Share (-3FQFQ)"          text,
	"Dividend Per Share (-4FQFQ)"          text,
	"Dividend Per Share (-1FY)"            text,
	"Dividend Per Share (-2FY)"            text,
	"Dividend Per Share (-3FY)"            text,
	"Dividend Per Share (-4FY)"            text,
	"Dividend Per Share (-5FY)"            text,
	"Enterprise Value (-1FQ)"              text,
	"Enterprise Value (-2FQ)"              text,
	"Enterprise Value (-3FQ)"              text,
	"Enterprise Value (-4FQ)"              text,
	"Enterprise Value (-1FY)"              text,
	"Enterprise Value (-2FY)"              text,
	"Enterprise Value (-3FY)"              text,
	"Enterprise Value (-4FY)"              text,
	"Enterprise Value (-5FY)"              text,
	"Volatility (1M)"                      text,
	"Volatility (3M)"                      text,
	"Volatility (6M)"                      text,
	"Volatility (1Y)"                      text,
	"EPS GAAP Est Avg Rev % (FY1E - 1W)"   text,
	"EPS GAAP Est Avg Rev % (FY1E - MTD)"  text,
	"EPS GAAP Est Avg Rev % (FY1E - QTD)"  text,
	"EPS GAAP Est Avg Rev % (FY1E - YTD)"  text,
	"Price Target - StdDev (MTD Ago)"      text,
	"Price Target - StdDev (QTD Ago)"      text,
	"Price Target - StdDev (YTD Ago)"      text,
	"EBIT (-0FQEstimate)"                  text,
	"EBIT (-1FQEstimate)"                  text,
	"EBIT (-2FQEstimate)"                  text,
	"EBIT (-3FQEstimate)"                  text,
	"EBIT (-4FQEstimate)"                  text,
	"EBIT (-0FQActual)"                    text,
	"EBIT (-1FQActual)"                    text,
	"EBIT (-2FQActual)"                    text,
	"EBIT (-3FQActual)"                    text,
	"EBIT (-4FQActual)"                    text,
	"EBIT (-0FYActual)"                    text,
	"EBIT (-1FYActual)"                    text,
	"EBIT (-2FYActual)"                    text,
	"EBIT (-3FYActual)"                    text,
	"EBIT (-4FYActual)"                    text,
	"EBIT (-5FYActual)"                    text,
	"EBIT (-0FYEstimate)"                  text,
	"EBIT (-1FYEstimate)"                  text,
	"EBIT (-2FYEstimate)"                  text,
	"EBIT (-3FYEstimate)"                  text,
	"EBIT (-4FYEstimate)"                  text,
	"EBIT (-5FYEstimate)"                  text,
	"EBIT (-0FQSurprise %)"                text,
	"EBIT (-1FQSurprise %)"                text,
	"EBIT (-2FQSurprise %)"                text,
	"EBIT (-3FQSurprise %)"                text,
	"EBIT (-4FQSurprise %)"                text,
	"EBIT (-0FYSurprise %)"                text,
	"EBIT (-1FYSurprise %)"                text,
	"EBIT (-2FYSurprise %)"                text,
	"EBIT (-3FYSurprise %)"                text,
	"EBIT (-4FYSurprise %)"                text,
	"EBIT (-5FYSurprise %)"                text,
	"EBITDA (-0FQEstimate)"                text,
	"EBITDA (-1FQEstimate)"                text,
	"EBITDA (-2FQEstimate)"                text,
	"EBITDA (-3FQEstimate)"                text,
	"EBITDA (-4FQEstimate)"                text,
	"EBITDA (-0FYEstimate)"                text,
	"EBITDA (-1FYEstimate)"                text,
	"EBITDA (-2FYEstimate)"                text,
	"EBITDA (-3FYEstimate)"                text,
	"EBITDA (-4FYEstimate)"                text,
	"EBITDA (-5FYEstimate)"                text,
	"EBITDA (-0FQActual)"                  text,
	"EBITDA (-1FQActual)"                  text,
	"EBITDA (-2FQActual)"                  text,
	"EBITDA (-3FQActual)"                  text,
	"EBITDA (-4FQActual)"                  text,
	"EBITDA (-0FYActual)"                  text,
	"EBITDA (-1FYActual)"                  text,
	"EBITDA (-2FYActual)"                  text,
	"EBITDA (-3FYActual)"                  text,
	"EBITDA (-4FYActual)"                  text,
	"EBITDA (-5FYActual)"                  text,
	"EBITDA (-0FQSurprise %)"              text,
	"EBITDA (-1FQSurprise %)"              text,
	"EBITDA (-2FQSurprise %)"              text,
	"EBITDA (-3FQSurprise %)"              text,
	"EBITDA (-4FQSurprise %)"              text,
	"EBITDA (-0FYSurprise %)"              text,
	"EBITDA (-1FYSurprise %)"              text,
	"EBITDA (-2FYSurprise %)"              text,
	"EBITDA (-3FYSurprise %)"              text,
	"EBITDA (-4FYSurprise %)"              text,
	"EBITDA (-5FYSurprise %)"              text,
	"Price (1D Ago)"                       text,
	"Price (YTD Ago)"                      text,
	"Price (MTD Ago)"                      text,
	"Sales (-0FQEstimate)"                 text,
	"Sales (-0FQActual)"                   text,
	"Sales (-0FQSurprise %)"               text,
	"Sales (-1FQEstimate)"                 text,
	"Sales (-1FQActual)"                   text,
	"Sales (-1FQSurprise %)"               text,
	"Sales (-2FQEstimate)"                 text,
	"Sales (-2FQActual)"                   text,
	"Sales (-2FQSurprise %)"               text,
	"Sales (-3FQEstimate)"                 text,
	"Sales (-3FQActual)"                   text,
	"Sales (-3FQSurprise %)"               text,
	"Sales (-4FQEstimate)"                 text,
	"Sales (-4FQActual)"                   text,
	"Sales (-4FQSurprise %)"               text,
	"Sales (-0FYEstimate)"                 text,
	"Sales (-0FYActual)"                   text,
	"Sales (-0FYSurprise %)"               text,
	"Sales (-1FYEstimate)"                 text,
	"Sales (-1FYActual)"                   text,
	"Sales (-1FYSurprise %)"               text,
	"Sales (-2FYEstimate)"                 text,
	"Sales (-2FYActual)"                   text,
	"Sales (-2FYSurprise %)"               text,
	"Sales (-3FYEstimate)"                 text,
	"Sales (-3FYActual)"                   text,
	"Sales (-3FYSurprise %)"               text,
	"Sales (-4FYEstimate)"                 text,
	"Sales (-4FYActual)"                   text,
	"Sales (-4FYSurprise %)"               text,
	"Sales (-5FYEstimate)"                 text,
	"Sales (-5FYActual)"                   text,
	"Sales (-5FYSurprise %)"               text,
	"FCF / Share (LTM)"                    text,
	"FCF / Share (FQ)"                     text,
	"FCF / Share (FY)"                     text,
	"FCF / Share (-1FQFQ)"                 text,
	"FCF / Share (-2FQFQ)"                 text,
	"FCF / Share (-3FQFQ)"                 text,
	"FCF / Share (-4FQFQ)"                 text,
	"FCF / Share (-1FY)"                   text,
	"FCF / Share (-2FY)"                   text,
	"FCF / Share (-3FY)"                   text,
	"FCF / Share (-4FY)"                   text,
	"FCF / Share (-5FY)"                   text,
	"Issuance of Common Stock (LTM)"       text,
	"Issuance of Common Stock (FQ)"        text,
	"Issuance of Common Stock (FY)"        text,
	"Issuance of Common Stock (-1FQFQ)"    text,
	"Issuance of Common Stock (-2FQFQ)"    text,
	"Issuance of Common Stock (-3FQFQ)"    text,
	"Issuance of Common Stock (-4FQFQ)"    text,
	"Issuance of Common Stock (-1FY)"      text,
	"Issuance of Common Stock (-2FY)"      text,
	"Issuance of Common Stock (-3FY)"      text,
	"Issuance of Common Stock (-4FY)"      text,
	"Issuance of Common Stock (-5FY)"      text,
	"Shrs Out (-1FQ)"                      text,
	"Shrs Out (-2FQ)"                      text,
	"Shrs Out (-3FQ)"                      text,
	"Shrs Out (-4FQ)"                      text,
	"Shrs Out (-2FY)"                      text,
	"Shrs Out (-3FY)"                      text,
	"Shrs Out (-4FY)"                      text,
	"Shrs Out (-5FY)"                      text,
	"Shrs Out (3YAVG)"                     text,
	"Shrs Out (5YAVG)"                     text,
	"Repurchase of Common Stock (LTM)"     text,
	"Repurchase of Common Stock (FQ)"      text,
	"Repurchase of Common Stock (FY)"      text,
	"Repurchase of Common Stock (-1FQFQ)"  text,
	"Repurchase of Common Stock (-2FQFQ)"  text,
	"Repurchase of Common Stock (-3FQFQ)"  text,
	"Repurchase of Common Stock (-4FQFQ)"  text,
	"Repurchase of Common Stock (-1FY)"    text,
	"Repurchase of Common Stock (-2FY)"    text,
	"Repurchase of Common Stock (-3FY)"    text,
	"Repurchase of Common Stock (-4FY)"    text,
	"Repurchase of Common Stock (-5FY)"    text,
	"Repurchase of Common Stock (3YAVGFQ)" text,
	"Repurchase of Common Stock (5YAVGFQ)" text,
	"PEG (NTM)"                            text,
	"PEG (-1FY)"                           text,
	"PEG (-2FY)"                           text,
	"PEG (-3FY)"                           text,
	"PEG (-4FY)"                           text,
	"PEG (-5FY)"                           text,
	"PEG (3YAVG)"                          text,
	"PEG (5YAVG)"                          text,
	"Gross Profit Margin % (FQ)"           text,
	"Gross Profit Margin % (-1FQFQ)"       text,
	"Gross Profit Margin % (-2FQFQ)"       text,
	"Gross Profit Margin % (-3FQFQ)"       text,
	"Gross Profit Margin % (-4FQFQ)"       text,
	"Gross Profit Margin % (-1FY)"         text,
	"Gross Profit Margin % (-2FY)"         text,
	"Gross Profit Margin % (-3FY)"         text,
	"Gross Profit Margin % (-4FY)"         text,
	"Gross Profit Margin % (-5FY)"         text,
	"Gross Profit Margin % (3YAVGFQ)"      text,
	"Gross Profit Margin % (5YAVGFQ)"      text
);

ALTER TABLE pml.staging
	OWNER TO postgres;