create table analytics.accounting_anomaly_analysis
(
    isin                                          text,
    ticker                                        text,
    name                                          text,
    description                                   text,
    region                                        text,
    country                                       text,
    trading_country                               text,
    exchange                                      text,
    sector                                        text,
    industry                                      text,
    dividend_record_frequency                     text,
    earnings_report_frequency                     text,
    fy_end                                        text,
    next_earnings_report                          text,
    next_earnings_status                          text,
    next_earnings_when                            text,
    next_fiscal_quarter                           text,
    reporting_interval                            double precision,
    size_class                                    text,
    style_class                                   text,
    unit                                          text,
    dividend_record_announce_date                 text,
    dividend_record_ex_date                       text,
    dividend_record_payable_date                  text,
    dividend_record_record_date                   text,
    fy_end_date                                   text,
    income_statement_report_date                  text,
    last_updated                                  date,
    next_earnings                                 date,
    next_fy_end_date                              text,
    next_income_statement_report_date             text,
    reference_date                                date,
    market_cap                                    double precision,
    enterprise_value                              double precision,
    last_price                                    double precision,
    price_target                                  double precision,
    shares_outstanding                            double precision,
    revenue_accelerating_flag                     bigint,
    has_goodwill_impairment                       bigint,
    has_asset_writedown                           bigint,
    has_restructuring                             bigint,
    wc_deteriorating_flag                         bigint,
    accumulated_deficit_flag                      bigint,
    has_goodwill_impairment_ltm                   bigint,
    intangibles_growth_flag                       bigint,
    debt_maturity_risk                            double precision,
    negative_wc_flag                              bigint,
    analyst_bearish_pct                           double precision,
    layoff_risk_flag                              bigint,
    overinvestment_flag                           bigint,
    inventory_buildup_flag                        bigint,
    inventory_reduction_flag                      bigint,
    recent_acquisition_flag                       bigint,
    impairment_risk_score                         double precision,
    high_rnd_intensity_flag                       bigint,
    has_unusual_items_flag                        bigint,
    low_tax_flag                                  bigint,
    accounting_anomaly_score                      double precision,
    exceptional_items_frequency_z_robust          double precision,
    exceptional_items_frequency_anomaly_flag      boolean,
    exceptional_items_frequency_dist_name         text,
    exceptional_items_frequency_dist_pvalue       double precision,
    gaap_adj_eps_gap_pct_z_robust                 double precision,
    gaap_adj_eps_gap_pct_anomaly_flag             boolean,
    gaap_adj_eps_gap_pct_dist_name                text,
    gaap_adj_eps_gap_pct_dist_pvalue              double precision,
    asset_sale_boost_z_robust                     double precision,
    asset_sale_boost_anomaly_flag                 boolean,
    asset_sale_boost_dist_name                    text,
    asset_sale_boost_dist_pvalue                  double precision,
    ebitda_adjustment_ratio_z_robust              double precision,
    ebitda_adjustment_ratio_anomaly_flag          boolean,
    ebitda_adjustment_ratio_dist_name             text,
    ebitda_adjustment_ratio_dist_pvalue           double precision,
    eps_adjustment_ratio_z_robust                 double precision,
    eps_adjustment_ratio_anomaly_flag             boolean,
    eps_adjustment_ratio_dist_name                text,
    eps_adjustment_ratio_dist_pvalue              double precision,
    exceptional_items_to_ebitda_z_robust          double precision,
    exceptional_items_to_ebitda_anomaly_flag      boolean,
    exceptional_items_to_ebitda_dist_name         text,
    exceptional_items_to_ebitda_dist_pvalue       double precision,
    restructuring_intensity_z_robust              double precision,
    restructuring_intensity_anomaly_flag          boolean,
    restructuring_intensity_dist_name             text,
    restructuring_intensity_dist_pvalue           double precision,
    goodwill_change_rate_z_robust                 double precision,
    goodwill_change_rate_anomaly_flag             boolean,
    goodwill_change_rate_dist_name                text,
    goodwill_change_rate_dist_pvalue              double precision,
    eps_adj_ltm_z_robust                          double precision,
    eps_adj_ltm_anomaly_flag                      boolean,
    eps_adj_ltm_dist_name                         text,
    eps_adj_ltm_dist_pvalue                       double precision,
    eps_adjustment_spread_ltm_z_robust            double precision,
    eps_adjustment_spread_ltm_anomaly_flag        boolean,
    eps_adjustment_spread_ltm_dist_name           text,
    eps_adjustment_spread_ltm_dist_pvalue         double precision,
    eps_adjustment_spread_fy_z_robust             double precision,
    eps_adjustment_spread_fy_anomaly_flag         boolean,
    eps_adjustment_spread_fy_dist_name            text,
    eps_adjustment_spread_fy_dist_pvalue          double precision,
    eps_adjustment_pct_z_robust                   double precision,
    eps_adjustment_pct_anomaly_flag               boolean,
    eps_adjustment_pct_dist_name                  text,
    eps_adjustment_pct_dist_pvalue                double precision,
    net_income_adjustment_ratio_ltm_z_robust      double precision,
    net_income_adjustment_ratio_ltm_anomaly_flag  boolean,
    net_income_adjustment_ratio_ltm_dist_name     text,
    net_income_adjustment_ratio_ltm_dist_pvalue   double precision,
    net_income_adjustment_ratio_fy_z_robust       double precision,
    net_income_adjustment_ratio_fy_anomaly_flag   boolean,
    net_income_adjustment_ratio_fy_dist_name      text,
    net_income_adjustment_ratio_fy_dist_pvalue    double precision,
    net_income_adjustment_pct_z_robust            double precision,
    net_income_adjustment_pct_anomaly_flag        boolean,
    net_income_adjustment_pct_dist_name           text,
    net_income_adjustment_pct_dist_pvalue         double precision,
    ebitda_adjustment_pct_ltm_z_robust            double precision,
    ebitda_adjustment_pct_ltm_anomaly_flag        boolean,
    ebitda_adjustment_pct_ltm_dist_name           text,
    ebitda_adjustment_pct_ltm_dist_pvalue         double precision,
    ebitda_adjustment_pct_fy_z_robust             double precision,
    ebitda_adjustment_pct_fy_anomaly_flag         boolean,
    ebitda_adjustment_pct_fy_dist_name            text,
    ebitda_adjustment_pct_fy_dist_pvalue          double precision,
    ebit_adjustment_pct_ltm_z_robust              double precision,
    ebit_adjustment_pct_ltm_anomaly_flag          boolean,
    ebit_adjustment_pct_ltm_dist_name             text,
    ebit_adjustment_pct_ltm_dist_pvalue           double precision,
    ebit_adjustment_pct_fy_z_robust               double precision,
    ebit_adjustment_pct_fy_anomaly_flag           boolean,
    ebit_adjustment_pct_fy_dist_name              text,
    ebit_adjustment_pct_fy_dist_pvalue            double precision,
    forward_eps_gaap_adj_spread_z_robust          double precision,
    forward_eps_gaap_adj_spread_anomaly_flag      boolean,
    forward_eps_gaap_adj_spread_dist_name         text,
    forward_eps_gaap_adj_spread_dist_pvalue       double precision,
    gaap_vs_norm_revision_spread_z_robust         double precision,
    gaap_vs_norm_revision_spread_anomaly_flag     boolean,
    gaap_vs_norm_revision_spread_dist_name        text,
    gaap_vs_norm_revision_spread_dist_pvalue      double precision,
    gaap_revision_momentum_z_robust               double precision,
    gaap_revision_momentum_anomaly_flag           boolean,
    gaap_revision_momentum_dist_name              text,
    gaap_revision_momentum_dist_pvalue            double precision,
    gaap_revision_1m_z_robust                     double precision,
    gaap_revision_1m_anomaly_flag                 boolean,
    gaap_revision_1m_dist_name                    text,
    gaap_revision_1m_dist_pvalue                  double precision,
    gaap_revision_3m_z_robust                     double precision,
    gaap_revision_3m_anomaly_flag                 boolean,
    gaap_revision_3m_dist_name                    text,
    gaap_revision_3m_dist_pvalue                  double precision,
    gaap_revision_6m_z_robust                     double precision,
    gaap_revision_6m_anomaly_flag                 boolean,
    gaap_revision_6m_dist_name                    text,
    gaap_revision_6m_dist_pvalue                  double precision,
    gaap_revision_1y_z_robust                     double precision,
    gaap_revision_1y_anomaly_flag                 boolean,
    gaap_revision_1y_dist_name                    text,
    gaap_revision_1y_dist_pvalue                  double precision,
    discontinued_ops_impact_z_robust              double precision,
    discontinued_ops_impact_anomaly_flag          boolean,
    discontinued_ops_impact_dist_name             text,
    discontinued_ops_impact_dist_pvalue           double precision,
    earnings_quality_warning_z_robust             double precision,
    earnings_quality_warning_anomaly_flag         boolean,
    earnings_quality_warning_dist_name            text,
    earnings_quality_warning_dist_pvalue          double precision,
    revision_quality_divergence_z_robust          double precision,
    revision_quality_divergence_anomaly_flag      boolean,
    revision_quality_divergence_dist_name         text,
    revision_quality_divergence_dist_pvalue       double precision,
    eps_growth_accel_z_robust                     double precision,
    eps_growth_accel_anomaly_flag                 boolean,
    eps_growth_accel_dist_name                    text,
    eps_growth_accel_dist_pvalue                  double precision,
    eps_surprise_pct_z_robust                     double precision,
    eps_surprise_pct_anomaly_flag                 boolean,
    eps_surprise_pct_dist_name                    text,
    eps_surprise_pct_dist_pvalue                  double precision,
    revenue_surprise_pct_z_robust                 double precision,
    revenue_surprise_pct_anomaly_flag             boolean,
    revenue_surprise_pct_dist_name                text,
    revenue_surprise_pct_dist_pvalue              double precision,
    total_unusual_items_z_robust                  double precision,
    total_unusual_items_anomaly_flag              boolean,
    total_unusual_items_dist_name                 text,
    total_unusual_items_dist_pvalue               double precision,
    unusual_items_to_revenue_z_robust             double precision,
    unusual_items_to_revenue_anomaly_flag         boolean,
    unusual_items_to_revenue_dist_name            text,
    unusual_items_to_revenue_dist_pvalue          double precision,
    unusual_items_to_ebitda_z_robust              double precision,
    unusual_items_to_ebitda_anomaly_flag          boolean,
    unusual_items_to_ebitda_dist_name             text,
    unusual_items_to_ebitda_dist_pvalue           double precision,
    earnings_quality_impact_z_robust              double precision,
    earnings_quality_impact_anomaly_flag          boolean,
    earnings_quality_impact_dist_name             text,
    earnings_quality_impact_dist_pvalue           double precision,
    asset_sale_gain_loss_ltm_z_robust             double precision,
    asset_sale_gain_loss_ltm_anomaly_flag         boolean,
    asset_sale_gain_loss_ltm_dist_name            text,
    asset_sale_gain_loss_ltm_dist_pvalue          double precision,
    asset_sale_frequency_z_robust                 double precision,
    asset_sale_frequency_anomaly_flag             boolean,
    asset_sale_frequency_dist_name                text,
    asset_sale_frequency_dist_pvalue              double precision,
    asset_sale_trend_z_robust                     double precision,
    asset_sale_trend_anomaly_flag                 boolean,
    asset_sale_trend_dist_name                    text,
    asset_sale_trend_dist_pvalue                  double precision,
    tax_rate_stability_z_robust                   double precision,
    tax_rate_stability_anomaly_flag               boolean,
    tax_rate_stability_dist_name                  text,
    tax_rate_stability_dist_pvalue                double precision,
    tax_rate_trend_4q_z_robust                    double precision,
    tax_rate_trend_4q_anomaly_flag                boolean,
    tax_rate_trend_4q_dist_name                   text,
    tax_rate_trend_4q_dist_pvalue                 double precision,
    interest_income_to_revenue_z_robust           double precision,
    interest_income_to_revenue_anomaly_flag       boolean,
    interest_income_to_revenue_dist_name          text,
    interest_income_to_revenue_dist_pvalue        double precision,
    interest_income_to_revenue_trend_z_robust     double precision,
    interest_income_to_revenue_trend_anomaly_flag boolean,
    interest_income_to_revenue_trend_dist_name    text,
    interest_income_to_revenue_trend_dist_pvalue  double precision,
    accumulated_deficit_flag_z_robust             double precision,
    accumulated_deficit_flag_anomaly_flag         boolean,
    accumulated_deficit_flag_dist_name            text,
    accumulated_deficit_flag_dist_pvalue          double precision,
    negative_wc_flag_z_robust                     double precision,
    negative_wc_flag_anomaly_flag                 boolean,
    negative_wc_flag_dist_name                    text,
    negative_wc_flag_dist_pvalue                  double precision,
    wc_deteriorating_flag_z_robust                double precision,
    wc_deteriorating_flag_anomaly_flag            boolean,
    wc_deteriorating_flag_dist_name               text,
    wc_deteriorating_flag_dist_pvalue             double precision,
    intangibles_growth_flag_z_robust              double precision,
    intangibles_growth_flag_anomaly_flag          boolean,
    intangibles_growth_flag_dist_name             text,
    intangibles_growth_flag_dist_pvalue           double precision,
    inventory_buildup_flag_z_robust               double precision,
    inventory_buildup_flag_anomaly_flag           boolean,
    inventory_buildup_flag_dist_name              text,
    inventory_buildup_flag_dist_pvalue            double precision,
    inventory_reduction_flag_z_robust             double precision,
    inventory_reduction_flag_anomaly_flag         boolean,
    inventory_reduction_flag_dist_name            text,
    inventory_reduction_flag_dist_pvalue          double precision,
    has_goodwill_impairment_z_robust              double precision,
    has_goodwill_impairment_anomaly_flag          boolean,
    has_goodwill_impairment_dist_name             text,
    has_goodwill_impairment_dist_pvalue           double precision,
    has_asset_writedown_z_robust                  double precision,
    has_asset_writedown_anomaly_flag              boolean,
    has_asset_writedown_dist_name                 text,
    has_asset_writedown_dist_pvalue               double precision,
    has_restructuring_z_robust                    double precision,
    has_restructuring_anomaly_flag                boolean,
    has_restructuring_dist_name                   text,
    has_restructuring_dist_pvalue                 double precision,
    has_goodwill_impairment_ltm_z_robust          double precision,
    has_goodwill_impairment_ltm_anomaly_flag      boolean,
    has_goodwill_impairment_ltm_dist_name         text,
    has_goodwill_impairment_ltm_dist_pvalue       double precision,
    impairment_risk_score_z_robust                double precision,
    impairment_risk_score_anomaly_flag            boolean,
    impairment_risk_score_dist_name               text,
    impairment_risk_score_dist_pvalue             double precision,
    revenue_accelerating_flag_z_robust            double precision,
    revenue_accelerating_flag_anomaly_flag        boolean,
    revenue_accelerating_flag_dist_name           text,
    revenue_accelerating_flag_dist_pvalue         double precision,
    overinvestment_flag_z_robust                  double precision,
    overinvestment_flag_anomaly_flag              boolean,
    overinvestment_flag_dist_name                 text,
    overinvestment_flag_dist_pvalue               double precision,
    recent_acquisition_flag_z_robust              double precision,
    recent_acquisition_flag_anomaly_flag          boolean,
    recent_acquisition_flag_dist_name             text,
    recent_acquisition_flag_dist_pvalue           double precision,
    high_rnd_intensity_flag_z_robust              double precision,
    high_rnd_intensity_flag_anomaly_flag          boolean,
    high_rnd_intensity_flag_dist_name             text,
    high_rnd_intensity_flag_dist_pvalue           double precision,
    has_unusual_items_flag_z_robust               double precision,
    has_unusual_items_flag_anomaly_flag           boolean,
    has_unusual_items_flag_dist_name              text,
    has_unusual_items_flag_dist_pvalue            double precision,
    low_tax_flag_z_robust                         double precision,
    low_tax_flag_anomaly_flag                     boolean,
    low_tax_flag_dist_name                        text,
    low_tax_flag_dist_pvalue                      double precision,
    layoff_risk_flag_z_robust                     double precision,
    layoff_risk_flag_anomaly_flag                 boolean,
    layoff_risk_flag_dist_name                    text,
    layoff_risk_flag_dist_pvalue                  double precision,
    analyst_bearish_pct_z_robust                  double precision,
    analyst_bearish_pct_anomaly_flag              boolean,
    analyst_bearish_pct_dist_name                 text,
    analyst_bearish_pct_dist_pvalue               double precision,
    debt_maturity_risk_z_robust                   double precision,
    debt_maturity_risk_anomaly_flag               boolean,
    debt_maturity_risk_dist_name                  text,
    debt_maturity_risk_dist_pvalue                double precision,
    mahalanobis_distance                          double precision,
    sector_relative_anomaly                       double precision,
    benford_chi2_pvalue                           double precision,
    anomaly_feature_count                         bigint,
    accounting_anomaly_tier                       text,
    quality_frequency_score                       bigint,
    repeat_offender_flag                          bigint,
    anomaly_severity_score                        double precision,
    anomaly_risk_rank                             double precision,
    sector_anomaly_percentile                     double precision,
    multi_flag_alert                              boolean,
    anomaly_conditional_probability               double precision,
    anomaly_posterior_mean                        double precision,
    anomaly_posterior_std                         double precision,
    anomaly_ci_lower                              double precision,
    anomaly_ci_upper                              double precision,
    sector_posterior_mean                         double precision,
    anomaly_posterior_location                    double precision
);

alter table analytics.accounting_anomaly_analysis
    owner to postgres;

