create table analytics.garp_stocks
(
    isin                              text,
    ticker                            text,
    name                              text,
    description                       text,
    region                            text,
    country                           text,
    trading_country                   text,
    exchange                          text,
    sector                            text,
    industry                          text,
    dividend_record_frequency         text,
    earnings_report_frequency         text,
    fy_end                            text,
    next_earnings_report              text,
    next_earnings_status              text,
    next_earnings_when                text,
    next_fiscal_quarter               text,
    reporting_interval                double precision,
    size_class                        text,
    style_class                       text,
    unit                              text,
    dividend_record_announce_date     text,
    dividend_record_ex_date           text,
    dividend_record_payable_date      text,
    dividend_record_record_date       text,
    fy_end_date                       date,
    income_statement_report_date      date,
    last_updated                      date,
    next_earnings                     date,
    next_fy_end_date                  date,
    next_income_statement_report_date date,
    reference_date                    date,
    market_cap                        double precision,
    enterprise_value                  double precision,
    last_price                        double precision,
    price_target                      double precision,
    volume_shrs                       double precision,
    shares_outstanding                double precision,
    total_return_ytd                  double precision,
    total_return_5y                   double precision,
    analyst_rating                    double precision,
    p_e_ratio                         double precision,
    peg_ratio                         double precision,
    ev_ebitda_vs_3y_avg               double precision,
    p_e_vs_3y_avg                     double precision,
    price_to_tangible_book            double precision,
    price_momentum_1y                 double precision,
    long_term_trend_score             double precision,
    secular_trend_flag                bigint,
    volatility_compression            double precision,
    eps_yoy_growth                    double precision,
    eps_trajectory_score              double precision,
    eps_adjustment_pct                double precision,
    gaap_positive_revision_flag       bigint,
    current_ratio                     double precision,
    beta_1y                           double precision,
    beta_stability_score              double precision,
    merger_impact_ratio               double precision,
    accounting_quality_score          double precision,
    debt_to_equity                    double precision,
    debt_deleveraging                 bigint,
    dividend_streak                   bigint,
    dividend_payout_ratio             double precision,
    fcf_dividend_coverage             double precision,
    dividend_growth_expectation       double precision,
    fcf_positive_years                bigint,
    fcf_yield                         double precision,
    rnd_intensity_ltm                 double precision,
    piotroski_f_score                 bigint,
    dilution_score                    double precision,
    quality_momentum_score            double precision,
    net_income_positive_years         bigint,
    earnings_quality_composite        double precision,
    volatility_1y                     double precision,
    effective_tax_rate_ltm            double precision,
    operating_leverage_score          double precision,
    fcf_est_cagr_5y                   double precision,
    net_buyback_flag                  bigint
);

alter table analytics.garp_stocks
    owner to postgres;

