create table equities
(
	ticker                                text,
	isin                                  text,
	name                                  text,
	description                           text,
	"Equity Type"                         text,
	"Trading Region"                      text,
	"Trading Country"                     text,
	exchange                              text,
	unit                                  text,
	region                                text,
	country                               text,
	sector                                text,
	industry                              text,
	"Style Class"                         text,
	"Size Class"                          text,
	"Last Updated"                        text,
	"Income Statement Report Date"        text,
	"FY End"                              text,
	"52W High Date/Adj"                   text,
	"52W Low Date/Adj"                    text,
	"Next Earnings"                       text,
	"Next Earnings (When)"                text,
	"Next Earnings (Status)"              text,
	"Dividend Record (Currency)"          text,
	"Dividend Record (Amount)"            double precision,
	"Dividend Record (Frequency)"         text,
	"Dividend Streak"                     integer,
	"Dividend Record (Announce Date)"     text,
	"Dividend Record (Payable Date)"      text,
	"Dividend Record (Record Date)"       text,
	"Dividend Record (Ex Date)"           text,
	"Market Cap"                          double precision,
	"Enterprise Value"                    double precision,
	"Last Price"                          double precision,
	"Price Target (YTD Ago)"              double precision,
	"Total Return (YTD)"                  double precision,
	"Price Target"                        double precision,
	"Price Target - Low"                  double precision,
	"Price Target - Median"               double precision,
	"Price Target - High"                 double precision,
	"Price Target - #"                    double precision,
	"P/E (NTM)"                           double precision,
	"P/E (LTM)"                           double precision,
	"Altman Z-Score (FY)"                 double precision,
	"Altman Z-Score (FQ)"                 double precision,
	"Altman Z-Score (LTM)"                double precision,
	"Beta (1Y)"                           double precision,
	"Beta (2Y)"                           double precision,
	"Beta (5Y)"                           double precision,
	"Analyst Rating"                      double precision,
	"# Strong Sell Ratings"               integer,
	"# Strong Buys Ratings"               integer,
	"# Hold Ratings"                      integer,
	"# Buys Ratings"                      integer,
	"# Sell Ratings"                      integer,
	"# No Opinion Ratings"                integer,
	"Market Cap (Country R)"              integer,
	"Volume (Shrs)"                       integer,
	"Dividend Per Share (LTM)"            double precision,
	"Div Yield (Ind)"                     double precision,
	"Div Yield (LTM)"                     double precision,
	"Gross Profit Margin % (FY)"          double precision,
	"Gross Profit Margin % (LTM)"         double precision,
	"EPS Norm - Est Avg (NTM)"            double precision,
	"EPS/Adj. (-1FY)"                     double precision,
	"EPS/Adj. (FY)"                       double precision,
	"EPS/Adj. (LTM)"                      double precision,
	"EPS Norm - Est Avg (FY1E)"           double precision,
	"Buyback Yield (LTM)"                 double precision,
	"Return on Assets (ROA) % (LTM)"      double precision,
	"Return on Assets (ROA) % (FY)"       double precision,
	"Div Yield (-1FYInd)"                 double precision,
	"P/B (LTM)"                           double precision,
	"P/B (-1FY)"                          double precision,
	"Div Yield (TTM)"                     double precision,
	"Div Yield (NTM)"                     double precision,
	"Rel. Volume"                         integer,
	"Avg Volume"                          integer,
	"Common Dividends Paid (LTM)"         double precision,
	"Common Dividends Paid (FY)"          double precision,
	"52W High/Adj"                        double precision,
	"52W Low/Adj"                         double precision,
	"EMA (20D)"                           double precision,
	"EMA (50D)"                           double precision,
	"EMA (250D)"                          double precision,
	"P/E (EST FY1)"                       double precision,
	"P/E (-1FYLTM)"                       double precision,
	"P/E (-2FYLTM)"                       double precision,
	"P/E (-3FYLTM)"                       double precision,
	"P/E (-1FQLTM)"                       double precision,
	"P/E (-2FQLTM)"                       double precision,
	"P/E (-3FQLTM)"                       double precision,
	"P/E (-0FQQoQLTM)"                    double precision,
	"P/E (-0FYYoYLTM)"                    double precision,
	"P/E (-1FYYoYLTM)"                    double precision,
	"P/E (-0FQYoYLTM)"                    double precision,
	"Full Time Employees (FQ)"            integer,
	"Full Time Employees (FY)"            integer,
	"Full Time Employees (-1FY)"          integer,
	"EPS Est Avg Rev % (FY1E - 1W)"       double precision,
	"EPS Est Avg Rev % (FY1E - 1M)"       double precision,
	"EPS Est Avg Rev % (FY1E - 3M)"       double precision,
	"EPS Est Avg Rev % (FY1E - 6M)"       double precision,
	"EPS Est Avg Rev % (FY1E - 1Y)"       double precision,
	"EBITDA - Est Avg (NTM)"              double precision,
	"EBITDA - Est Avg (FY1E)"             double precision,
	"EPS GAAP - Est Avg (NTM)"            double precision,
	"EPS GAAP - Est Avg (FY1E)"           double precision,
	"EPS GAAP Est Avg Rev % (FY1E - 1M)"  double precision,
	"EPS GAAP Est Avg Rev % (FY1E - 3M)"  double precision,
	"EPS GAAP Est Avg Rev % (FY1E - 6M)"  double precision,
	"EPS GAAP Est Avg Rev % (FY1E - 1Y)"  double precision,
	"EPS Norm - Est # (FY1E)"             integer,
	"Price Target (1W Ago)"               double precision,
	"Price Target (1M Ago)"               double precision,
	"Price Target (3M Ago)"               double precision,
	"Price Target (6M Ago)"               double precision,
	"Price Target (MTD Ago)"              double precision,
	"Price Target (QTD Ago)"              double precision,
	"Price Target (1Y Ago)"               double precision,
	"Price Target - # (3M Ago)"           double precision,
	"Price Target - # (6M Ago)"           double precision,
	"Price Target - # (YTD Ago)"          double precision,
	"Price Target - # (1Y Ago)"           double precision,
	"Price Target - # (1W Ago)"           double precision,
	"Price Target - # (1M Ago)"           double precision,
	"Price Target - # (MTD Ago)"          double precision,
	"Price Target - # (QTD Ago)"          text,
	"Price Target - High (1W Ago)"        text,
	"Price Target - High (1M Ago)"        text,
	"Price Target - High (6M Ago)"        text,
	"Price Target - High (MTD Ago)"       text,
	"Price Target - High (3M Ago)"        text,
	"Price Target - High (QTD Ago)"       text,
	"Price Target - High (1Y Ago)"        text,
	"Price Target - High (YTD Ago)"       text,
	"Price Target - Low (1W Ago)"         text,
	"Price Target - Low (1M Ago)"         text,
	"Price Target - Low (3M Ago)"         text,
	"Price Target - Low (6M Ago)"         text,
	"Price Target - Low (MTD Ago)"        text,
	"Price Target - Low (QTD Ago)"        text,
	"Price Target - Low (YTD Ago)"        text,
	"Price Target - Low (1Y Ago)"         text,
	"Price Target - Median (1W Ago)"      text,
	"Price Target - Median (1M Ago)"      text,
	"Price Target - Median (3M Ago)"      text,
	"Price Target - Median (6M Ago)"      text,
	"Price Target - Median (MTD Ago)"     text,
	"Price Target - Median (QTD Ago)"     text,
	"Price Target - Median (YTD Ago)"     text,
	"Price Target - Median (1Y Ago)"      text,
	"FCF - Est Avg (FY1E)"                text,
	"FCF - Est Avg (FY2E)"                text,
	"FCF - Est Avg (FY3E)"                text,
	"FCF - Est Avg (FY4E)"                text,
	"FCF - Est Avg (FY5E)"                text,
	"EPS (-0FYSurprise %)"                text,
	"EPS (-1FYSurprise %)"                text,
	"EPS (-0FQSurprise %)"                text,
	"EPS (-1FQSurprise %)"                text,
	"EPS (-2FQSurprise %)"                text,
	"EPS (-3FQSurprise %)"                text,
	"EPS (-4FQSurprise %)"                text,
	"FCF (LTM)"                           text,
	"FCF (FQ)"                            text,
	"FCF (-1FQFQ)"                        text,
	"FCF (-3FQFQ)"                        text,
	"FCF (-4FQFQ)"                        text,
	"FCF (-2FQFQ)"                        text,
	"FCF (FY)"                            text,
	"FCF (-1FY)"                          text,
	"Target % (Avg)"                      text,
	"Target % (Med)"                      text,
	"Target % (Low)"                      text,
	"Target % (High)"                     text,
	"Price Target - StdDev"               text,
	"Price Target - StdDev (1W Ago)"      text,
	"Price Target - StdDev (1M Ago)"      text,
	"Price Target - StdDev (3M Ago)"      text,
	"Price Target - StdDev (6M Ago)"      text,
	"Price Target - StdDev (1Y Ago)"      text,
	"Altman Z-Score (-1FY)"               text,
	"Altman Z-Score (-1FQFQ)"             text,
	"Altman Z-Score (-2FQFQ)"             text,
	"Altman Z-Score (-3FQFQ)"             text,
	"Altman Z-Score (-4FQFQ)"             text,
	"Altman Z-Score (-0FYYoYLTM)"         text,
	"Altman Z-Score (-1FYYoYLTM)"         text,
	"P/E (EST FY2)"                       text,
	"P/E (EST FY3)"                       text,
	"P/E (EST FY4)"                       text,
	"P/E (EST FY5)"                       text,
	"P/E (-4FYLTM)"                       text,
	"P/E (-4FQLTM)"                       text,
	"EPS Norm - Est Avg (FQ1E)"           text,
	"EPS Norm - Est Avg (FQ2E)"           text,
	"EPS Norm - Est Avg (FQ3E)"           text,
	"EPS Norm - Est Avg (FQ4E)"           text,
	"EPS Norm - Est Avg (FY2E)"           text,
	"EPS Norm - Est Avg (FY3E)"           text,
	"EPS Norm - Est Avg (FY4E)"           text,
	"EPS Norm - Est Avg (FY5E)"           text,
	"Capital Expenditure (LTM)"           text,
	"Capital Expenditure (FQ)"            text,
	"Capital Expenditure (FY)"            text,
	"Capital Expenditure (-1FQFQ)"        text,
	"Capital Expenditure (-2FQFQ)"        text,
	"Capital Expenditure (-3FQFQ)"        text,
	"Capital Expenditure (-4FQFQ)"        text,
	"CFF (LTM)"                           text,
	"CFF (FQ)"                            text,
	"CFF (FY)"                            text,
	"CFF (-1FQFQ)"                        text,
	"CFF (-2FQFQ)"                        text,
	"CFF (-3FQFQ)"                        text,
	"CFF (-4FQFQ)"                        text,
	"CFF (-1FY)"                          text,
	"CFI (LTM)"                           text,
	"CFI (FQ)"                            text,
	"CFI (FY)"                            text,
	"CFI (-1FQFQ)"                        text,
	"CFI (-2FQFQ)"                        text,
	"CFI (-3FQFQ)"                        text,
	"CFI (-4FQFQ)"                        text,
	"CFI (-1FY)"                          text,
	"CFO (LTM)"                           text,
	"CFO (FQ)"                            text,
	"CFO (FY)"                            text,
	"CFO (-1FQFQ)"                        text,
	"CFO (-2FQFQ)"                        text,
	"CFO (-4FQFQ)"                        text,
	"CFO (-3FQFQ)"                        text,
	"CFO (-1FY)"                          text,
	"Dividend Per Share (FQ)"             text,
	"Dividend Per Share (FY)"             text,
	"Dividend Per Share (-1FQFQ)"         text,
	"Dividend Per Share (-2FQFQ)"         text,
	"Dividend Per Share (-3FQFQ)"         text,
	"Dividend Per Share (-4FQFQ)"         text,
	"Dividend Per Share (-1FY)"           text,
	"Volatility (1M)"                     text,
	"Volatility (3M)"                     text,
	"Volatility (6M)"                     text,
	"Volatility (1Y)"                     text,
	"EPS GAAP Est Avg Rev % (FY1E - 1W)"  text,
	"EPS GAAP Est Avg Rev % (FY1E - MTD)" text,
	"EPS GAAP Est Avg Rev % (FY1E - QTD)" text,
	"EPS GAAP Est Avg Rev % (FY1E - YTD)" text,
	"Price Target - StdDev (MTD Ago)"     text,
	"Price Target - StdDev (QTD Ago)"     text,
	"Price Target - StdDev (YTD Ago)"     text,
	"EBIT (-0FQSurprise %)"               text,
	"EBIT (-1FQSurprise %)"               text,
	"EBIT (-2FQSurprise %)"               text,
	"EBIT (-3FQSurprise %)"               text,
	"EBIT (-4FQSurprise %)"               text,
	"EBIT (-0FYSurprise %)"               text,
	"EBIT (-1FYSurprise %)"               text,
	"EBITDA (-0FQSurprise %)"             text,
	"EBITDA (-1FQSurprise %)"             text,
	"EBITDA (-2FQSurprise %)"             text,
	"EBITDA (-3FQSurprise %)"             text,
	"EBITDA (-4FQSurprise %)"             text,
	"EBITDA (-0FYSurprise %)"             text,
	"EBITDA (-1FYSurprise %)"             text,
	"Price (1D Ago)"                      text,
	"Price (YTD Ago)"                     text,
	"Price (MTD Ago)"                     text,
	"Sales (-0FQSurprise %)"              text,
	"Sales (-1FQSurprise %)"              text,
	"Sales (-2FQSurprise %)"              text,
	"Sales (-3FQSurprise %)"              text,
	"Sales (-4FQSurprise %)"              text,
	"Sales (-0FYSurprise %)"              text,
	"Sales (-1FYSurprise %)"              text,
	"FCF / Share (LTM)"                   text,
	"FCF / Share (FQ)"                    text,
	"FCF / Share (FY)"                    text,
	"FCF / Share (-1FQFQ)"                text,
	"FCF / Share (-2FQFQ)"                text,
	"FCF / Share (-3FQFQ)"                text,
	"FCF / Share (-4FQFQ)"                text,
	"FCF / Share (-1FY)"                  text,
	"PEG (-1FY)"                          text,
	"Gross Profit Margin % (FQ)"          text,
	"Gross Profit Margin % (-1FQFQ)"      text,
	"Gross Profit Margin % (-2FQFQ)"      text,
	"Gross Profit Margin % (-3FQFQ)"      text,
	"Gross Profit Margin % (-4FQFQ)"      text,
	"Gross Profit Margin % (-1FY)"        text,
	"Total Return (QTD)"                  text,
	"Total Return (2025)"                 text,
	"Total Return (2024)"                 text,
	"Total Return (2023)"                 text,
	"Total Return (2022)"                 text,
	"Total Return (2021)"                 text,
	"Return on Assets (ROA) % (FQ)"       text,
	"Return on Assets (ROA) % (-1FQFQ)"   text,
	"Return on Assets (ROA) % (-2FQFQ)"   text,
	"Return on Assets (ROA) % (-3FQFQ)"   text,
	"Return on Assets (ROA) % (-4FQFQ)"   text,
	"Return on Assets (ROA) % (-1FY)"     text,
	"Asset Turnover (FQ)"                 text,
	"Asset Turnover (FY)"                 text,
	"Asset Turnover (-1FY)"               text,
	"Asset Turnover (-1FQFQ)"             text,
	"Asset Turnover (-2FQFQ)"             text,
	"Asset Turnover (-3FQFQ)"             text,
	"Asset Turnover (-4FQFQ)"             text,
	"Quick Ratio (LTM)"                   text,
	"Quick Ratio (FQ)"                    text,
	"Quick Ratio (FY)"                    text,
	"Quick Ratio (-1FQFQ)"                text,
	"Quick Ratio (-2FQFQ)"                text,
	"Quick Ratio (-3FQFQ)"                text,
	"Quick Ratio (-4FQFQ)"                text,
	"Quick Ratio (-1FY)"                  text,
	"Current Ratio (LTM)"                 text,
	"Current Ratio (FQ)"                  text,
	"Current Ratio (FY)"                  text,
	"Current Ratio (-1FQFQ)"              text,
	"Current Ratio (-2FQFQ)"              text,
	"Current Ratio (-3FQFQ)"              text,
	"Current Ratio (-4FQFQ)"              text,
	"Current Ratio (-1FY)"                text,
	"Long Term Debt / Equity (LTM)"       text,
	"Long Term Debt / Equity (FQ)"        text,
	"Long Term Debt / Equity (FY)"        text,
	"Long Term Debt / Equity (-1FQFQ)"    text,
	"Long Term Debt / Equity (-2FQFQ)"    text,
	"Long Term Debt / Equity (-3FQFQ)"    text,
	"Long Term Debt / Equity (-4FQFQ)"    text,
	"Long Term Debt / Equity (-1FY)"      text,
	"Net Income - (IS) (LTM)"             text,
	"Net Income - (IS) (FQ)"              text,
	"Net Income - (IS) (FY)"              text,
	"Net Income - (IS) (-1FQFQ)"          text,
	"Net Income - (IS) (-2FQFQ)"          text,
	"Net Income - (IS) (-3FQFQ)"          text,
	"Net Income - (IS) (-4FQFQ)"          text,
	"Net Income - (IS) (-1FY)"            text,
	"Price Chg. % (1D)"                   text,
	"Price Chg. % (5D)"                   text,
	"Price Chg. % (1W)"                   text,
	"Price Chg. % (1M)"                   text,
	"Price Chg. % (3M)"                   text,
	"Price Chg. % (6M)"                   text,
	"Price Chg. % (1Y)"                   text,
	"Price Chg. % (QTD)"                  text,
	"Price Chg. % (YTD)"                  text,
	"Price Chg. % (MTD)"                  text,
	"Buyback Yield (-1FY)"                text,
	"Buyback Yield (-1FQ)"                text,
	"Buyback Yield (-2FQ)"                text,
	"Buyback Yield (-3FQ)"                text,
	"Buyback Yield (-4FQ)"                text,
	"Book Value / Share (LTM)"            text,
	"Book Value / Share (FQ)"             text,
	"Book Value / Share (FY)"             text,
	"Book Value / Share (-1FQ)"           text,
	"Book Value / Share (-2FQ)"           text,
	"Book Value / Share (-3FQ)"           text,
	"Book Value / Share (-4FQ)"           text,
	"Book Value / Share (-1FY)"           text,
	"Above 52W Low %/Adj"                 text,
	"Below 52W High %/Adj"                text,
	"Insider B/S 1M"                      text,
	"Insider B/S 3M"                      text,
	"Insider B/S 6M"                      text,
	"Insider B/S 12M"                     text,
	"Top 5 Inst Own"                      text,
	"Top 10 Inst Own"                     text,
	"Top 20 Inst Own"                     text,
	"Top 5 Insider Own"                   text,
	"Top 10 Insider Own"                  text,
	"Top 20 Insider Own"                  text,
	"Return On Equity % (LTM)"            text,
	"Return On Equity % (FQ)"             text,
	"Return On Equity % (FY)"             text,
	"Return On Equity % (-1FQFQ)"         text,
	"Return On Equity % (-2FQFQ)"         text,
	"Return On Equity % (-3FQFQ)"         text,
	"Return On Equity % (-4FQFQ)"         text,
	"Return On Equity % (-1FY)"           text,
	"ROE - Est Med (FY1E)"                text,
	"ROE - Est Med (FY2E)"                text,
	"ROE - Est Med (FY3E)"                text,
	"ROE - Est Med (FY4E)"                text,
	"ROE - Est Med (FQ1E)"                text,
	"ROE - Est Med (FQ2E)"                text,
	"ROE - Est Med (FQ3E)"                text,
	"ROE - Est Med (FQ4E)"                text,
	"EMA (5D)"                            text,
	"EMA (8D)"                            text,
	"EMA (10D)"                           text,
	"EMA (21D)"                           text,
	"EMA (100D)"                          text,
	"EMA (150D)"                          text,
	"EMA (200D)"                          text,
	"EMA (300D)"                          text,
	"EPS GAAP (-0FQSurprise %)"           text,
	"EPS GAAP (-1FQSurprise %)"           text,
	"EPS GAAP (-2FQSurprise %)"           text,
	"EPS GAAP (-3FQSurprise %)"           text,
	"EPS GAAP (-4FQSurprise %)"           text,
	"EPS GAAP (-0FYSurprise %)"           text,
	"EPS GAAP (-1FYSurprise %)"           text,
	"Shareholder Yld (LTM)"               text,
	"Shareholder Yld (-1FQ)"              text,
	"Shareholder Yld (-2FQ)"              text,
	"Shareholder Yld (-3FQ)"              text,
	"Shareholder Yld (-4FQ)"              text,
	"Shareholder Yld (-1FY)"              text
)
;

alter table equities
	owner to postgres
;