create table equities.equities_df
(
	ticker                                varchar,
	isin                                  varchar,
	name                                  varchar,
	description                           varchar,
	"Equity Type"                         text,
	"Trading Region"                      text,
	"Trading Country"                     text,
	exchange                              text,
	unit                                  text,
	region                                text,
	country                               text,
	sector                                text,
	industry                              text,
	"Style Class"                         text,
	"Size Class"                          text,
	"Last Updated"                        text,
	"Income Statement Report Date"        text,
	"FY End"                              text,
	"52W High Date/Adj"                   text,
	"52W Low Date/Adj"                    text,
	"Next Earnings"                       text,
	"Next Earnings (When)"                text,
	"Next Earnings (Status)"              text,
	"Dividend Record (Currency)"          text,
	"Dividend Record (Amount)"            double precision,
	"Dividend Record (Frequency)"         text,
	"Dividend Streak"                     integer,
	"Dividend Record (Announce Date)"     text,
	"Dividend Record (Payable Date)"      text,
	"Dividend Record (Record Date)"       text,
	"Dividend Record (Ex Date)"           text,
	"Market Cap"                          double precision,
	"Enterprise Value"                    double precision,
	"Last Price"                          double precision,
	"Price Target (YTD Ago)"              double precision,
	"Total Return (YTD)"                  double precision,
	"Price Target"                        double precision,
	"Price Target - Low"                  double precision,
	"Price Target - Median"               double precision,
	"Price Target - High"                 double precision,
	"Price Target - #"                    double precision,
	"P/E (NTM)"                           double precision,
	"P/E (LTM)"                           double precision,
	"Altman Z-Score (FY)"                 double precision,
	"Altman Z-Score (FQ)"                 double precision,
	"Altman Z-Score (LTM)"                double precision,
	"Beta (1Y)"                           double precision,
	"Beta (2Y)"                           double precision,
	"Beta (5Y)"                           double precision,
	"Analyst Rating"                      double precision,
	"# Strong Sell Ratings"               integer,
	"# Strong Buys Ratings"               integer,
	"# Hold Ratings"                      integer,
	"# Buys Ratings"                      integer,
	"# Sell Ratings"                      integer,
	"# No Opinion Ratings"                integer,
	"Market Cap (Country R)"              integer,
	"Volume (Shrs)"                       integer,
	"Dividend Per Share (LTM)"            double precision,
	"Div Yield (Ind)"                     double precision,
	"Div Yield (LTM)"                     double precision,
	"Gross Profit Margin % (FY)"          double precision,
	"Gross Profit Margin % (LTM)"         double precision,
	"EPS Norm - Est Avg (NTM)"            double precision,
	"EPS/Adj. (-1FY)"                     double precision,
	"EPS/Adj. (FY)"                       double precision,
	"EPS/Adj. (LTM)"                      double precision,
	"EPS Norm - Est Avg (FY1E)"           double precision,
	"Buyback Yield (LTM)"                 double precision,
	"Return on Assets (ROA) % (LTM)"      double precision,
	"Return on Assets (ROA) % (FY)"       double precision,
	"Div Yield (-1FYInd)"                 double precision,
	"P/B (LTM)"                           double precision,
	"P/B (-1FY)"                          double precision,
	"Div Yield (TTM)"                     double precision,
	"Div Yield (NTM)"                     double precision,
	"Rel. Volume"                         integer,
	"Avg Volume"                          integer,
	"Common Dividends Paid (LTM)"         double precision,
	"Common Dividends Paid (FY)"          double precision,
	"52W High/Adj"                        double precision,
	"52W Low/Adj"                         double precision,
	"EMA (20D)"                           double precision,
	"EMA (50D)"                           double precision,
	"EMA (250D)"                          double precision,
	"P/E (EST FY1)"                       double precision,
	"P/E (-1FYLTM)"                       double precision,
	"P/E (-2FYLTM)"                       double precision,
	"P/E (-3FYLTM)"                       double precision,
	"P/E (-1FQLTM)"                       double precision,
	"P/E (-2FQLTM)"                       double precision,
	"P/E (-3FQLTM)"                       double precision,
	"P/E (-0FQQoQLTM)"                    double precision,
	"P/E (-0FYYoYLTM)"                    double precision,
	"P/E (-1FYYoYLTM)"                    double precision,
	"P/E (-0FQYoYLTM)"                    double precision,
	"Full Time Employees (FQ)"            integer,
	"Full Time Employees (FY)"            integer,
	"Full Time Employees (-1FY)"          integer,
	"EPS Est Avg Rev % (FY1E - 1W)"       double precision,
	"EPS Est Avg Rev % (FY1E - 1M)"       double precision,
	"EPS Est Avg Rev % (FY1E - 3M)"       double precision,
	"EPS Est Avg Rev % (FY1E - 6M)"       double precision,
	"EPS Est Avg Rev % (FY1E - 1Y)"       double precision,
	"EBITDA - Est Avg (NTM)"              double precision,
	"EBITDA - Est Avg (FY1E)"             double precision,
	"EPS GAAP - Est Avg (NTM)"            double precision,
	"EPS GAAP - Est Avg (FY1E)"           double precision,
	"EPS GAAP Est Avg Rev % (FY1E - 1M)"  double precision,
	"EPS GAAP Est Avg Rev % (FY1E - 3M)"  double precision,
	"EPS GAAP Est Avg Rev % (FY1E - 6M)"  double precision,
	"EPS GAAP Est Avg Rev % (FY1E - 1Y)"  double precision,
	"EPS Norm - Est # (FY1E)"             integer,
	"Price Target (1W Ago)"               double precision,
	"Price Target (1M Ago)"               double precision,
	"Price Target (3M Ago)"               double precision,
	"Price Target (6M Ago)"               double precision,
	"Price Target (MTD Ago)"              double precision,
	"Price Target (QTD Ago)"              double precision,
	"Price Target (1Y Ago)"               double precision,
	"Price Target - # (3M Ago)"           double precision,
	"Price Target - # (6M Ago)"           double precision,
	"Price Target - # (YTD Ago)"          double precision,
	"Price Target - # (1Y Ago)"           double precision,
	"Price Target - # (1W Ago)"           double precision,
	"Price Target - # (1M Ago)"           double precision,
	"Price Target - # (MTD Ago)"          double precision,
	"Price Target - # (QTD Ago)"          double precision,
	"Price Target - High (1W Ago)"        double precision,
	"Price Target - High (1M Ago)"        double precision,
	"Price Target - High (6M Ago)"        double precision,
	"Price Target - High (MTD Ago)"       double precision,
	"Price Target - High (3M Ago)"        double precision,
	"Price Target - High (QTD Ago)"       double precision,
	"Price Target - High (1Y Ago)"        double precision,
	"Price Target - High (YTD Ago)"       double precision,
	"Price Target - Low (1W Ago)"         double precision,
	"Price Target - Low (1M Ago)"         double precision,
	"Price Target - Low (3M Ago)"         double precision,
	"Price Target - Low (6M Ago)"         double precision,
	"Price Target - Low (MTD Ago)"        double precision,
	"Price Target - Low (QTD Ago)"        double precision,
	"Price Target - Low (YTD Ago)"        double precision,
	"Price Target - Low (1Y Ago)"         double precision,
	"Price Target - Median (1W Ago)"      double precision,
	"Price Target - Median (1M Ago)"      double precision,
	"Price Target - Median (3M Ago)"      double precision,
	"Price Target - Median (6M Ago)"      double precision,
	"Price Target - Median (MTD Ago)"     double precision,
	"Price Target - Median (QTD Ago)"     double precision,
	"Price Target - Median (YTD Ago)"     double precision,
	"Price Target - Median (1Y Ago)"      double precision,
	"FCF - Est Avg (FY1E)"                double precision,
	"FCF - Est Avg (FY2E)"                double precision,
	"FCF - Est Avg (FY3E)"                double precision,
	"FCF - Est Avg (FY4E)"                double precision,
	"FCF - Est Avg (FY5E)"                double precision,
	"EPS (-0FYSurprise %)"                double precision,
	"EPS (-1FYSurprise %)"                double precision,
	"EPS (-0FQSurprise %)"                double precision,
	"EPS (-1FQSurprise %)"                double precision,
	"EPS (-2FQSurprise %)"                double precision,
	"EPS (-3FQSurprise %)"                double precision,
	"EPS (-4FQSurprise %)"                double precision,
	"FCF (LTM)"                           double precision,
	"FCF (FQ)"                            double precision,
	"FCF (-1FQFQ)"                        double precision,
	"FCF (-3FQFQ)"                        double precision,
	"FCF (-4FQFQ)"                        double precision,
	"FCF (-2FQFQ)"                        double precision,
	"FCF (FY)"                            double precision,
	"FCF (-1FY)"                          double precision,
	"Target % (Avg)"                      double precision,
	"Target % (Med)"                      double precision,
	"Target % (Low)"                      double precision,
	"Target % (High)"                     double precision,
	"Price Target - StdDev"               double precision,
	"Price Target - StdDev (1W Ago)"      double precision,
	"Price Target - StdDev (1M Ago)"      double precision,
	"Price Target - StdDev (3M Ago)"      double precision,
	"Price Target - StdDev (6M Ago)"      double precision,
	"Price Target - StdDev (1Y Ago)"      double precision,
	"Altman Z-Score (-1FY)"               double precision,
	"Altman Z-Score (-1FQFQ)"             double precision,
	"Altman Z-Score (-2FQFQ)"             double precision,
	"Altman Z-Score (-3FQFQ)"             double precision,
	"Altman Z-Score (-4FQFQ)"             double precision,
	"Altman Z-Score (-0FYYoYLTM)"         double precision,
	"Altman Z-Score (-1FYYoYLTM)"         double precision,
	"P/E (EST FY2)"                       double precision,
	"P/E (EST FY3)"                       double precision,
	"P/E (EST FY4)"                       double precision,
	"P/E (EST FY5)"                       double precision,
	"P/E (-4FYLTM)"                       double precision,
	"P/E (-4FQLTM)"                       double precision,
	"EPS Norm - Est Avg (FQ1E)"           double precision,
	"EPS Norm - Est Avg (FQ2E)"           double precision,
	"EPS Norm - Est Avg (FQ3E)"           double precision,
	"EPS Norm - Est Avg (FQ4E)"           double precision,
	"EPS Norm - Est Avg (FY2E)"           double precision,
	"EPS Norm - Est Avg (FY3E)"           double precision,
	"EPS Norm - Est Avg (FY4E)"           double precision,
	"EPS Norm - Est Avg (FY5E)"           double precision,
	"Capital Expenditure (LTM)"           double precision,
	"Capital Expenditure (FQ)"            double precision,
	"Capital Expenditure (FY)"            double precision,
	"Capital Expenditure (-1FQFQ)"        double precision,
	"Capital Expenditure (-2FQFQ)"        double precision,
	"Capital Expenditure (-3FQFQ)"        double precision,
	"Capital Expenditure (-4FQFQ)"        double precision,
	"CFF (LTM)"                           double precision,
	"CFF (FQ)"                            double precision,
	"CFF (FY)"                            double precision,
	"CFF (-1FQFQ)"                        double precision,
	"CFF (-2FQFQ)"                        double precision,
	"CFF (-3FQFQ)"                        double precision,
	"CFF (-4FQFQ)"                        double precision,
	"CFF (-1FY)"                          double precision,
	"CFI (LTM)"                           double precision,
	"CFI (FQ)"                            double precision,
	"CFI (FY)"                            double precision,
	"CFI (-1FQFQ)"                        double precision,
	"CFI (-2FQFQ)"                        double precision,
	"CFI (-3FQFQ)"                        double precision,
	"CFI (-4FQFQ)"                        double precision,
	"CFI (-1FY)"                          double precision,
	"CFO (LTM)"                           double precision,
	"CFO (FQ)"                            double precision,
	"CFO (FY)"                            double precision,
	"CFO (-1FQFQ)"                        double precision,
	"CFO (-2FQFQ)"                        double precision,
	"CFO (-4FQFQ)"                        double precision,
	"CFO (-3FQFQ)"                        double precision,
	"CFO (-1FY)"                          double precision,
	"Dividend Per Share (FQ)"             double precision,
	"Dividend Per Share (FY)"             double precision,
	"Dividend Per Share (-1FQFQ)"         double precision,
	"Dividend Per Share (-2FQFQ)"         double precision,
	"Dividend Per Share (-3FQFQ)"         double precision,
	"Dividend Per Share (-4FQFQ)"         double precision,
	"Dividend Per Share (-1FY)"           double precision,
	"Volatility (1M)"                     double precision,
	"Volatility (3M)"                     double precision,
	"Volatility (6M)"                     double precision,
	"Volatility (1Y)"                     double precision,
	"EPS GAAP Est Avg Rev % (FY1E - 1W)"  double precision,
	"EPS GAAP Est Avg Rev % (FY1E - MTD)" double precision,
	"EPS GAAP Est Avg Rev % (FY1E - QTD)" double precision,
	"EPS GAAP Est Avg Rev % (FY1E - YTD)" double precision,
	"Price Target - StdDev (MTD Ago)"     double precision,
	"Price Target - StdDev (QTD Ago)"     double precision,
	"Price Target - StdDev (YTD Ago)"     double precision,
	"EBIT (-0FQSurprise %)"               double precision,
	"EBIT (-1FQSurprise %)"               double precision,
	"EBIT (-2FQSurprise %)"               double precision,
	"EBIT (-3FQSurprise %)"               double precision,
	"EBIT (-4FQSurprise %)"               double precision,
	"EBIT (-0FYSurprise %)"               double precision,
	"EBIT (-1FYSurprise %)"               double precision,
	"EBITDA (-0FQSurprise %)"             double precision,
	"EBITDA (-1FQSurprise %)"             double precision,
	"EBITDA (-2FQSurprise %)"             double precision,
	"EBITDA (-3FQSurprise %)"             double precision,
	"EBITDA (-4FQSurprise %)"             double precision,
	"EBITDA (-0FYSurprise %)"             double precision,
	"EBITDA (-1FYSurprise %)"             double precision,
	"Price (1D Ago)"                      double precision,
	"Price (YTD Ago)"                     double precision,
	"Price (MTD Ago)"                     double precision,
	"Sales (-0FQSurprise %)"              double precision,
	"Sales (-1FQSurprise %)"              double precision,
	"Sales (-2FQSurprise %)"              double precision,
	"Sales (-3FQSurprise %)"              double precision,
	"Sales (-4FQSurprise %)"              double precision,
	"Sales (-0FYSurprise %)"              double precision,
	"Sales (-1FYSurprise %)"              double precision,
	"FCF / Share (LTM)"                   double precision,
	"FCF / Share (FQ)"                    double precision,
	"FCF / Share (FY)"                    double precision,
	"FCF / Share (-1FQFQ)"                double precision,
	"FCF / Share (-2FQFQ)"                double precision,
	"FCF / Share (-3FQFQ)"                double precision,
	"FCF / Share (-4FQFQ)"                double precision,
	"FCF / Share (-1FY)"                  double precision,
	"PEG (-1FY)"                          double precision,
	"Gross Profit Margin % (FQ)"          double precision,
	"Gross Profit Margin % (-1FQFQ)"      double precision,
	"Gross Profit Margin % (-2FQFQ)"      double precision,
	"Gross Profit Margin % (-3FQFQ)"      double precision,
	"Gross Profit Margin % (-4FQFQ)"      double precision,
	"Gross Profit Margin % (-1FY)"        double precision,
	"Total Return (QTD)"                  double precision,
	"Total Return (2025)"                 double precision,
	"Total Return (2024)"                 double precision,
	"Total Return (2023)"                 double precision,
	"Total Return (2022)"                 double precision,
	"Total Return (2021)"                 double precision,
	"Return on Assets (ROA) % (FQ)"       double precision,
	"Return on Assets (ROA) % (-1FQFQ)"   double precision,
	"Return on Assets (ROA) % (-2FQFQ)"   double precision,
	"Return on Assets (ROA) % (-3FQFQ)"   double precision,
	"Return on Assets (ROA) % (-4FQFQ)"   double precision,
	"Return on Assets (ROA) % (-1FY)"     double precision,
	"Asset Turnover (FQ)"                 double precision,
	"Asset Turnover (FY)"                 double precision,
	"Asset Turnover (-1FY)"               double precision,
	"Asset Turnover (-1FQFQ)"             double precision,
	"Asset Turnover (-2FQFQ)"             double precision,
	"Asset Turnover (-3FQFQ)"             double precision,
	"Asset Turnover (-4FQFQ)"             double precision,
	"Quick Ratio (LTM)"                   double precision,
	"Quick Ratio (FQ)"                    double precision,
	"Quick Ratio (FY)"                    double precision,
	"Quick Ratio (-1FQFQ)"                double precision,
	"Quick Ratio (-2FQFQ)"                double precision,
	"Quick Ratio (-3FQFQ)"                double precision,
	"Quick Ratio (-4FQFQ)"                double precision,
	"Quick Ratio (-1FY)"                  double precision,
	"Current Ratio (LTM)"                 double precision,
	"Current Ratio (FQ)"                  double precision,
	"Current Ratio (FY)"                  double precision,
	"Current Ratio (-1FQFQ)"              double precision,
	"Current Ratio (-2FQFQ)"              double precision,
	"Current Ratio (-3FQFQ)"              double precision,
	"Current Ratio (-4FQFQ)"              double precision,
	"Current Ratio (-1FY)"                double precision,
	"Long Term Debt / Equity (LTM)"       double precision,
	"Long Term Debt / Equity (FQ)"        double precision,
	"Long Term Debt / Equity (FY)"        double precision,
	"Long Term Debt / Equity (-1FQFQ)"    double precision,
	"Long Term Debt / Equity (-2FQFQ)"    double precision,
	"Long Term Debt / Equity (-3FQFQ)"    double precision,
	"Long Term Debt / Equity (-4FQFQ)"    double precision,
	"Long Term Debt / Equity (-1FY)"      double precision,
	"Net Income - (IS) (LTM)"             double precision,
	"Net Income - (IS) (FQ)"              double precision,
	"Net Income - (IS) (FY)"              double precision,
	"Net Income - (IS) (-1FQFQ)"          double precision,
	"Net Income - (IS) (-2FQFQ)"          double precision,
	"Net Income - (IS) (-3FQFQ)"          double precision,
	"Net Income - (IS) (-4FQFQ)"          double precision,
	"Net Income - (IS) (-1FY)"            double precision,
	"Price Chg. % (1D)"                   double precision,
	"Price Chg. % (5D)"                   double precision,
	"Price Chg. % (1W)"                   double precision,
	"Price Chg. % (1M)"                   double precision,
	"Price Chg. % (3M)"                   double precision,
	"Price Chg. % (6M)"                   double precision,
	"Price Chg. % (1Y)"                   double precision,
	"Price Chg. % (QTD)"                  double precision,
	"Price Chg. % (YTD)"                  double precision,
	"Price Chg. % (MTD)"                  double precision,
	"Buyback Yield (-1FY)"                double precision,
	"Buyback Yield (-1FQ)"                double precision,
	"Buyback Yield (-2FQ)"                double precision,
	"Buyback Yield (-3FQ)"                double precision,
	"Buyback Yield (-4FQ)"                double precision,
	"Book Value / Share (LTM)"            double precision,
	"Book Value / Share (FQ)"             double precision,
	"Book Value / Share (FY)"             double precision,
	"Book Value / Share (-1FQ)"           double precision,
	"Book Value / Share (-2FQ)"           double precision,
	"Book Value / Share (-3FQ)"           double precision,
	"Book Value / Share (-4FQ)"           double precision,
	"Book Value / Share (-1FY)"           double precision,
	"Above 52W Low %/Adj"                 double precision,
	"Below 52W High %/Adj"                double precision,
	"Insider B/S 1M"                      double precision,
	"Insider B/S 3M"                      double precision,
	"Insider B/S 6M"                      double precision,
	"Insider B/S 12M"                     double precision,
	"Top 5 Inst Own"                      double precision,
	"Top 10 Inst Own"                     double precision,
	"Top 20 Inst Own"                     double precision,
	"Top 5 Insider Own"                   double precision,
	"Top 10 Insider Own"                  double precision,
	"Top 20 Insider Own"                  double precision,
	"Return On Equity % (LTM)"            double precision,
	"Return On Equity % (FQ)"             double precision,
	"Return On Equity % (FY)"             double precision,
	"Return On Equity % (-1FQFQ)"         double precision,
	"Return On Equity % (-2FQFQ)"         double precision,
	"Return On Equity % (-3FQFQ)"         double precision,
	"Return On Equity % (-4FQFQ)"         double precision,
	"Return On Equity % (-1FY)"           double precision,
	"ROE - Est Med (FY1E)"                double precision,
	"ROE - Est Med (FY2E)"                double precision,
	"ROE - Est Med (FY3E)"                double precision,
	"ROE - Est Med (FY4E)"                double precision,
	"ROE - Est Med (FQ1E)"                double precision,
	"ROE - Est Med (FQ2E)"                double precision,
	"ROE - Est Med (FQ3E)"                double precision,
	"ROE - Est Med (FQ4E)"                double precision,
	"EMA (5D)"                            double precision,
	"EMA (8D)"                            double precision,
	"EMA (10D)"                           double precision,
	"EMA (21D)"                           double precision,
	"EMA (100D)"                          double precision,
	"EMA (150D)"                          double precision,
	"EMA (200D)"                          double precision,
	"EMA (300D)"                          double precision,
	"EPS GAAP (-0FQSurprise %)"           double precision,
	"EPS GAAP (-1FQSurprise %)"           double precision,
	"EPS GAAP (-2FQSurprise %)"           double precision,
	"EPS GAAP (-3FQSurprise %)"           double precision,
	"EPS GAAP (-4FQSurprise %)"           double precision,
	"EPS GAAP (-0FYSurprise %)"           double precision,
	"EPS GAAP (-1FYSurprise %)"           double precision,
	"Shareholder Yld (LTM)"               double precision,
	"Shareholder Yld (-1FQ)"              double precision,
	"Shareholder Yld (-2FQ)"              double precision,
	"Shareholder Yld (-3FQ)"              double precision,
	"Shareholder Yld (-4FQ)"              double precision,
	"Shareholder Yld (-1FY)"              double precision
)
;

alter table equities.equities_df
	owner to postgres
;