create view information_schema.vw_features_cashflow
            (isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
             dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
             next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
             dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
             dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
             next_fy_end_date, next_income_statement_report_date, reference_date, cfo_to_net_income, fcf_to_net_income,
             fcf_margin, cfo_growth_yoy, fcf_positive_ratio, acquisition_intensity, self_funding_ratio,
             fcf_positive_years, fcf_always_positive, capex_vs_5y_avg, underinvestment_flag, cfo_share_of_cf,
             cfi_share_of_cf, cff_share_of_cf, self_funding_flag, acquisition_to_fcf, sustainable_ma_flag,
             fcf_4q_improvement, cash_flow_quality_score, capex_yoy_growth, capex_qoq_growth, capex_3y_trend,
             capex_volatility, capex_acceleration, capex_cut_flag, overinvestment_flag, acquisitions_yoy_growth,
             acquisitions_vs_5y_avg, acquisitions_ltm_total, ma_intensity_score, serial_acquirer_flag,
             acquisition_pause_flag, total_investment_to_cfo, organic_vs_inorganic, investment_efficiency,
             cfo_quarterly_trend, cfo_yoy_quarterly, cfi_quarterly_trend, cff_quarterly_trend, fcf_quarterly_trend,
             cfo_positive_quarters, cfi_negative_quarters, cff_pattern_score, cash_burn_rate, cf_volatility_score,
             operating_cf_momentum, financing_dependency, cfo_fq, cfo_ltm, cfo_fy, fcf_fq, fcf_ltm, fcf_fy,
             cfo_growth_yoy_comp, fcf_growth_yoy, cfo_to_net_income_comp, fcf_margin_comp, fcf_yield,
             cfo_positive_years, fcf_positive_years_comp, cash_flow_quality_score_comp, fcf_est_fy1, fcf_est_fy2,
             fcf_est_fy3, fcf_est_fy4, fcf_est_fy5, fcf_est_growth_fy1_vs_ltm, fcf_est_growth_fy2_vs_fy1,
             fcf_est_growth_fy3_vs_fy2, fcf_est_growth_fy4_vs_fy3, fcf_est_growth_fy5_vs_fy4, fcf_est_cagr_3y,
             fcf_est_cagr_5y, fcf_est_margin_fy1, fcf_est_yield_fy1, fcf_est_growth_acceleration,
             fcf_est_growth_deceleration, fcf_est_trajectory_score, fcf_est_always_positive, fcf_est_vs_historical,
             fcf_est_capex_implied_ratio)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       cf.cfo_to_net_income,
       cf.fcf_to_net_income,
       cf.fcf_margin,
       cf.cfo_growth_yoy,
       cf.fcf_positive_ratio,
       cf.acquisition_intensity,
       cf.self_funding_ratio,
       ecf.fcf_positive_years,
       ecf.fcf_always_positive,
       ecf.capex_vs_5y_avg,
       ecf.underinvestment_flag,
       ecf.cfo_share_of_cf,
       ecf.cfi_share_of_cf,
       ecf.cff_share_of_cf,
       ecf.self_funding_flag,
       ecf.acquisition_to_fcf,
       ecf.sustainable_ma_flag,
       ecf.fcf_4q_improvement,
       ecf.cash_flow_quality_score,
       ecf.capex_yoy_growth,
       ecf.capex_qoq_growth,
       ecf.capex_3y_trend,
       ecf.capex_volatility,
       ecf.capex_acceleration,
       ecf.capex_cut_flag,
       ecf.overinvestment_flag,
       ecf.acquisitions_yoy_growth,
       ecf.acquisitions_vs_5y_avg,
       ecf.acquisitions_ltm_total,
       ecf.ma_intensity_score,
       ecf.serial_acquirer_flag,
       ecf.acquisition_pause_flag,
       ecf.total_investment_to_cfo,
       ecf.organic_vs_inorganic,
       ecf.investment_efficiency,
       ctf.cfo_quarterly_trend,
       ctf.cfo_yoy_quarterly,
       ctf.cfi_quarterly_trend,
       ctf.cff_quarterly_trend,
       ctf.fcf_quarterly_trend,
       ctf.cfo_positive_quarters,
       ctf.cfi_negative_quarters,
       ctf.cff_pattern_score,
       ctf.cash_burn_rate,
       ctf.cf_volatility_score,
       ctf.operating_cf_momentum,
       ctf.financing_dependency,
       cc.cfo_fq,
       cc.cfo_ltm,
       cc.cfo_fy,
       cc.fcf_fq,
       cc.fcf_ltm,
       cc.fcf_fy,
       cc.cfo_growth_yoy          AS cfo_growth_yoy_comp,
       cc.fcf_growth_yoy,
       cc.cfo_to_net_income       AS cfo_to_net_income_comp,
       cc.fcf_margin              AS fcf_margin_comp,
       cc.fcf_yield,
       cc.cfo_positive_years,
       cc.fcf_positive_years      AS fcf_positive_years_comp,
       cc.cash_flow_quality_score AS cash_flow_quality_score_comp,
       fge.fcf_est_fy1,
       fge.fcf_est_fy2,
       fge.fcf_est_fy3,
       fge.fcf_est_fy4,
       fge.fcf_est_fy5,
       fge.fcf_est_growth_fy1_vs_ltm,
       fge.fcf_est_growth_fy2_vs_fy1,
       fge.fcf_est_growth_fy3_vs_fy2,
       fge.fcf_est_growth_fy4_vs_fy3,
       fge.fcf_est_growth_fy5_vs_fy4,
       fge.fcf_est_cagr_3y,
       fge.fcf_est_cagr_5y,
       fge.fcf_est_margin_fy1,
       fge.fcf_est_yield_fy1,
       fge.fcf_est_growth_acceleration,
       fge.fcf_est_growth_deceleration,
       fge.fcf_est_trajectory_score,
       fge.fcf_est_always_positive,
       fge.fcf_est_vs_historical,
       fge.fcf_est_capex_implied_ratio
FROM information_schema.vw_identifier_columns id
         LEFT JOIN information_schema.calc_cashflow_features() cf(isin, cfo_to_net_income, fcf_to_net_income,
                                                                  fcf_margin, cfo_growth_yoy, fcf_positive_ratio,
                                                                  acquisition_intensity, self_funding_ratio)
                   USING (isin)
         LEFT JOIN information_schema.calc_enhanced_cashflow_features() ecf(isin, fcf_positive_years,
                                                                            fcf_always_positive, capex_vs_5y_avg,
                                                                            underinvestment_flag, cfo_share_of_cf,
                                                                            cfi_share_of_cf, cff_share_of_cf,
                                                                            self_funding_flag, acquisition_to_fcf,
                                                                            sustainable_ma_flag, fcf_4q_improvement,
                                                                            cash_flow_quality_score, capex_yoy_growth,
                                                                            capex_qoq_growth, capex_3y_trend,
                                                                            capex_volatility, capex_acceleration,
                                                                            capex_cut_flag, overinvestment_flag,
                                                                            acquisitions_yoy_growth,
                                                                            acquisitions_vs_5y_avg,
                                                                            acquisitions_ltm_total, ma_intensity_score,
                                                                            serial_acquirer_flag,
                                                                            acquisition_pause_flag,
                                                                            total_investment_to_cfo,
                                                                            organic_vs_inorganic, investment_efficiency)
                   USING (isin)
         LEFT JOIN information_schema.calc_cashflow_temporal_features() ctf(isin, cfo_quarterly_trend,
                                                                            cfo_yoy_quarterly, cfi_quarterly_trend,
                                                                            cff_quarterly_trend, fcf_quarterly_trend,
                                                                            cfo_positive_quarters,
                                                                            cfi_negative_quarters, cff_pattern_score,
                                                                            cash_burn_rate, cf_volatility_score,
                                                                            operating_cf_momentum, financing_dependency)
                   USING (isin)
         LEFT JOIN information_schema.calc_cashflow_comprehensive() cc(isin, cfo_fq, cfo_ltm, cfo_fy, fcf_fq, fcf_ltm,
                                                                       fcf_fy, cfo_growth_yoy, fcf_growth_yoy,
                                                                       cfo_to_net_income, fcf_margin, fcf_yield,
                                                                       cfo_positive_years, fcf_positive_years,
                                                                       cash_flow_quality_score) USING (isin)
         LEFT JOIN information_schema.calc_fcf_growth_estimates() fge(isin, fcf_est_fy1, fcf_est_fy2, fcf_est_fy3,
                                                                      fcf_est_fy4, fcf_est_fy5,
                                                                      fcf_est_growth_fy1_vs_ltm,
                                                                      fcf_est_growth_fy2_vs_fy1,
                                                                      fcf_est_growth_fy3_vs_fy2,
                                                                      fcf_est_growth_fy4_vs_fy3,
                                                                      fcf_est_growth_fy5_vs_fy4, fcf_est_cagr_3y,
                                                                      fcf_est_cagr_5y, fcf_est_margin_fy1,
                                                                      fcf_est_yield_fy1, fcf_est_growth_acceleration,
                                                                      fcf_est_growth_deceleration,
                                                                      fcf_est_trajectory_score, fcf_est_always_positive,
                                                                      fcf_est_vs_historical,
                                                                      fcf_est_capex_implied_ratio) USING (isin);

comment on view information_schema.vw_features_cashflow is 'Cash flow metrics including CFO, FCF, CapEx analysis, and cash flow quality.
    Source functions: calc_cashflow_features, calc_enhanced_cashflow_features,
    calc_cashflow_temporal_features, calc_cashflow_comprehensive';

alter table information_schema.vw_features_cashflow
    owner to postgres;

