create view information_schema.vw_features_dividends
            (isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
             dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
             next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
             dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
             dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
             next_fy_end_date, next_income_statement_report_date, reference_date, dividend_streak, dividend_yield_ltm,
             dividend_yield_ntm, dividend_payout_ratio, fcf_dividend_coverage, buyback_yield, total_shareholder_yield,
             dividend_growth_expectation, days_since_ex_date, days_to_payment, dividend_announced_flag,
             ex_date_approaching_flag, dividend_frequency_score, dividend_consistency, recent_dividend_change,
             dividend_yield_vs_5y_avg, div_yield_ltm, div_yield_ntm, div_yield_ind, div_yield_1fy_ind, div_yield_5y_avg,
             div_yield_vs_5y_avg, div_yield_growth_expected, dividend_streak_comp, high_yield_flag,
             sustainable_dividend_flag)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       df.dividend_streak,
       df.dividend_yield_ltm,
       df.dividend_yield_ntm,
       df.dividend_payout_ratio,
       df.fcf_dividend_coverage,
       df.buyback_yield,
       df.total_shareholder_yield,
       df.dividend_growth_expectation,
       dt.days_since_ex_date,
       dt.days_to_payment,
       dt.dividend_announced_flag,
       dt.ex_date_approaching_flag,
       dt.dividend_frequency_score,
       dt.dividend_consistency,
       dt.recent_dividend_change,
       dt.dividend_yield_vs_5y_avg,
       dyc.div_yield_ltm,
       dyc.div_yield_ntm,
       dyc.div_yield_ind,
       dyc.div_yield_1fy_ind,
       dyc.div_yield_5y_avg,
       dyc.div_yield_vs_5y_avg,
       dyc.div_yield_growth_expected,
       dyc.dividend_streak AS dividend_streak_comp,
       dyc.high_yield_flag,
       dyc.sustainable_dividend_flag
FROM information_schema.vw_identifier_columns id
         LEFT JOIN information_schema.calc_dividend_features() df(isin, dividend_streak, dividend_yield_ltm,
                                                                  dividend_yield_ntm, dividend_payout_ratio,
                                                                  fcf_dividend_coverage, buyback_yield,
                                                                  total_shareholder_yield, dividend_growth_expectation)
                   USING (isin)
         LEFT JOIN information_schema.calc_dividend_timing() dt(isin, days_since_ex_date, days_to_payment,
                                                                dividend_announced_flag, ex_date_approaching_flag,
                                                                dividend_frequency_score, dividend_consistency,
                                                                recent_dividend_change, dividend_yield_vs_5y_avg)
                   USING (isin)
         LEFT JOIN information_schema.calc_dividend_yield_comprehensive() dyc(isin, div_yield_ltm, div_yield_ntm,
                                                                              div_yield_ind, div_yield_1fy_ind,
                                                                              div_yield_5y_avg, div_yield_vs_5y_avg,
                                                                              div_yield_growth_expected,
                                                                              dividend_streak, high_yield_flag,
                                                                              sustainable_dividend_flag) USING (isin);

comment on view information_schema.vw_features_dividends is 'Dividend metrics including yield, payout ratios, timing, and sustainability.
    Source functions: calc_dividend_features, calc_dividend_timing, calc_dividend_yield_comprehensive';

alter table information_schema.vw_features_dividends
    owner to postgres;

