create view information_schema.vw_features_cost_structure
            (isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
             dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
             next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
             dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
             dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
             next_fy_end_date, next_income_statement_report_date, reference_date, cogs_to_revenue, opex_to_revenue,
             sga_to_revenue, rnd_to_revenue, interest_to_revenue, sga_trend_yoy, operating_leverage_proxy,
             cost_efficiency_score, marketing_to_revenue, marketing_trend_yoy, marketing_vs_5y_avg, sga_vs_5y_avg,
             sga_efficiency_trend, rnd_ltm, rnd_fq, rnd_fy, rnd_1fqfq, rnd_2fqfq, rnd_3fqfq, rnd_4fqfq, rnd_1fy,
             rnd_2fy, rnd_3fy, rnd_4fy, rnd_intensity_ltm, rnd_intensity_fy, rnd_intensity_trend, rnd_qoq_growth,
             rnd_yoy_growth, rnd_cagr_3y, rnd_per_employee, rnd_to_gross_profit, rnd_roi_proxy, rnd_increasing_flag,
             rnd_cut_flag, high_rnd_intensity_flag, interest_income_ltm, interest_expense_ltm, net_interest_income,
             interest_coverage_ratio, interest_income_to_revenue, interest_expense_to_revenue,
             net_interest_margin_proxy)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       csf.cogs_to_revenue,
       csf.opex_to_revenue,
       csf.sga_to_revenue,
       csf.rnd_to_revenue,
       csf.interest_to_revenue,
       csf.sga_trend_yoy,
       csf.operating_leverage_proxy,
       csf.cost_efficiency_score,
       csf.marketing_to_revenue,
       csf.marketing_trend_yoy,
       csf.marketing_vs_5y_avg,
       csf.sga_vs_5y_avg,
       csf.sga_efficiency_trend,
       rtf.rnd_ltm,
       rtf.rnd_fq,
       rtf.rnd_fy,
       rtf.rnd_1fqfq,
       rtf.rnd_2fqfq,
       rtf.rnd_3fqfq,
       rtf.rnd_4fqfq,
       rtf.rnd_1fy,
       rtf.rnd_2fy,
       rtf.rnd_3fy,
       rtf.rnd_4fy,
       rtf.rnd_intensity_ltm,
       rtf.rnd_intensity_fy,
       rtf.rnd_intensity_trend,
       rtf.rnd_qoq_growth,
       rtf.rnd_yoy_growth,
       rtf.rnd_cagr_3y,
       rtf.rnd_per_employee,
       rtf.rnd_to_gross_profit,
       rtf.rnd_roi_proxy,
       rtf.rnd_increasing_flag,
       rtf.rnd_cut_flag,
       rtf.high_rnd_intensity_flag,
       iif.interest_income_ltm,
       iif.interest_expense_ltm,
       iif.net_interest_income,
       iif.interest_coverage_ratio,
       iif.interest_income_to_revenue,
       iif.interest_expense_to_revenue,
       iif.net_interest_margin_proxy
FROM information_schema.vw_identifier_columns id
         LEFT JOIN information_schema.calc_cost_structure_features() csf(isin, cogs_to_revenue, opex_to_revenue,
                                                                         sga_to_revenue, rnd_to_revenue,
                                                                         interest_to_revenue, sga_trend_yoy,
                                                                         operating_leverage_proxy,
                                                                         cost_efficiency_score, marketing_to_revenue,
                                                                         marketing_trend_yoy, marketing_vs_5y_avg,
                                                                         sga_vs_5y_avg, sga_efficiency_trend)
                   USING (isin)
         LEFT JOIN information_schema.calc_rnd_temporal_features() rtf(isin, rnd_ltm, rnd_fq, rnd_fy, rnd_1fqfq,
                                                                       rnd_2fqfq, rnd_3fqfq, rnd_4fqfq, rnd_1fy,
                                                                       rnd_2fy, rnd_3fy, rnd_4fy, rnd_intensity_ltm,
                                                                       rnd_intensity_fy, rnd_intensity_trend,
                                                                       rnd_qoq_growth, rnd_yoy_growth, rnd_cagr_3y,
                                                                       rnd_per_employee, rnd_to_gross_profit,
                                                                       rnd_roi_proxy, rnd_increasing_flag, rnd_cut_flag,
                                                                       high_rnd_intensity_flag) USING (isin)
         LEFT JOIN information_schema.calc_interest_income_features() iif(isin, interest_income_ltm,
                                                                          interest_expense_ltm, net_interest_income,
                                                                          interest_coverage_ratio,
                                                                          interest_income_to_revenue,
                                                                          interest_expense_to_revenue,
                                                                          net_interest_margin_proxy) USING (isin);

comment on view information_schema.vw_features_cost_structure is 'Cost structure metrics including SG&A, R&D intensity, and interest analysis.
    Source functions: calc_cost_structure_features, calc_rnd_temporal_features, calc_interest_income_features';

alter table information_schema.vw_features_cost_structure
    owner to postgres;

