create view information_schema.vw_features_growth
            (isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
             dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
             next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
             dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
             dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
             next_fy_end_date, next_income_statement_report_date, reference_date, revenue_growth_yoy, ebitda_growth_yoy,
             operating_income_growth, fcf_growth, revenue_cagr_5y, forward_revenue_growth, revenue_vs_5y_avg,
             revenue_est_spread, revenue_beat_potential, revenue_est_revision_trend, ebitda_est_vs_actual,
             forward_revenue_multiple, revenue_estimate_count, revenue_guidance_gap, consensus_revenue_growth,
             ebit_estimate_spread, forward_ebitda_margin, revenue_acceleration, estimate_confidence_score,
             revenue_est_avg_fy1e, revenue_est_med_fy1e, revenue_est_avg_ntm, revenue_est_med_ntm,
             revenue_avg_med_diff_pct, revenue_consensus_strength, revenue_revision_trend_rec, revenue_vs_current,
             revenue_fq, revenue_fy, revenue_ltm, revenue_5y_avg, revenue_1fqfq, revenue_2fqfq, revenue_3fqfq,
             revenue_4fqfq, revenue_1fy, revenue_2fy, revenue_3fy, revenue_4fy, revenue_qoq_growth, revenue_qoq_2q,
             revenue_qoq_3q, revenue_qoq_4q, revenue_yoy_quarterly, revenue_2y_growth, revenue_3y_growth,
             revenue_4y_growth, revenue_cagr_3y, revenue_cagr_4y, revenue_4q_trend, revenue_4q_avg,
             revenue_fq_vs_4q_avg, revenue_growth_flag, revenue_stability_score, revenue_accelerating_flag,
             revenue_positive_qoq_streak, revenue_5yavgfq, revenue_5yavgltm, revenue_vs_5y_avg_fq,
             revenue_vs_5y_avg_ltm, revenue_fq_vs_avg, revenue_momentum)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       gf.revenue_growth_yoy,
       gf.ebitda_growth_yoy,
       gf.operating_income_growth,
       gf.fcf_growth,
       gf.revenue_cagr_5y,
       gf.forward_revenue_growth,
       gf.revenue_vs_5y_avg,
       rff.revenue_est_spread,
       rff.revenue_beat_potential,
       rff.revenue_est_revision_trend,
       rff.ebitda_est_vs_actual,
       rff.forward_revenue_multiple,
       rff.revenue_estimate_count,
       rff.revenue_guidance_gap,
       rff.consensus_revenue_growth,
       rff.ebit_estimate_spread,
       rff.forward_ebitda_margin,
       rff.revenue_acceleration,
       rff.estimate_confidence_score,
       rec.revenue_est_avg_fy1e,
       rec.revenue_est_med_fy1e,
       rec.revenue_est_avg_ntm,
       rec.revenue_est_med_ntm,
       rec.revenue_avg_med_diff_pct,
       rec.revenue_consensus_strength,
       rec.revenue_revision_trend AS revenue_revision_trend_rec,
       rec.revenue_vs_current,
       rqf.revenue_fq,
       rqf.revenue_fy,
       rqf.revenue_ltm,
       rqf.revenue_5y_avg,
       rqf.revenue_1fqfq,
       rqf.revenue_2fqfq,
       rqf.revenue_3fqfq,
       rqf.revenue_4fqfq,
       rqf.revenue_1fy,
       rqf.revenue_2fy,
       rqf.revenue_3fy,
       rqf.revenue_4fy,
       rqf.revenue_qoq_growth,
       rqf.revenue_qoq_2q,
       rqf.revenue_qoq_3q,
       rqf.revenue_qoq_4q,
       rqf.revenue_yoy_quarterly,
       rqf.revenue_2y_growth,
       rqf.revenue_3y_growth,
       rqf.revenue_4y_growth,
       rqf.revenue_cagr_3y,
       rqf.revenue_cagr_4y,
       rqf.revenue_4q_trend,
       rqf.revenue_4q_avg,
       rqf.revenue_fq_vs_4q_avg,
       rqf.revenue_growth_flag,
       rqf.revenue_stability_score,
       rqf.revenue_accelerating_flag,
       rqf.revenue_positive_qoq_streak,
       trt.revenue_5yavgfq,
       trt.revenue_5yavgltm,
       trt.revenue_vs_5y_avg_fq,
       trt.revenue_vs_5y_avg_ltm,
       trt.revenue_fq_vs_avg,
       trt.revenue_momentum
FROM information_schema.vw_identifier_columns id
         LEFT JOIN information_schema.calc_growth_features() gf(isin, revenue_growth_yoy, ebitda_growth_yoy,
                                                                operating_income_growth, fcf_growth, revenue_cagr_5y,
                                                                forward_revenue_growth, revenue_vs_5y_avg) USING (isin)
         LEFT JOIN information_schema.calc_revenue_forecast_features() rff(isin, revenue_est_spread,
                                                                           revenue_beat_potential,
                                                                           revenue_est_revision_trend,
                                                                           ebitda_est_vs_actual,
                                                                           forward_revenue_multiple,
                                                                           revenue_estimate_count, revenue_guidance_gap,
                                                                           consensus_revenue_growth,
                                                                           ebit_estimate_spread, forward_ebitda_margin,
                                                                           revenue_acceleration,
                                                                           estimate_confidence_score) USING (isin)
         LEFT JOIN information_schema.calc_revenue_estimate_consensus() rec(isin, revenue_est_avg_fy1e,
                                                                            revenue_est_med_fy1e, revenue_est_avg_ntm,
                                                                            revenue_est_med_ntm,
                                                                            revenue_avg_med_diff_pct,
                                                                            revenue_consensus_strength,
                                                                            revenue_revision_trend, revenue_vs_current)
                   USING (isin)
         LEFT JOIN information_schema.calc_revenue_quarterly_features() rqf(isin, revenue_fq, revenue_fy, revenue_ltm,
                                                                            revenue_5y_avg, revenue_1fqfq,
                                                                            revenue_2fqfq, revenue_3fqfq, revenue_4fqfq,
                                                                            revenue_1fy, revenue_2fy, revenue_3fy,
                                                                            revenue_4fy, revenue_yoy_growth,
                                                                            revenue_vs_5y_avg, revenue_ltm_vs_fy,
                                                                            revenue_fq_vs_5y_avg_fq, revenue_qoq_growth,
                                                                            revenue_qoq_2q, revenue_qoq_3q,
                                                                            revenue_qoq_4q, revenue_yoy_quarterly,
                                                                            revenue_2y_growth, revenue_3y_growth,
                                                                            revenue_4y_growth, revenue_cagr_3y,
                                                                            revenue_cagr_4y, revenue_4q_trend,
                                                                            revenue_4q_avg, revenue_fq_vs_4q_avg,
                                                                            revenue_growth_flag,
                                                                            revenue_stability_score,
                                                                            revenue_accelerating_flag,
                                                                            revenue_positive_qoq_streak) USING (isin)
         LEFT JOIN information_schema.calc_total_revenues_temporal() trt(isin, revenue_fq, revenue_ltm, revenue_fy,
                                                                         revenue_1fy, revenue_5yavgfq, revenue_5yavgltm,
                                                                         revenue_growth_yoy, revenue_vs_5y_avg_fq,
                                                                         revenue_vs_5y_avg_ltm, revenue_fq_vs_avg,
                                                                         revenue_momentum) USING (isin);

comment on view information_schema.vw_features_growth is 'Growth metrics including revenue, EBITDA, FCF growth rates and forecasts.
    Source functions: calc_growth_features, calc_revenue_forecast_features,
    calc_revenue_estimate_consensus, calc_revenue_quarterly_features, calc_total_revenues_temporal';

alter table information_schema.vw_features_growth
    owner to postgres;

