create table analytics."04_panel_frame_v2"
(
	isin                              text,
	ticker                            text,
	name                              text,
	trading_region                    text,
	region                            text,
	country                           text,
	country_name                      text,
	trading_country                   text,
	trading_country_name              text,
	exchange                          text,
	exchange_name                     text,
	unit                              text,
	unit_name                         text,
	style_class                       text,
	size_class                        text,
	sector                            text,
	industry                          text,
	last_updated                      date,
	income_statement_report_date      date,
	next_earnings                     date,
	next_earnings_when                text,
	next_earnings_status              text,
	fy_end_date                       date,
	next_fiscal_quarter               date,
	next_income_statement_report_date date,
	next_fy_end_date                  date,
	expected_report_date              date,
	days_to_next_earnings             bigint,
	days_since_last_report            bigint,
	days_to_next_fy_end               double precision,
	days_to_next_fiscal_quarter       double precision,
	days_to_next_report               double precision,
	days_to_expected_report           double precision,
	days_since_fy_end                 bigint,
	market_cap                        double precision,
	enterprise_value                  double precision,
	market_cap_global_r               bigint,
	market_cap_global_sec_r           bigint,
	market_cap_region_r               bigint,
	market_cap_region_sec_r           bigint,
	market_cap_country_r              bigint,
	market_cap_country_sec_r          bigint,
	feat_rel_volume                   double precision,
	observed_pt                       double precision,
	last_price                        double precision,
	price_target_median               double precision,
	price_target_high                 double precision,
	price_target_low                  double precision,
	n_analysts                        double precision,
	price_target_1w_ago               double precision,
	price_target_mtd_ago              double precision,
	price_target_1m_ago               double precision,
	price_target_qtd_ago              double precision,
	price_target_3m_ago               double precision,
	price_target_6m_ago               double precision,
	price_target_ytd_ago              double precision,
	price_target_1y_ago               double precision,
	price_target_low_1w_ago           double precision,
	price_target_low_mtd_ago          double precision,
	price_target_low_1m_ago           double precision,
	price_target_low_qtd_ago          double precision,
	price_target_low_3m_ago           double precision,
	price_target_low_6m_ago           double precision,
	price_target_low_ytd_ago          double precision,
	price_target_low_1y_ago           double precision,
	price_target_high_1w_ago          double precision,
	price_target_high_mtd_ago         double precision,
	price_target_high_1m_ago          double precision,
	price_target_high_qtd_ago         double precision,
	price_target_high_3m_ago          double precision,
	price_target_high_6m_ago          double precision,
	price_target_high_ytd_ago         double precision,
	price_target_high_1y_ago          double precision,
	price_target_median_1w_ago        double precision,
	price_target_median_mtd_ago       double precision,
	price_target_median_1m_ago        double precision,
	price_target_median_qtd_ago       double precision,
	price_target_median_3m_ago        double precision,
	price_target_median_6m_ago        double precision,
	price_target_median_ytd_ago       double precision,
	price_target_median_1y_ago        double precision,
	price_target_num_1w_ago           double precision,
	price_target_num_mtd_ago          double precision,
	price_target_num_1m_ago           double precision,
	price_target_num_qtd_ago          double precision,
	price_target_num_3m_ago           double precision,
	price_target_num_6m_ago           double precision,
	price_target_num_ytd_ago          double precision,
	price_target_num_1y_ago           double precision,
	price_1d_ago                      double precision,
	price_5d_ago                      double precision,
	price_1w_ago                      double precision,
	price_mtd_ago                     double precision,
	price_1m_ago                      double precision,
	price_3m_ago                      double precision,
	price_6m_ago                      double precision,
	price_ytd_ago                     double precision,
	price_1y_ago                      double precision,
	price_3y_ago                      double precision,
	price_5y_ago                      double precision,
	price_qtd_ago                     double precision,
	feat_implied_upside               double precision,
	feat_holds                        bigint,
	feat_buys                         bigint,
	feat_sells                        bigint,
	feat_no_opinion                   bigint,
	feat_analyst_bullish_pct          double precision,
	feat_analyst_bearish_pct          double precision,
	feat_analyst_neutral_pct          double precision,
	feat_analyst_conviction           double precision,
	feat_analyst_rating               double precision,
	feat_pt_achievement_1y            double precision,
	feat_pt_accuracy_1y               double precision,
	feat_pt_range_hit_rate            double precision,
	feat_pt_drift                     double precision,
	feat_pt_drift_n                   bigint,
	feat_price_drift                  double precision,
	feat_price_drift_n                bigint,
	feat_pt_high_drift                double precision,
	feat_pt_low_drift                 double precision,
	feat_pt_median_drift              double precision,
	feat_coverage_drift               double precision,
	feat_pt_noise_drift               double precision,
	feat_pt_noise_sigma               double precision,
	price_target_stddev_1w_ago        double precision,
	price_target_stddev_mtd_ago       double precision,
	price_target_stddev_1m_ago        double precision,
	price_target_stddev_qtd_ago       double precision,
	price_target_stddev_3m_ago        double precision,
	price_target_stddev_6m_ago        double precision,
	price_target_stddev_ytd_ago       double precision,
	price_target_stddev_1y_ago        double precision,
	feat_pt_range_norm                double precision,
	feat_one_day_return               double precision,
	feat_price_chg_pct_3m             double precision,
	feat_vol_drift                    double precision,
	feat_vol_drift_n                  bigint,
	feat_vol_level                    double precision,
	feat_log_mcap                     double precision,
	beta_1y                           double precision,
	beta_2y                           double precision,
	beta_5y                           double precision,
	feat_avg_beta                     double precision,
	feat_total_return_ytd             double precision,
	feat_total_return_5y              double precision,
	feat_total_return_10y             double precision,
	feat_tr_cagr_3y                   double precision,
	feat_tr_cagr_10y                  double precision,
	feat_tr_cagr_5y                   double precision,
	feat_tr_cagr_1y                   double precision,
	feat_total_return_1d              double precision,
	feat_total_return_5d              double precision,
	feat_total_return_1w              double precision,
	feat_total_return_1m              double precision,
	feat_total_return_3m              double precision,
	feat_total_return_6m              double precision,
	feat_total_return_1y              double precision,
	feat_total_return_3y              double precision,
	feat_total_return_mtd             double precision,
	feat_total_return_qtd             double precision,
	feat_total_return_2025            double precision,
	feat_total_return_2024            double precision,
	feat_total_return_2023            double precision,
	feat_total_return_2022            double precision,
	feat_total_return_2021            double precision,
	feat_mcap_global_r                double precision,
	feat_mcap_global_sec_r            double precision,
	feat_mcap_region_r                double precision,
	feat_mcap_region_sec_r            double precision,
	feat_mcap_country_r               double precision,
	feat_mcap_country_sec_r           double precision,
	feat_net_eps_drift                double precision,
	feat_net_eps_drift_n              bigint,
	feat_last_q_surprise              double precision,
	feat_last_y_surprise              double precision,
	feat_eps_beat_rate                double precision,
	feat_eps_beat_rate_annual         double precision,
	feat_piotroski_f_score_fy         bigint,
	feat_piotroski_f_score_neg1fy     bigint,
	feat_piotroski_f_score_neg2fy     bigint,
	feat_piotroski_f_score_neg3fy     bigint,
	feat_median_piotroski_f_score     double precision,
	feat_log_uplift_now               double precision,
	feat_log_uplift_1w                double precision,
	feat_log_uplift_1m                double precision,
	feat_log_uplift_3m                double precision,
	feat_log_uplift_6m                double precision,
	feat_log_uplift_1y                double precision,
	n_trail_obs                       bigint,
	n_analysts_1w                     double precision,
	n_analysts_1m                     double precision,
	n_analysts_3m                     double precision,
	n_analysts_6m                     double precision,
	n_analysts_1y                     double precision,
	feat_eps_signal_surprise          double precision,
	feat_eps_signal_beat              double precision,
	feat_eps_signal_coverage          double precision,
	built_at                          timestamp with time zone,
	run_id                            text,
	exported_at                       timestamp with time zone,
	source_sha                        text,
	source_dirty                      boolean
)
;

alter table analytics."04_panel_frame_v2"
	owner to postgres
;