-- ===========================================================================
-- analytics.09_diagnostics_v2
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- do not hand-edit; it is rewritten
-- on every export.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- This is the **v2** table. v1 continues to write
-- analytics.kalman_filtered_price_targets, which is what the GEIB dashboard
-- reads; the two coexist so the models can be compared on one database.
-- Promoting v2 means repointing the dashboard, not renaming this table.
-- ===========================================================================

DROP TABLE IF EXISTS analytics."09_diagnostics_v2";
CREATE TABLE analytics."09_diagnostics_v2"
(
    "index" TEXT,
    "mean" DOUBLE PRECISION,
    "sd" DOUBLE PRECISION,
    "eti89_lb" DOUBLE PRECISION,
    "eti89_ub" DOUBLE PRECISION,
    "ess_bulk" DOUBLE PRECISION,
    "ess_tail" DOUBLE PRECISION,
    "r_hat" DOUBLE PRECISION,
    "mcse_mean" DOUBLE PRECISION,
    "mcse_sd" DOUBLE PRECISION,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN analytics."09_diagnostics_v2"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN analytics."09_diagnostics_v2"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN analytics."09_diagnostics_v2"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN analytics."09_diagnostics_v2"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';
