-- ===========================================================================
-- analytics.09b_comparison_v2
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- DO NOT HAND-EDIT. It is rewritten
-- on every export, so an edit here is lost on the next run and, worse, is
-- invisible until then.
--
-- This line is also how the test suite FINDS these files. A reformatting pass
-- stripped it from all eleven in August 2026, and
-- `test_generated_analytics_ddls_carry_the_identity_block` went from checking
-- eleven schemas to checking zero -- passing the whole time, because it counts
-- what it found rather than what it expected to find. Reformat these files and
-- the committed schema stops being provably in sync with the code.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- WHO WRITES WHAT (2026-08-31). The fit `pymc_kalman_filter_pt_v2.py` writes
-- the panel, the diagnostics and the comparison; `kalman_portfolio.py` writes
-- the screen, the risk book and the canonical decision table the GEIB dashboard
-- reads. The replay's own frames live in the `kalman_portfolio` schema instead,
-- append-only.
-- ===========================================================================

DROP TABLE IF EXISTS analytics."09b_comparison_v2";
CREATE TABLE analytics."09b_comparison_v2"
(
    "arm" TEXT,
    "rank" BIGINT,
    "elpd_diff" DOUBLE PRECISION,
    "dse" DOUBLE PRECISION,
    "p_worse" DOUBLE PRECISION,
    "diag_diff" TEXT,
    "diag_elpd" TEXT,
    "p" DOUBLE PRECISION,
    "elpd" DOUBLE PRECISION,
    "se" DOUBLE PRECISION,
    "weight" DOUBLE PRECISION,
    "divergences" BIGINT,
    "min_ess_bulk" DOUBLE PRECISION,
    "min_ess_param" TEXT,
    "max_r_hat" DOUBLE PRECISION,
    "max_r_hat_param" TEXT,
    "n_group_levels" BIGINT,
    "backend" TEXT,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN analytics."09b_comparison_v2"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN analytics."09b_comparison_v2"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN analytics."09b_comparison_v2"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN analytics."09b_comparison_v2"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';
