-- ===========================================================================
-- analytics.10_screen_mc_summary_v2
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- do not hand-edit; it is rewritten
-- on every export.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- This is the **v2** table. v1 continues to write
-- analytics.kalman_filtered_price_targets, which is what the GEIB dashboard
-- reads; the two coexist so the models can be compared on one database.
-- Promoting v2 means repointing the dashboard, not renaming this table.
-- ===========================================================================

DROP TABLE IF EXISTS analytics."10_screen_mc_summary_v2";
CREATE TABLE analytics."10_screen_mc_summary_v2"
(
    "isin" TEXT,
    "er_mean" DOUBLE PRECISION,
    "er_sd" DOUBLE PRECISION,
    "er_p05" DOUBLE PRECISION,
    "er_p50" DOUBLE PRECISION,
    "er_p95" DOUBLE PRECISION,
    "mc_prob_pos" DOUBLE PRECISION,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN analytics."10_screen_mc_summary_v2"."er_mean" IS
    'Mean forward return over the Monte-Carlo horizon. Raw decimal.';
COMMENT ON COLUMN analytics."10_screen_mc_summary_v2"."er_sd" IS
    'Pooled sd of the forward-return draws. Denominator of expected_sharpe_ratio.';
COMMENT ON COLUMN analytics."10_screen_mc_summary_v2"."er_p05" IS
    '5th percentile forward return. Drives the upper out_of_support test.';
COMMENT ON COLUMN analytics."10_screen_mc_summary_v2"."er_p95" IS
    '95th percentile forward return. Drives the lower out_of_support test.';
COMMENT ON COLUMN analytics."10_screen_mc_summary_v2"."mc_prob_pos" IS
    'Share of Monte-Carlo forward-return draws above zero.';
COMMENT ON COLUMN analytics."10_screen_mc_summary_v2"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN analytics."10_screen_mc_summary_v2"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN analytics."10_screen_mc_summary_v2"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN analytics."10_screen_mc_summary_v2"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_10_screen_mc_summary_v2_isin
    ON analytics."10_screen_mc_summary_v2" (isin);
