create table analytics."15_forecast_summary_v2"
(
	isin                              text,
	ticker                            text,
	name                              text,
	trading_region                    text,
	region                            text,
	country                           text,
	country_name                      text,
	trading_country                   text,
	trading_country_name              text,
	exchange                          text,
	exchange_name                     text,
	unit                              text,
	unit_name                         text,
	style_class                       text,
	size_class                        text,
	sector                            text,
	industry                          text,
	last_updated                      timestamp,
	income_statement_report_date      timestamp,
	next_earnings                     timestamp,
	next_earnings_when                text,
	next_earnings_status              text,
	fy_end_date                       timestamp,
	next_fiscal_quarter               timestamp,
	next_income_statement_report_date timestamp,
	next_fy_end_date                  timestamp,
	expected_report_date              timestamp,
	days_to_next_earnings             bigint,
	days_since_last_report            bigint,
	days_to_next_fy_end               bigint,
	days_to_next_fiscal_quarter       bigint,
	days_to_next_report               bigint,
	days_to_expected_report           bigint,
	days_since_fy_end                 bigint,
	market_cap                        double precision,
	enterprise_value                  double precision,
	market_cap_global_r               bigint,
	market_cap_global_sec_r           bigint,
	market_cap_region_r               bigint,
	market_cap_region_sec_r           bigint,
	market_cap_country_r              bigint,
	market_cap_country_sec_r          bigint,
	er_mean                           double precision,
	er_sd                             double precision,
	er_p05                            double precision,
	er_p50                            double precision,
	er_p95                            double precision,
	prob_pos                          double precision,
	er_mean_terminal                  double precision,
	er_sd_terminal                    double precision,
	er_p05_terminal                   double precision,
	er_p50_terminal                   double precision,
	er_p95_terminal                   double precision,
	prob_pos_terminal                 double precision,
	backend                           text,
	factor_share                      double precision,
	horizon_days                      double precision,
	out_of_support                    boolean,
	run_id                            text,
	exported_at                       timestamp with time zone,
	source_sha                        text,
	source_dirty                      boolean
)
;

alter table analytics."15_forecast_summary_v2"
	owner to postgres
;