-- ===========================================================================
-- analytics.15_forecast_summary_v2
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- do not hand-edit; it is rewritten
-- on every export.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- This is the **v2** table. v1 continues to write
-- analytics.kalman_filtered_price_targets, which is what the GEIB dashboard
-- reads; the two coexist so the models can be compared on one database.
-- Promoting v2 means repointing the dashboard, not renaming this table.
-- ===========================================================================

DROP TABLE IF EXISTS analytics."15_forecast_summary_v2";
CREATE TABLE analytics."15_forecast_summary_v2"
(
    "isin" TEXT,
    "ticker" TEXT,
    "name" TEXT,
    "trading_region" TEXT,
    "region" TEXT,
    "country" TEXT,
    "country_name" TEXT,
    "trading_country" TEXT,
    "trading_country_name" TEXT,
    "exchange" TEXT,
    "exchange_name" TEXT,
    "unit" TEXT,
    "unit_name" TEXT,
    "style_class" TEXT,
    "size_class" TEXT,
    "sector" TEXT,
    "industry" TEXT,
    "last_updated" DATE,
    "income_statement_report_date" DATE,
    "next_earnings" DATE,
    "next_earnings_when" TEXT,
    "next_earnings_status" TEXT,
    "fy_end_date" DATE,
    "next_fiscal_quarter" DATE,
    "next_income_statement_report_date" DATE,
    "next_fy_end_date" DATE,
    "expected_report_date" DATE,
    "days_to_next_earnings" INTEGER,
    "days_since_last_report" INTEGER,
    "days_to_next_fy_end" INTEGER,
    "days_to_next_fiscal_quarter" INTEGER,
    "days_to_next_report" INTEGER,
    "days_to_expected_report" INTEGER,
    "days_since_fy_end" INTEGER,
    "market_cap" DOUBLE PRECISION,
    "enterprise_value" DOUBLE PRECISION,
    "market_cap_global_r" INTEGER,
    "market_cap_global_sec_r" INTEGER,
    "market_cap_region_r" INTEGER,
    "market_cap_region_sec_r" INTEGER,
    "market_cap_country_r" INTEGER,
    "market_cap_country_sec_r" INTEGER,
    "er_mean" DOUBLE PRECISION,
    "er_sd" DOUBLE PRECISION,
    "er_p05" DOUBLE PRECISION,
    "er_p50" DOUBLE PRECISION,
    "er_p95" DOUBLE PRECISION,
    "prob_pos" DOUBLE PRECISION,
    "er_mean_terminal" DOUBLE PRECISION,
    "er_sd_terminal" DOUBLE PRECISION,
    "er_p05_terminal" DOUBLE PRECISION,
    "er_p50_terminal" DOUBLE PRECISION,
    "er_p95_terminal" DOUBLE PRECISION,
    "prob_pos_terminal" DOUBLE PRECISION,
    "backend" TEXT,
    "factor_share" DOUBLE PRECISION,
    "horizon_days" DOUBLE PRECISION,
    "out_of_support" BOOLEAN,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN analytics."15_forecast_summary_v2"."er_mean" IS
    'Mean forward return over the Monte-Carlo horizon. Raw decimal.';
COMMENT ON COLUMN analytics."15_forecast_summary_v2"."er_sd" IS
    'Pooled sd of the forward-return draws. Denominator of expected_sharpe_ratio.';
COMMENT ON COLUMN analytics."15_forecast_summary_v2"."er_p05" IS
    '5th percentile forward return. Drives the upper out_of_support test.';
COMMENT ON COLUMN analytics."15_forecast_summary_v2"."er_p95" IS
    '95th percentile forward return. Drives the lower out_of_support test.';
COMMENT ON COLUMN analytics."15_forecast_summary_v2"."prob_pos" IS
    'NON-RANKING -- reported diagnostic. Share of the per-name posterior above zero. Do not rank, filter or size on it; rank on p_upside_pos_cond. It saturates: 59.4% of the universe sat at exactly 1.0 on run 0aa3397b1d01 and 87.4% on the pass-through 49e84d7e9d59, because the smoother is Rao-Blackwellised over the latent and the posterior sd collapsed to 0.47pp. The forecast-error term added 2026-08-20 widens it and the prob_pos_degenerate gate warns if it re-pins -- but that gate passes at 59.4% against a 60% ceiling, so it is reporting the threshold as much as the model. A column pinned for three names in five has almost no ordering to offer.';
COMMENT ON COLUMN analytics."15_forecast_summary_v2"."out_of_support" IS
    'TRUE when the forward-return distribution is pinned at a clip bound (er_p05 at the +500% cap or er_p95 at the -95% floor). Ranking metrics are NULL for these rows; identity and the raw er_* distribution are kept.';
COMMENT ON COLUMN analytics."15_forecast_summary_v2"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN analytics."15_forecast_summary_v2"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN analytics."15_forecast_summary_v2"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN analytics."15_forecast_summary_v2"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_15_forecast_summary_v2_isin
    ON analytics."15_forecast_summary_v2" (isin);
