-- ===========================================================================
-- analytics.15b_decision_analytics_v2
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- do not hand-edit; it is rewritten
-- on every export.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- This is the **v2** table. v1 continues to write
-- analytics.kalman_filtered_price_targets, which is what the GEIB dashboard
-- reads; the two coexist so the models can be compared on one database.
-- Promoting v2 means repointing the dashboard, not renaming this table.
-- ===========================================================================

DROP TABLE IF EXISTS analytics."15b_decision_analytics_v2";
CREATE TABLE analytics."15b_decision_analytics_v2"
(
    "isin" TEXT,
    "ticker" TEXT,
    "name" TEXT,
    "trading_region" TEXT,
    "region" TEXT,
    "country" TEXT,
    "country_name" TEXT,
    "trading_country" TEXT,
    "trading_country_name" TEXT,
    "exchange" TEXT,
    "exchange_name" TEXT,
    "unit" TEXT,
    "unit_name" TEXT,
    "style_class" TEXT,
    "size_class" TEXT,
    "sector" TEXT,
    "industry" TEXT,
    "last_updated" DATE,
    "income_statement_report_date" DATE,
    "next_earnings" DATE,
    "next_earnings_when" TEXT,
    "next_earnings_status" TEXT,
    "fy_end_date" DATE,
    "next_fiscal_quarter" DATE,
    "next_income_statement_report_date" DATE,
    "next_fy_end_date" DATE,
    "expected_report_date" DATE,
    "days_to_next_earnings" INTEGER,
    "days_since_last_report" INTEGER,
    "days_to_next_fy_end" INTEGER,
    "days_to_next_fiscal_quarter" INTEGER,
    "days_to_next_report" INTEGER,
    "days_to_expected_report" INTEGER,
    "days_since_fy_end" INTEGER,
    "market_cap" DOUBLE PRECISION,
    "enterprise_value" DOUBLE PRECISION,
    "market_cap_global_r" INTEGER,
    "market_cap_global_sec_r" INTEGER,
    "market_cap_region_r" INTEGER,
    "market_cap_region_sec_r" INTEGER,
    "market_cap_country_r" INTEGER,
    "market_cap_country_sec_r" INTEGER,
    "expected_return" DOUBLE PRECISION,
    "er_sd" DOUBLE PRECISION,
    "kelly_fraction" DOUBLE PRECISION,
    "kelly_interior" BOOLEAN,
    "kelly_endpoint_score" DOUBLE PRECISION,
    "kelly_max_feasible" DOUBLE PRECISION,
    "kelly_unbounded" BOOLEAN,
    "gvar" DOUBLE PRECISION,
    "ges" DOUBLE PRECISION,
    "gtr" DOUBLE PRECISION,
    "downside_dev" DOUBLE PRECISION,
    "er_p05" DOUBLE PRECISION,
    "er_p95" DOUBLE PRECISION,
    "tail_risk" DOUBLE PRECISION,
    "tail_risk_on_floor" BOOLEAN,
    "downside_dev_floored" BOOLEAN,
    "reward_to_downside" DOUBLE PRECISION,
    "tail_risk_floored" BOOLEAN,
    "reward_to_cvar" DOUBLE PRECISION,
    "rank_denominator_pctile" DOUBLE PRECISION,
    "weight" DOUBLE PRECISION,
    "backend" TEXT,
    "factor_share" DOUBLE PRECISION,
    "out_of_support" BOOLEAN,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."er_sd" IS
    'Pooled sd of the forward-return draws. Denominator of expected_sharpe_ratio.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."kelly_fraction" IS
    'Log-optimal position size solved on the forward-return draws by bisection on E[r / (1 + f*r)]. Read it WITH kelly_interior and kelly_unbounded: the bare column reads 1.000 both when the criterion chose the cap and when it had nothing to solve.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."kelly_interior" IS
    'TRUE when the Kelly solution lies strictly inside (0, max_fraction), i.e. the criterion actually chose it rather than being pinned at a bound. FALSE for 89.3% of the universe on run 448e7f055ef3.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."kelly_max_feasible" IS
    'Largest f with 1 + f*r > 0 on every draw. NULL where no finite bound exists -- see kelly_unbounded. Carried +inf until 2026-08-27, which is not exportable: it blocked export_finite and a float8 Infinity poisons every downstream aggregate.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."kelly_unbounded" IS
    'TRUE when the name''s draws contain no losing scenario, so no finite feasible fraction exists and kelly_max_feasible is NULL. That is a statement about the simulation, not about the opportunity. 626 of 6,513 names on run 6efb530d5881.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."er_p05" IS
    '5th percentile forward return. Drives the upper out_of_support test.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."er_p95" IS
    '95th percentile forward return. Drives the lower out_of_support test.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."downside_dev_floored" IS
    'TRUE when the ranking denominator floor excluded this name from the reward_to_downside arm -- its modelled downside sat below the floor, so the ratio would have ranked it on the ABSENCE of modelled risk.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."tail_risk_floored" IS
    'As downside_dev_floored, for the reward_to_cvar arm.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."reward_to_cvar" IS
    'expected_return_kalman / tail_risk (STARR). NULL when out_of_support.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."rank_denominator_pctile" IS
    'Where this name''s ranking denominator sits in the eligible universe''s distribution of the same. The column that makes ''selected on the absence of modelled downside'' a read rather than a diagnosis: every name of the run 448e7f055ef3 book sat in its bottom ~2%.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."out_of_support" IS
    'TRUE when the forward-return distribution is pinned at a clip bound (er_p05 at the +500% cap or er_p95 at the -95% floor). Ranking metrics are NULL for these rows; identity and the raw er_* distribution are kept.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN analytics."15b_decision_analytics_v2"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_15b_decision_analytics_v2_isin
    ON analytics."15b_decision_analytics_v2" (isin);
