CREATE TABLE analytics.etf
(
	ticker                                 text,
	isin                                   text,
	issuer                                 text,
	name                                   text,
	"Fund Category"                        text,
	exchange                               text,
	region                                 text,
	"Fund Benchmark"                       text,
	administrator                          text,
	custodian                              text,
	"Fund Investment Strategy"             text,
	"Broad Benchmark"                      text,
	"Is Levered"                           text,
	"Inception Date"                       text,
	"Launch Date"                          text,
	"Notional Volume"                      double precision,
	distributor                            text,
	"Investment Advisor"                   text,
	classification                         text,
	"Peer Benchmark"                       text,
	class                                  text,
	"Last Updated"                         text,
	"ETF FY End"                           text,
	"Last Price"                           double precision,
	"1-Day Chg"                            double precision,
	"1-Day %"                              double precision,
	"Price Chg. % (1D)"                    double precision,
	"Price Chg. % (5D)"                    double precision,
	"Price Chg. % (1W)"                    double precision,
	"Price Chg. % (1M)"                    double precision,
	"Price Chg. % (3M)"                    double precision,
	"Price Chg. % (6M)"                    double precision,
	"Price Chg. % (1Y)"                    double precision,
	"Price Chg. % (3Y)"                    double precision,
	"Price Chg. % (5Y)"                    double precision,
	"Yield Month-End"                      double precision,
	"30-Day SEC Yield"                     double precision,
	"Beta 1Y Quarter End"                  double precision,
	"Beta 3Y Quarter End"                  double precision,
	"Beta 5Y Quarter End"                  double precision,
	"Net Expense Ratio Reported"           double precision,
	aum                                    double precision,
	"Put/Call Ratio"                       double precision,
	"52W High"                             double precision,
	"52W High/Adj"                         double precision,
	"52W Low"                              double precision,
	"52W Low/Adj"                          double precision,
	"EMA (5D)"                             double precision,
	"EMA (8D)"                             double precision,
	"EMA (10D)"                            double precision,
	"EMA (20D)"                            double precision,
	"EMA (21D)"                            double precision,
	"EMA (50D)"                            double precision,
	"EMA (100D)"                           double precision,
	"Active Return"                        double precision,
	"Alpha (1Y)"                           double precision,
	"Alpha (3Y)"                           double precision,
	"Alpha (5Y)"                           double precision,
	"Asset Type"                           text,
	"Arithmetic Mean (1Y)"                 double precision,
	"Arithmetic Mean (3Y)"                 double precision,
	"Arithmetic Mean (5Y)"                 double precision,
	"Beta (1Y)"                            double precision,
	"Beta (3Y)"                            double precision,
	"Beta (5Y)"                            double precision,
	"Effective Duration (Yrs)"             double precision,
	"Downside Capture Ratio (1Y)"          double precision,
	"Downside Capture Ratio (3Y)"          double precision,
	"Downside Capture Ratio (5Y)"          double precision,
	"Information Ratio (1Y)"               double precision,
	"Information Ratio (3Y)"               double precision,
	"Information Ratio (5Y)"               double precision,
	domicile                               text,
	"Kurtosis (1Y)"                        double precision,
	"Kurtosis (3Y)"                        double precision,
	"Kurtosis (5Y)"                        double precision,
	"Sortino Ratio (1Y)"                   double precision,
	"Sortino Ratio (3Y)"                   double precision,
	"Sortino Ratio (5Y)"                   double precision,
	"Sharpe Ratio (1Y)"                    double precision,
	"Sharpe Ratio (3Y)"                    double precision,
	"Sharpe Ratio (5Y)"                    double precision,
	"Skewness (1Y)"                        double precision,
	"Skewness (3Y)"                        double precision,
	"Skewness (5Y)"                        double precision,
	"ETF Category"                         text,
	"Effective Maturity (Yrs)"             double precision,
	ytm                                    double precision,
	"Fund Total Assets (Day-End)"          double precision,
	"Mgmt Fees"                            double precision,
	"R-Squared (1Y)"                       double precision,
	"R-Squared (3Y)"                       double precision,
	"R-Squared (5Y)"                       double precision,
	"Months with Negative Performance YTD" double precision,
	"Months with Positive Performance YTD" double precision,
	"Batting Average (1Y)"                 double precision,
	"Batting Average (3Y)"                 double precision,
	"Batting Average (5Y)"                 double precision,
	"Volatility Score"                     double precision,
	"Upside Capture Ratio (1Y)"            double precision,
	"Upside Capture Ratio (3Y)"            double precision,
	"Upside Capture Ratio (5Y)"            double precision,
	"Risk Free Rate"                       text,
	"SEC Yield"                            double precision
);

ALTER TABLE analytics.etf
	OWNER TO postgres;