CREATE TABLE analytics.kalman_filtered_price_targets
(
	isin                              text,
	ticker                            text,
	name                              text,
	trading_region                    text,
	trading_country                   text,
	region                            text,
	country                           text,
	unit                              text,
	exchange                          text,
	sector                            text,
	industry                          text,
	style_class                       text,
	size_class                        text,
	last_updated                      date,
	next_earnings                     date,
	next_earnings_when                text,
	next_earnings_status              text,
	fy_end_date                       date,
	next_fiscal_quarter               date,
	income_statement_report_date      date,
	next_income_statement_report_date date,
	next_fy_end_date                  date,
	expected_report_date              date,
	days_to_next_earnings             bigint,
	days_since_last_report            bigint,
	days_to_next_fy_end               double precision,
	days_to_next_fiscal_quarter       double precision,
	days_to_next_report               double precision,
	days_to_expected_report           double precision,
	days_since_fy_end                 bigint,
	expected_return_kalman            double precision,
	price_target_kalman               double precision,
	kalman_variance                   double precision,
	kalman_gain                       double precision,
	signal_strength                   double precision,
	original_price                    double precision,
	original_target                   double precision,
	beta                              double precision,
	price_target_median               double precision,
	price_target_high                 double precision,
	price_target_low                  double precision,
	price_target_1w_ago               double precision,
	price_target_mtd_ago              double precision,
	price_target_1m_ago               double precision,
	price_target_qtd_ago              double precision,
	price_target_3m_ago               double precision,
	price_target_6m_ago               double precision,
	price_target_ytd_ago              double precision,
	price_target_1y_ago               double precision,
	price_5d_ago                      double precision,
	price_3m_ago                      double precision,
	price_5y_ago                      double precision,
	price_1y_ago                      double precision,
	price_6m_ago                      double precision,
	price_qtd_ago                     double precision,
	price_1m_ago                      double precision,
	price_1w_ago                      double precision,
	price_3y_ago                      double precision,
	market_cap                        double precision,
	enterprise_value                  double precision,
	expected_pt_hdi_lo                double precision,
	expected_pt_hdi_hi                double precision,
	risk_adj_return                   double precision,
	er_mean                           double precision,
	er_p05                            double precision,
	er_p50                            double precision,
	er_p95                            double precision,
	mc_prob_pos                       double precision,
	cvar_book_weight                  double precision,
	cvar_5pct_kalman                  double precision,
	reward_to_cvar                    double precision,
	expected_vol_kalman               double precision,
	expected_sharpe_ratio             double precision,
	p_upside_pos_cond                 double precision
);

ALTER TABLE analytics.kalman_filtered_price_targets
	OWNER TO postgres;