CREATE TABLE analytics.kalman_filtered_price_targets_prev
(
	isin                              text,
	ticker                            text,
	name                              text,
	trading_region                    text,
	region                            text,
	country                           text,
	unit                              text,
	exchange                          text,
	sector                            text,
	industry                          text,
	style_class                       text,
	size_class                        text,
	last_updated                      date,
	next_earnings                     date,
	next_earnings_when                text,
	next_earnings_status              text,
	fy_end_date                       date,
	income_statement_report_date      date,
	next_income_statement_report_date date,
	next_fy_end_date                  date,
	expected_report_date              date,
	days_to_next_earnings             bigint,
	days_since_last_report            bigint,
	days_to_next_fy_end               double precision,
	days_to_next_report               bigint,
	days_to_expected_report           bigint,
	days_to_fy_end                    double precision,
	expected_return_kalman            double precision,
	price_target_kalman               double precision,
	kalman_variance                   double precision,
	kalman_gain                       double precision,
	signal_strength                   double precision,
	original_price                    double precision,
	original_target                   double precision,
	market_cap                        double precision,
	enterprise_value                  double precision,
	expected_pt_hdi_lo                double precision,
	expected_pt_hdi_hi                double precision,
	risk_adj_return                   double precision,
	er_mean                           double precision,
	er_p05                            double precision,
	er_p50                            double precision,
	er_p95                            double precision,
	mc_prob_pos                       double precision,
	cvar_book_weight                  double precision,
	cvar_5pct_kalman                  double precision,
	reward_to_cvar                    double precision
);

ALTER TABLE analytics.kalman_filtered_price_targets_prev
	OWNER TO postgres;