create table analytics.kalman_filtered_price_targets_v2
(
	isin                   text,
	ticker                 text,
	name                   text,
	sector                 text,
	industry               text,
	trading_region         text,
	country                text,
	style_class            text,
	size_class             text,
	n_analysts             double precision,
	market_cap             double precision,
	mcap_global_r          double precision,
	mcap_country_r         double precision,
	original_price         double precision,
	original_target        double precision,
	expected_return_kalman double precision,
	expected_upside_sd     double precision,
	prob_pos               double precision,
	implied_upside         double precision,
	price_target_kalman    double precision,
	expected_pt_hdi_lo     double precision,
	expected_pt_hdi_hi     double precision,
	shrink_gain            double precision,
	risk_adj_return        double precision,
	kalman_gain            double precision,
	er_mean                double precision,
	er_sd                  double precision,
	er_p05                 double precision,
	er_p50                 double precision,
	er_p95                 double precision,
	mc_prob_pos            double precision,
	p_upside_pos_cond      double precision,
	p_upside_pos           double precision,
	band_width             double precision,
	cvar_5pct_kalman       double precision,
	expected_vol_kalman    double precision,
	ret_vol_ratio          double precision,
	expected_sharpe_ratio  double precision,
	tail_risk              double precision,
	reward_to_cvar         double precision,
	cvar_book_weight       double precision,
	out_of_support         boolean,
	run_id                 text,
	exported_at            timestamp with time zone,
	source_sha             text,
	source_dirty           boolean
)
;

alter table analytics.kalman_filtered_price_targets_v2
	owner to postgres
;