-- analytics.kalman_filtered_price_targets
--
-- Generated by ``export_analytics`` in pymc_kalman_filter_pt.py -- do not edit by
-- hand; ``export_to_analytics_db(..., if_exists='replace')`` drops and recreates
-- the table on every run and this file is rewritten alongside it.
--
-- UNIT CONVENTION (since 0.9.9.7): every return / risk column stores a **raw
-- decimal** return (0.25 = +25%), including ``cvar_5pct_kalman`` and
-- ``expected_vol_kalman``. Percent scaling happens only at visualization and
-- print boundaries. Probabilities are decimals in [0, 1].
--
-- WHAT THE "RISK" COLUMNS ACTUALLY MEASURE (read before building on them):
-- ``cvar_5pct_kalman``, ``expected_vol_kalman`` and ``reward_to_cvar`` are all
-- computed from the POSTERIOR expected-upside draws, so they quantify
-- ESTIMATION uncertainty, not return risk. ``cvar_5pct_kalman`` is a tail MEAN
-- and is positive for ~84% of rows -- it is not a loss. ``expected_sharpe_ratio``
-- divides by the dispersion of simulated log price-target uplift, not of a
-- realised return, so it behaves as a t-statistic. Per-column COMMENTs below
-- carry the detail; see also RiskBookModel.compute_cvar_aware_book.

CREATE TABLE analytics.kalman_filtered_price_targets
(
	isin                              text,
	ticker                            text,
	name                              text,
	trading_region                    text,
	trading_country                   text,
	trading_country_name              text,
	region                            text,
	country                           text,
	country_name                      text,
	unit                              text,
	unit_name                         text,
	exchange                          text,
	exchange_name                     text,
	sector                            text,
	industry                          text,
	style_class                       text,
	size_class                        text,
	last_updated                      date,
	next_earnings                     date,
	next_earnings_when                text,
	next_earnings_status              text,
	fy_end_date                       date,
	next_fiscal_quarter               date,
	income_statement_report_date      date,
	next_income_statement_report_date date,
	next_fy_end_date                  date,
	expected_report_date              date,
	days_to_next_earnings             bigint,
	days_since_last_report            bigint,
	days_to_next_fy_end               double precision,
	days_to_next_fiscal_quarter       double precision,
	days_to_next_report               double precision,
	days_to_expected_report           double precision,
	days_since_fy_end                 bigint,
	market_cap                        double precision,
	enterprise_value                  double precision,
	mcap_country_r                    double precision,
	mcap_global_r                     double precision,
	beta                              double precision,
	original_price                    double precision,
	original_target                   double precision,
	price_target_kalman               double precision,
	implied_upside                    double precision,
	expected_return_kalman            double precision,
	kalman_variance                   double precision,
	kalman_gain                       double precision,
	signal_strength                   double precision,
	n_holds                           double precision,
	n_buys                            double precision,
	n_sells                           double precision,
	n_analysts                        double precision,
	feat_no_opinion                   double precision,
	analyst_bullish_pct               double precision,
	analyst_bearish_pct               double precision,
	analyst_neutral_pct               double precision,
	analyst_conviction                double precision,
	analyst_rating                    double precision,
	piotroski_f_score_median          double precision,
	piotroski_f_score_fy              double precision,
	piotroski_f_score_neg1fy          double precision,
	piotroski_f_score_neg2fy          double precision,
	piotroski_f_score_neg3fy          double precision,
	pt_achievement_1y                 double precision,
	pt_range_hit_rate                 double precision,
	price_target_median               double precision,
	price_target_high                 double precision,
	price_target_low                  double precision,
	price_target_1w_ago               double precision,
	price_target_mtd_ago              double precision,
	price_target_1m_ago               double precision,
	price_target_qtd_ago              double precision,
	price_target_3m_ago               double precision,
	price_target_6m_ago               double precision,
	price_target_ytd_ago              double precision,
	price_target_1y_ago               double precision,
	price_5d_ago                      double precision,
	price_3m_ago                      double precision,
	price_5y_ago                      double precision,
	price_1y_ago                      double precision,
	price_6m_ago                      double precision,
	price_qtd_ago                     double precision,
	price_1m_ago                      double precision,
	price_1w_ago                      double precision,
	price_3y_ago                      double precision,
	expected_pt_hdi_lo                double precision,
	expected_pt_hdi_hi                double precision,
	risk_adj_return                   double precision,
	er_mean                           double precision,
	er_sd                             double precision,
	er_p05                            double precision,
	er_p50                            double precision,
	er_p95                            double precision,
	mc_prob_pos                       double precision,
	cvar_book_weight                  double precision,
	cvar_5pct_kalman                  double precision,
	reward_to_cvar                    double precision,
	expected_vol_kalman               double precision,
	expected_sharpe_ratio             double precision,
	p_upside_pos_cond                 double precision,
	out_of_support                    boolean,
	run_id                            text,
	exported_at                       timestamp
);

ALTER TABLE analytics.kalman_filtered_price_targets
	OWNER TO postgres;

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."price_target_kalman"
	IS 'Posterior-mean Kalman-smoothed price target (price units).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."implied_upside"
	IS 'Raw analyst-consensus implied upside vs last price (decimal return).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."expected_return_kalman"
	IS 'Posterior-mean expected return (decimal return, 0.25 = +25%).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."kalman_variance"
	IS 'Posterior variance of the smoothed price target (price units squared).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."kalman_gain"
	IS 'achieve_prob = sigmoid(risk_adj_return): probability the target is achieved (decimal in [0, 1]).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."signal_strength"
	IS '|E[risk_adj_return]| / sd(risk_adj_return) (dimensionless).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."expected_pt_hdi_lo"
	IS 'Lower bound of the 94% posterior price-target HDI (price units).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."expected_pt_hdi_hi"
	IS 'Upper bound of the 94% posterior price-target HDI (price units).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."risk_adj_return"
	IS 'Posterior-mean risk-adjusted-return latent (decimal return).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."er_mean"
	IS 'Structural-TS Monte-Carlo mean forward return (decimal return).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."er_sd"
	IS 'Pooled std of the structural-TS Monte-Carlo forward-return draws (decimal return); denominator of expected_sharpe_ratio.';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."er_p05"
	IS '5th percentile of the Monte-Carlo forward-return draws (decimal return).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."er_p50"
	IS 'Median of the Monte-Carlo forward-return draws (decimal return).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."er_p95"
	IS '95th percentile of the Monte-Carlo forward-return draws (decimal return).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."mc_prob_pos"
	IS 'Monte-Carlo probability of a positive forward return (decimal in [0, 1]).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."cvar_book_weight"
	IS 'Normalised CVaR-aware long-book weight; held names sum to 1 (0 for names outside the sized book).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."cvar_5pct_kalman"
	IS 'NOT A LOSS -- read the sign before using this. It is the conditional MEAN of the worst 5% of the POSTERIOR expected-upside draws, so it is positive whenever the upside posterior is wholly positive: on the 2026-08-15 export 5473 of 6487 rows were > 0, universe mean +0.186. A value of 0.48 is a +48% return, not a 48% loss. The dispersion measure is (expected_return_kalman - cvar_5pct_kalman); for a downside quantile of the forward-return distribution use er_p05 instead. Decimal return.';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."reward_to_cvar"
	IS 'STARR ratio: expected upside / tail_risk, where tail_risk = max(expected_upside - cvar05, -er_p05, 0.01). Measures reward per unit of POSTERIOR dispersion, so universe values of 4 and book values of 8-12 are normal and are not comparable to a return-based STARR. Dimensionless. NULL when out_of_support.';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."out_of_support"
	IS 'TRUE when the forward-return distribution is pinned at EITHER uplift winsorisation bound -- the +500% cap (via er_p05) or the -95% floor (via er_p95) -- so the model has no reliable estimate for this name. The ranking metrics (expected_sharpe_ratio, reward_to_cvar, cvar_book_weight) are NULL for these rows; exclude them from risk-adjusted rankings rather than treating a missing score as a zero.';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."expected_vol_kalman"
	IS 'Std of the POSTERIOR upside draws -- estimation uncertainty, not return volatility. Universe mean is ~0.025 (2.5%), roughly an order of magnitude below any realised equity vol; do not substitute it for one. Decimal return.';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."expected_sharpe_ratio"
	IS 'NOT AN INVESTMENT SHARPE RATIO. er_mean / er_sd over Monte-Carlo draws of the LOG PRICE-TARGET UPLIFT (the distance from price to the smoothed target), not of a realised return. It reads as a t-statistic on the uplift estimate, which is why book values of 5-7 are routine here. Dimensionless; NULL when out_of_support or when er_sd falls below the MIN_RATIO_DENOMINATOR floor.';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."p_upside_pos_cond"
	IS 'mc_prob_pos x kalman_gain: probability of a positive upside given state confidence (decimal in [0, 1]); the p_long gate applies here.';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."pt_achievement_1y"
	IS 'Historic 1y price-target achievement rate (decimal in [0, 1]).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."pt_range_hit_rate"
	IS 'Share of history inside the analyst target range (decimal in [0, 1]).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."analyst_bullish_pct"
	IS 'Share of analysts rating the name a buy (decimal in [0, 1]).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."analyst_bearish_pct"
	IS 'Share of analysts rating the name a sell (decimal in [0, 1]).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."analyst_neutral_pct"
	IS 'Share of analysts rating the name a hold (decimal in [0, 1]).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."analyst_conviction"
	IS 'Net buy-minus-sell analyst conviction (decimal in [-1, 1]).';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."run_id"
	IS 'Identifier of the workflow run that produced this row. Constant within one run and shared with the six other analytics frames exported alongside it, so SELECT count(DISTINCT run_id) detects a mixed-vintage schema and a join across tables can assert the vintages match. Added 2026-08-16.';

COMMENT ON COLUMN analytics.kalman_filtered_price_targets."exported_at"
	IS 'UTC start time of the run identified by run_id. This is an export timestamp, NOT a data as-of date -- for data recency read last_updated, which varies per name.';
