-- ===========================================================================
-- analytics.kalman_filtered_price_targets_v2
-- ===========================================================================
-- Generated by pymc_kalman_filter_pt_v2.py -- do not hand-edit; it is rewritten
-- on every export.
--
-- UNITS: all return-like columns are RAW DECIMALS (0.25 = +25%), per the
-- 0.9.9.7 convention. Percent scaling happens only at display boundaries.
--
-- This is the **v2** table. v1 continues to write
-- analytics.kalman_filtered_price_targets, which is what the GEIB dashboard
-- reads; the two coexist so the models can be compared on one database.
-- Promoting v2 means repointing the dashboard, not renaming this table.
-- ===========================================================================

DROP TABLE IF EXISTS analytics."kalman_filtered_price_targets_v2";
CREATE TABLE analytics."kalman_filtered_price_targets_v2"
(
    "isin" TEXT,
    "ticker" TEXT,
    "name" TEXT,
    "sector" TEXT,
    "industry" TEXT,
    "trading_region" TEXT,
    "country" TEXT,
    "style_class" TEXT,
    "size_class" TEXT,
    "n_analysts" DOUBLE PRECISION,
    "market_cap" DOUBLE PRECISION,
    "mcap_global_r" DOUBLE PRECISION,
    "mcap_country_r" DOUBLE PRECISION,
    "original_price" DOUBLE PRECISION,
    "original_target" DOUBLE PRECISION,
    "expected_return_kalman" DOUBLE PRECISION,
    "expected_upside_sd" DOUBLE PRECISION,
    "prob_pos" DOUBLE PRECISION,
    "implied_upside" DOUBLE PRECISION,
    "price_target_kalman" DOUBLE PRECISION,
    "expected_pt_hdi_lo" DOUBLE PRECISION,
    "expected_pt_hdi_hi" DOUBLE PRECISION,
    "shrink_gain" DOUBLE PRECISION,
    "risk_adj_return" DOUBLE PRECISION,
    "kalman_gain" DOUBLE PRECISION,
    "er_mean" DOUBLE PRECISION,
    "er_sd" DOUBLE PRECISION,
    "er_p05" DOUBLE PRECISION,
    "er_p50" DOUBLE PRECISION,
    "er_p95" DOUBLE PRECISION,
    "mc_prob_pos" DOUBLE PRECISION,
    "p_upside_pos_cond" DOUBLE PRECISION,
    "p_upside_pos" DOUBLE PRECISION,
    "band_width" DOUBLE PRECISION,
    "cvar_5pct_kalman" DOUBLE PRECISION,
    "expected_vol_kalman" DOUBLE PRECISION,
    "ret_vol_ratio" DOUBLE PRECISION,
    "expected_sharpe_ratio" DOUBLE PRECISION,
    "tail_risk" DOUBLE PRECISION,
    "reward_to_cvar" DOUBLE PRECISION,
    "cvar_book_weight" DOUBLE PRECISION,
    "out_of_support" BOOLEAN,
    "run_id" TEXT,
    "exported_at" TEXT,
    "source_sha" TEXT,
    "source_dirty" BOOLEAN
);

COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."expected_return_kalman" IS
    'Posterior mean expected upside. Raw decimal (0.25 = +25%).';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."expected_upside_sd" IS
    'Posterior sd of the per-name expected upside -- ESTIMATION uncertainty, not return risk. This is what expected_vol_kalman used to hold. Since 2026-08-20 it also carries the forecast-error term, so it is roughly an order of magnitude wider than the 0.47pp of run 49e84d7e9d59. Raw decimal.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."prob_pos" IS
    'Share of the per-name posterior above zero. REPORTED, NOT RANKED -- rank on p_upside_pos_cond. Historically this saturated at 1.0 for most of the universe (87.4% on run 49e84d7e9d59) because the smoother is Rao-Blackwellised over the latent and the posterior sd collapsed to 0.47pp; the forecast-error term added 2026-08-20 widens it, and the prob_pos_degenerate gate warns if it re-pins.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."implied_upside" IS
    'Analyst consensus upside, original_target/original_price - 1. Raw decimal.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."price_target_kalman" IS
    'Smoothed price target, in the security''s own currency.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."shrink_gain" IS
    'Weight on the name''s own smoothed observation in the forecast-error update; 1 - shrink_gain is the weight on the pooled drift + hierarchy prediction. Low for thinly covered or widely dispersed consensus. This is the column kalman_gain was mistakenly believed to be.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."kalman_gain" IS
    'DEPRECATED NAME, changed meaning 2026-08-20. Now P(risk_adj_return > 0) over posterior draws -- a real tail probability. It was sigmoid(risk_adj_return), a sigmoid of a standardised log-uplift, which is not the probability of any event and correlated -0.004 with analyst count. It is NOT a Kalman gain and never was: for the shrinkage weight see shrink_gain.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."er_mean" IS
    'Mean forward return over the Monte-Carlo horizon. Raw decimal.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."er_sd" IS
    'Pooled sd of the forward-return draws. Denominator of expected_sharpe_ratio.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."er_p05" IS
    '5th percentile forward return. Drives the upper out_of_support test.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."er_p95" IS
    '95th percentile forward return. Drives the lower out_of_support test.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."mc_prob_pos" IS
    'Share of Monte-Carlo forward-return draws above zero.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."p_upside_pos_cond" IS
    'THE PRIMARY PROBABILITY COLUMN -- rank on this one. P(risk-adjusted forward return > 0): the share of Monte-Carlo forward-return draws that are positive after the same risk / size / volume penalties the model applies to risk_adj_return. Changed 2026-08-20 from mc_prob_pos * kalman_gain, a probability times a sigmoid, whose ordering was usable but whose level was the probability of nothing. NULL when out_of_support.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."cvar_5pct_kalman" IS
    '5% expected shortfall of the Monte-Carlo FORWARD-RETURN distribution: the mean of the worst 5% of simulated returns. Raw decimal, and genuinely negative for a name with downside. Changed 2026-08-20 -- it was previously the tail mean of the posterior EXPECTED-UPSIDE draws, i.e. estimation uncertainty about a point, which made it positive for 88.4% of names and correlated 0.9998 with expected_return_kalman. For the estimation-uncertainty view use expected_upside_sd.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."expected_vol_kalman" IS
    'Standard deviation of the Monte-Carlo forward-return draws -- the same quantity as er_sd. Raw decimal. Changed 2026-08-20: it was previously the posterior dispersion of expected upside (median 0.47pp against a return sd of 19.03pp, a factor of 40), which is why the dashboard derived its own volatility rather than using this column.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."expected_sharpe_ratio" IS
    'er_mean / er_sd over Monte-Carlo draws of log price-target uplift. A t-statistic on the distance from price to the smoothed target, NOT an investment Sharpe ratio -- the numerator is an uplift, not a realised excess return. Median ~1.05, which is exactly the range a reader mistakes for a Sharpe. NULL when out_of_support.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."reward_to_cvar" IS
    'expected_return_kalman / tail_risk (STARR). NULL when out_of_support.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."cvar_book_weight" IS
    'Weight in the CVaR-sized book, 0 outside it and 0 when out_of_support.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."out_of_support" IS
    'TRUE when the forward-return distribution is pinned at a clip bound (er_p05 at the +500% cap or er_p95 at the -95% floor). Ranking metrics are NULL for these rows; identity and the raw er_* distribution are kept.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."run_id" IS
    'Export provenance. Every table written by one run shares it.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."exported_at" IS
    'Export provenance timestamp (UTC).';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."source_sha" IS
    'Git HEAD SHA of the source that produced this run, or NULL outside a checkout. Cross-run comparisons -- notably any ELPD contrast between comparison arms fitted in different runs -- are only legitimate between rows sharing this value AND having source_dirty = FALSE.';
COMMENT ON COLUMN analytics."kalman_filtered_price_targets_v2"."source_dirty" IS
    'TRUE when tracked files differed from source_sha at export time. NOT an error: most runs have an uncommitted tree. It is what tells a reader that source_sha does not fully determine the code that ran, so two runs sharing a SHA may still not share a specification.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_kalman_filtered_price_targets_v2_isin
    ON analytics."kalman_filtered_price_targets_v2" (isin);
