CREATE FUNCTION public.calc_gaap_adjusted_analytics(p_isin text default NULL::text)
	RETURNS table("isin" text, "eps_adjustment_spread_ltm" numeric, "eps_adjustment_spread_fy" numeric, "eps_adjustment_spread_1fy" numeric, "eps_adjustment_spread_fq" numeric, "eps_adjustment_spread_1fqfq" numeric, "eps_adjustment_spread_2fqfq" numeric, "eps_adjustment_spread_3fqfq" numeric, "eps_adjustment_spread_4fqfq" numeric, "eps_adjustment_spread_2fy" numeric, "eps_adjustment_spread_3fy" numeric, "eps_adjustment_spread_4fy" numeric, "eps_adjustment_pct" numeric, "net_income_adjustment_ratio_ltm" numeric, "net_income_adjustment_ratio_fy" numeric, "net_income_adjustment_ratio_1fy" numeric, "net_income_adjustment_ratio_fq" numeric, "net_income_adjustment_ratio_5yavgfq" numeric, "net_income_adjustment_ratio_1fqfq" numeric, "net_income_adjustment_ratio_2fqfq" numeric, "net_income_adjustment_ratio_3fqfq" numeric, "net_income_adjustment_ratio_4fqfq" numeric, "net_income_adjustment_ratio_2fy" numeric, "net_income_adjustment_ratio_3fy" numeric, "net_income_adjustment_ratio_4fy" numeric, "net_income_adjustment_pct" numeric, "ebitda_adjustment_pct_ltm" numeric, "ebitda_adjustment_pct_fy" numeric, "ebitda_adjustment_pct_1fy" numeric, "ebitda_adjustment_pct_fq" numeric, "ebitda_adjustment_pct_1fqfq" numeric, "ebitda_adjustment_pct_2fqfq" numeric, "ebitda_adjustment_pct_3fqfq" numeric, "ebitda_adjustment_pct_4fqfq" numeric, "ebitda_adjustment_pct_2fy" numeric, "ebitda_adjustment_pct_3fy" numeric, "ebitda_adjustment_pct_4fy" numeric, "ebit_adjustment_pct_ltm" numeric, "ebit_adjustment_pct_fy" numeric, "ebit_adjustment_pct_1fy" numeric, "ebit_adjustment_pct_fq" numeric, "ebit_adjustment_pct_1fqfq" numeric, "ebit_adjustment_pct_2fqfq" numeric, "ebit_adjustment_pct_3fqfq" numeric, "ebit_adjustment_pct_4fqfq" numeric, "ebit_adjustment_pct_2fy" numeric, "ebit_adjustment_pct_3fy" numeric, "ebit_adjustment_pct_4fy" numeric, "earnings_quality_score" numeric, "earnings_quality_warning" integer, "forward_eps_gaap_adj_spread" numeric)
	STABLE PARALLEL SAFE
	LANGUAGE sql
AS
$$ BEGIN
	-- missing source code
END;
$$;

ALTER FUNCTION public.calc_gaap_adjusted_analytics(text) OWNER TO postgres;