create materialized view mv_equities as
SELECT "Ticker"                                           AS ticker,
       "ISIN"                                             AS isin,
       "Name"                                             AS name,
       "Description"                                      AS description,
       "Region"                                           AS region,
       "Country"                                          AS country,
       "Trading Country"                                  AS trading_country,
       "Exchange"                                         AS exchange,
       "Unit"                                             AS unit,
       "Sector"                                           AS sector,
       "Industry"                                         AS industry,
       "Style Class"                                      AS style_class,
       "Size Class"                                       AS size_class,
       "FY End"                                           AS fy_end,
       "Next Earnings (When)"                             AS next_earnings_when,
       "Next Earnings (Status)"                           AS next_earnings_status,
       "Dividend Record (Currency)"                       AS dividend_record_currency,
       "Dividend Record (Frequency)"                      AS dividend_record_frequency,
       "Current Fiscal Quarter"                           AS current_fiscal_quarter,
       "Next Fiscal Quarter"                              AS next_fiscal_quarter,
       "Next Earnings (Report)"                           AS next_earnings_report,
       "Reporting Interval"                               AS reporting_interval,
       "Earnings Report (Frequency)"                      AS earnings_report_frequency,
       "Last Updated"                                     AS last_updated,
       "Income Statement Report Date"                     AS income_statement_report_date,
       "Next Earnings"                                    AS next_earnings,
       "Dividend Record (Announce Date)"                  AS dividend_record_announce_date,
       "Dividend Record (Payable Date)"                   AS dividend_record_payable_date,
       "Dividend Record (Record Date)"                    AS dividend_record_record_date,
       "Dividend Record (Ex Date)"                        AS dividend_record_ex_date,
       "Reference Date"                                   AS reference_date,
       "FY End Date"                                      AS fy_end_date,
       "Next FY End Date"                                 AS next_fy_end_date,
       "Next Income Statement Report Date"                AS next_income_statement_report_date,
       "Price Target"                                     AS price_target,
       "Price Target - Median"                            AS price_target_median,
       "Dividend Record (Amount)"                         AS dividend_record_amount,
       "Market Cap"                                       AS market_cap,
       "Enterprise Value"                                 AS enterprise_value,
       "Last Price"                                       AS last_price,
       "Price Target (YTD Ago)"                           AS price_target_ytd_ago,
       "Price Target - Low"                               AS price_target_low,
       "Price Target - High"                              AS price_target_high,
       "Market Cap (Country R)"                           AS market_cap_country_r,
       "Volume (Shrs)"                                    AS volume_shrs,
       "Dividend Per Share (LTM)"                         AS dividend_per_share_ltm,
       "Price (5D Ago)"                                   AS price_5d_ago,
       "Price (1W Ago)"                                   AS price_1w_ago,
       "Price (1M Ago)"                                   AS price_1m_ago,
       "Price (3M Ago)"                                   AS price_3m_ago,
       "Price (6M Ago)"                                   AS price_6m_ago,
       "Price (1Y Ago)"                                   AS price_1y_ago,
       "Price (3Y Ago)"                                   AS price_3y_ago,
       "Price (5Y Ago)"                                   AS price_5y_ago,
       "Price (QTD Ago)"                                  AS price_qtd_ago,
       "Rel. Volume"                                      AS rel_volume,
       "52W High/Adj"                                     AS "52w_high_adj",
       "52W Low/Adj"                                      AS "52w_low_adj",
       "EMA (20D)"                                        AS ema_20d,
       "EMA (50D)"                                        AS ema_50d,
       "EMA (100D)"                                       AS ema_100d,
       "EMA (250D)"                                       AS ema_250d,
       "Price Target (1W Ago)"                            AS price_target_1w_ago,
       "Price Target (1M Ago)"                            AS price_target_1m_ago,
       "Price Target (3M Ago)"                            AS price_target_3m_ago,
       "Price Target (6M Ago)"                            AS price_target_6m_ago,
       "Price Target (MTD Ago)"                           AS price_target_mtd_ago,
       "Price Target (QTD Ago)"                           AS price_target_qtd_ago,
       "Price Target (1Y Ago)"                            AS price_target_1y_ago,
       "Price Target - High (1W Ago)"                     AS price_target_high_1w_ago,
       "Price Target - High (1M Ago)"                     AS price_target_high_1m_ago,
       "Price Target - High (6M Ago)"                     AS price_target_high_6m_ago,
       "Price Target - High (MTD Ago)"                    AS price_target_high_mtd_ago,
       "Price Target - High (3M Ago)"                     AS price_target_high_3m_ago,
       "Price Target - High (QTD Ago)"                    AS price_target_high_qtd_ago,
       "Price Target - High (1Y Ago)"                     AS price_target_high_1y_ago,
       "Price Target - High (YTD Ago)"                    AS price_target_high_ytd_ago,
       "Price Target - Low (1W Ago)"                      AS price_target_low_1w_ago,
       "Price Target - Low (1M Ago)"                      AS price_target_low_1m_ago,
       "Price Target - Low (3M Ago)"                      AS price_target_low_3m_ago,
       "Price Target - Low (6M Ago)"                      AS price_target_low_6m_ago,
       "Price Target - Low (MTD Ago)"                     AS price_target_low_mtd_ago,
       "Price Target - Low (QTD Ago)"                     AS price_target_low_qtd_ago,
       "Price Target - Low (YTD Ago)"                     AS price_target_low_ytd_ago,
       "Price Target - Low (1Y Ago)"                      AS price_target_low_1y_ago,
       "Price Target - Median (1W Ago)"                   AS price_target_median_1w_ago,
       "Price Target - Median (1M Ago)"                   AS price_target_median_1m_ago,
       "Price Target - Median (3M Ago)"                   AS price_target_median_3m_ago,
       "Price Target - Median (6M Ago)"                   AS price_target_median_6m_ago,
       "Price Target - Median (MTD Ago)"                  AS price_target_median_mtd_ago,
       "Price Target - Median (QTD Ago)"                  AS price_target_median_qtd_ago,
       "Price Target - Median (YTD Ago)"                  AS price_target_median_ytd_ago,
       "Price Target - Median (1Y Ago)"                   AS price_target_median_1y_ago,
       "Target % (Avg)"                                   AS avg_target,
       "Total Revenues (FQ)"                              AS total_revenues_fq,
       "Total Revenues (-1FY)"                            AS total_revenues_1fy,
       "Total Revenues (FY)"                              AS total_revenues_fy,
       "Total Revenues (LTM)"                             AS total_revenues_ltm,
       "Total Operating Expenses (LTM)"                   AS total_operating_expenses_ltm,
       "Total Operating Expenses (FQ)"                    AS total_operating_expenses_fq,
       "Total Operating Expenses (FY)"                    AS total_operating_expenses_fy,
       "Total Operating Expenses (-1FQFQ)"                AS total_operating_expenses_1fqfq,
       "Total Operating Expenses (-2FQFQ)"                AS total_operating_expenses_2fqfq,
       "Total Operating Expenses (-3FQFQ)"                AS total_operating_expenses_3fqfq,
       "Total Operating Expenses (-4FQFQ)"                AS total_operating_expenses_4fqfq,
       "Total Operating Expenses (-1FY)"                  AS total_operating_expenses_1fy,
       "Total Operating Expenses (-2FY)"                  AS total_operating_expenses_2fy,
       "Total Operating Expenses (-3FY)"                  AS total_operating_expenses_3fy,
       "Total Operating Expenses (-4FY)"                  AS total_operating_expenses_4fy,
       "Net Income/Adj. (-1FY)"                           AS net_income_adj_1fy,
       "EBITDA (FQ)"                                      AS ebitda_fq,
       "EBITDA (LTM)"                                     AS ebitda_ltm,
       "EBITDA (FY)"                                      AS ebitda_fy,
       "EBITDA (-1FY)"                                    AS ebitda_1fy,
       "EBITDA/Adj. (LTM)"                                AS ebitda_adj_ltm,
       "EBITDA/Adj. (FY)"                                 AS ebitda_adj_fy,
       "EBITDA/Adj. (-1FY)"                               AS ebitda_adj_1fy,
       "EBIT (FQ)"                                        AS ebit_fq,
       "EBIT (LTM)"                                       AS ebit_ltm,
       "EBIT (FY)"                                        AS ebit_fy,
       "EBIT (-1FY)"                                      AS ebit_1fy,
       "EBIT/Adj. (-1FY)"                                 AS ebit_adj_1fy,
       "EBIT/Adj. (FY)"                                   AS ebit_adj_fy,
       "EBIT/Adj. (LTM)"                                  AS ebit_adj_ltm,
       "EBIT - Est Med (FY1E)"                            AS ebit_est_med_fy1e,
       "EBIT - Est Med (NTM)"                             AS ebit_est_med_ntm,
       "Net Income - (IS) (FY)"                           AS net_income_is_fy,
       "Net Income - (IS) (LTM)"                          AS net_income_is_ltm,
       "Normalized Net Income (FY)"                       AS normalized_net_income_fy,
       "Normalized Net Income (LTM)"                      AS normalized_net_income_ltm,
       "Net Income/Adj. (FY)"                             AS net_income_adj_fy,
       "Net Income/Adj. (LTM)"                            AS net_income_adj_ltm,
       "Gross Profit (LTM)"                               AS gross_profit_ltm,
       "Gross Profit (FY)"                                AS gross_profit_fy,
       "Cost Of Revenues (LTM)"                           AS cost_of_revenues_ltm,
       "Operating Income (LTM)"                           AS operating_income_ltm,
       "Operating Income (FY)"                            AS operating_income_fy,
       "R&D Expenses (LTM)"                               AS randd_expenses_ltm,
       "Interest Expense/Total (LTM)"                     AS interest_expense_total_ltm,
       "Interest Income On Investments (LTM)"             AS interest_income_on_investments_ltm,
       "Net Income - (IS) (-1FY)"                         AS net_income_is_1fy,
       "Normalized Net Income (-1FY)"                     AS normalized_net_income_1fy,
       "Total Revenues (5YAVGFQ)"                         AS total_revenues_5yavgfq,
       "EBITDA (5YAVGFQ)"                                 AS ebitda_5yavgfq,
       "EBIT (5YAVGFQ)"                                   AS ebit_5yavgfq,
       "Operating Income (FQ)"                            AS operating_income_fq,
       "Operating Income (5YAVGFQ)"                       AS operating_income_5yavgfq,
       "Normalized Net Income (FQ)"                       AS normalized_net_income_fq,
       "Normalized Net Income (5YAVGFQ)"                  AS normalized_net_income_5yavgfq,
       "Net Income/Adj. (FQ)"                             AS net_income_adj_fq,
       "Net Income/Adj. (5YAVGFQ)"                        AS net_income_adj_5yavgfq,
       "Net Income - (IS) (FQ)"                           AS net_income_is_fq,
       "Net Income - (IS) (5YAVGFQ)"                      AS net_income_is_5yavgfq,
       "Net Income - (IS) (5YAVGLTM)"                     AS net_income_is_5yavgltm,
       "Normalized Net Income (5YAVGLTM)"                 AS normalized_net_income_5yavgltm,
       "EBITDA (5YAVGLTM)"                                AS ebitda_5yavgltm,
       "EBIT (5YAVGLTM)"                                  AS ebit_5yavgltm,
       "Total Revenues (5YAVGLTM)"                        AS total_revenues_5yavgltm,
       "Selling General & Admin Expenses/Total (FQ)"      AS selling_general_and_admin_expenses_total_fq,
       "Selling General & Admin Expenses/Total (FY)"      AS selling_general_and_admin_expenses_total_fy,
       "Selling General & Admin Expenses/Total (-1FY)"    AS selling_general_and_admin_expenses_total_1fy,
       "Selling General & Admin Expenses/Total (5YAVGFQ)" AS selling_general_and_admin_expenses_total_5yavgfq,
       "Marketing Expenses (FQ)"                          AS marketing_expenses_fq,
       "Marketing Expenses (FY)"                          AS marketing_expenses_fy,
       "Marketing Expenses (-1FY)"                        AS marketing_expenses_1fy,
       "Marketing Expenses (5YAVGLTM)"                    AS marketing_expenses_5yavgltm,
       "Revenues - Est Avg (NTM)"                         AS revenues_est_avg_ntm,
       "Revenues - Est Avg (FY1E)"                        AS revenues_est_avg_fy1e,
       "Revenues - Est Med (NTM)"                         AS revenues_est_med_ntm,
       "Revenues - Est Med (FY1E)"                        AS revenues_est_med_fy1e,
       "EBITDA - Est Avg (NTM)"                           AS ebitda_est_avg_ntm,
       "EBITDA - Est Avg (FY1E)"                          AS ebitda_est_avg_fy1e,
       "Total Revenues (-1FQFQ)"                          AS total_revenues_1fqfq,
       "Total Revenues (-2FQFQ)"                          AS total_revenues_2fqfq,
       "Total Revenues (-3FQFQ)"                          AS total_revenues_3fqfq,
       "Total Revenues (-4FQFQ)"                          AS total_revenues_4fqfq,
       "Total Revenues (-2FY)"                            AS total_revenues_2fy,
       "Total Revenues (-3FY)"                            AS total_revenues_3fy,
       "Total Revenues (-4FY)"                            AS total_revenues_4fy,
       "Gross Profit (FQ)"                                AS gross_profit_fq,
       "Gross Profit (-1FQFQ)"                            AS gross_profit_1fqfq,
       "Gross Profit (-2FQFQ)"                            AS gross_profit_2fqfq,
       "Gross Profit (-3FQFQ)"                            AS gross_profit_3fqfq,
       "Gross Profit (-4FQFQ)"                            AS gross_profit_4fqfq,
       "Gross Profit (-1FY)"                              AS gross_profit_1fy,
       "Gross Profit (-2FY)"                              AS gross_profit_2fy,
       "Gross Profit (-3FY)"                              AS gross_profit_3fy,
       "Gross Profit (-4FY)"                              AS gross_profit_4fy,
       "Operating Income (-1FQFQ)"                        AS operating_income_1fqfq,
       "Operating Income (-2FQFQ)"                        AS operating_income_2fqfq,
       "Operating Income (-3FQFQ)"                        AS operating_income_3fqfq,
       "Operating Income (-4FQFQ)"                        AS operating_income_4fqfq,
       "Operating Income (-1FY)"                          AS operating_income_1fy,
       "Operating Income (-2FY)"                          AS operating_income_2fy,
       "Operating Income (-3FY)"                          AS operating_income_3fy,
       "Operating Income (-4FY)"                          AS operating_income_4fy,
       "R&D Expenses (FQ)"                                AS randd_expenses_fq,
       "R&D Expenses (FY)"                                AS randd_expenses_fy,
       "R&D Expenses (-1FQFQ)"                            AS randd_expenses_1fqfq,
       "R&D Expenses (-2FQFQ)"                            AS randd_expenses_2fqfq,
       "R&D Expenses (-3FQFQ)"                            AS randd_expenses_3fqfq,
       "R&D Expenses (-4FQFQ)"                            AS randd_expenses_4fqfq,
       "R&D Expenses (-1FY)"                              AS randd_expenses_1fy,
       "R&D Expenses (-2FY)"                              AS randd_expenses_2fy,
       "R&D Expenses (-3FY)"                              AS randd_expenses_3fy,
       "R&D Expenses (-4FY)"                              AS randd_expenses_4fy,
       "Net Income - (IS) (-1FQFQ)"                       AS net_income_is_1fqfq,
       "Net Income - (IS) (-2FQFQ)"                       AS net_income_is_2fqfq,
       "Net Income - (IS) (-3FQFQ)"                       AS net_income_is_3fqfq,
       "Net Income - (IS) (-4FQFQ)"                       AS net_income_is_4fqfq,
       "Net Income - (IS) (-2FY)"                         AS net_income_is_2fy,
       "Net Income - (IS) (-3FY)"                         AS net_income_is_3fy,
       "Net Income - (IS) (-4FY)"                         AS net_income_is_4fy,
       "Normalized Net Income (-1FQFQ)"                   AS normalized_net_income_1fqfq,
       "Normalized Net Income (-2FQFQ)"                   AS normalized_net_income_2fqfq,
       "Normalized Net Income (-3FQFQ)"                   AS normalized_net_income_3fqfq,
       "Normalized Net Income (-4FQFQ)"                   AS normalized_net_income_4fqfq,
       "Normalized Net Income (-2FY)"                     AS normalized_net_income_2fy,
       "Normalized Net Income (-3FY)"                     AS normalized_net_income_3fy,
       "Normalized Net Income (-4FY)"                     AS normalized_net_income_4fy,
       "Net Income/Adj. (-1FQFQ)"                         AS net_income_adj_1fqfq,
       "Net Income/Adj. (-2FQFQ)"                         AS net_income_adj_2fqfq,
       "Net Income/Adj. (-3FQFQ)"                         AS net_income_adj_3fqfq,
       "Net Income/Adj. (-4FQFQ)"                         AS net_income_adj_4fqfq,
       "Net Income/Adj. (-2FY)"                           AS net_income_adj_2fy,
       "Net Income/Adj. (-3FY)"                           AS net_income_adj_3fy,
       "Net Income/Adj. (-4FY)"                           AS net_income_adj_4fy,
       "EBIT (-1FQFQ)"                                    AS ebit_1fqfq,
       "EBIT (-2FQFQ)"                                    AS ebit_2fqfq,
       "EBIT (-3FQFQ)"                                    AS ebit_3fqfq,
       "EBIT (-4FQFQ)"                                    AS ebit_4fqfq,
       "EBIT (-2FY)"                                      AS ebit_2fy,
       "EBIT (-3FY)"                                      AS ebit_3fy,
       "EBIT (-4FY)"                                      AS ebit_4fy,
       "EBIT/Adj. (FQ)"                                   AS ebit_adj_fq,
       "EBIT/Adj. (-1FQFQ)"                               AS ebit_adj_1fqfq,
       "EBIT/Adj. (-2FQFQ)"                               AS ebit_adj_2fqfq,
       "EBIT/Adj. (-3FQFQ)"                               AS ebit_adj_3fqfq,
       "EBIT/Adj. (-4FQFQ)"                               AS ebit_adj_4fqfq,
       "EBIT/Adj. (-2FY)"                                 AS ebit_adj_2fy,
       "EBIT/Adj. (-3FY)"                                 AS ebit_adj_3fy,
       "EBIT/Adj. (-4FY)"                                 AS ebit_adj_4fy,
       "EBITDA (-1FQFQ)"                                  AS ebitda_1fqfq,
       "EBITDA (-2FQFQ)"                                  AS ebitda_2fqfq,
       "EBITDA (-3FQFQ)"                                  AS ebitda_3fqfq,
       "EBITDA (-4FQFQ)"                                  AS ebitda_4fqfq,
       "EBITDA (-2FY)"                                    AS ebitda_2fy,
       "EBITDA (-3FY)"                                    AS ebitda_3fy,
       "EBITDA (-4FY)"                                    AS ebitda_4fy,
       "EBITDA/Adj. (FQ)"                                 AS ebitda_adj_fq,
       "EBITDA/Adj. (-1FQFQ)"                             AS ebitda_adj_1fqfq,
       "EBITDA/Adj. (-2FQFQ)"                             AS ebitda_adj_2fqfq,
       "EBITDA/Adj. (-3FQFQ)"                             AS ebitda_adj_3fqfq,
       "EBITDA/Adj. (-4FQFQ)"                             AS ebitda_adj_4fqfq,
       "EBITDA/Adj. (-2FY)"                               AS ebitda_adj_2fy,
       "EBITDA/Adj. (-3FY)"                               AS ebitda_adj_3fy,
       "EBITDA/Adj. (-4FY)"                               AS ebitda_adj_4fy,
       "Gain (Loss) On Sale Of Assets (LTM)"              AS gain_loss_on_sale_of_assets_ltm,
       "Impairment of Goodwill (FQ)"                      AS impairment_of_goodwill_fq,
       "Impairment of Goodwill (LTM)"                     AS impairment_of_goodwill_ltm,
       "Impairment of Goodwill (-1FY)"                    AS impairment_of_goodwill_1fy,
       "Impairment of Goodwill (FY)"                      AS impairment_of_goodwill_fy,
       "Asset Writedown (LTM)"                            AS asset_writedown_ltm,
       "Asset Writedown (FY)"                             AS asset_writedown_fy,
       "Asset Writedown (-1FY)"                           AS asset_writedown_1fy,
       "Restructuring Charges (LTM)"                      AS restructuring_charges_ltm,
       "Restructuring Charges (FQ)"                       AS restructuring_charges_fq,
       "Restructuring Charges (-1FY)"                     AS restructuring_charges_1fy,
       "Restructuring Charges (FY)"                       AS restructuring_charges_fy,
       "Merger & Restructuring Charges (LTM)"             AS merger_and_restructuring_charges_ltm,
       "Other Unusual Items/Total (LTM)"                  AS other_unusual_items_total_ltm,
       "Asset Writedown (FQ)"                             AS asset_writedown_fq,
       "Asset Writedown (5YAVGFQ)"                        AS asset_writedown_5yavgfq,
       "Impairment of Goodwill (5YAVGFQ)"                 AS impairment_of_goodwill_5yavgfq,
       "Restructuring Charges (5YAVGFQ)"                  AS restructuring_charges_5yavgfq,
       "Merger & Restructuring Charges (FQ)"              AS merger_and_restructuring_charges_fq,
       "Merger & Restructuring Charges (FY)"              AS merger_and_restructuring_charges_fy,
       "Merger & Restructuring Charges (5YAVGFQ)"         AS merger_and_restructuring_charges_5yavgfq,
       "Merger & Restructuring Charges (-1FQFQ)"          AS merger_and_restructuring_charges_1fqfq,
       "Merger & Restructuring Charges (-2FQFQ)"          AS merger_and_restructuring_charges_2fqfq,
       "Merger & Restructuring Charges (-3FQFQ)"          AS merger_and_restructuring_charges_3fqfq,
       "Merger & Restructuring Charges (-4FQFQ)"          AS merger_and_restructuring_charges_4fqfq,
       "Merger & Restructuring Charges (-1FY)"            AS merger_and_restructuring_charges_1fy,
       "Merger & Restructuring Charges (-2FY)"            AS merger_and_restructuring_charges_2fy,
       "Merger & Restructuring Charges (-3FY)"            AS merger_and_restructuring_charges_3fy,
       "Merger & Restructuring Charges (-4FY)"            AS merger_and_restructuring_charges_4fy,
       "Impairment of Goodwill (-1FQFQ)"                  AS impairment_of_goodwill_1fqfq,
       "Impairment of Goodwill (-2FQFQ)"                  AS impairment_of_goodwill_2fqfq,
       "Impairment of Goodwill (-3FQFQ)"                  AS impairment_of_goodwill_3fqfq,
       "Impairment of Goodwill (-4FQFQ)"                  AS impairment_of_goodwill_4fqfq,
       "Impairment of Goodwill (-2FY)"                    AS impairment_of_goodwill_2fy,
       "Impairment of Goodwill (-3FY)"                    AS impairment_of_goodwill_3fy,
       "Impairment of Goodwill (-4FY)"                    AS impairment_of_goodwill_4fy,
       "Asset Writedown (-1FQFQ)"                         AS asset_writedown_1fqfq,
       "Asset Writedown (-2FQFQ)"                         AS asset_writedown_2fqfq,
       "Asset Writedown (-3FQFQ)"                         AS asset_writedown_3fqfq,
       "Asset Writedown (-4FQFQ)"                         AS asset_writedown_4fqfq,
       "Asset Writedown (-2FY)"                           AS asset_writedown_2fy,
       "Asset Writedown (-3FY)"                           AS asset_writedown_3fy,
       "Asset Writedown (-4FY)"                           AS asset_writedown_4fy,
       "Asset Writedown (-5FY)"                           AS asset_writedown_5fy,
       "Gain (Loss) On Sale Of Assets (FQ)"               AS gain_loss_on_sale_of_assets_fq,
       "Gain (Loss) On Sale Of Assets (FY)"               AS gain_loss_on_sale_of_assets_fy,
       "Gain (Loss) On Sale Of Assets (-1FQFQ)"           AS gain_loss_on_sale_of_assets_1fqfq,
       "Gain (Loss) On Sale Of Assets (-2FQFQ)"           AS gain_loss_on_sale_of_assets_2fqfq,
       "Gain (Loss) On Sale Of Assets (-3FQFQ)"           AS gain_loss_on_sale_of_assets_3fqfq,
       "Gain (Loss) On Sale Of Assets (-4FQFQ)"           AS gain_loss_on_sale_of_assets_4fqfq,
       "Gain (Loss) On Sale Of Assets (-1FY)"             AS gain_loss_on_sale_of_assets_1fy,
       "Gain (Loss) On Sale Of Assets (-2FY)"             AS gain_loss_on_sale_of_assets_2fy,
       "Gain (Loss) On Sale Of Assets (-3FY)"             AS gain_loss_on_sale_of_assets_3fy,
       "Gain (Loss) On Sale Of Assets (-4FY)"             AS gain_loss_on_sale_of_assets_4fy,
       "Restructuring Charges (-1FQFQ)"                   AS restructuring_charges_1fqfq,
       "Restructuring Charges (-2FQFQ)"                   AS restructuring_charges_2fqfq,
       "Restructuring Charges (-3FQFQ)"                   AS restructuring_charges_3fqfq,
       "Restructuring Charges (-4FQFQ)"                   AS restructuring_charges_4fqfq,
       "Restructuring Charges (-2FY)"                     AS restructuring_charges_2fy,
       "Restructuring Charges (-3FY)"                     AS restructuring_charges_3fy,
       "Restructuring Charges (-4FY)"                     AS restructuring_charges_4fy,
       "Interest And Investment Income (LTM)"             AS interest_and_investment_income_ltm,
       "Interest And Investment Income (FQ)"              AS interest_and_investment_income_fq,
       "Interest And Investment Income (FY)"              AS interest_and_investment_income_fy,
       "Interest And Investment Income (-1FQFQ)"          AS interest_and_investment_income_1fqfq,
       "Interest And Investment Income (-2FQFQ)"          AS interest_and_investment_income_2fqfq,
       "Interest And Investment Income (-3FQFQ)"          AS interest_and_investment_income_3fqfq,
       "Interest And Investment Income (-4FQFQ)"          AS interest_and_investment_income_4fqfq,
       "Interest And Investment Income (-1FY)"            AS interest_and_investment_income_1fy,
       "Interest And Investment Income (-2FY)"            AS interest_and_investment_income_2fy,
       "Interest And Investment Income (-3FY)"            AS interest_and_investment_income_3fy,
       "Interest And Investment Income (-4FY)"            AS interest_and_investment_income_4fy,
       "Effective Tax Rate - (Ratio) (LTM)"               AS effective_tax_rate_ltm,
       "Effective Tax Rate - (Ratio) (FQ)"                AS effective_tax_rate_fq,
       "Effective Tax Rate - (Ratio) (-1FQFQ)"            AS effective_tax_rate_1fqfq,
       "Effective Tax Rate - (Ratio) (-2FQFQ)"            AS effective_tax_rate_2fqfq,
       "Effective Tax Rate - (Ratio) (-4FQFQ)"            AS effective_tax_rate_4fqfq,
       "Effective Tax Rate - (Ratio) (-3FQFQ)"            AS effective_tax_rate_3fqfq,
       "Effective Tax Rate - (Ratio) (FY)"                AS effective_tax_rate_fy,
       "Effective Tax Rate - (Ratio) (-1FY)"              AS effective_tax_rate_1fy,
       "Effective Tax Rate - (Ratio) (-2FY)"              AS effective_tax_rate_2fy,
       "Effective Tax Rate - (Ratio) (-3FY)"              AS effective_tax_rate_3fy,
       "Effective Tax Rate - (Ratio) (-4FY)"              AS effective_tax_rate_4fy,
       "TBV (FY)"                                         AS tbv_fy,
       "TBV (LTM)"                                        AS tbv_ltm,
       "Total Debt (FY)"                                  AS total_debt_fy,
       "Total Equity (FY)"                                AS total_equity_fy,
       "Total Equity (LTM)"                               AS total_equity_ltm,
       "Total Debt (LTM)"                                 AS total_debt_ltm,
       "Total Assets (LTM)"                               AS total_assets_ltm,
       "Total Assets (FY)"                                AS total_assets_fy,
       "Inventory (LTM)"                                  AS inventory_ltm,
       "Goodwill (FQ)"                                    AS goodwill_fq,
       "Goodwill (LTM)"                                   AS goodwill_ltm,
       "Goodwill (FY)"                                    AS goodwill_fy,
       "Goodwill (-1FY)"                                  AS goodwill_1fy,
       "Retained Earnings (LTM)"                          AS retained_earnings_ltm,
       "Total Current Assets (LTM)"                       AS total_current_assets_ltm,
       "Total Current Liabilities (LTM)"                  AS total_current_liabilities_ltm,
       "Working Capital (LTM)"                            AS working_capital_ltm,
       "Cash And Equivalents (LTM)"                       AS cash_and_equivalents_ltm,
       "Cash And Equivalents (FQ)"                        AS cash_and_equivalents_fq,
       "Cash And Equivalents (FY)"                        AS cash_and_equivalents_fy,
       "Cash And Equivalents (5YAVGFQ)"                   AS cash_and_equivalents_5yavgfq,
       "Inventory (FQ)"                                   AS inventory_fq,
       "Inventory (FY)"                                   AS inventory_fy,
       "Goodwill (5YAVGFQ)"                               AS goodwill_5yavgfq,
       "Inventory (5YAVGFQ)"                              AS inventory_5yavgfq,
       "Retained Earnings (FQ)"                           AS retained_earnings_fq,
       "Retained Earnings (FY)"                           AS retained_earnings_fy,
       "Retained Earnings (5YAVGFQ)"                      AS retained_earnings_5yavgfq,
       "Working Capital (FQ)"                             AS working_capital_fq,
       "Working Capital (FY)"                             AS working_capital_fy,
       "Working Capital (5YAVGFY)"                        AS working_capital_5yavgfy,
       "Gross Intangible Assets (LTM)"                    AS gross_intangible_assets_ltm,
       "Gross Intangible Assets (FY)"                     AS gross_intangible_assets_fy,
       "Gross Intangible Assets (5YAVGFQ)"                AS gross_intangible_assets_5yavgfq,
       "Accounts Receivable/Total (FY)"                   AS accounts_receivable_total_fy,
       "Accounts Receivable/Total (-1FY)"                 AS accounts_receivable_total_1fy,
       "Accounts Receivable/Total (5YAVGFQ)"              AS accounts_receivable_total_5yavgfq,
       "Working Capital (-1FQ)"                           AS working_capital_1fq,
       "Working Capital (-2FQ)"                           AS working_capital_2fq,
       "Working Capital (-3FQ)"                           AS working_capital_3fq,
       "Working Capital (-4FQ)"                           AS working_capital_4fq,
       "Working Capital (-1FY)"                           AS working_capital_1fy,
       "Working Capital (-2FY)"                           AS working_capital_2fy,
       "Working Capital (-3FY)"                           AS working_capital_3fy,
       "Working Capital (-4FY)"                           AS working_capital_4fy,
       "Total Debt (FQ)"                                  AS total_debt_fq,
       "Total Debt (-1FQ)"                                AS total_debt_1fq,
       "Total Debt (-2FQ)"                                AS total_debt_2fq,
       "Total Debt (-3FQ)"                                AS total_debt_3fq,
       "Total Debt (-4FQ)"                                AS total_debt_4fq,
       "Total Debt (-1FY)"                                AS total_debt_1fy,
       "Total Debt (-2FY)"                                AS total_debt_2fy,
       "Total Debt (-3FY)"                                AS total_debt_3fy,
       "Total Debt (-4FY)"                                AS total_debt_4fy,
       "Total Assets (FQ)"                                AS total_assets_fq,
       "Total Assets (-1FQ)"                              AS total_assets_1fq,
       "Total Assets (-2FQ)"                              AS total_assets_2fq,
       "Total Assets (-3FQ)"                              AS total_assets_3fq,
       "Total Assets (-4FQ)"                              AS total_assets_4fq,
       "Total Assets (-1FY)"                              AS total_assets_1fy,
       "Total Assets (-2FY)"                              AS total_assets_2fy,
       "Total Assets (-3FY)"                              AS total_assets_3fy,
       "Total Assets (-4FY)"                              AS total_assets_4fy,
       "Inventory (-1FQ)"                                 AS inventory_1fq,
       "Inventory (-2FQ)"                                 AS inventory_2fq,
       "Inventory (-3FQ)"                                 AS inventory_3fq,
       "Inventory (-4FQ)"                                 AS inventory_4fq,
       "Inventory (-1FY)"                                 AS inventory_1fy,
       "Inventory (-2FY)"                                 AS inventory_2fy,
       "Inventory (-3FY)"                                 AS inventory_3fy,
       "Inventory (-4FY)"                                 AS inventory_4fy,
       "Goodwill (-1FQ)"                                  AS goodwill_1fq,
       "Goodwill (-2FQ)"                                  AS goodwill_2fq,
       "Goodwill (-3FQ)"                                  AS goodwill_3fq,
       "Goodwill (-4FQ)"                                  AS goodwill_4fq,
       "Goodwill (-2FY)"                                  AS goodwill_2fy,
       "Goodwill (-3FY)"                                  AS goodwill_3fy,
       "Goodwill (-4FY)"                                  AS goodwill_4fy,
       "Retained Earnings (-1FQ)"                         AS retained_earnings_1fq,
       "Retained Earnings (-2FQ)"                         AS retained_earnings_2fq,
       "Retained Earnings (-3FQ)"                         AS retained_earnings_3fq,
       "Retained Earnings (-4FQ)"                         AS retained_earnings_4fq,
       "Retained Earnings (-1FY)"                         AS retained_earnings_1fy,
       "Retained Earnings (-2FY)"                         AS retained_earnings_2fy,
       "Retained Earnings (-3FY)"                         AS retained_earnings_3fy,
       "Retained Earnings (-4FY)"                         AS retained_earnings_4fy,
       "Cash And Equivalents (-1FQ)"                      AS cash_and_equivalents_1fq,
       "Cash And Equivalents (-2FQ)"                      AS cash_and_equivalents_2fq,
       "Cash And Equivalents (-3FQ)"                      AS cash_and_equivalents_3fq,
       "Cash And Equivalents (-4FQ)"                      AS cash_and_equivalents_4fq,
       "Cash And Equivalents (-1FY)"                      AS cash_and_equivalents_1fy,
       "Cash And Equivalents (-2FY)"                      AS cash_and_equivalents_2fy,
       "Cash And Equivalents (-3FY)"                      AS cash_and_equivalents_3fy,
       "Cash And Equivalents (-4FY)"                      AS cash_and_equivalents_4fy,
       "Gross Intangible Assets (FQ)"                     AS gross_intangible_assets_fq,
       "Gross Intangible Assets (-1FQ)"                   AS gross_intangible_assets_1fq,
       "Gross Intangible Assets (-2FQ)"                   AS gross_intangible_assets_2fq,
       "Gross Intangible Assets (-3FQ)"                   AS gross_intangible_assets_3fq,
       "Gross Intangible Assets (-4FQ)"                   AS gross_intangible_assets_4fq,
       "Gross Intangible Assets (-1FY)"                   AS gross_intangible_assets_1fy,
       "Gross Intangible Assets (-2FY)"                   AS gross_intangible_assets_2fy,
       "Gross Intangible Assets (-3FY)"                   AS gross_intangible_assets_3fy,
       "Gross Intangible Assets (-4FY)"                   AS gross_intangible_assets_4fy,
       "CFF (LTM)"                                        AS cff_ltm,
       "CFI (LTM)"                                        AS cfi_ltm,
       "FCF (LTM)"                                        AS fcf_ltm,
       "CFO (LTM)"                                        AS cfo_ltm,
       "Cash Acquisitions (LTM)"                          AS cash_acquisitions_ltm,
       "Cash Acquisitions (FY)"                           AS cash_acquisitions_fy,
       "Cash Acquisitions (-1FY)"                         AS cash_acquisitions_1fy,
       "Capital Expenditure (LTM)"                        AS capital_expenditure_ltm,
       "Capital Expenditure (-1FY)"                       AS capital_expenditure_1fy,
       "Capital Expenditure (FY)"                         AS capital_expenditure_fy,
       "CFF (FY)"                                         AS cff_fy,
       "CFF (-1FY)"                                       AS cff_1fy,
       "CFI (FY)"                                         AS cfi_fy,
       "CFI (-1FY)"                                       AS cfi_1fy,
       "CFO (FY)"                                         AS cfo_fy,
       "CFO (-1FY)"                                       AS cfo_1fy,
       "FCF (FY)"                                         AS fcf_fy,
       "FCF (-1FY)"                                       AS fcf_1fy,
       "Capital Expenditure (FQ)"                         AS capital_expenditure_fq,
       "Capital Expenditure (5YAVGFQ)"                    AS capital_expenditure_5yavgfq,
       "CFF (FQ)"                                         AS cff_fq,
       "CFI (FQ)"                                         AS cfi_fq,
       "CFO (FQ)"                                         AS cfo_fq,
       "FCF (FQ)"                                         AS fcf_fq,
       "FCF (5YAVGFQ)"                                    AS fcf_5yavgfq,
       "Cash Acquisitions (FQ)"                           AS cash_acquisitions_fq,
       "Cash Acquisitions (5YAVGFQ)"                      AS cash_acquisitions_5yavgfq,
       "Common Dividends Paid (LTM)"                      AS common_dividends_paid_ltm,
       "Common Dividends Paid (FY)"                       AS common_dividends_paid_fy,
       "CFO (-1FQFQ)"                                     AS cfo_1fqfq,
       "CFO (-2FQFQ)"                                     AS cfo_2fqfq,
       "CFO (-3FQFQ)"                                     AS cfo_3fqfq,
       "CFO (-4FQFQ)"                                     AS cfo_4fqfq,
       "CFI (-1FQFQ)"                                     AS cfi_1fqfq,
       "CFI (-2FQFQ)"                                     AS cfi_2fqfq,
       "CFI (-3FQFQ)"                                     AS cfi_3fqfq,
       "CFI (-4FQFQ)"                                     AS cfi_4fqfq,
       "CFI (-2FY)"                                       AS cfi_2fy,
       "CFI (-3FY)"                                       AS cfi_3fy,
       "CFI (-4FY)"                                       AS cfi_4fy,
       "FCF (-1FQFQ)"                                     AS fcf_1fqfq,
       "FCF (-2FQFQ)"                                     AS fcf_2fqfq,
       "FCF (-3FQFQ)"                                     AS fcf_3fqfq,
       "FCF (-4FQFQ)"                                     AS fcf_4fqfq,
       "CFF (-2FY)"                                       AS cff_2fy,
       "CFF (-3FY)"                                       AS cff_3fy,
       "CFF (-4FY)"                                       AS cff_4fy,
       "CFF (-1FQFQ)"                                     AS cff_1fqfq,
       "CFF (-2FQFQ)"                                     AS cff_2fqfq,
       "CFF (-3FQFQ)"                                     AS cff_3fqfq,
       "CFF (-4FQFQ)"                                     AS cff_4fqfq,
       "CFO (-2FY)"                                       AS cfo_2fy,
       "CFO (-3FY)"                                       AS cfo_3fy,
       "CFO (-4FY)"                                       AS cfo_4fy,
       "Cash Acquisitions (-1FQFQ)"                       AS cash_acquisitions_1fqfq,
       "Cash Acquisitions (-2FQFQ)"                       AS cash_acquisitions_2fqfq,
       "Cash Acquisitions (-3FQFQ)"                       AS cash_acquisitions_3fqfq,
       "Cash Acquisitions (-4FQFQ)"                       AS cash_acquisitions_4fqfq,
       "FCF (-2FY)"                                       AS fcf_2fy,
       "FCF (-3FY)"                                       AS fcf_3fy,
       "FCF (-4FY)"                                       AS fcf_4fy,
       "Cash Acquisitions (-2FY)"                         AS cash_acquisitions_2fy,
       "Cash Acquisitions (-3FY)"                         AS cash_acquisitions_3fy,
       "Cash Acquisitions (-4FY)"                         AS cash_acquisitions_4fy,
       "Capital Expenditure (-1FQFQ)"                     AS capital_expenditure_1fqfq,
       "Capital Expenditure (-2FQFQ)"                     AS capital_expenditure_2fqfq,
       "Capital Expenditure (-3FQFQ)"                     AS capital_expenditure_3fqfq,
       "Capital Expenditure (-4FQFQ)"                     AS capital_expenditure_4fqfq,
       "Capital Expenditure (-2FY)"                       AS capital_expenditure_2fy,
       "Capital Expenditure (-3FY)"                       AS capital_expenditure_3fy,
       "Capital Expenditure (-4FY)"                       AS capital_expenditure_4fy,
       "FCF - Est Avg (FY1E)"                             AS fcf_est_avg_fy1e,
       "FCF - Est Avg (FY2E)"                             AS fcf_est_avg_fy2e,
       "FCF - Est Avg (FY3E)"                             AS fcf_est_avg_fy3e,
       "FCF - Est Avg (FY4E)"                             AS fcf_est_avg_fy4e,
       "FCF - Est Avg (FY5E)"                             AS fcf_est_avg_fy5e,
       "P/E (NTM)"                                        AS p_e_ntm,
       "P/E (LTM)"                                        AS p_e_ltm,
       "Altman Z-Score (FY)"                              AS altman_z_score_fy,
       "Altman Z-Score (FQ)"                              AS altman_z_score_fq,
       "Altman Z-Score (LTM)"                             AS altman_z_score_ltm,
       "P/TBV (LTM)"                                      AS p_tbv_ltm,
       "Return On Equity % (LTM)"                         AS return_on_equity_pct_ltm,
       "Return On Equity % (FY)"                          AS return_on_equity_pct_fy,
       "Current Ratio (FY)"                               AS current_ratio_fy,
       "Current Ratio (LTM)"                              AS current_ratio_ltm,
       "Asset Turnover (FY)"                              AS asset_turnover_fy,
       "Asset Turnover (LTM)"                             AS asset_turnover_ltm,
       "EPS Norm - Est Avg (NTM)"                         AS eps_norm_est_avg_ntm,
       "EPS/Adj. (-1FY)"                                  AS eps_adj_1fy,
       "EPS/Adj. (FY)"                                    AS eps_adj_fy,
       "EPS/Adj. (LTM)"                                   AS eps_adj_ltm,
       "EPS Norm - Est Avg (FY1E)"                        AS eps_norm_est_avg_fy1e,
       "Return on Assets (ROA) % (LTM)"                   AS return_on_assets_roa_pct_ltm,
       "Return on Assets (ROA) % (FY)"                    AS return_on_assets_roa_pct_fy,
       "P/B (LTM)"                                        AS p_b_ltm,
       "P/B (-1FY)"                                       AS p_b_1fy,
       "P/B (5YAVG)"                                      AS p_b_5yavg,
       "EV/Sales (EST FY1)"                               AS ev_sales_est_fy1,
       "EV/Sales (LTM)"                                   AS ev_sales_ltm,
       "EV/Sales (NTM)"                                   AS ev_sales_ntm,
       "EV/Sales (-1FYLTM)"                               AS ev_sales_1fyltm,
       "EV/Sales (-2FYLTM)"                               AS ev_sales_2fyltm,
       "EV/Sales (-3FYLTM)"                               AS ev_sales_3fyltm,
       "EV/Sales (3YAVGLTM)"                              AS ev_sales_3yavgltm,
       "EV/Sales (-1FQLTM)"                               AS ev_sales_1fqltm,
       "EV/Sales (-2FQLTM)"                               AS ev_sales_2fqltm,
       "EV/Sales (-3FQLTM)"                               AS ev_sales_3fqltm,
       "EV/Sales (-4FQLTM)"                               AS ev_sales_4fqltm,
       "EV/EBITDA (LTM)"                                  AS ev_ebitda_ltm,
       "EV/EBITDA (NTM)"                                  AS ev_ebitda_ntm,
       "EV/EBITDA (-1FYLTM)"                              AS ev_ebitda_1fyltm,
       "EV/EBITDA (-1FQLTM)"                              AS ev_ebitda_1fqltm,
       "EV/EBITDA (3YAVGLTM)"                             AS ev_ebitda_3yavgltm,
       "EV/EBITDA (EST FY1)"                              AS ev_ebitda_est_fy1,
       "P/E (EST FY1)"                                    AS p_e_est_fy1,
       "P/E (-1FYLTM)"                                    AS p_e_1fyltm,
       "P/E (-2FYLTM)"                                    AS p_e_2fyltm,
       "P/E (-3FYLTM)"                                    AS p_e_3fyltm,
       "P/E (3YAVGLTM)"                                   AS p_e_3yavgltm,
       "P/E (-1FQLTM)"                                    AS p_e_1fqltm,
       "P/E (-2FQLTM)"                                    AS p_e_2fqltm,
       "P/E (-3FQLTM)"                                    AS p_e_3fqltm,
       "P/E (5YAVGLTM)"                                   AS p_e_5yavgltm,
       "P/E (-0FQQoQLTM)"                                 AS p_e_0fqqoqltm,
       "P/E (-0FYYoYLTM)"                                 AS p_e_0fyyoyltm,
       "P/E (-1FYYoYLTM)"                                 AS p_e_1fyyoyltm,
       "P/E (-0FQYoYLTM)"                                 AS p_e_0fqyoyltm,
       "Net EPS - Basic (LTM)"                            AS net_eps_basic_ltm,
       "Net EPS - Basic (FQ)"                             AS net_eps_basic_fq,
       "Net EPS - Basic (FY)"                             AS net_eps_basic_fy,
       "Net EPS - Basic (-1FQFQ)"                         AS net_eps_basic_1fqfq,
       "Net EPS - Basic (-2FQFQ)"                         AS net_eps_basic_2fqfq,
       "Net EPS - Basic (-3FQFQ)"                         AS net_eps_basic_3fqfq,
       "Net EPS - Basic (-4FQFQ)"                         AS net_eps_basic_4fqfq,
       "Net EPS - Basic (-1FY)"                           AS net_eps_basic_1fy,
       "Net EPS - Basic (-2FY)"                           AS net_eps_basic_2fy,
       "Net EPS - Basic (-3FY)"                           AS net_eps_basic_3fy,
       "Net EPS - Basic (-4FY)"                           AS net_eps_basic_4fy,
       "Net EPS - Basic (-5FY)"                           AS net_eps_basic_5fy,
       "EPS GAAP - Est Avg (NTM)"                         AS eps_gaap_est_avg_ntm,
       "EPS GAAP - Est Avg (FY1E)"                        AS eps_gaap_est_avg_fy1e,
       "Basic EPS - Cont (LTM)"                           AS basic_eps_cont_ltm,
       "Basic EPS - Cont (FQ)"                            AS basic_eps_cont_fq,
       "Basic EPS - Cont (FY)"                            AS basic_eps_cont_fy,
       "Basic EPS - Cont (-1FQFQ)"                        AS basic_eps_cont_1fqfq,
       "Basic EPS - Cont (-2FQFQ)"                        AS basic_eps_cont_2fqfq,
       "Basic EPS - Cont (-3FQFQ)"                        AS basic_eps_cont_3fqfq,
       "Basic EPS - Cont (-4FQFQ)"                        AS basic_eps_cont_4fqfq,
       "Basic EPS - Cont (-1FY)"                          AS basic_eps_cont_1fy,
       "Basic EPS - Cont (-2FY)"                          AS basic_eps_cont_2fy,
       "Basic EPS - Cont (-3FY)"                          AS basic_eps_cont_3fy,
       "Basic EPS - Cont (-4FY)"                          AS basic_eps_cont_4fy,
       "EPS/Adj. (FQ)"                                    AS eps_adj_fq,
       "EPS/Adj. (-1FQFQ)"                                AS eps_adj_1fqfq,
       "EPS/Adj. (-2FQFQ)"                                AS eps_adj_2fqfq,
       "EPS/Adj. (-3FQFQ)"                                AS eps_adj_3fqfq,
       "EPS/Adj. (-4FQFQ)"                                AS eps_adj_4fqfq,
       "EPS/Adj. (-2FY)"                                  AS eps_adj_2fy,
       "EPS/Adj. (-3FY)"                                  AS eps_adj_3fy,
       "EPS/Adj. (-4FY)"                                  AS eps_adj_4fy,
       "Total Return (YTD)"                               AS total_return_ytd,
       "Beta (1Y)"                                        AS beta_1y,
       "Beta (2Y)"                                        AS beta_2y,
       "Beta (5Y)"                                        AS beta_5y,
       "Total Revenues/CAGR (5Y FY)"                      AS total_revenues_cagr_5y_fy,
       "Tot. Return %/CAGR (3Y)"                          AS tot_return_pct_cagr_3y,
       "Tot. Return %/CAGR (10Y)"                         AS tot_return_pct_cagr_10y,
       "Total Return (5Y)"                                AS total_return_5y,
       "Total Return (10Y)"                               AS total_return_10y,
       "Net Income Margin % (FY)"                         AS net_income_margin_pct_fy,
       "Net Income Margin % (LTM)"                        AS net_income_margin_pct_ltm,
       "Volatility (1M)"                                  AS volatility_1m,
       "Volatility (3M)"                                  AS volatility_3m,
       "Volatility (6M)"                                  AS volatility_6m,
       "Volatility (1Y)"                                  AS volatility_1y,
       "Div Yield (Ind)"                                  AS div_yield_ind,
       "Div Yield (LTM)"                                  AS div_yield_ltm,
       "Gross Profit Margin % (FY)"                       AS gross_profit_margin_pct_fy,
       "Gross Profit Margin % (LTM)"                      AS gross_profit_margin_pct_ltm,
       "Buyback Yield (LTM)"                              AS buyback_yield_ltm,
       "Div Yield (-1FYInd)"                              AS div_yield_1fyind,
       "Div Yield (TTM)"                                  AS div_yield_ttm,
       "Div Yield (NTM)"                                  AS div_yield_ntm,
       "Div Yield (5YAVGLTM)"                             AS div_yield_5yavgltm,
       "Revenues - Est YoY % (FY1E)"                      AS revenues_est_yoy_pct_fy1e,
       "Price Chg. % (1M)"                                AS price_chg_pct_1m,
       "Price Chg. % (3M)"                                AS price_chg_pct_3m,
       "1-Day %"                                          AS one_day_pct,
       "EPS Est Avg Rev % (FY1E - 1W)"                    AS eps_est_avg_rev_pct_fy1e_1w,
       "EPS Est Avg Rev % (FY1E - 1M)"                    AS eps_est_avg_rev_pct_fy1e_1m,
       "EPS Est Avg Rev % (FY1E - 3M)"                    AS eps_est_avg_rev_pct_fy1e_3m,
       "EPS Est Avg Rev % (FY1E - 6M)"                    AS eps_est_avg_rev_pct_fy1e_6m,
       "EPS Est Avg Rev % (FY1E - 1Y)"                    AS eps_est_avg_rev_pct_fy1e_1y,
       "Div Yield (-2FYInd)"                              AS div_yield_2fyind,
       "Div Yield (-3FYInd)"                              AS div_yield_3fyind,
       "Div Yield (-4FYInd)"                              AS div_yield_4fyind,
       "Div Yield (-5FYInd)"                              AS div_yield_5fyind,
       "EPS GAAP Est Avg Rev % (FY1E - 1M)"               AS eps_gaap_est_avg_rev_pct_fy1e_1m,
       "EPS GAAP Est Avg Rev % (FY1E - 3M)"               AS eps_gaap_est_avg_rev_pct_fy1e_3m,
       "EPS GAAP Est Avg Rev % (FY1E - 6M)"               AS eps_gaap_est_avg_rev_pct_fy1e_6m,
       "EPS GAAP Est Avg Rev % (FY1E - 1Y)"               AS eps_gaap_est_avg_rev_pct_fy1e_1y,
       "Target % (Avg)"                                   AS target_vs_price_pct,
       "Dividend Streak"                                  AS dividend_streak,
       "Price Target - #"                                 AS price_target_count,
       "Analyst Rating"                                   AS analyst_rating,
       "# Strong Sell Ratings"                            AS num_strong_sell_ratings,
       "# Strong Buys Ratings"                            AS num_strong_buys_ratings,
       "# Hold Ratings"                                   AS num_hold_ratings,
       "# Buys Ratings"                                   AS num_buys_ratings,
       "# Sell Ratings"                                   AS num_sell_ratings,
       "# No Opinion Ratings"                             AS num_no_opinion_ratings,
       "Shrs Out"                                         AS shares_outstanding,
       "Shrs Out (-1FY)"                                  AS shrs_out_1fy,
       "Full Time Employees (FQ)"                         AS full_time_employees_fq,
       "Full Time Employees (FY)"                         AS full_time_employees_fy,
       "Full Time Employees (-1FY)"                       AS full_time_employees_1fy,
       "Full Time Employees (-2FY)"                       AS full_time_employees_2fy,
       "Full Time Employees (-3FY)"                       AS full_time_employees_3fy,
       "Avg Employees (5YAVGFY)"                          AS avg_employees_5yavgfy,
       "EPS Norm - Est # (FY1E)"                          AS eps_norm_est_num_fy1e,
       "Price Target - # (3M Ago)"                        AS price_target_num_3m_ago,
       "Price Target - # (6M Ago)"                        AS price_target_num_6m_ago,
       "Price Target - # (YTD Ago)"                       AS price_target_num_ytd_ago,
       "Price Target - # (1Y Ago)"                        AS price_target_num_1y_ago,
       "Price Target - # (1W Ago)"                        AS price_target_num_1w_ago,
       "Price Target - # (1M Ago)"                        AS price_target_num_1m_ago,
       "Price Target - # (MTD Ago)"                       AS price_target_num_mtd_ago,
       "Price Target - # (QTD Ago)"                       AS price_target_num_qtd_ago,
       "Fiscal Month"                                     AS fiscal_month,
       "Fiscal Quarter"                                   AS fiscal_quarter,
       "Fiscal Year"                                      AS fiscal_year,
       "Reporting Lag"                                    AS reporting_lag,
       CURRENT_TIMESTAMP                                  AS table_calculated_at
FROM equities e;

comment on materialized view mv_equities is 'Aliased snapshot of the equities table. Column names sourced from equities_schema_metadata.column_alias. Refresh with: REFRESH MATERIALIZED VIEW CONCURRENTLY mv_equities;';

alter materialized view mv_equities owner to postgres;

create unique index idx_mv_equities_isin
    on mv_equities (isin);

create index idx_mv_equities_ticker
    on mv_equities (ticker);

create index idx_mv_equities_geography
    on mv_equities (region, country, exchange);

create index idx_mv_equities_class
    on mv_equities (sector, industry, size_class, style_class);

create index idx_mv_equities_market_cap
    on mv_equities (market_cap desc);

create index idx_mv_equities_fiscal
    on mv_equities (fiscal_year, fiscal_quarter, income_statement_report_date);

