CREATE TABLE public.screening_etf
(
	ticker                                 text,
	isin                                   text,
	issuer                                 text,
	name                                   text,
	"Fund Category"                        text,
	exchange                               text,
	region                                 text,
	"Fund Benchmark"                       text,
	administrator                          text,
	custodian                              text,
	"Fund Investment Strategy"             text,
	"Broad Benchmark"                      text,
	"Is Levered"                           text,
	"Inception Date"                       text,
	"Launch Date"                          text,
	"Notional Volume"                      double precision,
	distributor                            text,
	"Investment Advisor"                   text,
	classification                         text,
	"Peer Benchmark"                       text,
	class                                  text,
	"Last Updated"                         date,
	"ETF FY End"                           text,
	"Last Price"                           double precision,
	"1-Day Chg"                            double precision,
	"1-Day %"                              double precision,
	"Price Chg. % (1D)"                    double precision DEFAULT 0,
	"Price Chg. % (5D)"                    text,
	"Price Chg. % (1W)"                    text,
	"Price Chg. % (1M)"                    text,
	"Price Chg. % (3M)"                    text,
	"Price Chg. % (6M)"                    text,
	"Price Chg. % (1Y)"                    text,
	"Price Chg. % (3Y)"                    text,
	"Price Chg. % (5Y)"                    text,
	"Yield Month-End"                      text,
	"30-Day SEC Yield"                     text,
	"Beta 1Y Quarter End"                  text,
	"Beta 3Y Quarter End"                  text,
	"Beta 5Y Quarter End"                  text,
	"Net Expense Ratio Reported"           text,
	aum                                    text,
	"Put/Call Ratio"                       text,
	"52W High"                             text,
	"52W High/Adj"                         text,
	"52W Low"                              text,
	"52W Low/Adj"                          text,
	"EMA (5D)"                             text,
	"EMA (8D)"                             text,
	"EMA (10D)"                            text,
	"EMA (20D)"                            text,
	"EMA (21D)"                            text,
	"EMA (50D)"                            text,
	"EMA (100D)"                           text,
	"Active Return"                        text,
	"Alpha (1Y)"                           text,
	"Alpha (3Y)"                           text,
	"Alpha (5Y)"                           text,
	"Annualized excess returns"            text,
	"Annualized returns"                   text,
	"Asset Type"                           text,
	"Arithmetic Mean (1Y)"                 text,
	"Arithmetic Mean (3Y)"                 text,
	"Arithmetic Mean (5Y)"                 text,
	"Beta (1Y)"                            text,
	"Beta (3Y)"                            text,
	"Beta (5Y)"                            text,
	"Effective Duration (Yrs)"             text,
	"Downside Capture Ratio (1Y)"          text,
	"Downside Capture Ratio (3Y)"          text,
	"Downside Capture Ratio (5Y)"          text,
	"Information Ratio (1Y)"               text,
	"Information Ratio (3Y)"               text,
	"Information Ratio (5Y)"               text,
	domicile                               text,
	"Kurtosis (1Y)"                        text,
	"Kurtosis (3Y)"                        text,
	"Kurtosis (5Y)"                        text,
	"Sortino Ratio (1Y)"                   text,
	"Sortino Ratio (3Y)"                   text,
	"Sortino Ratio (5Y)"                   text,
	"Sharpe Ratio (1Y)"                    text,
	"Sharpe Ratio (3Y)"                    text,
	"Sharpe Ratio (5Y)"                    text,
	"Skewness (1Y)"                        text,
	"Skewness (3Y)"                        text,
	"Skewness (5Y)"                        text,
	"12B-1"                                text,
	"ETF Category"                         text,
	"Effective Maturity (Yrs)"             text,
	ytm                                    text,
	"Fund Total Assets (Day-End)"          text,
	"Mgmt Fees"                            text,
	"R-Squared (1Y)"                       text,
	"R-Squared (3Y)"                       text,
	"R-Squared (5Y)"                       text,
	"Months with Negative Performance YTD" text,
	"Months with Positive Performance YTD" text,
	"Batting Average (1Y)"                 text,
	"Batting Average (3Y)"                 text,
	"Batting Average (5Y)"                 text,
	"Volatility Score"                     text,
	"Upside Capture Ratio (1Y)"            text,
	"Upside Capture Ratio (3Y)"            text,
	"Upside Capture Ratio (5Y)"            text,
	"Risk Free Rate"                       text,
	"SEC Yield"                            text
);

ALTER TABLE public.screening_etf
	OWNER TO postgres;