CREATE VIEW public.vw_features_balance_sheet
			(isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
			 dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
			 next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
			 dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
			 dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
			 next_fy_end_date, next_income_statement_report_date, reference_date, assets_fq, assets_fy, assets_ltm,
			 assets_1fq, assets_2fq, assets_3fq, assets_4fq, assets_1fy, assets_2fy, assets_3fy, assets_4fy,
			 assets_qoq_growth, assets_yoy_growth, assets_3y_cagr, asset_growth_accel, asset_base_stable, inventory_ltm,
			 inventory_fq, inventory_fy, inventory_1fq, inventory_2fq, inventory_3fq, inventory_4fq, inventory_1fy,
			 inventory_2fy, inventory_3fy, inventory_4fy, inventory_qoq_change, inventory_yoy_change,
			 inventory_4q_trend, inventory_vs_5y_avg, inventory_days, inventory_turnover, inventory_to_revenue,
			 inventory_to_assets, inventory_buildup_flag, inventory_reduction_flag, inventory_volatility, goodwill_fq,
			 goodwill_ltm, goodwill_fy, goodwill_1fq, goodwill_2fq, goodwill_3fq, goodwill_4fq, goodwill_1fy,
			 goodwill_2fy, goodwill_3fy, goodwill_4fy, goodwill_qoq_change, goodwill_yoy_change, goodwill_3y_growth,
			 goodwill_vs_5y_avg, recent_acquisition_flag, goodwill_accumulation_rate, goodwill_to_assets_trend,
			 impairment_risk_score, goodwill_concentration)
AS
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       tat.assets_fq,
       tat.assets_fy,
       tat.assets_ltm,
       tat.assets_1fq,
       tat.assets_2fq,
       tat.assets_3fq,
       tat.assets_4fq,
       tat.assets_1fy,
       tat.assets_2fy,
       tat.assets_3fy,
       tat.assets_4fy,
       tat.assets_qoq_growth,
       tat.assets_yoy_growth,
       tat.assets_3y_cagr,
       tat.asset_growth_accel,
       tat.asset_base_stable,
       itf.inventory_ltm,
       itf.inventory_fq,
       itf.inventory_fy,
       itf.inventory_1fq,
       itf.inventory_2fq,
       itf.inventory_3fq,
       itf.inventory_4fq,
       itf.inventory_1fy,
       itf.inventory_2fy,
       itf.inventory_3fy,
       itf.inventory_4fy,
       itf.inventory_qoq_change,
       itf.inventory_yoy_change,
       itf.inventory_4q_trend,
       itf.inventory_vs_5y_avg,
       itf.inventory_days,
       itf.inventory_turnover,
       itf.inventory_to_revenue,
       itf.inventory_to_assets,
       itf.inventory_buildup_flag,
       itf.inventory_reduction_flag,
       itf.inventory_volatility,
       gtf.goodwill_fq,
       gtf.goodwill_ltm,
       gtf.goodwill_fy,
       gtf.goodwill_1fq,
       gtf.goodwill_2fq,
       gtf.goodwill_3fq,
       gtf.goodwill_4fq,
       gtf.goodwill_1fy,
       gtf.goodwill_2fy,
       gtf.goodwill_3fy,
       gtf.goodwill_4fy,
       gtf.goodwill_qoq_change,
       gtf.goodwill_yoy_change,
       gtf.goodwill_3y_growth,
       gtf.goodwill_vs_5y_avg,
       gtf.recent_acquisition_flag,
       gtf.goodwill_accumulation_rate,
       gtf.goodwill_to_assets_trend,
       gtf.impairment_risk_score,
       gtf.goodwill_concentration
FROM vw_identifier_columns                            id
	     LEFT JOIN calc_total_assets_temporal()       tat(isin, assets_fq, assets_fy, assets_ltm, assets_1fq,
	                                                      assets_2fq, assets_3fq, assets_4fq, assets_1fy, assets_2fy,
	                                                      assets_3fy, assets_4fy, assets_qoq_growth, assets_yoy_growth,
	                                                      assets_3y_cagr, asset_growth_accel, asset_base_stable)
	               USING (isin)
	     LEFT JOIN calc_inventory_temporal_features() itf(isin, inventory_ltm, inventory_fq, inventory_fy,
	                                                      inventory_1fq, inventory_2fq, inventory_3fq, inventory_4fq,
	                                                      inventory_1fy, inventory_2fy, inventory_3fy, inventory_4fy,
	                                                      inventory_qoq_change, inventory_yoy_change,
	                                                      inventory_4q_trend, inventory_vs_5y_avg, inventory_days,
	                                                      inventory_turnover, inventory_to_revenue, inventory_to_assets,
	                                                      inventory_buildup_flag, inventory_reduction_flag,
	                                                      inventory_volatility) USING (isin)
	     LEFT JOIN calc_goodwill_temporal_features()  gtf(isin, goodwill_fq, goodwill_ltm, goodwill_fy, goodwill_1fq,
	                                                      goodwill_2fq, goodwill_3fq, goodwill_4fq, goodwill_1fy,
	                                                      goodwill_2fy, goodwill_3fy, goodwill_4fy, goodwill_qoq_change,
	                                                      goodwill_yoy_change, goodwill_3y_growth, goodwill_vs_5y_avg,
	                                                      recent_acquisition_flag, goodwill_accumulation_rate,
	                                                      goodwill_to_assets_trend, impairment_risk_score,
	                                                      goodwill_concentration) USING (isin);

COMMENT ON VIEW public.vw_features_balance_sheet IS 'Balance sheet temporal analysis including assets, inventory, and goodwill trends.
    Source functions: calc_total_assets_temporal, calc_inventory_temporal_features, calc_goodwill_temporal_features';

ALTER TABLE public.vw_features_balance_sheet
	OWNER TO postgres;