CREATE VIEW public.vw_features_profitability
			(isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
			 dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
			 next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
			 dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
			 dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
			 next_fy_end_date, next_income_statement_report_date, reference_date, roe, roa, gross_margin_pct,
			 operating_margin_pct, net_margin_pct, ebitda_margin_pct, roic, rnd_intensity, equity_multiplier,
			 gross_margin_trend_yoy, operating_margin_trend, net_margin_trend_yoy, ebitda_margin_trend,
			 margin_expansion_flag, margin_stability_score, ebit_fq, ebit_ltm, ebit_fy, ebit_1fy, ebit_2fy, ebit_3fy,
			 ebit_4fy, ebitda_fq, ebitda_ltm, ebitda_fy, ebitda_1fy, ebitda_2fy, ebitda_3fy, ebitda_4fy, ebit_5yavgfq,
			 ebit_5yavgltm, ebitda_5yavgfq, ebitda_5yavgltm, ebit_adj_fq, ebit_adj_ltm, ebit_adj_fy, ebitda_adj_fq,
			 ebitda_adj_ltm, ebitda_adj_fy, ebit_growth_yoy, ebitda_growth_yoy, ebit_margin_ltm, ebitda_margin_ltm,
			 ebit_positive_years, ebitda_positive_years, ebit_qoq_growth, ebitda_qoq_growth, ebit_cagr_3y,
			 ebitda_cagr_3y, ebit_vs_5y_avg, ebitda_vs_5y_avg, gp_fq, gp_fy, gp_ltm, gp_1fqfq, gp_2fqfq, gp_3fqfq,
			 gp_4fqfq, gp_1fy, gp_2fy, gp_3fy, gp_4fy, gp_qoq_growth, gp_yoy_growth, gp_margin_fq, gp_margin_trend,
			 gp_positive_quarters, gp_margin_expansion)
AS
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       pf.roe,
       pf.roa,
       pf.gross_margin_pct,
       pf.operating_margin_pct,
       pf.net_margin_pct,
       pf.ebitda_margin_pct,
       pf.roic,
       pf.rnd_intensity,
       pf.equity_multiplier,
       mt.gross_margin_trend_yoy,
       mt.operating_margin_trend,
       mt.net_margin_trend_yoy,
       mt.ebitda_margin_trend,
       mt.margin_expansion_flag,
       mt.margin_stability_score,
       eec.ebit_fq,
       eec.ebit_ltm,
       eec.ebit_fy,
       eec.ebit_1fy,
       eec.ebit_2fy,
       eec.ebit_3fy,
       eec.ebit_4fy,
       eec.ebitda_fq,
       eec.ebitda_ltm,
       eec.ebitda_fy,
       eec.ebitda_1fy,
       eec.ebitda_2fy,
       eec.ebitda_3fy,
       eec.ebitda_4fy,
       eec.ebit_5yavgfq,
       eec.ebit_5yavgltm,
       eec.ebitda_5yavgfq,
       eec.ebitda_5yavgltm,
       eec.ebit_adj_fq,
       eec.ebit_adj_ltm,
       eec.ebit_adj_fy,
       eec.ebitda_adj_fq,
       eec.ebitda_adj_ltm,
       eec.ebitda_adj_fy,
       eec.ebit_growth_yoy,
       eec.ebitda_growth_yoy,
       eec.ebit_margin_ltm,
       eec.ebitda_margin_ltm,
       eec.ebit_positive_years,
       eec.ebitda_positive_years,
       eec.ebit_qoq_growth,
       eec.ebitda_qoq_growth,
       eec.ebit_cagr_3y,
       eec.ebitda_cagr_3y,
       eec.ebit_vs_5y_avg,
       eec.ebitda_vs_5y_avg,
       gpt.gp_fq,
       gpt.gp_fy,
       gpt.gp_ltm,
       gpt.gp_1fqfq,
       gpt.gp_2fqfq,
       gpt.gp_3fqfq,
       gpt.gp_4fqfq,
       gpt.gp_1fy,
       gpt.gp_2fy,
       gpt.gp_3fy,
       gpt.gp_4fy,
       gpt.gp_qoq_growth,
       gpt.gp_yoy_growth,
       gpt.gp_margin_fq,
       gpt.gp_margin_trend,
       gpt.gp_positive_quarters,
       gpt.gp_margin_expansion
FROM vw_identifier_columns                          id
	     LEFT JOIN calc_profitability_features()    pf(isin, roe, roa, gross_margin_pct, operating_margin_pct,
	                                                   net_margin_pct, ebitda_margin_pct, roic, rnd_intensity,
	                                                   equity_multiplier) USING (isin)
	     LEFT JOIN calc_margin_trends()             mt(isin, gross_margin_trend_yoy, operating_margin_trend,
	                                                   net_margin_trend_yoy, ebitda_margin_trend, margin_expansion_flag,
	                                                   margin_stability_score) USING (isin)
	     LEFT JOIN calc_ebit_ebitda_comprehensive() eec(isin, ebit_fq, ebit_ltm, ebit_fy, ebit_1fy, ebitda_fq,
	                                                    ebitda_ltm, ebitda_fy, ebitda_1fy, ebit_2fy, ebit_3fy, ebit_4fy,
	                                                    ebitda_2fy, ebitda_3fy, ebitda_4fy, ebit_1fqfq, ebit_2fqfq,
	                                                    ebit_3fqfq, ebit_4fqfq, ebitda_1fqfq, ebitda_2fqfq,
	                                                    ebitda_3fqfq, ebitda_4fqfq, ebit_5yavgfq, ebit_5yavgltm,
	                                                    ebitda_5yavgfq, ebitda_5yavgltm, ebit_adj_fq, ebit_adj_ltm,
	                                                    ebit_adj_fy, ebitda_adj_fq, ebitda_adj_ltm, ebitda_adj_fy,
	                                                    ebit_growth_yoy, ebitda_growth_yoy, ebit_margin_ltm,
	                                                    ebitda_margin_ltm, ebit_positive_years, ebitda_positive_years,
	                                                    ebit_qoq_growth, ebitda_qoq_growth, ebit_cagr_3y,
	                                                    ebitda_cagr_3y, ebit_vs_5y_avg, ebitda_vs_5y_avg) USING (isin)
	     LEFT JOIN calc_gross_profit_temporal()     gpt(isin, gp_fq, gp_fy, gp_ltm, gp_1fqfq, gp_2fqfq, gp_3fqfq,
	                                                    gp_4fqfq, gp_1fy, gp_2fy, gp_3fy, gp_4fy, gp_qoq_growth,
	                                                    gp_yoy_growth, gp_margin_fq, gp_margin_trend,
	                                                    gp_positive_quarters, gp_margin_expansion) USING (isin);

COMMENT ON VIEW public.vw_features_profitability IS 'Profitability metrics including ROE, ROA, margins, EBIT/EBITDA comprehensive analysis.
    Source functions: calc_profitability_features, calc_margin_trends,
    calc_ebit_ebitda_comprehensive, calc_gross_profit_temporal';

ALTER TABLE public.vw_features_profitability
	OWNER TO postgres;