create view vw_features_leverage_liquidity
            (isin, ticker, name, description, region, country, trading_country, exchange, sector, industry,
             dividend_record_frequency, earnings_report_frequency, fy_end, next_earnings_report, next_earnings_status,
             next_earnings_when, next_fiscal_quarter, reporting_interval, size_class, style_class, unit,
             dividend_record_announce_date, dividend_record_ex_date, dividend_record_payable_date,
             dividend_record_record_date, fy_end_date, income_statement_report_date, last_updated, next_earnings,
             next_fy_end_date, next_income_statement_report_date, reference_date, debt_to_equity, debt_to_assets,
             equity_ratio, interest_coverage, current_ratio, cash_ratio, working_capital_ratio, asset_turnover,
             inventory_turnover, receivables_days, working_capital_turns, cash_to_assets_pct, cash_change_qoq,
             cash_vs_5y_avg, inventory_change_yoy, inventory_vs_5y_avg, receivables_change_yoy, receivables_vs_5y_avg,
             working_capital_vs_5y_avg, retained_earnings_vs_5y, intangibles_growth_flag, asset_quality_score,
             balance_sheet_strength, debt_maturity_risk, wc_fq, wc_fy, wc_ltm, wc_5yavgfy, wc_1fq, wc_2fq, wc_3fq,
             wc_4fq, wc_1fy, wc_2fy, wc_3fy, wc_4fy, wc_qoq_change, wc_yoy_change, wc_4q_trend, wc_vs_5y_avg,
             wc_positive_quarters, wc_improving_flag, wc_volatility, debt_fq, debt_fy, debt_ltm, debt_1fq, debt_2fq,
             debt_3fq, debt_4fq, debt_1fy, debt_2fy, debt_3fy, debt_4fy, debt_qoq_change, debt_yoy_change,
             debt_4q_trend, debt_3y_cagr, debt_deleveraging, debt_to_equity_trend, wc_ltm_deep, wc_fq_deep, wc_fy_deep,
             wc_to_revenue, wc_to_assets, wc_change_qoq_deep, wc_change_yoy_deep, days_working_capital,
             wc_efficiency_score, negative_wc_flag, wc_improvement_flag_deep)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.description,
       id.region,
       id.country,
       id.trading_country,
       id.exchange,
       id.sector,
       id.industry,
       id.dividend_record_frequency,
       id.earnings_report_frequency,
       id.fy_end,
       id.next_earnings_report,
       id.next_earnings_status,
       id.next_earnings_when,
       id.next_fiscal_quarter,
       id.reporting_interval,
       id.size_class,
       id.style_class,
       id.unit,
       id.dividend_record_announce_date,
       id.dividend_record_ex_date,
       id.dividend_record_payable_date,
       id.dividend_record_record_date,
       id.fy_end_date,
       id.income_statement_report_date,
       id.last_updated,
       id.next_earnings,
       id.next_fy_end_date,
       id.next_income_statement_report_date,
       id.reference_date,
       lf.debt_to_equity,
       lf.debt_to_assets,
       lf.equity_ratio,
       lf.interest_coverage,
       lf.current_ratio,
       lf.cash_ratio,
       lf.working_capital_ratio,
       er.asset_turnover,
       er.inventory_turnover,
       er.receivables_days,
       er.working_capital_turns,
       bsd.cash_to_assets_pct,
       bsd.cash_change_qoq,
       bsd.cash_vs_5y_avg,
       bsd.inventory_change_yoy,
       bsd.inventory_vs_5y_avg,
       bsd.receivables_change_yoy,
       bsd.receivables_vs_5y_avg,
       bsd.working_capital_vs_5y_avg,
       bsd.retained_earnings_vs_5y,
       bsd.intangibles_growth_flag,
       bsd.asset_quality_score,
       bsd.balance_sheet_strength,
       bsd.debt_maturity_risk,
       wct.wc_fq,
       wct.wc_fy,
       wct.wc_ltm,
       wct.wc_5yavgfy,
       wct.wc_1fq,
       wct.wc_2fq,
       wct.wc_3fq,
       wct.wc_4fq,
       wct.wc_1fy,
       wct.wc_2fy,
       wct.wc_3fy,
       wct.wc_4fy,
       wct.wc_qoq_change,
       wct.wc_yoy_change,
       wct.wc_4q_trend,
       wct.wc_vs_5y_avg,
       wct.wc_positive_quarters,
       wct.wc_improving_flag,
       wct.wc_volatility,
       tdt.debt_fq,
       tdt.debt_fy,
       tdt.debt_ltm,
       tdt.debt_1fq,
       tdt.debt_2fq,
       tdt.debt_3fq,
       tdt.debt_4fq,
       tdt.debt_1fy,
       tdt.debt_2fy,
       tdt.debt_3fy,
       tdt.debt_4fy,
       tdt.debt_qoq_change,
       tdt.debt_yoy_change,
       tdt.debt_4q_trend,
       tdt.debt_3y_cagr,
       tdt.debt_deleveraging,
       tdt.debt_to_equity_trend,
       wcd.working_capital_ltm AS wc_ltm_deep,
       wcd.working_capital_fq  AS wc_fq_deep,
       wcd.working_capital_fy  AS wc_fy_deep,
       wcd.wc_to_revenue,
       wcd.wc_to_assets,
       wcd.wc_change_qoq       AS wc_change_qoq_deep,
       wcd.wc_change_yoy       AS wc_change_yoy_deep,
       wcd.days_working_capital,
       wcd.wc_efficiency_score,
       wcd.negative_wc_flag,
       wcd.wc_improvement_flag AS wc_improvement_flag_deep
FROM vw_identifier_columns id
         LEFT JOIN calc_leverage_features() lf(isin, debt_to_equity, debt_to_assets, equity_ratio, interest_coverage,
                                               current_ratio, cash_ratio, working_capital_ratio) USING (isin)
         LEFT JOIN calc_efficiency_ratios() er(isin, asset_turnover, inventory_turnover, receivables_days,
                                               working_capital_turns) USING (isin)
         LEFT JOIN calc_balance_sheet_dynamics() bsd(isin, cash_to_assets_pct, cash_change_qoq, cash_vs_5y_avg,
                                                     inventory_change_yoy, inventory_vs_5y_avg, receivables_change_yoy,
                                                     receivables_vs_5y_avg, working_capital_vs_5y_avg,
                                                     retained_earnings_vs_5y, intangibles_growth_flag,
                                                     asset_quality_score, balance_sheet_strength, debt_maturity_risk)
                   USING (isin)
         LEFT JOIN calc_working_capital_temporal() wct(isin, wc_fq, wc_fy, wc_ltm, wc_5yavgfy, wc_1fq, wc_2fq, wc_3fq,
                                                       wc_4fq, wc_1fy, wc_2fy, wc_3fy, wc_4fy, wc_qoq_change,
                                                       wc_yoy_change, wc_4q_trend, wc_vs_5y_avg, wc_positive_quarters,
                                                       wc_improving_flag, wc_volatility) USING (isin)
         LEFT JOIN calc_total_debt_temporal() tdt(isin, debt_fq, debt_fy, debt_ltm, debt_1fq, debt_2fq, debt_3fq,
                                                  debt_4fq, debt_1fy, debt_2fy, debt_3fy, debt_4fy, debt_qoq_change,
                                                  debt_yoy_change, debt_4q_trend, debt_3y_cagr, debt_deleveraging,
                                                  debt_to_equity_trend) USING (isin)
         LEFT JOIN calc_working_capital_deep_features() wcd(isin, working_capital_ltm, working_capital_fq,
                                                            working_capital_fy, wc_to_revenue, wc_to_assets,
                                                            wc_change_qoq, wc_change_yoy, days_working_capital,
                                                            wc_efficiency_score, negative_wc_flag, wc_improvement_flag)
                   USING (isin);

comment on view vw_features_leverage_liquidity is 'Leverage and liquidity metrics including debt ratios, working capital, and balance sheet dynamics.
    Source functions: calc_leverage_features, calc_efficiency_ratios, calc_balance_sheet_dynamics,
    calc_working_capital_temporal, calc_total_debt_temporal, calc_working_capital_deep_features';

alter table vw_features_leverage_liquidity
    owner to postgres;

